import os
import re
import json

test_dir = r"c:\Users\quazi\Downloads\PPOM-UNO-Problems"
files = [f for f in os.listdir(test_dir) if f.startswith("Test_L") and f.endswith(".js")]

total_questions = 0
longest_is_correct_count = 0
file_stats = []

for file in files:
    try:
        path = os.path.join(test_dir, file)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
            
        # Extract array content: matches [ ... ] (including newlines)
        # We look for "const Test_L... = (" and then capture until the end semicolon or file end.
        # Actually, finding the first '[' and the last ']' might be safer if the structure is simple.
        
        match = re.search(r"=\s*(\[.*\])\s*;?", content, re.DOTALL)
        if match:
            json_str = match.group(1)
            # Python's json.loads requires property names to be enclosed in double quotes.
            # JS objects might have unquoted keys or single quotes. 
            # We will attempt to fix common JS-to-JSON issues:
            # 1. Trailing commas (remove them)
            # 2. Single quotes to double quotes (if strictly used for strings) - hazardous if content has single quotes.
            # Given the files are likely generated by me or structurally similar, let's try strict parse first.
            
            try:
                questions = json.loads(json_str)
            except json.JSONDecodeError:
                # Fallback: simple regex approach to find questions
                # This is less accurate but robust against syntax variations
                 # We'll just skip complex parsing and look for patterns manually if JSON fails.
                 # or try to clean up trailing commas
                json_str_clean = re.sub(r",\s*\]", "]", json_str)
                json_str_clean = re.sub(r",\s*\}", "}", json_str_clean)
                try:
                    questions = json.loads(json_str_clean)
                except:
                     # print(f"Skipping {file} - invalid JSON format")
                     # continue
                     # Let's assume it failed and try a very dumb regex scan for this file
                     pass
                     questions = []
            
            file_correct = 0
            file_qs = 0
            
            # If we parsed it successfully
            if questions:
                for q in questions:
                    # Defensive coding
                    if "options" not in q or "correctAnswerIndex" not in q:
                        continue
                        
                    options = q["options"]
                    correct_idx = q["correctAnswerIndex"]
                    
                    if not isinstance(options, list) or correct_idx >= len(options):
                         continue

                    # Calculate lengths
                    lengths = [len(o["text"]) for o in options]
                    correct_len = lengths[correct_idx]
                    max_len = max(lengths)
                    
                    if correct_len == max_len:
                        file_correct += 1
                        longest_is_correct_count += 1
                    
                    total_questions += 1
                    file_qs += 1
                
                if file_qs > 0:
                    percent = (file_correct / file_qs) * 100
                    file_stats.append((file, percent, file_correct, file_qs))
            else:
                 # Regex fallback for files that failed JSON parsing
                 # This is tricky because of nested braces. 
                 pass

    except Exception as e:
        print(f"Error processing {file}: {e}")

print("--- Analysis Results ---")
print(f"Total Files Analyzed: {len(file_stats)}")
print(f"Total Questions: {total_questions}")
print(f"Longest Answer is Correct: {longest_is_correct_count} times")
if total_questions > 0:
    print(f"Overall Percentage: {longest_is_correct_count / total_questions * 100:.2f}%")

print("\n--- Top Files with Bias ---")
# Sort by percentage descending
file_stats.sort(key=lambda x: x[1], reverse=True)
for name, pct, corr, tot in file_stats:
    print(f"{name}: {pct:.1f}% ({corr}/{tot})")
