const Test_CV31 = [
  {
    "id": 1,
    "category": "Pharmacology: Thiazide Diuretics",
    "questionText": "A 54-year-old woman with newly diagnosed primary hypertension is started on a single oral agent. A 24-hour urine collection two weeks later shows increased sodium and chloride excretion with only a moderate increase in urine volume, and urinary calcium excretion has fallen below her pretreatment value. Serum potassium is 3.4 mEq/L and serum bicarbonate is mildly elevated. Which transporter is this drug inhibiting?",
    "options": [
      { "text": "Na+-Cl- cotransporter of the distal convoluted tubule", "explanation": "Correct. Moderate natriuresis with only moderate diuresis fits a site where just 5-10% of filtered sodium remains, which is the early distal convoluted tubule. Falling urinary calcium is the signature: blocking luminal NCC lowers intracellular sodium, drives basolateral NCX1 harder, and pulls calcium in through apical TRPV5 for export to the blood. The mild hypokalemia and metabolic alkalosis come from the increased sodium load delivered to aldosterone-sensitive principal cells downstream." },
      { "text": "Na+-K+-2Cl- cotransporter of the thick ascending limb of Henle", "explanation": "Incorrect. Blocking NKCC2 produces far more vigorous natriuresis and diuresis than described, and it abolishes the lumen-positive potential that drives paracellular calcium reabsorption, so urinary calcium would RISE rather than fall. It would also collapse the medullary gradient. This would be the correct answer if the patient had brisk diuresis with hypercalciuria and an inability to concentrate urine." },
      { "text": "Epithelial sodium channel of the cortical collecting duct principal cells", "explanation": "Incorrect. Blocking ENaC affects only 2-5% of filtered sodium, which is a weak natriuretic effect, and it abolishes the lumen-negative potential so potassium is RETAINED. This patient is hypokalemic, the opposite direction. This would be the correct answer if a mild natriuresis were accompanied by a rising serum potassium and a mild metabolic acidosis." },
      { "text": "Carbonic anhydrase in the proximal tubule brush border and cytosol", "explanation": "Incorrect. Carbonic anhydrase inhibition produces bicarbonate wasting with alkaline urine and a hyperchloremic metabolic ACIDOSIS, not the mild alkalosis seen here, and the diuretic effect is self-limited within days. This would be the correct answer if the urine were alkaline with a large bicarbonate load and the serum bicarbonate had fallen." },
      { "text": "Aquaporin-2 water channels of the medullary collecting duct", "explanation": "Incorrect. Blocking AQP2 would produce a water diuresis without significant sodium or chloride loss, and would not change urinary calcium at all. No agent in this lecture works this way. This would be the correct answer if the urine volume rose sharply with dilute urine and unchanged electrolyte excretion." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: a diuretic that lowers urinary calcium is a thiazide - it is the only class that retains calcium, while loop diuretics waste it.",
    "pdfPage": 6,
    "pdfQuote": "sodium chloride cotransporter (NCC) in the distal convoluted tubule"
  },
  {
    "id": 2,
    "category": "Pharmacology: Thiazide Diuretics",
    "questionText": "A 47-year-old man with recurrent nephrolithiasis is placed on a distal convoluted tubule diuretic and his 24-hour urinary calcium falls by nearly 40%. His serum calcium remains within the reference range. Which mechanism best accounts for the reduction in urinary calcium?",
    "options": [
      { "text": "Blockade of paracellular calcium reabsorption raises the lumen-positive potential of the thick ascending limb", "explanation": "Incorrect. Paracellular calcium reabsorption in the thick ascending limb is driven by a lumen-positive potential generated by NKCC2 activity, and no thiazide acts there. Losing that potential would increase, not decrease, urinary calcium. This would be the correct answer if you were explaining why loop diuretics are used as an adjunct in hypercalcemia." },
      { "text": "Lower intracellular Na+ enhances basolateral NCX1, so Ca2+ enters via apical TRPV5", "explanation": "Correct. Blocking luminal NCC lowers the intracellular sodium concentration, which steepens the gradient the basolateral Na+/Ca2+ exchanger NCX1 works on (3 Na+ in, 1 Ca2+ out). NCX1 therefore runs harder, intracellular calcium falls, and that low intracellular calcium creates a stronger driving force for calcium entry from the lumen through TRPV5. The calcium is carried across on calbindin and exported to the blood by NCX1, with PMCA1b acting only as a fine-tuner." },
      { "text": "Direct agonism at the parathyroid hormone receptor increases distal calcium channel expression", "explanation": "Incorrect. PTH and vitamin D do regulate active calcium reabsorption in the DCT, but thiazides are not PTH receptor agonists; the effect is electrochemical and downstream of sodium handling. This would be the correct answer if the question described a PTH analog or a condition of primary hyperparathyroidism." },
      { "text": "Inhibition of PMCA1b traps calcium inside the tubular cell and prevents its export", "explanation": "Incorrect. PMCA1b is a plasma membrane calcium ATPase that fine-tunes calcium export and keeps intracellular calcium very low; it is explicitly a secondary, not primary, mechanism, and inhibiting it would impair rather than promote calcium reabsorption. This would be the correct answer if the question asked which pump maintains very low intracellular calcium concentrations." },
      { "text": "Increased tubular flow rate shortens contact time and reduces calcium secretion into urine", "explanation": "Incorrect. Calcium is reabsorbed rather than actively secreted in the distal nephron, and a higher flow rate would if anything reduce reabsorption. Thiazides produce only moderate diuresis in any case. This would be the correct answer if the question concerned solute washout during a brisk osmotic diuresis." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: thiazide calcium retention is indirect - block sodium entry, and the sodium-calcium exchanger does the rest.",
    "pdfPage": 11,
    "pdfQuote": "basolateral NCX1 activity (3Na+ in, 1 Ca2+ out)"
  },
  {
    "id": 3,
    "category": "Pharmacology: Thiazide Diuretics",
    "questionText": "A 63-year-old man with hypertension is switched from an agent with a 6-15 hour elimination half-life to a structurally related agent with a 40-60 hour half-life and a 24-72 hour duration of action. Both drugs inhibit the same tubular transporter. Which outcome should be anticipated on the longer-acting agent?",
    "options": [
      { "text": "Superior reduction in myocardial infarction and stroke compared with the shorter-acting drug in randomized trials", "explanation": "Incorrect. Large observational studies and randomized trials found that both agents reduce blood pressure and lower the risk of heart attack, stroke and heart failure at SIMILAR rates. The longer half-life did not translate into a cardiovascular outcome advantage. This would be the correct answer if the trials had demonstrated separation in hard endpoints, which they did not." },
      { "text": "Loss of the calcium-sparing effect because the drug lacks a benzothiadiazine ring", "explanation": "Incorrect. Thiazide-like drugs lack the benzothiadiazine structure but have the same actions, including calcium retention, because the target transporter is unchanged. Structure defines the family name, not the pharmacology. This would be the correct answer if the two agents acted at different transporters." },
      { "text": "Smoother 24-hour control with a greater risk of hypokalemia", "explanation": "Correct. The longer half-life keeps blood levels stable over a full dosing interval, which provides smoother 24-hour blood pressure control. Because the drug is on board continuously, the increased distal sodium delivery that drives ENaC-mediated potassium secretion is also sustained, so the risk of hypokalemia is higher than with the shorter-acting agent. Outcome data for the two are comparable, so the choice often comes down to individual tolerability." },
      { "text": "A shift from moderate to high-ceiling natriuresis because more drug accumulates at the site", "explanation": "Incorrect. Natriuretic ceiling is determined by the fraction of filtered sodium available at the site of action, which is 5-10% in the distal convoluted tubule regardless of how long the drug persists. Accumulation lengthens duration, not maximal efficacy. This would be the correct answer if the drug had been switched to an agent acting in the thick ascending limb." },
      { "text": "Elimination of the need for a potassium-sparing agent in combination therapy", "explanation": "Incorrect. The opposite is true: a longer-acting thiazide increases the likelihood of needing an ENaC inhibitor or MR antagonist to offset potassium wasting. This would be the correct answer if the switch had been to a potassium-sparing drug." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: chlorthalidone gives smoother 24-hour blood pressure control and more hypokalemia than hydrochlorothiazide, but equivalent cardiovascular outcomes.",
    "pdfPage": 10,
    "pdfQuote": "smoother 24-hour blood pressure control"
  },
  {
    "id": 4,
    "category": "Pharmacology: Antihypertensive Mechanisms",
    "questionText": "A 58-year-old woman has been taking a first-line antihypertensive diuretic for eight months. Repeat testing shows that her plasma volume has drifted back close to pretreatment values, yet her blood pressure remains 20 mmHg below baseline and her calculated peripheral vascular resistance is reduced. Which mechanism best explains the persistent blood pressure reduction?",
    "options": [
      { "text": "Persistent reduction in plasma volume maintains a lower cardiac output for the duration of therapy", "explanation": "Incorrect. This describes the ACUTE mechanism, and the vignette specifically states that plasma volume has returned toward pretreatment levels, which is an expected and desirable adaptation. Cardiac output cannot be the sustained explanation here. This would be the correct answer if the question were about the first days to weeks of therapy." },
      { "text": "Continuous stimulation of renal prostaglandin synthesis maintains afferent arteriolar dilation", "explanation": "Incorrect. Renal prostaglandins support renal blood flow and GFR but do not lower systemic peripheral vascular resistance in this sustained way, and thiazides do not stimulate their synthesis. This would be the correct answer if the question asked why an NSAID blunts the antihypertensive response." },
      { "text": "Chronic aldosterone suppression lowers sodium reabsorption in the aldosterone-sensitive distal nephron", "explanation": "Incorrect. Thiazide-induced volume contraction ACTIVATES the renin-angiotensin-aldosterone system rather than suppressing it, which is precisely why potassium wasting occurs. This would be the correct answer if the patient were taking a mineralocorticoid receptor antagonist." },
      { "text": "Chronic sodium depletion reduces vascular smooth muscle responsiveness to vasoconstrictors", "explanation": "Correct. Over time the body resets to a new steady state of sodium in and sodium out, and vascular smooth muscle becomes chronically sodium-depleted. That depletion decreases the responsiveness of the smooth muscle to circulating vasoconstrictors, so peripheral vascular resistance falls and stays low. This vascular mechanism, not the initial volume effect, is what sustains the antihypertensive benefit of thiazides." },
      { "text": "Baroreceptor resetting eliminates the reflex tachycardia that normally opposes diuretic therapy", "explanation": "Incorrect. Baroreceptor resetting does occur with sustained pressure changes, but it does not by itself lower peripheral vascular resistance and is not the mechanism described in this lecture. This would be the correct answer if the question concerned the loss of a compensatory heart rate response." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: thiazides lower BP acutely by shrinking ECF and cardiac output, but chronically by desensitizing vascular smooth muscle to vasoconstrictors.",
    "pdfPage": 13,
    "pdfQuote": "Sustained effect is due to chronic sodium depletion"
  },
  {
    "id": 5,
    "category": "Pharmacology: Diuretic Adverse Effects",
    "questionText": "A 71-year-old woman on a distal convoluted tubule diuretic presents with confusion. Serum sodium is 124 mEq/L, urine osmolality is high, and she reports drinking large volumes of water because she has felt thirsty. Which combination of renal capacities explains her hyponatremia?",
    "options": [
      { "text": "Both diluting and concentrating ability are impaired, so urine osmolality is fixed near plasma", "explanation": "Incorrect. This is the loop diuretic pattern, and it is exactly why loop diuretics carry a LOWER hyponatremia risk than thiazides. Her urine osmolality is high, which proves concentrating ability is intact. This would be the correct answer if she were taking furosemide and had isosthenuric urine." },
      { "text": "Concentrating ability is impaired while diluting ability remains fully preserved", "explanation": "Incorrect. This is the pattern of vasopressin resistance, in which dilute urine is produced despite adequate ADH, and it causes hypernatremia with polyuria rather than hyponatremia. Her urine is concentrated. This would be the correct answer if she had lithium-induced nephrogenic diabetes insipidus." },
      { "text": "Both capacities are preserved but ADH secretion is inappropriately suppressed by volume expansion", "explanation": "Incorrect. Suppressed ADH would produce dilute urine and water excretion, correcting rather than causing hyponatremia, and thiazide therapy contracts rather than expands volume. This would be the correct answer if she had primary polydipsia with maximally dilute urine." },
      { "text": "Sodium is lost faster than water because the medullary osmotic gradient has been destroyed", "explanation": "Incorrect. Thiazides act in the distal convoluted tubule and have nothing to do with building the medullary gradient, which remains intact. The problem is water retention exceeding sodium loss, not the reverse. This would be the correct answer if the agent were acting on NKCC2 in the thick ascending limb." },
      { "text": "Urine dilution is impaired while concentrating ability is preserved", "explanation": "Correct. NCC inhibition leaves solute in the tubular fluid of the diluting segment, so solute-free water cannot be excreted. Meanwhile the medullary gradient is untouched, the collecting duct still responds to ADH, AQP2 is inserted and free water is reabsorbed. Retention of water therefore exceeds retention of sodium, and her increased thirst adds still more water, producing dilutional hyponatremia." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: thiazides impair dilution but not concentration, which is why they are the leading diuretic cause of hyponatremia.",
    "pdfPage": 19,
    "pdfQuote": "Retention of water is greater than retention of sodium"
  },
  {
    "id": 6,
    "category": "Pharmacology: Diuretic Adverse Effects",
    "questionText": "A 60-year-old man started on a distal convoluted tubule diuretic six weeks ago has a serum potassium of 3.0 mEq/L, a serum bicarbonate of 32 mEq/L, and a serum chloride of 94 mEq/L. Which mechanism best explains this laboratory picture?",
    "options": [
      { "text": "Increased distal Na+ delivery plus aldosterone deepen the lumen-negative potential", "explanation": "Correct. Blocking NCC increases sodium and water delivery to the aldosterone-sensitive distal nephron. Volume contraction activates RAAS, and aldosterone upregulates ENaC and the Na+/K+ ATPase, so more sodium is reabsorbed through ENaC, the lumen-negative potential deepens, and potassium exits through ROMK. Increased hydrogen secretion accompanies the potassium loss, and hypochloremia with bicarbonate retention sustains the metabolic alkalosis." },
      { "text": "Direct pharmacologic inhibition of the ROMK potassium channel in the principal cells of the collecting duct", "explanation": "Incorrect. No diuretic in this lecture blocks ROMK directly; the potassium loss is entirely electrochemical and secondary to sodium handling. Blocking ROMK would actually reduce potassium secretion. This would be the correct answer if a drug had been designed to plug the potassium exit channel itself." },
      { "text": "Loss of bicarbonate in the urine as filtered bicarbonate escapes proximal reabsorption", "explanation": "Incorrect. That mechanism produces a metabolic ACIDOSIS with alkaline urine, which is the carbonic anhydrase inhibitor pattern; this patient has an elevated serum bicarbonate. This would be the correct answer if the patient were on acetazolamide with a falling serum bicarbonate." },
      { "text": "Impaired hydrogen ion secretion by type A intercalated cells caused by direct drug binding", "explanation": "Incorrect. Hydrogen secretion is increased rather than impaired in this setting, and the change is aldosterone-driven rather than a direct drug effect. Impaired H+ secretion would produce acidosis. This would be the correct answer if the patient had a distal renal tubular acidosis." },
      { "text": "Redistribution of potassium into cells driven by the alkalosis rather than true total-body depletion", "explanation": "Incorrect. Alkalosis does shift potassium intracellularly, but here the alkalosis is a consequence of the same renal potassium and hydrogen handling, and there is genuine urinary potassium loss with total-body depletion. This would be the correct answer if the hypokalemia followed an acute respiratory alkalosis with no urinary potassium wasting." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: hypokalemic metabolic alkalosis with hypochloremia is the fingerprint of upstream sodium blockade plus RAAS activation.",
    "pdfPage": 19,
    "pdfQuote": "aldosterone (due to RAAS activation) upregulates ENaC and"
  },
  {
    "id": 7,
    "category": "Pharmacology: Diuretic Adverse Effects",
    "questionText": "A 66-year-old woman on long-term thiazide therapy is found to have a serum magnesium of 1.2 mg/dL on routine monitoring. She has no diarrhea, takes no proton pump inhibitor, and eats a normal diet. Which mechanism explains her urinary magnesium wasting?",
    "options": [
      { "text": "Downregulation of the apical TRPM6 channel after distal convoluted tubule remodeling", "explanation": "Correct. Chronic thiazide exposure causes structural remodeling of the distal convoluted tubule with downregulation of the apical TRPM6 magnesium channel, the main route for transcellular magnesium reabsorption at this site. Less magnesium is reclaimed and urinary wasting increases. Because this develops over time with continued therapy, magnesium should be monitored in patients on chronic thiazides." },
      { "text": "Loss of the lumen-positive potential in the thick ascending limb that normally drives paracellular magnesium uptake", "explanation": "Incorrect. That is the loop diuretic mechanism: blocking NKCC2 removes the lumen-positive potential and dumps both magnesium and calcium into the urine. Thiazides do not act in the thick ascending limb. This would be the correct answer if the patient were on furosemide with concurrent hypocalcemia." },
      { "text": "Competitive displacement of magnesium from albumin binding sites by the diuretic", "explanation": "Incorrect. Magnesium is only partly protein bound and thiazides do not meaningfully displace it; displacement would alter free fraction, not net renal loss. This would be the correct answer if the question concerned a drug that alters protein binding of a highly bound cation." },
      { "text": "Increased intestinal secretion of magnesium driven by the drug's sulfonamide moiety", "explanation": "Incorrect. The sulfonamide moiety is a structural feature relevant to allergy cross-reactivity, not to intestinal magnesium handling, and the vignette excludes gastrointestinal losses. This would be the correct answer if the patient had chronic diarrhea or malabsorption." },
      { "text": "Aldosterone-mediated upregulation of a basolateral magnesium exporter in principal cells", "explanation": "Incorrect. Aldosterone acts on sodium, potassium and hydrogen handling in principal and intercalated cells; magnesium handling in this lecture is a distal convoluted tubule phenomenon centered on TRPM6. This would be the correct answer if magnesium loss tracked directly with aldosterone excess." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: TRPM6 - the M stands for magnesium - is downregulated by chronic thiazide-induced DCT remodeling, so check magnesium on long-term therapy.",
    "pdfPage": 15,
    "pdfQuote": "downregulation of apical TRPM6 magnesium"
  },
  {
    "id": 8,
    "category": "Pharmacology: Metabolic Effects of Diuretics",
    "questionText": "A 59-year-old man with prediabetes is started on a thiazide diuretic. Three months later his fasting glucose has risen from 108 to 141 mg/dL, his serum potassium is 3.1 mEq/L, and his triglycerides are mildly elevated. Which mechanism is the primary driver of his hyperglycemia?",
    "options": [
      { "text": "Thiazides directly antagonize the insulin receptor tyrosine kinase in skeletal muscle and adipose tissue", "explanation": "Incorrect. Thiazides do reduce tissue utilization of glucose, but through a general impairment of insulin sensitivity rather than direct receptor antagonism, and this is described as a contributing rather than primary mechanism. This would be the correct answer if a drug were shown to bind and block the insulin receptor itself." },
      { "text": "Increased hepatic gluconeogenesis driven by the compensatory rise in circulating aldosterone", "explanation": "Incorrect. RAAS activation is a real consequence of thiazide therapy, but the lecture attributes hyperglycemia to impaired insulin release and reduced insulin sensitivity, not to aldosterone-driven gluconeogenesis. This would be the correct answer if the question concerned glucocorticoid excess." },
      { "text": "Hypokalemia impairs beta-cell ATP-sensitive K+ channel function and insulin release", "explanation": "Correct. Glucose entry into the pancreatic beta cell triggers a cascade in which the ATP-sensitive potassium channel depolarizes the membrane, calcium channels open, and insulin is released. Low serum potassium disrupts that channel's function and impairs insulin release, and this is identified as the primary mechanism. Reduced tissue glucose utilization adds a second contribution, and the mild dyslipidemia follows from the same impaired insulin sensitivity." },
      { "text": "Osmotic diuresis with glycosuria depletes the beta-cell insulin reserve over several months", "explanation": "Incorrect. Thiazides do not cause glycosuria or an osmotic diuresis; that description fits SGLT2 inhibitors, which the lecturer mentions only in passing as behaving like mild osmotic diuretics. This would be the correct answer if the patient were taking an SGLT2 inhibitor." },
      { "text": "Sulfonamide-mediated destruction of pancreatic beta cells producing an absolute insulin deficiency", "explanation": "Incorrect. The sulfonamide moiety is a structural feature of thiazide-type drugs and is not cytotoxic to beta cells; the defect here is functional and reversible with potassium repletion. This would be the correct answer if the patient had autoimmune or toxic destruction of islets with C-peptide deficiency." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: fix the potassium and you often fix the glucose - hypokalemia blocks the beta-cell K-ATP channel and impairs insulin release.",
    "pdfPage": 20,
    "pdfQuote": "Hypokalemia disrupts the function of the ATP-sensitive K+ channels"
  },
  {
    "id": 9,
    "category": "Pharmacology: Drug Interactions",
    "questionText": "A 42-year-old woman with bipolar disorder maintained on a stable dose of lithium for six years is started on a thiazide diuretic for hypertension. Ten days later she presents with coarse tremor, nausea, ataxia and confusion. Her lithium dose has not changed. Which mechanism best explains the rise in her lithium level?",
    "options": [
      { "text": "Competition between lithium and the diuretic for organic anion transporters in the proximal tubule reduces lithium secretion", "explanation": "Incorrect. Lithium is a cation and is not handled by organic anion transporters; the OAT pathway is how the thiazide itself reaches the tubular lumen, which is why probenecid interferes with the diuretic rather than with lithium. This would be the correct answer if the interacting drug were probenecid blunting thiazide efficacy." },
      { "text": "Compensatory proximal reabsorption of sodium and lithium raises plasma lithium", "explanation": "Correct. Lithium takes advantage of sodium transporters. When the thiazide increases sodium excretion and contracts effective circulating volume, the proximal tubule compensates by reabsorbing sodium avidly, and lithium is reclaimed along with it. Plasma lithium rises, and because lithium has a very narrow therapeutic window even a modest increase can produce the neurologic toxicity described here." },
      { "text": "Displacement of lithium from plasma protein binding sites increases the free, pharmacologically active fraction", "explanation": "Incorrect. Lithium is not protein bound to any meaningful degree, so displacement interactions do not apply to it. This would be the correct answer if the interacting drug were displacing a highly albumin-bound agent such as warfarin or phenytoin." },
      { "text": "Inhibition of hepatic CYP3A4 metabolism slows lithium clearance and prolongs its half-life", "explanation": "Incorrect. Lithium is an ion that is eliminated unchanged by the kidney and is not metabolized by cytochrome P450 at all. This would be the correct answer if the interacting drug were a strong CYP3A4 inhibitor given with eplerenone." },
      { "text": "Thiazide-induced hypokalemia increases the sensitivity of neurons to a normal serum lithium concentration", "explanation": "Incorrect. Thiazides do cause hypokalemia, and hypokalemia does potentiate digoxin toxicity, but the lithium interaction is a genuine pharmacokinetic increase in plasma level rather than a sensitization effect. This would be the correct answer if the drug in question were digoxin." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: lithium rides sodium transporters, so any drug that triggers avid proximal sodium reabsorption can push a narrow-window lithium level into toxicity.",
    "pdfPage": 16,
    "pdfQuote": "compensatory reabsorption of both Na+ and Li+"
  },
  {
    "id": 10,
    "category": "Pharmacology: Drug Interactions",
    "questionText": "A 68-year-old man with gout and hypertension has been well controlled on a thiazide. After a urate-lowering agent that inhibits renal organic anion transport is added, his blood pressure rises and his weight increases despite unchanged dosing and good adherence. Serum drug concentration is unchanged. Which mechanism explains the loss of effect?",
    "options": [
      { "text": "Induction of hepatic metabolism accelerates clearance and lowers the amount of active drug", "explanation": "Incorrect. Thiazides are largely not metabolized and are excreted as intact drug, and the vignette specifically states that the serum concentration is unchanged, which excludes an elimination interaction. This would be the correct answer if the added agent were a strong enzyme inducer acting on a hepatically cleared drug." },
      { "text": "Enhanced glomerular filtration of the diuretic washes it through the nephron before it can act", "explanation": "Incorrect. Faster passage through the nephron is not how these drugs lose effect, and thiazides are only partly filtered because they are protein bound. This would be the correct answer if the concern were rapid transit in a hyperfiltering state, which is not a mechanism taught here." },
      { "text": "Increased plasma protein binding reduces the fraction of drug available for tubular secretion", "explanation": "Incorrect. Protein binding of thiazides is moderate and is not altered by this interaction; the block is at the transporter, not at the binding step. This would be the correct answer if the added drug were a high-affinity albumin binder changing the free fraction." },
      { "text": "Antagonism at the NCC transporter itself prevents the diuretic from occupying its binding site", "explanation": "Incorrect. Urate-lowering agents that act on organic anion transporters do not compete at the sodium-chloride cotransporter; the interaction is about drug delivery, not receptor competition. This would be the correct answer if the two drugs shared a common target site in the distal tubule." },
      { "text": "Organic anion transporter blockade lowers drug levels inside the nephron", "explanation": "Correct. Because thiazides are protein bound, most of the dose reaches its luminal target by secretion into the proximal tubule via organic anion transporters. Probenecid is a potent OAT inhibitor and was designed specifically to block that family of transporters. Blocking them keeps the diuretic in the blood rather than in the tubular fluid, so the concentration at the site of action falls and efficacy drops even though the plasma level looks normal." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: a diuretic can fail with a perfectly normal serum level if OAT-mediated secretion into the tubule is blocked.",
    "pdfPage": 20,
    "pdfQuote": "Probenecid is a potent inhibitor of organic anion transporters"
  },
  {
    "id": 11,
    "category": "Pharmacology: Drug Interactions",
    "questionText": "A 64-year-old man on a thiazide for hypertension begins taking over-the-counter naproxen twice daily for shoulder pain. Two weeks later his blood pressure has risen from 128/78 to 152/92 mmHg and he has developed mild ankle edema. Which combination of mechanisms best explains this?",
    "options": [
      { "text": "Efferent arteriolar dilation lowers glomerular capillary pressure and markedly reduces filtration fraction", "explanation": "Incorrect. Efferent dilation is the hallmark of ACE inhibitors and ARBs, not of NSAIDs, which act on the afferent side by removing prostaglandin-mediated vasodilation. This would be the correct answer if the added drug were lisinopril in a patient with renal artery stenosis." },
      { "text": "Enhanced organic anion transporter secretion delivers excess drug and causes tachyphylaxis at the NCC", "explanation": "Incorrect. NSAIDs inhibit rather than enhance organic anion transport, and tachyphylaxis at the transporter is not a described phenomenon. This would be the correct answer if increased delivery of drug produced receptor downregulation, which does not occur here." },
      { "text": "Suppression of aldosterone secretion causes sodium wasting and reflex vasoconstriction", "explanation": "Incorrect. NSAIDs do suppress renin and therefore aldosterone, but the consequence is potassium retention rather than sodium wasting, and it does not explain rising blood pressure with edema. This would be the correct answer if the question asked why an NSAID raises serum potassium in a patient on a potassium-sparing agent." },
      { "text": "Afferent constriction cuts renal blood flow, GFR and drug delivery to the DCT", "explanation": "Correct. NSAIDs block renal prostaglandin synthesis, removing the afferent arteriolar vasodilation that supports renal blood flow. Filtration pressure and GFR fall, and both filtration and OAT-mediated secretion deliver less thiazide to the distal convoluted tubule. On top of that, NSAIDs directly increase sodium and water reabsorption upstream of the NCC, which blunts the blood pressure lowering effect and promotes edema." },
      { "text": "Increased free water clearance from removal of the tonic prostaglandin inhibition of vasopressin", "explanation": "Incorrect. Removing prostaglandin opposition ENHANCES vasopressin effect and water reabsorption, which decreases free water clearance and increases hyponatremia risk. This would be the correct answer if the question asked why NSAIDs increase the risk of thiazide-induced hyponatremia." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: always ask about OTC NSAIDs - they blunt every diuretic by cutting renal blood flow, cutting drug delivery, and retaining sodium.",
    "pdfPage": 21,
    "pdfQuote": "Afferent arteriole vasoconstriction that lowers renal blood flow and drug secretion"
  },
  {
    "id": 12,
    "category": "Pharmacology: Diuretic Combinations",
    "questionText": "A 72-year-old man with refractory edema is on a maximal dose of a loop diuretic with an inadequate response. A second diuretic acting in the distal convoluted tubule is added, and urine output increases substantially more than either drug produced alone. What is the mechanistic basis for this synergy?",
    "options": [
      { "text": "Both agents inhibit the same transporter, so the combination achieves complete transporter occupancy", "explanation": "Incorrect. The two drugs act at entirely different transporters in different nephron segments, NKCC2 in the thick ascending limb and NCC in the distal convoluted tubule; that difference is the whole point. This would be the correct answer if two agents of the same class were being combined, which would add toxicity without synergy." },
      { "text": "The added drug prolongs the half-life of the loop diuretic by competing for tubular secretion", "explanation": "Incorrect. A pharmacokinetic interaction of that kind would blunt rather than enhance the response, as happens with probenecid. The synergy here is pharmacodynamic and anatomic. This would be the correct answer if the question described reduced loop diuretic efficacy after adding an OAT inhibitor." },
      { "text": "The added drug reverses the compensatory rise in aldosterone that limits loop diuretic efficacy", "explanation": "Incorrect. A thiazide contracts volume and therefore ACTIVATES rather than reverses RAAS; blunting aldosterone is what a mineralocorticoid receptor antagonist does. This would be the correct answer if spironolactone had been added to the regimen." },
      { "text": "Blocking NCC prevents distal recapture of the sodium load escaping the thick ascending limb", "explanation": "Correct. When a loop diuretic blocks NKCC2, a large sodium load is delivered downstream and a substantial fraction is reclaimed at distal sites, especially by the NCC in the distal convoluted tubule. Adding a thiazide blocks that second reabsorptive site, so the escaped sodium continues down the nephron and is excreted. This sequential nephron blockade produces a synergistic natriuretic and diuretic effect and is a standard strategy in refractory edema." },
      { "text": "The combination restores the medullary osmotic gradient that the loop diuretic had abolished", "explanation": "Incorrect. Thiazides act distal to the thick ascending limb and play no part in generating the medullary gradient, so they cannot restore it. This would be the correct answer if a drug existed that rebuilt medullary tonicity during loop diuretic therapy." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: sequential nephron blockade works because the nephron reclaims downstream what you blocked upstream - block both sites and the sodium leaves.",
    "pdfPage": 21,
    "pdfQuote": "Reduction of edema by sequential nephron blockade"
  },
  {
    "id": 13,
    "category": "Pharmacology: Potassium-Sparing Diuretics",
    "questionText": "A resident asks why amiloride and spironolactone are both described as weak diuretics even though they act on a segment that is under tight hormonal control. Which statement provides the correct mechanistic basis?",
    "options": [
      { "text": "They must compete with endogenous organic cations for tubular secretion, so luminal concentrations stay low", "explanation": "Incorrect. Amiloride does reach the nephron by organic cation transporter secretion, but competition for that pathway is not why the class is weak, and spironolactone does not need to reach the lumen at all. This would be the correct answer if the question asked how amiloride gains access to the tubular fluid." },
      { "text": "Only 2-5% of filtered sodium is reabsorbed at their site of action", "explanation": "Correct. Both classes act on principal cells of the late distal convoluted tubule, connecting tubule and collecting ducts, and only about 2-5% of the filtered sodium load is reabsorbed there. Blocking a small fraction of total sodium reabsorption can only produce a small natriuresis, and water follows sodium, so diuresis is small as well. This is why they are used as adjuncts rather than as primary agents for edema." },
      { "text": "Their onset of action is too slow for the drug to reach steady state during a dosing interval", "explanation": "Incorrect. Half-lives of these agents comfortably support once- or twice-daily dosing, and steady state is readily achieved. Efficacy is limited by anatomy, not by kinetics. This would be the correct answer if a drug had a duration far shorter than its dosing interval." },
      { "text": "Compensatory upstream sodium reabsorption in the proximal tubule fully offsets any distal blockade", "explanation": "Incorrect. Compensatory reabsorption is a real limitation for proximally acting agents such as carbonic anhydrase inhibitors, where distal segments reclaim the load. For a drug acting at the last reabsorptive site there is no downstream segment left to compensate. This would be the correct answer if the drug were acetazolamide." },
      { "text": "They act only in the presence of high circulating aldosterone, which most patients do not have", "explanation": "Incorrect. This is partly true of MR antagonists, whose potency scales with the aldosterone level, but it is not true of ENaC inhibitors, which block the channel regardless, and it is not the explanation given for the class. This would be the correct answer if the question asked why spironolactone works so well in cirrhotic ascites." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: diuretic potency is set by how much filtered sodium is still available at the site of action - 2-5% at the principal cell means a weak diuretic.",
    "pdfPage": 34,
    "pdfQuote": "Approximately 2-5% of sodium excretion occurs in the principal cells"
  },
  {
    "id": 14,
    "category": "Pharmacology: Potassium-Sparing Diuretics",
    "questionText": "A 55-year-old woman started on a weak diuretic to offset the potassium loss from her thiazide now has a serum potassium of 5.4 mEq/L. Her aldosterone level is normal and she takes no other medications. Which single electrical event explains the potassium retention?",
    "options": [
      { "text": "Loss of the lumen-negative potential removes the gradient for K+ secretion", "explanation": "Correct. Sodium entering the principal cell through ENaC leaves the tubular lumen electrically negative, and that lumen-negative transepithelial potential is what drives potassium out of the cell through ROMK. When sodium entry is blocked, the potential is neutralized, the electrochemical gradient for potassium secretion disappears, and potassium is retained in the blood. This is the shared final pathway for both ENaC inhibitors and MR antagonists, and it is the source of the hyperkalemia risk." },
      { "text": "Inhibition of the basolateral Na+/K+ ATPase prevents potassium from entering the principal cell at all", "explanation": "Incorrect. The Na+/K+ ATPase continues to load potassium into the cell; what changes is the driving force for its exit into the lumen. Blocking the pump would produce a very different and far more toxic picture. This would be the correct answer if the drug were a cardiac glycoside acting on the sodium pump." },
      { "text": "Reversal of the lumen-positive potential in the thick ascending limb reduces paracellular potassium flux", "explanation": "Incorrect. The lumen-positive potential belongs to the thick ascending limb and governs paracellular calcium and magnesium movement, not the collecting duct potassium story. This would be the correct answer if the question concerned loop diuretic effects on divalent cations." },
      { "text": "Increased hydrogen secretion by type A intercalated cells consumes the gradient available for potassium", "explanation": "Incorrect. Hydrogen secretion is actually decreased when aldosterone action is blocked, which contributes to the mild metabolic acidosis of this class rather than explaining potassium retention. This would be the correct answer if the question asked why potassium-sparing agents produce a mild acidosis." },
      { "text": "Direct pharmacologic blockade of the ROMK channel prevents potassium from leaving the cell", "explanation": "Incorrect. Neither ENaC inhibitors nor MR antagonists bind ROMK; the channel is simply left without a driving force. This is a common student misconception. This would be the correct answer if a selective ROMK blocker were being described." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: potassium sparing is not a potassium drug effect - it is the disappearance of the lumen-negative voltage that ENaC normally creates.",
    "pdfPage": 34,
    "pdfQuote": "abolishes the transepithelial potential difference"
  },
  {
    "id": 15,
    "category": "Pharmacology: Potassium-Sparing Diuretics",
    "questionText": "Two potassium-sparing agents are compared. One reaches its target by secretion into the tubular lumen and plugs a channel from the luminal side; the other requires several hours to take effect and continues to act long after plasma levels have fallen. Which statement describes the second agent?",
    "options": [
      { "text": "It is secreted into the lumen by organic anion transporters and plugs the channel pore from outside", "explanation": "Incorrect. This describes a luminally acting agent with a rapid onset, which is the first drug in the comparison rather than the second, and organic anion transport is not how the cationic ENaC inhibitors travel either. This would be the correct answer if the question were describing the route by which a thiazide reaches the distal convoluted tubule." },
      { "text": "It competitively antagonizes aldosterone at a cell surface G protein-coupled receptor on the luminal membrane", "explanation": "Incorrect. The mineralocorticoid receptor is an intracellular nuclear receptor in the cytosol, not a surface G protein-coupled receptor, which is precisely why the onset and offset are slow. This would be the correct answer if aldosterone signaled through a membrane receptor with second messengers." },
      { "text": "It binds a cytosolic receptor and blocks transcription of ENaC and ROMK", "explanation": "Correct. MR antagonists diffuse across the basolateral membrane and bind the mineralocorticoid receptor in the cytosol of principal cells. The drug-receptor complex translocates to the nucleus and binds response elements on DNA, blocking transcription of the genes aldosterone normally upregulates, including ENaC, the Na+/K+ ATPase and ROMK. Because the effect requires changes in gene expression and protein turnover, onset and offset lag well behind the plasma concentration, which is why eplerenone acts for 7-9 hours despite a half-life under 2 hours." },
      { "text": "It irreversibly alkylates the epithelial sodium channel, so recovery requires synthesis of new channels", "explanation": "Incorrect. No agent in this lecture alkylates ENaC; amiloride binds reversibly, and its long duration comes from high potency and slow dissociation rather than covalent modification. This would be the correct answer if a drug covalently inactivated its target, as aspirin does to cyclooxygenase." },
      { "text": "It inhibits 11-beta-hydroxysteroid dehydrogenase type 2, allowing cortisol to activate the receptor", "explanation": "Incorrect. That enzyme protects the mineralocorticoid receptor by converting cortisol to inactive cortisone; inhibiting it would cause apparent mineralocorticoid EXCESS with hypertension and hypokalemia, the opposite of a potassium-sparing effect. This would be the correct answer if the question concerned licorice ingestion." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: MR antagonists work by blocking gene transcription, so their duration of action is set by protein turnover, not by plasma half-life.",
    "pdfPage": 34,
    "pdfQuote": "MR antagonists pass through the basolateral membrane"
  },
  {
    "id": 16,
    "category": "Pharmacology: Vasopressin Resistance",
    "questionText": "A 38-year-old man on lithium for 9 years reports urinating more than 6 liters daily and constant thirst. Serum sodium is 148 mEq/L, urine osmolality is 120 mOsm/kg, and it does not rise after desmopressin. His psychiatrist judges that lithium must be continued for now. He is started on a low-sodium, low-protein diet, an NSAID, and a distal convoluted tubule diuretic, and over the following weeks his urine volume falls by roughly 40%. Which mechanism explains the fall in urine output?",
    "options": [
      { "text": "The drug restores aquaporin-2 insertion in the collecting duct so that circulating vasopressin becomes effective again", "explanation": "Incorrect. Thiazides act at the distal convoluted tubule and do nothing to AQP2 expression or trafficking; the collecting duct remains unresponsive to vasopressin throughout treatment. Preventing AQP2 downregulation is what an ENaC inhibitor accomplishes by keeping lithium out of the principal cell. This would be the correct answer if the added drug had been amiloride." },
      { "text": "Increased medullary tonicity from distal chloride retention strengthens the osmotic gradient for water reabsorption", "explanation": "Incorrect. The distal convoluted tubule contributes nothing to generation of the medullary osmotic gradient, so the gradient is unchanged by a thiazide. This would be the correct answer if a drug increased urea recycling or NKCC2 activity in the thick ascending limb." },
      { "text": "Direct inhibition of the collecting duct water channel reduces obligatory solute-driven water loss", "explanation": "Incorrect. Inhibiting water channels would worsen rather than reduce water loss, and no diuretic in this lecture blocks aquaporins. This would be the correct answer if a vasopressin receptor antagonist were being used to treat hyponatremia." },
      { "text": "Increased distal sodium delivery raises aldosterone, which drives direct reabsorption of the excess water", "explanation": "Incorrect. Aldosterone promotes sodium reabsorption and potassium secretion at the principal cell; water reabsorption there requires ADH-driven AQP2, which is exactly what is failing in this patient. This would be the correct answer if aldosterone were the hormone that inserts water channels, which it is not." },
      { "text": "Volume contraction raises proximal reabsorption, so less filtrate reaches the collecting duct", "explanation": "Correct. The paradox resolves once you notice that the drug never acts on the collecting duct. Thiazide-induced mild volume contraction activates RAAS and lowers GFR, and the sodium that is still filtered is reabsorbed in the proximal tubule along with water. Far less filtrate therefore reaches the ADH-insensitive collecting duct, and overall urine output falls by up to 30-50%, settling at a new lower steady state that persists while the drug is taken. The low-solute diet reduces the obligatory osmolar load and the NSAID enhances ADH effect by removing prostaglandin opposition." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: in vasopressin resistance a thiazide reduces urine output by sending less fluid downstream, not by making the collecting duct work.",
    "pdfPage": 14,
    "pdfQuote": "overall urine output decreases by up to 30-50%"
  },
  {
    "id": 17,
    "category": "Pharmacology: Nephrolithiasis",
    "questionText": "A 45-year-old woman has passed four calcium oxalate stones in three years. Serum calcium and parathyroid hormone are normal, but 24-hour urinary calcium is 380 mg. She already drinks 3 liters of fluid daily and has modified her diet. A diuretic is added for stone prevention. Which effect of that agent reduces her stone recurrence?",
    "options": [
      { "text": "Alkalinization of the urine increases the solubility of calcium oxalate crystals in the collecting system", "explanation": "Incorrect. Urinary alkalinization is a carbonic anhydrase inhibitor effect, and it actually promotes calcium PHOSPHATE precipitation and stone formation rather than preventing stones. This would be the correct answer if the goal were to alkalinize urine for uric acid or cystine stones with a different agent." },
      { "text": "Increased urine flow rate dilutes all solutes below their saturation thresholds", "explanation": "Incorrect. Increased fluid intake is a component of prevention, but the diuretic is added for a specific effect on calcium handling, and a thiazide produces only moderate diuresis in any case. This would be the correct answer if the question asked about the role of increased fluid intake alone." },
      { "text": "Enhanced parathyroid hormone secretion drives calcium into bone and away from the filtrate", "explanation": "Incorrect. Thiazides do not stimulate PTH secretion, and the calcium-conserving effect is a direct tubular phenomenon. PTH regulates active distal calcium reabsorption physiologically, but it is not the drug mechanism. This would be the correct answer if the therapy were a calcimimetic or a bone-directed agent." },
      { "text": "Chelation of oxalate in the tubular lumen prevents crystal nucleation on tubular epithelium", "explanation": "Incorrect. No diuretic chelates oxalate; oxalate binding is achieved with dietary calcium or agents in the gut lumen, not in the nephron. This would be the correct answer if the intervention were dietary calcium taken with meals to bind intestinal oxalate." },
      { "text": "Reduced urinary calcium lowers supersaturation of calcium salts", "explanation": "Correct. Thiazides decrease calcium excretion through the distal convoluted tubule mechanism in which reduced intracellular sodium drives basolateral NCX1 and calcium enters through apical TRPV5. Lower urinary calcium reduces the supersaturation of calcium oxalate and calcium phosphate, so crystal formation is less likely and recurrence falls in selected hypercalciuric patients. Preventive therapy remains a package of increased fluid intake, dietary modification, weight loss and drug therapy." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: thiazides prevent recurrence in idiopathic hypercalciuric stone formers by lowering urinary calcium and therefore supersaturation.",
    "pdfPage": 14,
    "pdfQuote": "Thiazides decrease Ca2+ excretion, which lowers Ca2+ concentration in"
  },
  {
    "id": 18,
    "category": "Pharmacology: Diuretic Adverse Effects",
    "questionText": "A 58-year-old woman newly diagnosed with primary hypertension was started on hydrochlorothiazide. At follow-up four weeks later her blood pressure has improved. She reports trying to follow dietary advice but admits to eating salted popcorn every afternoon. Routine testing shows a serum potassium of 3.1 mEq/L, previously normal (reference 3.5-5.2). She denies muscle weakness and palpitations. Which mechanism best explains the fall in potassium?",
    "options": [
      { "text": "Direct inhibition of potassium reabsorption by intercalated cells of the cortical collecting duct", "explanation": "Incorrect. Thiazides do not act on intercalated cells, and potassium reabsorption by those cells is not the pathway involved. The potassium loss here is secretion by principal cells driven by an electrical gradient. This would be the correct answer if the drug targeted the H+/K+ ATPase of the alpha-intercalated cell." },
      { "text": "Higher distal sodium delivery drives ENaC-mediated reabsorption and potassium secretion", "explanation": "Correct. Thiazides increase sodium delivery to the aldosterone-sensitive distal nephron, and her high dietary sodium intake increases that delivery further. More sodium enters principal cells through ENaC, the lumen becomes more negative, and potassium follows that electrochemical gradient out through ROMK into the urine. The dietary history is the key detail in the vignette: the salt load is amplifying an effect the drug started." },
      { "text": "Dietary sodium loading suppresses renin and aldosterone, which reduces potassium reabsorption in the distal nephron", "explanation": "Incorrect. Aldosterone promotes potassium SECRETION, not reabsorption, so suppressing it would raise rather than lower serum potassium. Moreover thiazide-induced volume contraction activates RAAS. This would be the correct answer if the question described Liddle syndrome, in which renin and aldosterone are genuinely suppressed." },
      { "text": "Transcellular shift of potassium into skeletal muscle caused by the accompanying metabolic alkalosis", "explanation": "Incorrect. Alkalosis does shift potassium intracellularly, but the alkalosis here is a consequence of the same renal handling, and the dominant problem is genuine urinary potassium loss with total-body depletion. This would be the correct answer if hypokalemia followed acute hyperventilation with no urinary potassium wasting." },
      { "text": "Magnesium depletion has removed the inhibitory influence of intracellular magnesium on ROMK conductance", "explanation": "Incorrect. Magnesium depletion can aggravate refractory hypokalemia and thiazides do cause magnesium wasting through TRPM6 downregulation, but the primary and immediate mechanism here is increased distal sodium delivery. This would be the correct answer if her hypokalemia had proved resistant to potassium repletion alone." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: dietary salt makes thiazide hypokalemia worse, because distal sodium delivery is what drives potassium out through ROMK.",
    "pdfPage": 22,
    "pdfQuote": "Routine laboratory testing reveals serum potassium 3.1 mEq/L"
  },
  {
    "id": 19,
    "category": "Pharmacology: Drug Interactions",
    "questionText": "A 77-year-old woman has taken hydrochlorothiazide uneventfully for three years. Two weeks after starting ibuprofen 600 mg three times daily for hip pain she presents with headache, nausea and gait unsteadiness. Serum sodium is 121 mEq/L, urine osmolality is 540 mOsm/kg, and urine sodium is elevated. Which mechanism explains why the NSAID precipitated her hyponatremia?",
    "options": [
      { "text": "The NSAID reduces glomerular filtration so severely that sodium can no longer be reabsorbed proximally", "explanation": "Incorrect. NSAIDs do reduce GFR through afferent constriction, and that raises AKI risk, but a low GFR would reduce filtered sodium delivery rather than cause the free water retention that produces dilutional hyponatremia. This would be the correct answer if her presentation were a rising creatinine with oliguria rather than hypotonic hyponatremia." },
      { "text": "The NSAID inhibits aldosterone release, causing sodium wasting that exceeds the free water retained", "explanation": "Incorrect. NSAIDs do suppress prostaglandin-dependent renin release and therefore aldosterone, but the clinical consequence of that is potassium RETENTION, and hyponatremia from thiazides is dilutional rather than depletional. This would be the correct answer if the question asked why an NSAID raises potassium in a patient on spironolactone." },
      { "text": "The NSAID displaces the thiazide from albumin, raising free drug levels and intensifying natriuresis", "explanation": "Incorrect. Protein binding displacement is not the described interaction, and increased natriuresis alone does not produce concentrated urine with severe hyponatremia. This would be the correct answer if the interaction were a classic albumin displacement affecting a highly bound narrow-window drug." },
      { "text": "The NSAID removes prostaglandin opposition to ADH, increasing water reabsorption", "explanation": "Correct. Thiazides already impair urine dilution while leaving concentrating ability intact, so free water excretion is limited. Renal prostaglandins normally counteract ADH; blocking their synthesis enhances ADH effect, so more AQP2 is inserted and more free water is reabsorbed. Her high urine osmolality confirms that concentrating ability is fully operational. Water retention now clearly exceeds sodium retention, and dilutional hyponatremia deepens." },
      { "text": "The NSAID competes with the thiazide at the organic anion transporter, causing drug accumulation in blood", "explanation": "Incorrect. NSAIDs do inhibit OATs, but the consequence is less diuretic in the tubule and therefore reduced efficacy, not hyponatremia. This would be the correct answer if the patient's blood pressure had risen and her edema worsened rather than her sodium falling." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: prostaglandins oppose ADH, so an NSAID added to a thiazide converts a limited free water excretion problem into frank hyponatremia.",
    "pdfPage": 15,
    "pdfQuote": "Concomitant NSAID increases risk by enhancing ADH effect"
  },
  {
    "id": 20,
    "category": "Pharmacology: Diuretic Adverse Effects",
    "questionText": "A 61-year-old man with a remote history of podagra starts a thiazide for hypertension. Five weeks later he wakes with an exquisitely painful, red, swollen first metatarsophalangeal joint. Serum uric acid is 10.2 mg/dL, up from 7.1 mg/dL before therapy. His weight is down 2 kg and his blood pressure has improved. Which mechanism best explains the rise in uric acid?",
    "options": [
      { "text": "Volume contraction increases urate reabsorption and reduces its secretion via URAT1", "explanation": "Correct. Extracellular fluid contraction is an expected consequence of thiazide therapy, and hypovolemia enhances proximal tubular reabsorption of uric acid. On top of that, thiazides directly decrease uric acid excretion at the level of the transporter, URAT1, which is a member of the organic anion transporter family. Serum urate therefore rises, and in a patient with a prior tendency to gout that rise is enough to precipitate an acute attack." },
      { "text": "Increased hepatic purine turnover raises uric acid production during chronic diuretic therapy", "explanation": "Incorrect. Thiazides do not increase purine synthesis or turnover; the hyperuricemia is entirely a renal handling problem. This would be the correct answer if the patient had a high cell turnover state such as tumor lysis or a myeloproliferative disorder." },
      { "text": "Hypokalemia impairs urate secretion by reducing the activity of the basolateral sodium pump", "explanation": "Incorrect. Hypokalemia is real here and explains other thiazide problems such as impaired insulin release and digoxin toxicity, but urate handling is governed by volume status and transporter competition rather than by potassium. This would be the correct answer if the question concerned insulin release or digoxin binding." },
      { "text": "Metabolic alkalosis reduces the solubility of monosodium urate in synovial fluid and promotes crystal formation", "explanation": "Incorrect. Local temperature and urate concentration matter far more than systemic pH for crystallization, and the vignette shows a genuine rise in serum urate, so a solubility argument is unnecessary. This would be the correct answer if serum urate had been unchanged and only crystal deposition had increased." },
      { "text": "Competitive inhibition of xanthine oxidase by the sulfonamide moiety increases circulating urate precursors", "explanation": "Incorrect. Inhibiting xanthine oxidase would LOWER uric acid, which is how allopurinol and febuxostat work, and no thiazide has that action. This would be the correct answer if the drug in question were a urate-lowering agent used incorrectly during an acute flare." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: thiazide hyperuricemia is a two-hit renal effect - volume contraction increases urate reabsorption and the drug blocks URAT1-mediated secretion.",
    "pdfPage": 15,
    "pdfQuote": "Hypovolemia associated enhanced uric acid reabsorption and reduced secretion via URAT1"
  },
  {
    "id": 21,
    "category": "Pharmacology: Drug Interactions",
    "questionText": "An 80-year-old woman with heart failure and atrial fibrillation takes digoxin at a stable dose. A thiazide is added for hypertension. Three weeks later she reports nausea and visual disturbance; ECG shows frequent premature ventricular contractions with bidirectional ventricular tachycardia. Serum potassium is 2.9 mEq/L and her digoxin concentration is only slightly above her usual value. Which mechanism best explains the toxicity?",
    "options": [
      { "text": "Alkalosis has increased the ionized fraction of digoxin available to bind cardiac tissue", "explanation": "Incorrect. Digoxin is not an ionizable weak acid whose activity varies with pH in this way, and the metabolic alkalosis is simply a companion finding of the potassium loss. This would be the correct answer if the drug's tissue binding were genuinely pH-dependent." },
      { "text": "The thiazide displaces digoxin from skeletal muscle binding sites and raises the free plasma concentration", "explanation": "Incorrect. The vignette specifically notes that the digoxin level is only slightly changed, so a redistribution explanation cannot account for such marked toxicity. The problem is increased sensitivity at a near-normal level. This would be the correct answer if the digoxin concentration had risen sharply into the toxic range." },
      { "text": "Less K+ competes at the Na+/K+ ATPase, so more digoxin binds", "explanation": "Correct. Digoxin competes with potassium for the extracellular potassium-binding site on the cardiomyocyte Na+/K+ ATPase. When serum potassium falls, less potassium is available to compete, so a greater fraction of pumps are occupied by digoxin and inhibition is stronger at any given serum concentration. The result is intracellular calcium overload, increased automaticity and arrhythmia - which is why the level looks nearly normal while the patient is frankly toxic." },
      { "text": "Reduced renal clearance of digoxin caused by the thiazide has raised the serum concentration into the toxic range", "explanation": "Incorrect. Thiazides do not meaningfully impair digoxin clearance, and the level here is described as only slightly elevated. The interaction is pharmacodynamic rather than pharmacokinetic. This would be the correct answer if amiodarone or quinidine had been added, which do raise digoxin levels." },
      { "text": "Concurrent spironolactone therapy has produced a falsely elevated digoxin assay result", "explanation": "Incorrect. Spironolactone does interfere with serum digoxin assays and give false results, but this patient is on a thiazide and the clinical picture with hypokalemia is genuine toxicity, not an assay artifact. This would be the correct answer if a patient on spironolactone had an unexpectedly high digoxin level without symptoms." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: digoxin toxicity can occur at a normal-looking level whenever potassium is low, because potassium is the competitor at the pump.",
    "pdfPage": 20,
    "pdfQuote": "Digoxin competes with K+ binding to the Na+/K+ ATPase in cardiomyocytes"
  },
  {
    "id": 22,
    "category": "Pharmacology: Potassium-Sparing Diuretics",
    "questionText": "A 19-year-old man is evaluated for hypertension of 168/104 mmHg found at a sports physical. His father and paternal grandmother were both hypertensive before age 25. Serum potassium is 2.8 mEq/L with a bicarbonate of 31 mEq/L. Plasma renin activity and serum aldosterone are both markedly suppressed, and an adrenal CT is normal. Which treatment directly addresses the underlying defect?",
    "options": [
      { "text": "Hydrochlorothiazide with oral potassium supplementation and close monitoring", "explanation": "Incorrect. A thiazide increases distal sodium delivery, which would drive even more sodium through the overexpressed channels and worsen both the hypertension and the potassium loss. This would be the correct answer if the patient had ordinary primary hypertension with normal renin and aldosterone." },
      { "text": "Spironolactone titrated to normalize the serum potassium and the blood pressure", "explanation": "Incorrect. This is the most tempting distractor because it treats the same cell and spares potassium, but a mineralocorticoid receptor antagonist can only block a receptor that aldosterone is activating, and here aldosterone is suppressed. The channels are constitutively overactive independent of the hormone. This would be the correct answer if aldosterone were elevated, as in primary aldosteronism." },
      { "text": "Amiloride plus dietary sodium restriction", "explanation": "Correct. The combination of early-onset hypertension, hypokalemia with metabolic alkalosis, a family history suggesting autosomal dominant inheritance, and suppressed renin AND aldosterone points to Liddle syndrome, a gain-of-function mutation in the genes regulating ENaC. Excess channel expression drives unregulated sodium reabsorption, a deeper lumen-negative potential and increased potassium and hydrogen secretion. Blocking the channel itself with an ENaC inhibitor plus restricting sodium corrects both the hypertension and the hypokalemia." },
      { "text": "An angiotensin converting enzyme inhibitor to interrupt the renin-angiotensin-aldosterone axis", "explanation": "Incorrect. The axis is already suppressed by the sodium and fluid retention, so there is nothing left to block, and this will not correct the primary channel defect. This would be the correct answer if the patient had renovascular hypertension with high renin activity." },
      { "text": "Adrenalectomy after confirmatory adrenal vein sampling to localize the source", "explanation": "Incorrect. Surgery targets an aldosterone-producing adenoma, but aldosterone is suppressed here and the adrenal imaging is normal. The lesion is a renal tubular channel, not an adrenal tumor. This would be the correct answer if the patient had hypertension with hypokalemia and an ELEVATED aldosterone-to-renin ratio." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: hypertension with hypokalemia and BOTH renin and aldosterone suppressed is Liddle syndrome - block the channel, not the receptor.",
    "pdfPage": 27,
    "pdfQuote": "ENaC inhibitor + sodium restriction for treatment of hypertension and hypokalemia"
  },
  {
    "id": 23,
    "category": "Pharmacology: Vasopressin Resistance",
    "questionText": "A 44-year-old woman with bipolar disorder well stabilized on lithium develops polyuria of 5 liters daily with dilute urine that does not concentrate after desmopressin. Her psychiatrist states that no alternative mood stabilizer has controlled her illness. A potassium-sparing agent acting on the luminal membrane of principal cells is added, and her urine volume falls. Which mechanism explains the benefit?",
    "options": [
      { "text": "Increasing the tubular flow rate washes lithium out of the collecting duct before it can be taken up", "explanation": "Incorrect. Increasing flow would if anything worsen the polyuria, and the problem is lithium already inside the principal cell rather than lithium in transit. This would be the correct answer if lithium toxicity were being managed by forced diuresis in an acute overdose." },
      { "text": "Antagonism of the mineralocorticoid receptor reduces aldosterone-driven collecting duct water retention", "explanation": "Incorrect. This describes a different potassium-sparing class acting on a cytosolic receptor, and aldosterone does not control water permeability, which is an ADH and AQP2 function. This would be the correct answer if the question described spironolactone used for cirrhotic ascites." },
      { "text": "Chelation of intracellular lithium accelerates its removal from the principal cell cytoplasm", "explanation": "Incorrect. No diuretic chelates lithium; the strategy is to prevent entry rather than to remove what is already inside. This would be the correct answer if a chelating agent existed for monovalent cations, which it does not in this context." },
      { "text": "Enhanced proximal tubular secretion of lithium lowers its concentration in the tubular fluid", "explanation": "Incorrect. Lithium is filtered and reabsorbed rather than actively secreted, and the drug does not promote lithium secretion. This would be the correct answer if lithium were handled by a secretory pathway that the drug could stimulate." },
      { "text": "Blocking ENaC keeps lithium out of principal cells and preserves AQP2", "explanation": "Correct. Lithium enters principal cells through ENaC because the channel does not discriminate against it, and the Na+/K+ ATPase does not export it, so it accumulates. Chronic accumulation causes principal cell injury and downregulates the expression and trafficking of AQP2, leaving the collecting duct impermeable to water even when ADH is present. Amiloride blocks the channel and prevents that entry, addressing the root cause. A thiazide is usually added for its volume-contraction effect, and lithium levels must be monitored closely." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: lithium enters the principal cell through ENaC and cannot leave - amiloride shuts the door and protects AQP2 expression.",
    "pdfPage": 27,
    "pdfQuote": "Amiloride prevents ENaC-mediated transport of Li+ into principal cells"
  },
  {
    "id": 24,
    "category": "Pharmacology: Drug Interactions",
    "questionText": "A 74-year-old man with hypertension and stage 3 chronic kidney disease takes hydrochlorothiazide with amiloride. His nephrologist adds lisinopril for proteinuria, and he independently begins ibuprofen for back pain. Ten days later serum potassium is 6.2 mEq/L with peaked T waves. Which mechanism best explains the additive hyperkalemia contributed by the two newly added drugs?",
    "options": [
      { "text": "Both agents inhibit the Na+/K+ ATPase in skeletal muscle, shifting potassium out of cells into plasma", "explanation": "Incorrect. Neither an ACE inhibitor nor an NSAID inhibits the sodium pump; that is the mechanism of digitalis toxicity. The hyperkalemia here is renal retention rather than transcellular shift. This would be the correct answer if the patient had taken a large digoxin overdose." },
      { "text": "Reduced aldosterone leaves ENaC and ROMK downregulated, so potassium is retained", "explanation": "Correct. ACE inhibitors, ARBs and direct renin inhibitors all reduce angiotensin II-mediated aldosterone secretion, and NSAIDs suppress prostaglandin-dependent renin release, which lowers angiotensin II-mediated aldosterone as well. Less aldosterone means less upregulation of ENaC, the Na+/K+ ATPase and ROMK, so the lumen-negative potential and potassium secretion both fall. Added to amiloride, which already blocks ENaC directly, and to his renal impairment and age, the effect is additive and dangerous." },
      { "text": "Beta-adrenergic blockade shifts potassium out of cells into the extracellular compartment over days", "explanation": "Incorrect. Beta-blockade can impair cellular potassium uptake, but neither drug added in this vignette is a beta-blocker. This would be the correct answer if the newly added agent had been propranolol in a patient with impaired renal potassium handling." },
      { "text": "Metabolic acidosis from the NSAID drives potassium out of cells in exchange for hydrogen ions", "explanation": "Incorrect. NSAIDs do not produce a metabolic acidosis of this kind, and the mild acidosis of potassium-sparing therapy is a consequence of reduced hydrogen secretion, not the cause of the hyperkalemia. This would be the correct answer if the patient had a mineral acid acidosis such as diabetic ketoacidosis." },
      { "text": "Increased dietary potassium absorption from the gut caused by the combination of the two agents", "explanation": "Incorrect. Neither drug increases intestinal potassium absorption; the kidney is where the potassium balance is failing. Potassium supplements and salt substitutes are separate risk factors worth asking about. This would be the correct answer if the patient had started a potassium chloride supplement or a potassium-based salt substitute." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: RAS inhibitors, NSAIDs, potassium supplements and calcineurin inhibitors are the four groups that turn a potassium-sparing diuretic dangerous.",
    "pdfPage": 28,
    "pdfQuote": "Drug Interactions that increase the risk of"
  },
  {
    "id": 25,
    "category": "Pharmacology: Cirrhosis and Ascites",
    "questionText": "A 56-year-old man with alcohol-related cirrhosis has tense ascites and 2+ pedal edema. Serum albumin is 2.4 g/dL, serum sodium is 129 mEq/L, and urine sodium is very low. He is normotensive with warm extremities and a wide pulse pressure. Which initial diuretic strategy is preferred and why?",
    "options": [
      { "text": "Spironolactone, because secondary hyperaldosteronism is driving the sodium retention", "explanation": "Correct. Portal hypertension raises hydrostatic pressure and transudes fluid into the peritoneum, while nitric-oxide-mediated splanchnic vasodilation lowers systemic vascular resistance; hypoalbuminemia reduces oncotic pressure and worsens the leak. All three reduce effective circulating volume, activating the sympathetic nervous system, the renin-angiotensin-aldosterone system and vasopressin. The patient is in a state of secondary hyperaldosteronism, and because MR antagonist potency scales with the prevailing aldosterone level, spironolactone is the drug of choice here." },
      { "text": "Furosemide alone, because loop diuretics produce the greatest natriuresis of any diuretic class", "explanation": "Incorrect. Loop diuretics are the most potent natriuretics, but furosemide is explicitly not used alone in cirrhotic ascites; it may be combined with spironolactone. Using it alone leaves the aldosterone drive untreated and courts hypokalemia. This would be the correct answer if the patient had acute pulmonary edema requiring rapid volume removal." },
      { "text": "Acetazolamide, because bicarbonate wasting will correct the metabolic alkalosis accompanying ascites", "explanation": "Incorrect. Carbonic anhydrase inhibitors are weak diuretics and are contraindicated in severe hepatic disease because reduced ammonium production can precipitate hyperammonemia and encephalopathy. This would be the correct answer if the goal were treating metabolic alkalosis or altitude sickness in a patient with normal liver function." },
      { "text": "Amiloride, because blocking the epithelial sodium channel directly prevents the sodium reabsorption", "explanation": "Incorrect. An ENaC inhibitor does spare potassium and would reduce distal sodium reabsorption, but the guideline choice targets the hormone driving the process, and spironolactone carries the evidence base in cirrhosis. This would be the correct answer if the patient had Liddle syndrome, where aldosterone is suppressed and the channel is the defect." },
      { "text": "Mannitol, because raising plasma osmolality will draw the ascitic fluid back into the vascular space", "explanation": "Incorrect. Mannitol expands plasma volume and would risk pulmonary edema and electrolyte disturbance without addressing the aldosterone-driven sodium retention. This would be the correct answer if the clinical problem were raised intracranial or intraocular pressure." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: spironolactone is first-line for cirrhotic ascites because the patient is in secondary hyperaldosteronism - and MRA potency tracks the aldosterone level.",
    "pdfPage": 35,
    "pdfQuote": "Spironolactone is drug of choice in the treatment because of its aldosterone antagonism"
  },
  {
    "id": 26,
    "category": "Pharmacology: Mineralocorticoid Receptor Antagonists",
    "questionText": "A 62-year-old man with heart failure with reduced ejection fraction has been on optimal therapy plus a steroidal aldosterone antagonist for eight months. He now reports painful bilateral breast enlargement, reduced libido and erectile dysfunction. Serum potassium is 4.6 mEq/L and renal function is stable. Which management step best addresses his complaint while preserving the therapeutic benefit?",
    "options": [
      { "text": "Continue the current drug and add a low-dose aromatase inhibitor to reverse the breast tissue changes", "explanation": "Incorrect. This treats a downstream consequence while leaving the causative androgen receptor antagonism in place, and it adds an unnecessary drug with its own effects. This would be the correct answer if no MR-selective alternative existed for this indication." },
      { "text": "Stop mineralocorticoid receptor blockade entirely and substitute an epithelial sodium channel inhibitor", "explanation": "Incorrect. An ENaC inhibitor would spare potassium but would not deliver the mortality benefit shown for MR blockade in heart failure, which depends on blocking mineralocorticoid receptors overexpressed in heart and vasculature. This would be the correct answer if the goal were purely to offset thiazide-induced hypokalemia in a patient with hypertension." },
      { "text": "Reduce the dose by half, since the antiandrogenic effects of this class are entirely dose-dependent", "explanation": "Incorrect. Dose reduction may lessen the symptom somewhat, but it also reduces the therapeutic effect and does not eliminate the androgen receptor antagonism, which is a property of the molecule. This would be the correct answer if the adverse effect were a purely dose-dependent electrolyte disturbance such as hyperkalemia." },
      { "text": "Switch to eplerenone, which is MR-selective and lacks antiandrogen activity", "explanation": "Correct. His symptoms come from spironolactone acting as an androgen receptor antagonist and interfering with testosterone biosynthesis, which shifts the estradiol-to-testosterone balance toward estradiol and produces gynecomastia, impotence and loss of libido. Eplerenone is more selective for the mineralocorticoid receptor and finerenone is MR-selective as well, so neither causes these effects. Switching preserves the mineralocorticoid blockade the patient needs while removing the cause of the complaint." },
      { "text": "Add a thiazide diuretic to permit a lower dose of the aldosterone antagonist to be used", "explanation": "Incorrect. Adding a potassium-wasting agent changes the electrolyte balance but does nothing about androgen receptor blockade, and it complicates the regimen. This would be the correct answer if the problem were inadequate diuresis rather than an endocrine adverse effect." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: gynecomastia, impotence and loss of libido belong to spironolactone alone - eplerenone and finerenone are MR-selective and spare them.",
    "pdfPage": 33,
    "pdfQuote": "Androgen receptor antagonist and interference with testosterone"
  },
  {
    "id": 27,
    "category": "Pharmacology: Heart Failure",
    "questionText": "A 68-year-old woman with heart failure and an ejection fraction of 30% is stable on guideline-directed therapy. Her potassium is 4.1 mEq/L and eGFR is 62 mL/min. Her cardiologist adds an aldosterone antagonist even though she is euvolemic and needs no further diuresis. Which rationale best supports this decision?",
    "options": [
      { "text": "The drug prevents thiazide-induced hypokalemia, which is the leading cause of arrhythmic death in heart failure", "explanation": "Incorrect. Offsetting potassium wasting is a genuine use of this class, but the vignette gives no thiazide and the heart failure indication rests on tissue effects rather than on electrolyte protection. This would be the correct answer if the patient were hypokalemic on a thiazide for hypertension." },
      { "text": "MR overexpression in heart and vessels drives inflammation, remodeling and fibrosis", "explanation": "Correct. The mineralocorticoid receptor is overexpressed in nonepithelial tissues, including blood vessels and myocardium, where its activation contributes to inflammation, myocardial remodeling and fibrosis in addition to the sodium retention and potassium loss it causes at the distal tubule. Randomized trial evidence supports adding spironolactone to standard therapy in patients with HFrEF or HFpEF who are already stabilized and at low risk for hyperkalemia, and the benefit is an outcome benefit rather than a diuretic one." },
      { "text": "The additional natriuresis produced at the collecting duct lowers preload more effectively than a loop diuretic can", "explanation": "Incorrect. These are weak diuretics acting where only 2-5% of filtered sodium remains, so they cannot outperform a loop diuretic for preload reduction, and the patient is euvolemic anyway. This would be the correct answer if the question asked why a loop diuretic is chosen for acute decompensated heart failure." },
      { "text": "Blocking the receptor increases circulating aldosterone, which exerts protective effects on the myocardium", "explanation": "Incorrect. Aldosterone levels do rise with receptor blockade, but aldosterone is the harmful signal being blocked, not a protective one. This distractor inverts the pathophysiology. This would be the correct answer if aldosterone had a cardioprotective role, which it does not." },
      { "text": "The drug inhibits 11-beta-hydroxysteroid dehydrogenase type 2, allowing cortisol to occupy cardiac receptors", "explanation": "Incorrect. That enzyme protects the mineralocorticoid receptor by inactivating cortisol to cortisone, and inhibiting it would create apparent mineralocorticoid excess rather than blockade. This would be the correct answer if the question concerned the mechanism of licorice-induced hypertension." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: MR antagonists earn their place in HFrEF and HFpEF through antifibrotic and anti-remodeling effects on nonepithelial tissue, not through diuresis.",
    "pdfPage": 32,
    "pdfQuote": "MR overexpression in nonepithelial tissues, such as blood vessels and"
  },
  {
    "id": 28,
    "category": "Pharmacology: Drug Interactions",
    "questionText": "A 59-year-old woman with resistant hypertension is switched from spironolactone to eplerenone after developing breast tenderness. She is also taking clarithromycin for a respiratory infection and drinks two glasses of grapefruit juice each morning. Two weeks later her serum potassium is 5.9 mEq/L. Which mechanism best explains the rise?",
    "options": [
      { "text": "Displacement from alpha-1 acid glycoprotein has increased the free fraction of the drug in plasma", "explanation": "Incorrect. Eplerenone is about 50% bound to alpha-1 acid glycoprotein, but neither clarithromycin nor grapefruit juice acts by displacing it, and modest binding changes rarely produce clinically important effects. This would be the correct answer if the interacting agent were a high-affinity competitor for the same binding protein." },
      { "text": "Conversion of the drug to canrenone, an active metabolite with a long half-life, has prolonged its action", "explanation": "Incorrect. Canrenone is an active metabolite of spironolactone, not of eplerenone; eplerenone has inactive metabolites. This is a plausible mix-up between the two agents. This would be the correct answer if the patient had remained on spironolactone with its enterohepatic circulation and long-acting metabolites." },
      { "text": "Reduced renal excretion of the parent drug caused by the antibiotic's direct nephrotoxicity", "explanation": "Incorrect. Clarithromycin is not characteristically nephrotoxic, and the vignette gives no evidence of falling renal function. The interaction is metabolic. This would be the correct answer if the added antibiotic had been an aminoglycoside with rising creatinine." },
      { "text": "Competitive antagonism at the androgen receptor has increased aldosterone secretion from the adrenal cortex", "explanation": "Incorrect. Eplerenone is MR-selective and has no meaningful androgen receptor activity, which is precisely why she was switched to it. Aldosterone does rise with MR blockade, but that is expected and is not the cause here. This would be the correct answer if the question concerned spironolactone's endocrine adverse effects." },
      { "text": "CYP3A4 inhibition raises eplerenone exposure", "explanation": "Correct. Eplerenone is metabolized by CYP3A4, and both clarithromycin, a strong CYP3A4 inhibitor, and grapefruit juice, which raises eplerenone AUC by roughly 25%, reduce its clearance. Higher drug exposure means more mineralocorticoid receptor blockade, less ENaC and ROMK expression, less potassium secretion and therefore hyperkalemia. The manufacturer recommends avoiding strong CYP3A4 inhibitors and inducers with eplerenone and finerenone." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: eplerenone is a CYP3A4 substrate - strong inhibitors and even grapefruit juice raise exposure and push serum potassium up.",
    "pdfPage": 33,
    "pdfQuote": "Grapefruit juice increases eplerenone AUC ~25% by CYP3A4 inhibition"
  },
  {
    "id": 29,
    "category": "Pharmacology: Osmotic Diuretics",
    "questionText": "A 65-year-old man is admitted with traumatic brain injury and elevated intracranial pressure and receives an intravenous bolus of an inert, freely filtered solute. His neurologic status initially improves. Several hours later he develops acute shortness of breath, crackles on lung exam and an oxygen saturation of 88%. Chest imaging shows bilateral pulmonary edema. His echocardiogram from admission showed an ejection fraction of 35%. Which mechanism explains this complication?",
    "options": [
      { "text": "The solute crossed the injured blood-brain barrier and produced rebound cerebral and pulmonary edema", "explanation": "Incorrect. Accumulation in injured brain tissue is a recognized concern and is the reason intermittent boluses rather than continuous infusion are used, but it would present as worsening neurologic status rather than as acute bilateral pulmonary edema with crackles. This would be the correct answer if he had deteriorated neurologically with rising intracranial pressure after repeated dosing." },
      { "text": "Profound osmotic diuresis produced hypovolemia with hypernatremia and secondary pulmonary vasoconstriction", "explanation": "Incorrect. Excessive diuresis with dehydration and hypernatremia is a real adverse effect of this drug, but it produces volume depletion, not the volume overload picture of pulmonary edema. This would be the correct answer if he had presented with hypotension, rising sodium and poor skin turgor." },
      { "text": "Plasma volume expansion raises preload and pulmonary capillary pressure", "explanation": "Correct. The agent stays in the extracellular space and raises plasma osmolality, so the osmotic gradient pulls water from the intracellular to the interstitial to the intravascular compartment. Plasma volume expands rapidly, increasing venous return and therefore preload, which raises pulmonary capillary hydrostatic pressure. In a patient with a reduced ejection fraction the heart cannot pump the extra volume forward, so fluid is forced into the lung tissue and alveolar spaces. Heart failure, renal impairment and existing volume overload are the key risk factors." },
      { "text": "Hypersensitivity to the drug triggered a noncardiogenic capillary leak with alveolar flooding", "explanation": "Incorrect. Allergy to the drug is a listed contraindication, but an allergic reaction would present with typical hypersensitivity features rather than as a delayed hydrostatic pulmonary edema in a patient with known systolic dysfunction. This would be the correct answer if he had urticaria, bronchospasm and hypotension shortly after the infusion." },
      { "text": "Acute kidney injury from the drug caused fluid retention that accumulated over several hours", "explanation": "Incorrect. Nephrotoxicity with acute kidney injury does occur in about 6-7% of patients, particularly with pre-existing renal dysfunction, but it develops over a longer course and the vignette describes an immediate volume shift in a patient with reduced ejection fraction. This would be the correct answer if he had rising creatinine and oliguria over days." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: every drop of water mannitol moves passes through the plasma first, so preload rises before the kidney can clear it - a real hazard in left-sided heart failure.",
    "pdfPage": 46,
    "pdfQuote": "Increased intravascular volume increases venous return to the heart"
  },
  {
    "id": 30,
    "category": "Pharmacology: Osmotic Diuretics",
    "questionText": "A 70-year-old woman with advanced chronic kidney disease and a urine output of less than 100 mL daily receives intravenous mannitol for elevated intracranial pressure after a fall. Over the next several hours her serum sodium falls from 138 to 126 mEq/L, her jugular venous pressure rises, and her blood pressure climbs to 198/108 mmHg. Which mechanism best explains her hyponatremia?",
    "options": [
      { "text": "Profound osmotic diuresis has caused free water loss in excess of electrolyte loss, concentrating the plasma", "explanation": "Incorrect. That sequence produces dehydration with HYPERnatremia and hyperkalemia, and it requires the drug to be excreted, which is impossible here. Her rising jugular venous pressure indicates volume expansion, not depletion. This would be the correct answer if she had a preserved GFR, brisk urine output and a rising serum sodium." },
      { "text": "The drug is metabolized to an osmotically inactive product that leaves free water behind in the plasma", "explanation": "Incorrect. Osmotic diuretics are pharmacologically inert and are not metabolized; that inertness is one of their four defining properties. This would be the correct answer if the agent underwent hepatic conversion, which it does not." },
      { "text": "Increased vasopressin release from the volume expansion has caused excessive free water reabsorption", "explanation": "Incorrect. Volume expansion suppresses rather than stimulates vasopressin release, and her kidneys are barely producing urine, so tubular water handling cannot explain a 12 mEq/L fall. This would be the correct answer if she had a hypovolemic stimulus to non-osmotic ADH release with preserved renal function." },
      { "text": "Retained mannitol pulls water from cells into plasma, diluting serum sodium", "explanation": "Correct. Mannitol requires a functioning kidney because it works by being freely filtered and not reabsorbed. In severe renal impairment or anuria it cannot be excreted, so it is retained in the blood, where it continues to osmotically extract water from cells into the vascular space. The plasma volume rises and everything dissolved in it, including sodium, is diluted. Volume overload with pulmonary edema, hypertensive crisis, hypertensive encephalopathy and renal failure follow, which is why anuria and severe renal disease are contraindications." },
      { "text": "Redistribution of sodium into the intracellular compartment follows the osmotic gradient created by the drug", "explanation": "Incorrect. Sodium is excluded from cells by the Na+/K+ ATPase and does not follow water intracellularly in this setting; it is water movement outward that dilutes plasma sodium. This would be the correct answer if the disturbance were a genuine transcellular cation shift, as with insulin driving potassium into cells." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: mannitol needs a working kidney - in anuria it is retained, keeps pulling water into the plasma, and causes dilutional hyponatremia with volume overload.",
    "pdfPage": 42,
    "pdfQuote": "In patients with severe renal impairment, mannitol cannot be excreted"
  }
];

window.Test_CV31 = Test_CV31;
