// Thinking Process (Part 2 — strictly 2nd/3rd-order vignettes per v5 prompt):
// 1. High-Yield Concept: Application/diagnosis/management of acute and chronic leukemias and MPNs (APL, AML, ALL, CML, CLL, hairy cell, PV, ET, PMF, MDS).
// 2. The "Trap": Confusing APL (medical emergency, ATRA-responsive) with other AML; missing T315I as the ponatinib-only mutation in CML; using platelet transfusion in TTP/HIT; confusing CML blast crisis with new AML.
// 3. Key Distractor: Hydroxyurea is used in CML AND PV AND sickle cell — context matters; imatinib first-line CML BUT ponatinib needed for T315I; ATRA + ATO for low-risk APL replaces chemo.
// 4. Vignette Strategy: Vignettes use full demographics + presenting cytopenia/cytosis + smear and marrow + cytogenetic/molecular result + force student to pick targeted therapy or next best step.
//
// PDF Mapping Check: Found
// PDF Filename: Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf
// Mapping Key: 17-Hematology: Leukemias, Lymphomas, and Plasma Cell Neoplasms - Vignettes (L154 Part 2)
// Status: Verified

const Test_L154_Part2 = [
  {
    "id": 1,
    "category": "Hematology: APL Medical Emergency",
    "questionText": "A 42-year-old woman presents to the ED with fatigue, easy bruising over 2 weeks, and now gingival bleeding and a nosebleed that started this morning. Vitals: T 38.0°C, BP 110/68, HR 110, RR 18. Exam: pale, scattered petechiae and ecchymoses, oozing from IV site, no organomegaly. Labs: WBC 1.5 (60% blasts in peripheral blood), Hgb 7.5, platelets 15K, PT 22 (prolonged), PTT 50 (prolonged), fibrinogen 75 (LOW), D-dimer markedly elevated, schistocytes on smear. Bone marrow shows abnormal promyelocytes with BUNDLED AUER RODS ('faggot cells'). FISH confirms t(15;17) PML-RARA. Which is the most appropriate IMMEDIATE management?",
    "options": [
      { "text": "Standard 7+3 induction chemotherapy (cytarabine + idarubicin) for AML", "explanation": "Incorrect. Standard 7+3 induction is used for most AML subtypes — but NOT for APL. APL is uniquely responsive to ATRA + arsenic trioxide and standard chemotherapy alone is inferior. APL also has a high early mortality from DIC that can be rapidly reversed by ATRA, so starting ATRA empirically is essential. This would be the correct answer for non-APL AML (M1, M2, M4, M5, M7)." },
      { "text": "Initiate ALL-TRANS RETINOIC ACID (ATRA) IMMEDIATELY based on clinical suspicion (even before final cytogenetic confirmation) + arsenic trioxide; aggressive supportive care for DIC (cryoprecipitate to keep fibrinogen >150, FFP, platelets >50K)", "explanation": "Correct. APL (M3 AML) is a MEDICAL EMERGENCY with high early mortality (30-day mortality up to 30%) from severe DIC and hemorrhage (often fatal CNS bleeding). The promyelocyte granules release pro-coagulant tissue factor and fibrinolytic substances, causing simultaneous consumption coagulopathy. ATRA reverses the differentiation block of t(15;17) PML-RARA, allowing maturation of promyelocytes AND rapidly resolving the DIC within days. Management: (1) ATRA immediately upon clinical suspicion — do NOT wait for FISH/cytogenetic confirmation (the clinical picture of pancytopenia + DIC + promyelocytes/faggot cells is enough); (2) ARSENIC TRIOXIDE (ATO) is added — for LOW-RISK APL (WBC <10K), ATRA + ATO alone is curative without chemotherapy; for HIGH-RISK APL (WBC >10K), add anthracycline (idarubicin); (3) AGGRESSIVE SUPPORTIVE CARE: cryoprecipitate to maintain fibrinogen >150, FFP for PT/PTT correction, platelets to >50K (or higher with active bleeding), packed RBCs; (4) Monitor for DIFFERENTIATION SYNDROME (formerly APL syndrome) — occurs ~3-21 days after starting ATRA, presents with fever, dyspnea, weight gain, pulmonary infiltrates, pleural/pericardial effusions, hypotension; treat with dexamethasone (10 mg IV BID), continue ATRA unless severe; (5) Cure rates >90% with ATRA + ATO in low-risk APL." },
      { "text": "Heparin infusion to treat the DIC", "explanation": "Incorrect. Heparin is generally NOT used in APL-DIC because the bleeding tendency dominates. The primary treatment of APL-DIC is to eliminate the underlying cause (ATRA), with supportive transfusion (cryo, FFP, platelets). Heparin can worsen bleeding. This would be the correct answer in a rare DIC variant with predominant thrombosis and minimal bleeding." },
      { "text": "Transfer to ICU for observation only until cytogenetic results return in 48-72 hours", "explanation": "Incorrect. APL has high early mortality from DIC bleeding; waiting 48-72 hours for cytogenetic confirmation before starting ATRA can result in fatal hemorrhage. Start ATRA on clinical suspicion. This would be the correct answer when there is no clinical urgency, which is NEVER true in suspected APL." },
      { "text": "Initiate plasma exchange to remove the abnormal promyelocytes", "explanation": "Incorrect. Plasma exchange is not therapy for APL. The treatment is targeted differentiation with ATRA + ATO. Leukapheresis is occasionally considered in hyperleukocytosis but is NOT routine in APL. This would be the correct answer in TTP." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: APL = MEDICAL EMERGENCY. Start ATRA IMMEDIATELY on clinical suspicion (before FISH results). ATRA + ATO cures low-risk APL (WBC <10K) without chemo. Aggressive supportive care for DIC. Watch for differentiation syndrome.",
    "pdfPage": 3,
    "pdfQuote": "APL"
  },
  {
    "id": 2,
    "category": "Hematology: CML Targeted Therapy",
    "questionText": "A 56-year-old man presents with progressive fatigue, early satiety, and left upper quadrant fullness. Vitals: BP 130/80, HR 78. Exam: massive splenomegaly (16 cm below costal margin), no lymphadenopathy. Labs: WBC 120,000 with marked left shift (myeloblasts 2%, promyelocytes 3%, myelocytes 18%, metamyelocytes 14%, bands 25%, neutrophils 28%, basophils 7%, eosinophils 3%), Hgb 11.5, platelets 480K, LAP score LOW. Bone marrow: hypercellular myeloid hyperplasia with M:E ratio 12:1. FISH POSITIVE for t(9;22) BCR-ABL. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Standard 7+3 induction chemotherapy (cytarabine + anthracycline)", "explanation": "Incorrect. 7+3 is induction for acute leukemias (AML), but this patient has CHRONIC PHASE CML (blasts only 2%, full spectrum of granulocyte maturation visible) — not AML. CML in chronic phase is treated with tyrosine kinase inhibitors, not cytotoxic induction. This would be the correct answer in AML with >20% blasts." },
      { "text": "IMATINIB (Gleevec) — first-generation tyrosine kinase inhibitor targeting BCR-ABL — as first-line therapy in chronic phase CML; alternatively second-generation TKIs (dasatinib, nilotinib, bosutinib) for higher-risk disease or as first-line in some patients", "explanation": "Correct. CHRONIC PHASE CML is now a chronic, manageable disease thanks to TYROSINE KINASE INHIBITORS targeting the BCR-ABL fusion protein from t(9;22). Imatinib (Gleevec, 2001) was the first TKI, revolutionizing CML care — patients with CML in chronic phase on imatinib now have near-normal life expectancy. SECOND-GENERATION TKIs (dasatinib, nilotinib, bosutinib) achieve deeper molecular responses faster and are often used first-line in higher-risk disease or as alternatives. THIRD-GENERATION ponatinib is reserved for refractory disease or for the T315I mutation (which resists imatinib, dasatinib, nilotinib, and bosutinib). MONITORING: quantitative RT-PCR for BCR-ABL transcript every 3 months — goal is MAJOR MOLECULAR RESPONSE (BCR-ABL <0.1% IS). Patients in deep molecular response for ≥2 years can attempt TREATMENT-FREE REMISSION. Side effects: imatinib generally well-tolerated (edema, GI upset, myalgia); dasatinib (pleural effusion, bleeding); nilotinib (QT prolongation, vascular events); ponatinib (arterial events, hepatotoxicity). For ACCELERATED or BLAST PHASE CML, more intensive therapy (combination TKI + chemo) and allogeneic SCT are considered." },
      { "text": "Hydroxyurea monotherapy as definitive therapy", "explanation": "Incorrect. While hydroxyurea was historically used in CML (and is still used briefly for cytoreduction in hyperleukocytosis), it is NOT definitive therapy — it controls counts but does not target BCR-ABL and does not prevent progression to blast crisis. TKIs are definitive. Hydroxyurea remains a useful brief temporizing agent and is also used in PV and sickle cell. This would be the correct answer for hyperleukocytosis temporization." },
      { "text": "Allogeneic stem cell transplant as first-line therapy", "explanation": "Incorrect. In the TKI era, allogeneic SCT is RESERVED for: CML in accelerated/blast phase, failure of multiple TKIs, T315I with intolerance to ponatinib, or some pediatric patients. First-line for chronic phase CML is a TKI — most patients never need transplant. This would be the correct answer for relapsed/refractory CML after multiple TKI failure." },
      { "text": "Watchful waiting with serial CBCs every 3 months", "explanation": "Incorrect. CML in chronic phase will progress to accelerated phase and blast crisis if untreated — TKI therapy should be initiated promptly upon diagnosis. This would be the correct answer in monoclonal B-cell lymphocytosis without symptoms (not CML)." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Chronic phase CML (BCR-ABL+, <10% blasts) = IMATINIB or 2nd-gen TKI (dasatinib/nilotinib/bosutinib). Ponatinib for T315I. Goal: BCR-ABL <0.1% (major molecular response). Allogeneic SCT for blast crisis or TKI failure.",
    "pdfPage": 2,
    "pdfQuote": "imatinib"
  },
  {
    "id": 3,
    "category": "Hematology: Pediatric ALL Induction",
    "questionText": "A 4-year-old boy presents to the ED with a 3-week history of fatigue, pallor, fever, and easy bruising. Vitals: T 38.6°C, HR 130, BP 88/52, RR 24. Exam: lethargic, pale, scattered bruising and petechiae, mild hepatosplenomegaly, no lymphadenopathy. Labs: WBC 45,000 (90% blasts), Hgb 6.5, platelets 12K, LDH 1,500 (elevated), uric acid 8.5, K 4.8, phosphorus 4.6, creatinine 0.6, calcium 9.0. Bone marrow: 95% blasts, TdT POSITIVE, CD19+ CD10+ CD22+ (B-cell ALL), MPO negative. Cytogenetics: hyperdiploidy (favorable), no Philadelphia chromosome. Which is the most appropriate INITIAL management approach?",
    "options": [
      { "text": "Outpatient watchful waiting with weekly CBCs until counts decline spontaneously", "explanation": "Incorrect. ALL is a rapidly progressive acute leukemia that requires immediate hospital admission and chemotherapy. Untreated, it is universally fatal within weeks. This would be the correct answer in a chronic indolent condition." },
      { "text": "Hospital admission, urgent multi-agent INDUCTION CHEMOTHERAPY (typically VINCRISTINE + STEROIDS + L-ASPARAGINASE ± anthracycline) + tumor lysis prophylaxis (IV hydration, allopurinol or rasburicase) + CNS prophylaxis (intrathecal methotrexate); workup includes lumbar puncture, echocardiogram, blood typing", "explanation": "Correct. Childhood B-cell ALL is the most common pediatric malignancy and the most curable adult/pediatric leukemia (cure rates >85% in standard-risk pediatric B-ALL). Management requires HOSPITAL ADMISSION at a pediatric oncology center and follows a multi-phase protocol: (1) INDUCTION — 4 weeks of vincristine + corticosteroids (prednisone or dexamethasone) + L-asparaginase ± anthracycline (daunorubicin), aiming for complete remission; (2) CONSOLIDATION/intensification — high-dose methotrexate + cytarabine + ongoing other agents; (3) MAINTENANCE — 2-3 years of low-intensity oral 6-mercaptopurine + methotrexate; (4) CNS PROPHYLAXIS — intrathecal methotrexate (± cytarabine, hydrocortisone) is critical because ALL has a tropism for the CNS and untreated CNS relapse is common. PRE-TREATMENT WORKUP: (a) TUMOR LYSIS PROPHYLAXIS — IV hydration + allopurinol or rasburicase (this patient has elevated LDH and uric acid, indicating significant tumor burden — TLS risk is high during cytoreduction); (b) Lumbar puncture for CNS staging; (c) Echocardiogram before anthracyclines (baseline EF); (d) Blood typing for likely transfusions; (e) Central line access. POOR prognostic features include: age <1 or >10, hyperleukocytosis (WBC >50K at presentation), Philadelphia chromosome (Ph+ — needs added TKI like imatinib), hypodiploidy, MLL rearrangement, persistent minimal residual disease after induction. This patient has hyperdiploidy (FAVORABLE) and is 4 years old (favorable age), suggesting good prognosis." },
      { "text": "Allogeneic stem cell transplant in first complete remission as primary therapy", "explanation": "Incorrect. Allogeneic SCT in first CR is reserved for pediatric ALL with VERY HIGH-RISK features (e.g., Ph+ ALL pre-TKI era, MLL rearrangement, hypodiploidy, persistent MRD after consolidation, induction failure) — not all standard-risk patients. The patient has favorable features and would receive standard chemotherapy. This would be the correct answer in induction failure or very high-risk features." },
      { "text": "CAR-T cell therapy (tisagenlecleucel) as first-line treatment", "explanation": "Incorrect. CAR-T (CD19-directed, e.g., tisagenlecleucel) is FDA-approved for relapsed/refractory pediatric B-ALL, NOT first-line. Standard induction chemotherapy comes first; CAR-T is reserved for refractory or relapsed disease. This would be the correct answer in relapsed B-ALL after 2+ prior therapies." },
      { "text": "Single-agent imatinib monotherapy", "explanation": "Incorrect. The patient is Ph-NEGATIVE (no Philadelphia chromosome / no BCR-ABL), so imatinib would not be indicated. Even in Ph+ ALL, imatinib is ADDED to standard chemotherapy, not used alone. This would be the correct answer ONLY in Ph+ ALL where imatinib would be added to standard chemo." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Pediatric B-ALL = highly curable (>85% with treatment). Induction = vincristine + steroids + L-asparaginase ± anthracycline. CNS prophylaxis with intrathecal MTX. Tumor lysis prophylaxis (hydration + allopurinol/rasburicase). 2-3 years maintenance.",
    "pdfPage": 1,
    "pdfQuote": "ALL"
  },
  {
    "id": 4,
    "category": "Hematology: CLL with del(17p)",
    "questionText": "A 68-year-old man with newly diagnosed CLL by smudge cells and CD5+ CD19+ CD23+ B cells on flow cytometry presents for treatment planning. He has progressive lymphadenopathy, B symptoms, and Hgb 9.5 (Rai stage 3-4). FISH studies show DELETION 17p (TP53 loss) in 60% of cells. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "FCR (fludarabine + cyclophosphamide + rituximab) chemoimmunotherapy", "explanation": "Incorrect. FCR is highly effective in IGHV-MUTATED CLL WITHOUT 17p deletion or TP53 mutation, where it can produce long-term remissions in younger fit patients. However, del(17p)/TP53-mutant CLL is RESISTANT to chemoimmunotherapy because TP53 loss disables the p53-dependent apoptosis pathway that chemo relies on. Outcomes with FCR in del(17p) are very poor. This would be the correct answer in IGHV-mutated, del(17p)-negative CLL in young fit patients (where it can give durable remission)." },
      { "text": "Targeted therapy with BTK INHIBITOR (acalabrutinib, zanubrutinib, or ibrutinib) or BCL-2 INHIBITOR (venetoclax) + obinutuzumab; AVOID FCR/chemoimmunotherapy", "explanation": "Correct. DEL(17p) / TP53 MUTATION confers a particularly aggressive CLL phenotype with poor response to traditional chemoimmunotherapy (FCR, bendamustine + rituximab) because the disabled p53 pathway prevents chemotherapy-induced apoptosis. Modern first-line therapies for CLL — and especially essential for del(17p) — are TARGETED ORAL AGENTS that work independently of p53: (1) BTK INHIBITORS (Bruton tyrosine kinase): ACALABRUTINIB (preferred over ibrutinib due to better cardiovascular safety, less afib/HTN/bleeding), ZANUBRUTINIB, or IBRUTINIB. Continuous daily oral therapy; very effective in del(17p). (2) BCL-2 INHIBITOR: VENETOCLAX + OBINUTUZUMAB (anti-CD20 mAb) — fixed-duration 12-month regimen achieving deep undetectable MRD remissions. Pre-treatment risk assessment for venetoclax is critical to avoid TUMOR LYSIS SYNDROME (start at low dose, weekly ramp-up, aggressive hydration and uric acid management). For del(17p) specifically, BTK inhibitors and venetoclax are preferred over chemo. Acalabrutinib has overtaken ibrutinib in many centers due to better tolerability." },
      { "text": "Allogeneic stem cell transplant as first-line therapy", "explanation": "Incorrect. Allogeneic SCT in CLL is reserved for select younger, fit patients with VERY POOR-RISK disease that has failed multiple targeted therapies and chemoimmunotherapy. In the modern era of BTK and BCL-2 inhibitors, most CLL patients (even with del(17p)) do not require transplant in first-line. This would be the correct answer in refractory CLL after multiple targeted therapy failures." },
      { "text": "Watchful waiting (the patient has CLL — observation is standard)", "explanation": "Incorrect. Watchful waiting IS appropriate for ASYMPTOMATIC EARLY-STAGE CLL (Rai stage 0-1, Binet A, without active disease features), but this patient has Rai stage 3-4 with progressive lymphadenopathy, B symptoms, and anemia — clear indications for treatment per iwCLL criteria. This would be the correct answer in early-stage asymptomatic CLL." },
      { "text": "Rituximab single-agent therapy", "explanation": "Incorrect. Single-agent rituximab is not effective enough for active CLL requiring treatment. Rituximab is given as part of combination regimens (FCR, BR, venetoclax + obinutuzumab). This would be the correct answer for low-grade relapse maintenance in indolent lymphoma." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: CLL with del(17p)/TP53 mutation = RESISTANT to chemoimmunotherapy. Use targeted therapy: BTK inhibitor (acalabrutinib preferred) OR venetoclax + obinutuzumab. AVOID FCR/BR.",
    "pdfPage": 2,
    "pdfQuote": "CLL"
  },
  {
    "id": 5,
    "category": "Hematology: Hairy Cell Leukemia Treatment",
    "questionText": "A 56-year-old man presents with fatigue, recurrent infections, and a sense of abdominal fullness over 6 months. Vitals: BP 122/74, HR 80. Exam: massive splenomegaly (12 cm below costal margin), no lymphadenopathy. Labs: WBC 2.5 (ANC 600), Hgb 8.5, platelets 75K. Bone marrow aspirate is a 'dry tap' (cannot aspirate). Biopsy shows interstitial infiltrate of small lymphoid cells with abundant cytoplasm and 'hairy' projections, with surrounding reticulin fibrosis. Flow cytometry: CD20+ CD11c+ CD25+ CD103+ CD123+. BRAF V600E mutation POSITIVE. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Imatinib (Gleevec) targeting BRAF V600E", "explanation": "Incorrect. Imatinib targets BCR-ABL in CML, not BRAF. While BRAF inhibitors (vemurafenib, dabrafenib) DO target BRAF V600E (and have activity in hairy cell leukemia as salvage), they are not first-line for newly diagnosed hairy cell. Purine analogues (cladribine, pentostatin) remain first-line. This would be the correct answer in BRAF V600E mutant melanoma." },
      { "text": "Single-agent CLADRIBINE (2-CdA, a purine analog) given as a 5-7 day continuous infusion or daily SC injection; alternative is pentostatin (deoxycoformycin)", "explanation": "Correct. HAIRY CELL LEUKEMIA is a rare indolent B-cell malignancy with distinctive features: middle-aged man + pancytopenia + massive splenomegaly + 'hairy' cells with cytoplasmic projections + bone marrow DRY TAP (due to reticulin fibrosis) + characteristic flow (CD20+ CD11c+ CD25+ CD103+ CD123+) + BRAF V600E mutation (>90% of cases). First-line therapy is the PURINE NUCLEOSIDE ANALOG CLADRIBINE (2-chlorodeoxyadenosine, 2-CdA) — a SINGLE 5-7 day course produces complete remission in >80% of patients with durable responses. Mechanism: resistant to deoxycytidine kinase metabolism → accumulates as triphosphate in cells → DNA damage → apoptosis. Toxicities: profound and prolonged myelosuppression, lymphocyte depletion (CD4+ T-cell suppression for months — opportunistic infection prophylaxis often needed), neurotoxicity at high doses. Alternative purine analog: pentostatin. For RELAPSED disease: rituximab (often combined with cladribine), or moxetumomab pasudotox (anti-CD22 immunotoxin), or BRAF inhibitors (vemurafenib ± rituximab) for BRAF V600E-positive cases, or BTK inhibitors. Splenectomy was historic standard but is no longer first-line." },
      { "text": "Splenectomy as definitive first-line therapy", "explanation": "Incorrect. While splenectomy was historically a key treatment for hairy cell leukemia (before purine analogs), it is NO LONGER first-line. Cladribine is so effective and durable that splenectomy is now reserved for highly select cases (massive symptomatic splenomegaly with refractory disease, splenic rupture). This would be the correct answer in the pre-cladribine era." },
      { "text": "Allogeneic stem cell transplant in first remission", "explanation": "Incorrect. Allogeneic SCT is far too aggressive for hairy cell, which is well-managed with purine analogs. This would be the correct answer in high-risk refractory leukemias with matched donors in young patients." },
      { "text": "Rituximab single-agent therapy", "explanation": "Incorrect. Single-agent rituximab has activity in hairy cell but is not as effective as cladribine for first-line. Rituximab is often added to cladribine for deeper responses, or used in relapse. This would be the correct answer in low-grade B-cell lymphoma with minimal disease, or as adjunct to cladribine." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Hairy cell leukemia = dry tap + massive splenomegaly + BRAF V600E. First-line = single-course CLADRIBINE (2-CdA) — produces durable CR in >80%. Salvage: rituximab, moxetumomab, BRAF inhibitors.",
    "pdfPage": 3,
    "pdfQuote": "TRAP"
  },
  {
    "id": 6,
    "category": "Hematology: Polycythemia Vera Management",
    "questionText": "A 62-year-old man presents with intermittent headache, blurred vision, and intense pruritus after hot showers. PMH: history of DVT 2 years ago. Vitals: BP 144/88, HR 76. Exam: ruddy complexion, mild splenomegaly, no telangiectasias. Labs: Hgb 19.5, Hct 60%, RBC 7.5 million, WBC 12,000, platelets 580K, EPO level LOW. Bone marrow shows hypercellularity with trilineage hyperplasia. JAK2 V617F mutation POSITIVE. Abdominal Doppler shows no portal/hepatic vein thrombosis. Which is the most appropriate management?",
    "options": [
      { "text": "Observation only with serial CBCs", "explanation": "Incorrect. The patient has POLYCYTHEMIA VERA with HIGH-RISK features (prior thrombosis, age >60) requiring active management. Observation alone risks fatal thrombotic event from hyperviscosity. This would be the correct answer in asymptomatic mild secondary erythrocytosis without primary disease." },
      { "text": "Therapeutic PHLEBOTOMY (target Hct <45%) + LOW-DOSE ASPIRIN (81 mg daily) + CYTOREDUCTIVE THERAPY with HYDROXYUREA (because of high-risk features: age >60 and/or prior thrombosis); manage cardiovascular risk factors; ruxolitinib for hydroxyurea-refractory or intolerant patients", "explanation": "Correct. POLYCYTHEMIA VERA is a chronic myeloproliferative neoplasm driven by JAK2 V617F mutation (>95% of cases). Diagnostic criteria: elevated Hgb/Hct + JAK2 mutation + characteristic marrow + low EPO. Classic symptoms: aquagenic pruritus (itching after hot shower, due to mast cell mediator release), erythromelalgia (burning hands/feet), plethora, headache, blurred vision, splenomegaly. KEY RISK: thrombosis (both arterial and venous, including Budd-Chiari syndrome) — the dominant cause of mortality. Management: (1) THERAPEUTIC PHLEBOTOMY — target Hct <45% to reduce hyperviscosity (CYTO-PV trial showed lower thrombosis with <45% target); (2) LOW-DOSE ASPIRIN 81 mg daily for thrombosis prevention; (3) CYTOREDUCTIVE THERAPY for HIGH-RISK patients (age >60 OR prior thrombosis OR very high platelets) — HYDROXYUREA is first-line; PEGYLATED INTERFERON ALFA is preferred in younger patients (no long-term leukemogenic concerns) and during pregnancy; RUXOLITINIB (JAK1/2 inhibitor) for hydroxyurea-refractory or intolerant patients; (4) Cardiovascular risk factor modification (BP, lipids, smoking cessation); (5) Manage pruritus (antihistamines, ruxolitinib, phototherapy); (6) Avoid iron supplementation (paradoxically can stimulate erythropoiesis — most PV patients are mildly iron-deficient from phlebotomy and that's OK); (7) Surveillance for transformation to MDS or AML. LOW-risk patients (age <60 AND no prior thrombosis) typically need only phlebotomy + aspirin." },
      { "text": "Allogeneic stem cell transplant as definitive cure", "explanation": "Incorrect. Allogeneic SCT is rarely used in PV — reserved for transformation to myelofibrosis or AML in young patients. PV in chronic phase is well-managed with phlebotomy + aspirin + hydroxyurea. This would be the correct answer in post-PV myelofibrosis or transformation to AML." },
      { "text": "Erythropoietin therapy to reduce platelet counts", "explanation": "Incorrect. EPO would WORSEN polycythemia (more RBCs!). PV is driven by autonomous erythropoiesis with already low EPO; adding EPO is harmful. This would be the correct answer in CKD anemia, not PV." },
      { "text": "Iron supplementation to address occult iron deficiency", "explanation": "Incorrect. Iron supplementation in PV is generally AVOIDED because it can stimulate more erythropoiesis. PV patients often become mildly iron-deficient from chronic phlebotomy and this is the desired state. This would be the correct answer in true iron deficiency anemia." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: PV management = phlebotomy (target Hct <45%) + aspirin + hydroxyurea for HIGH-RISK (age >60 or prior thrombosis). PegIFN alpha in young/pregnant. Ruxolitinib for refractory. Avoid iron supplementation.",
    "pdfPage": 3,
    "pdfQuote": "JAK2"
  },
  {
    "id": 7,
    "category": "Hematology: APL Differentiation Syndrome",
    "questionText": "A 38-year-old woman with newly diagnosed APL was started on ATRA + arsenic trioxide 8 days ago. Her DIC has resolved. Today she develops new-onset dyspnea, a low-grade fever (38.4°C), and 4 kg of weight gain over 48 hours. Vitals: T 38.4°C, HR 105, BP 95/60 (down from 120/80), RR 24, O2 sat 88% on room air. Exam: bilateral basilar crackles, JVP elevated, mild pedal edema. Labs: WBC 18,000 (up from 2,000 — RISING), Hgb 9.0, platelets 60K. Chest X-ray: new bilateral patchy pulmonary infiltrates and small pleural effusions. Which is the most likely diagnosis and best management?",
    "options": [
      { "text": "Pulmonary embolism — start therapeutic anticoagulation with heparin", "explanation": "Incorrect. While PE is possible in cancer patients, the constellation of features (rising WBC, weight gain, fever, bilateral infiltrates, hypotension, pleural effusions) within ~3-21 days of starting ATRA is highly characteristic of differentiation syndrome. Anticoagulation in APL also carries bleeding risk. This would be the correct answer with focal embolic findings, segmental defects on CT angiography, and no differentiation syndrome features." },
      { "text": "DIFFERENTIATION SYNDROME (formerly retinoic acid syndrome / APL syndrome) — initiate DEXAMETHASONE 10 mg IV BID; continue ATRA unless severe; supportive care", "explanation": "Correct. DIFFERENTIATION SYNDROME (DS) is a serious complication of ATRA (and arsenic trioxide) therapy in APL, occurring in 10-25% of patients, typically 3-21 days after starting therapy. Pathophysiology: as APL blasts differentiate into mature granulocytes, they release inflammatory cytokines causing capillary leak and end-organ infiltration. CLINICAL FEATURES: (1) fever (often the earliest sign), (2) dyspnea/hypoxia, (3) weight gain (capillary leak with fluid retention), (4) hypotension, (5) bilateral pulmonary infiltrates on CXR, (6) pleural and pericardial effusions, (7) acute kidney injury, (8) RISING WBC (sign of differentiation working, but also of risk). MANAGEMENT: (1) START DEXAMETHASONE 10 mg IV BID immediately upon suspicion (do NOT wait for full criteria — early treatment prevents progression to severe disease); (2) Continue ATRA unless very severe (some interrupt and resume after improvement); (3) Supportive care: oxygen, judicious fluid management (capillary leak — diuretics may help volume overload but be cautious with hypotension), monitor renal function, treat any infections. (4) Differentiation syndrome PROPHYLAXIS in high-risk patients (WBC >5K at presentation): prophylactic dexamethasone starting at induction. (5) HYDROXYUREA can be added to reduce WBC if it rises very high (hyperleukocytosis). Mortality from DS has declined significantly with early dexamethasone, from ~30% to ~5-10%. AVOID leukapheresis (can worsen DIC in APL)." },
      { "text": "Septic shock — initiate broad-spectrum antibiotics and aggressive fluid resuscitation", "explanation": "Incorrect. While infection must be considered in a neutropenic or post-chemotherapy patient with fever, the combination of weight gain, pulmonary infiltrates, pleural effusions, hypotension, AND timing within days of ATRA start is highly specific for differentiation syndrome. Antibiotics may be added empirically while assessing for infection, but the primary intervention is dexamethasone. This would be the correct answer with documented bacteremia or clear infectious source without DS features." },
      { "text": "Heart failure exacerbation from anthracycline cardiotoxicity — initiate IV diuresis and discontinue chemotherapy", "explanation": "Incorrect. While anthracycline cardiotoxicity is a recognized concern, it typically presents as new heart failure over weeks-months and would be unusual within 8 days of starting therapy. The picture fits DS. Echocardiogram can help differentiate if needed (DS shows pleural effusions and capillary leak; cardiotoxicity shows decreased EF). This would be the correct answer with documented severe LV dysfunction on echo." },
      { "text": "Continue all current therapy, observe for spontaneous resolution", "explanation": "Incorrect. Differentiation syndrome can progress to severe respiratory failure and death; observation without treatment is not appropriate. Early dexamethasone is critical. This would be the correct answer NEVER in suspected DS." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Differentiation syndrome (3-21 days after ATRA) = fever + dyspnea + weight gain + hypotension + bilateral infiltrates + pleural effusions + RISING WBC. Treat with DEXAMETHASONE 10 mg IV BID immediately. Prophylaxis if WBC >5K at presentation.",
    "pdfPage": 3,
    "pdfQuote": "APL"
  },
  {
    "id": 8,
    "category": "Hematology: Elderly AML Frontline Therapy",
    "questionText": "A 75-year-old man with hypertension and prior MI presents with progressive fatigue, easy bruising, and recurrent infections over 2 months. Vitals: T 37.8°C, BP 130/80, HR 92. Exam: pale, scattered bruising, no significant organomegaly, ECOG performance status 2. Labs: WBC 25,000 (50% blasts with Auer rods), Hgb 7.8, platelets 30K. Bone marrow: 60% myeloblasts with Auer rods, MPO+, CD13+, CD33+, CD117+; cytogenetics show normal karyotype; FLT3 NEGATIVE, NPM1 mutated, IDH2 mutated. He is not a candidate for intensive 7+3 induction due to age, performance status, and cardiac history. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Intensive 7+3 induction (cytarabine + idarubicin) as standard for all AML", "explanation": "Incorrect. Intensive 7+3 induction has substantial treatment-related mortality in elderly or unfit patients (15-30% mortality from induction alone in patients >70). This patient is not a candidate due to age, comorbidities (cardiac), and performance status. This would be the correct answer in a fit younger patient with good performance status." },
      { "text": "AZACITIDINE (hypomethylating agent) + VENETOCLAX (BCL-2 inhibitor) as a less intensive induction; consider midostaurin or gilteritinib if FLT3 mutated; consider ivosidenib for IDH1 or enasidenib for IDH2 mutations; supportive care", "explanation": "Correct. ELDERLY AML or AML in patients UNFIT FOR INTENSIVE INDUCTION is now treated with the LESS-INTENSIVE COMBINATION AZACITIDINE + VENETOCLAX, based on the VIALE-A trial showing improved survival vs azacitidine alone. Mechanism: azacitidine is a HYPOMETHYLATING AGENT (HMA) that inhibits DNA methyltransferase, reactivating tumor suppressor genes; venetoclax is a BCL-2 inhibitor inducing apoptosis. The combination is far better tolerated than 7+3 in elderly patients while achieving meaningful responses (~70% CR/CRi). TUMOR LYSIS SYNDROME prophylaxis is essential during venetoclax ramp-up. Other targeted agents to consider based on molecular profile: (1) MIDOSTAURIN or GILTERITINIB for FLT3-mutated AML; (2) IVOSIDENIB for IDH1-mutated AML; (3) ENASIDENIB for IDH2-mutated AML (this patient has IDH2 mutation — could add or use enasidenib monotherapy in some cases); (4) GEMTUZUMAB OZOGAMICIN (anti-CD33 ADC) for CD33+ AML; (5) GLASDEGIB (hedgehog inhibitor) + low-dose cytarabine; (6) Allogeneic SCT may still be considered in selected older patients with favorable comorbidities and matched donor (reduced-intensity conditioning). Standard supportive care: transfusions, infection prophylaxis, growth factors. The era of 'AML in elderly = palliation only' has ended." },
      { "text": "Supportive care alone (transfusions, antibiotics for infections) without disease-directed therapy", "explanation": "Incorrect. With current less-intensive regimens (azacitidine + venetoclax), even older patients can achieve meaningful responses with manageable toxicity. Supportive care alone is reserved for the most frail patients or for those who choose hospice. This would be the correct answer in a very frail patient (ECOG 4) who has chosen hospice/palliative care only." },
      { "text": "Single-agent imatinib targeting BCR-ABL", "explanation": "Incorrect. The patient has AML, not Ph+ ALL or CML. There is no BCR-ABL target. This would be the correct answer in CML or Ph+ ALL." },
      { "text": "Single-agent ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is specific to APL (M3 AML with t(15;17) PML-RARA) — this patient has non-APL AML with NPM1/IDH2 mutations, normal karyotype. ATRA would not be effective. This would be the correct answer in confirmed APL." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Elderly/unfit AML = azacitidine + venetoclax (less-intensive, VIALE-A trial). Add targeted agents per mutations: FLT3 (midostaurin/gilteritinib), IDH1 (ivosidenib), IDH2 (enasidenib). Era of 'palliation only' is over.",
    "pdfPage": 3,
    "pdfQuote": "AML"
  },
  {
    "id": 9,
    "category": "Hematology: CML T315I and Ponatinib",
    "questionText": "A 48-year-old man with CML in chronic phase (t(9;22) BCR-ABL positive) initially responded to imatinib achieving a complete cytogenetic response after 1 year. However, his BCR-ABL transcript has been rising over 6 months and he has lost his molecular response. He was switched to dasatinib with initial improvement but again lost response. Repeat BCR-ABL kinase domain mutation analysis now shows the T315I mutation. Which is the most appropriate next-line TKI?",
    "options": [
      { "text": "Nilotinib (a second-generation TKI)", "explanation": "Incorrect. Nilotinib is a second-generation TKI but is INACTIVE against T315I (like imatinib, dasatinib, bosutinib). The T315I mutation alters the ATP-binding pocket in a way that prevents these drugs from binding. This would be the correct answer for resistance/intolerance to imatinib without T315I." },
      { "text": "PONATINIB — third-generation TKI specifically designed to overcome T315I; alternatively asciminib (allosteric BCR-ABL inhibitor) for T315I; allogeneic SCT consideration", "explanation": "Correct. The T315I MUTATION ('gatekeeper mutation') in BCR-ABL is the classic mechanism of resistance to first- and second-generation TKIs (imatinib, dasatinib, nilotinib, bosutinib). T315I substitutes isoleucine for threonine at position 315, sterically blocking these drugs from the ATP-binding pocket. THIRD-GENERATION PONATINIB was specifically engineered with a triple-bond linker that bypasses this steric block. Ponatinib is highly effective against T315I and other resistant mutations. However, PONATINIB has significant CARDIOVASCULAR TOXICITY (arterial occlusive events — MI, stroke, peripheral artery disease), so careful cardiovascular risk assessment, BP control, and lipid management are essential. Lower starting doses are now often used to balance efficacy and toxicity. NEWER OPTION: ASCIMINIB is an allosteric inhibitor (binds the myristoyl pocket of BCR-ABL, distinct from the ATP-binding site), active against T315I and other resistant mutations, with a different toxicity profile. ALLOGENEIC SCT remains an option for younger fit patients with T315I or other refractory disease. Always reassess BCR-ABL kinase domain mutations at each loss of response to guide TKI selection." },
      { "text": "Switch back to imatinib at higher dose", "explanation": "Incorrect. Imatinib is INACTIVE against T315I — dose escalation will not overcome the mutation. The patient already failed imatinib, then dasatinib, with documented T315I. Returning to imatinib is futile. This would be the correct answer for some kinase domain mutations sensitive to higher imatinib doses (but NOT T315I)." },
      { "text": "Continue dasatinib at higher dose to overcome resistance", "explanation": "Incorrect. Dasatinib is INACTIVE against T315I. Dose escalation cannot overcome a complete resistance mutation. This would be the correct answer for resistance from non-T315I mutations sensitive to dasatinib at higher doses." },
      { "text": "Hydroxyurea monotherapy", "explanation": "Incorrect. Hydroxyurea is not a targeted CML therapy — it does not target BCR-ABL and does not produce molecular responses. It can transiently reduce WBC in hyperleukocytosis. This would be the correct answer for temporary cytoreduction in CML or PV." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: T315I 'gatekeeper' mutation resists imatinib/dasatinib/nilotinib/bosutinib. Use PONATINIB (cardiovascular toxicity!) or ASCIMINIB (allosteric inhibitor). Consider allogeneic SCT in young fit patients.",
    "pdfPage": 2,
    "pdfQuote": "imatinib"
  },
  {
    "id": 10,
    "category": "Hematology: Essential Thrombocythemia Management",
    "questionText": "A 52-year-old woman is found to have a platelet count of 1,200K on a routine CBC done for fatigue. She is otherwise asymptomatic, no thrombotic history. Vitals: BP 124/78, HR 76. Exam: no organomegaly, normal cardiopulmonary findings. Labs: WBC 9.2, Hgb 13.5, platelets 1,200K confirmed on repeat. CRP normal, ferritin normal, no inflammation or iron deficiency. JAK2 V617F mutation POSITIVE. Bone marrow: increased megakaryocytes with large hyperlobated nuclei. Cytogenetics normal. Which is the most appropriate management?",
    "options": [
      { "text": "Aggressive cytoreduction with hydroxyurea for all patients regardless of risk", "explanation": "Incorrect. ET management is risk-stratified. Young (<60) low-risk patients without thrombosis history may need only observation or low-dose aspirin. Cytoreduction is reserved for HIGH-RISK patients. This patient is age 52 (<60) with no thrombosis history — low-intermediate risk. This would be the correct answer in HIGH-RISK ET (age >60 with thrombosis history)." },
      { "text": "Risk-stratified approach: low-dose ASPIRIN (81 mg daily) for thrombosis prevention since JAK2-positive; consider HYDROXYUREA cytoreduction only if she becomes high-risk (age >60, prior thrombosis, very high platelets >1500K with symptoms, cardiovascular risk factors)", "explanation": "Correct. ESSENTIAL THROMBOCYTHEMIA (ET) is a chronic myeloproliferative neoplasm characterized by sustained thrombocytosis (>450K, often into the millions) without secondary cause. Driver mutations: JAK2 V617F (~60%), CALR (~25%), MPL (~5%), triple negative (~10%). Symptoms when present: erythromelalgia, headache, visual changes, thrombosis (arterial > venous), occasionally paradoxical bleeding (very high platelets can cause acquired vWF deficiency from vWF cleaving on platelet surface). Risk stratification (IPSET): very-low / low / intermediate / high based on age, thrombosis history, JAK2 status, and cardiovascular risk factors. Management by risk: (1) VERY-LOW RISK (age <60, no thrombosis, no JAK2): observation; (2) LOW RISK (age <60, no thrombosis, JAK2+ OR cardiovascular risk factors): low-dose aspirin; (3) INTERMEDIATE RISK: low-dose aspirin; (4) HIGH RISK (age >60 + JAK2+ AND/OR prior thrombosis): low-dose aspirin + cytoreduction. HYDROXYUREA is first-line cytoreduction; alternatives include pegylated interferon (young, pregnancy) or anagrelide (platelet-specific). RUXOLITINIB is reserved for hydroxyurea-refractory cases. AVOID ASPIRIN if extreme thrombocytosis (>1500K) with acquired vWF deficiency (bleeding risk). Pregnancy: aspirin + sometimes interferon. Transformation to MDS, AML, or post-ET myelofibrosis is a long-term risk." },
      { "text": "Plateletpheresis as definitive management of thrombocytosis", "explanation": "Incorrect. Plateletpheresis is reserved for acute symptomatic thrombocytosis with active thrombosis or impending stroke as a temporizing measure — it is not chronic management. Long-term control is achieved with cytoreduction (hydroxyurea, interferon, anagrelide). This would be the correct answer in acute thrombotic crisis with extreme thrombocytosis." },
      { "text": "Allogeneic stem cell transplant for definitive cure", "explanation": "Incorrect. SCT is reserved for ET that has transformed to myelofibrosis or AML; for primary ET, the prognosis is generally favorable with medical management. This would be the correct answer in post-ET myelofibrosis in a young patient." },
      { "text": "Aggressive anticoagulation with warfarin or DOACs as primary prevention", "explanation": "Incorrect. Anticoagulation is reserved for ACTIVE thrombosis treatment, not primary prevention in ET (which uses aspirin). Anticoagulation increases bleeding risk without proven prevention benefit in ET. This would be the correct answer after an established thrombotic event." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: ET management = risk-stratified. Low-risk (age <60, no thrombosis, JAK2+) = low-dose aspirin. High-risk (age >60 OR prior thrombosis) = aspirin + hydroxyurea cytoreduction. Avoid aspirin if extreme thrombocytosis (>1500K, vWF deficiency).",
    "pdfPage": 3,
    "pdfQuote": "JAK2"
  },
  {
    "id": 11,
    "category": "Hematology: Primary Myelofibrosis with Ruxolitinib",
    "questionText": "A 68-year-old man presents with progressive fatigue, drenching night sweats, 8 kg weight loss over 6 months, and abdominal distension. Vitals: T 37.4°C, BP 130/76, HR 84. Exam: cachectic, MASSIVE splenomegaly (palpable to the pelvis), no lymphadenopathy. Labs: WBC 18,000 with leukoerythroblastic picture (immature WBC + nucleated RBCs), Hgb 7.5, platelets 95K. Smear: TEAR-DROP RBCs (dacrocytes), few blasts (3%). Bone marrow ASPIRATE: DRY TAP. BIOPSY: marked reticulin and collagen FIBROSIS with clusters of atypical megakaryocytes. JAK2 V617F mutation POSITIVE. Which is the most appropriate management?",
    "options": [
      { "text": "Observation only — primary myelofibrosis is incurable, so no therapy is indicated", "explanation": "Incorrect. The patient has symptomatic disease (constitutional symptoms, severe splenomegaly, cytopenias) requiring intervention to improve quality of life and survival. Treatment options exist and are effective. This would be the correct answer in asymptomatic, very-low-risk PMF without splenomegaly or constitutional symptoms." },
      { "text": "RUXOLITINIB (JAK1/2 inhibitor) for symptom control and splenomegaly reduction; supportive transfusions for anemia; consider ALLOGENEIC STEM CELL TRANSPLANT as the only curative therapy in eligible patients (age, performance status, donor availability)", "explanation": "Correct. PRIMARY MYELOFIBROSIS (PMF) is the most aggressive MPN. Pathogenesis: clonal HSC mutation (JAK2 ~50%, CALR ~25%, MPL ~5%, triple negative ~10%) → cytokine-driven bone marrow FIBROSIS (collagen + reticulin) → ineffective hematopoiesis → cytopenias + extramedullary hematopoiesis (massive splenomegaly, hepatomegaly) → constitutional B symptoms from cytokines. Diagnostic features: TEAR-DROP RBCs (dacrocytes — distorted by passage through fibrotic marrow), LEUKOERYTHROBLASTIC smear (immature WBC + nucleated RBC, sign of marrow stress/extramedullary hematopoiesis), DRY TAP bone marrow with FIBROSIS on biopsy, driver mutation. Risk stratification (DIPSS, DIPSS+): age, Hgb, WBC, blasts, constitutional symptoms, cytogenetics, transfusion dependence. Management: (1) SYMPTOMATIC: RUXOLITINIB (JAK1/2 inhibitor) markedly reduces splenomegaly and constitutional symptoms within weeks; modest survival benefit. Side effects: dose-related anemia and thrombocytopenia (already present in this patient — adjust dose); withdrawal can trigger rebound symptoms. FEDRATINIB is a second JAK2 inhibitor (boxed warning for Wernicke encephalopathy → supplement thiamine). MOMELOTINIB (newer JAK1/2 inhibitor with ACVR1 activity) is particularly useful in PMF with anemia. PACRITINIB for severe thrombocytopenia. (2) ANEMIA: ESA (epoetin), androgens (danazol), thalidomide/lenalidomide, transfusions, momelotinib. (3) Splenectomy for refractory splenomegaly. (4) CURATIVE: ALLOGENEIC STEM CELL TRANSPLANT is the ONLY curative therapy — reserved for younger fit patients with intermediate-2/high-risk DIPSS scores and matched donors. (5) Risk of transformation to AML (~20% over 10 years)." },
      { "text": "Imatinib targeting BCR-ABL", "explanation": "Incorrect. The patient is BCR-ABL negative (CML t(9;22) is not the driver in PMF). Imatinib has no role. This would be the correct answer in CML." },
      { "text": "Thalidomide single-agent therapy as primary treatment", "explanation": "Incorrect. While thalidomide/lenalidomide can be used adjunctively for anemia in PMF, they are not first-line for the dominant problem here (constitutional symptoms + splenomegaly), which is better managed with ruxolitinib. This would be the correct answer for PMF-associated anemia (with concurrent prednisone for synergy)." },
      { "text": "Splenectomy as immediate first-line therapy", "explanation": "Incorrect. Splenectomy in PMF carries high mortality and morbidity and is reserved for refractory symptomatic splenomegaly or severe transfusion-dependent cytopenias when other therapies have failed. It is NOT first-line. This would be the correct answer in refractory disease after ruxolitinib failure or for very symptomatic splenomegaly with hypersplenism causing transfusion dependence." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: PMF = tear-drop cells + leukoerythroblastic + dry tap + marrow fibrosis + JAK2/CALR/MPL. Treat with RUXOLITINIB (JAK1/2 inhibitor) for symptoms + splenomegaly. Allogeneic SCT = only curative option for eligible patients.",
    "pdfPage": 3,
    "pdfQuote": "myelofibrosis"
  },
  {
    "id": 12,
    "category": "Hematology: MDS with del(5q) and Lenalidomide",
    "questionText": "A 72-year-old woman presents with progressive fatigue and pallor over 6 months. PMH: hypothyroidism. Vitals: BP 128/76, HR 78. Exam: pale, no organomegaly. Labs: Hgb 7.8 (transfusion-dependent for 4 months), MCV 102, RDW 19, WBC 4.0 (mild leukopenia), platelets 280K (NORMAL/elevated), retic 0.8%. Bone marrow: hypercellular with macrocytic erythroid dysplasia, megakaryocyte hypolobation, 4% blasts (no excess), and DEL(5q) [5q minus syndrome] on cytogenetics; no other abnormalities. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Standard 7+3 chemotherapy for AML induction", "explanation": "Incorrect. The patient has MDS, not AML — blasts are 4%, well below the 20% threshold for AML. Intensive AML chemotherapy is not appropriate. This would be the correct answer in AML with blasts ≥20%." },
      { "text": "LENALIDOMIDE — particularly effective in del(5q) MDS, producing high rates of transfusion independence and cytogenetic remission", "explanation": "Correct. The 'DEL(5q) SYNDROME' (also called '5q minus syndrome') is a distinctive MDS subtype with: predominantly REFRACTORY MACROCYTIC ANEMIA, NORMAL or ELEVATED platelets (often surprisingly), mild leukopenia, hypolobated megakaryocytes, and the isolated del(5q) cytogenetic abnormality. It tends to affect older women and has a better prognosis than most MDS. The breakthrough therapy is LENALIDOMIDE (an immunomodulatory drug, IMiD), which produces TRANSFUSION INDEPENDENCE in ~67% of patients and CYTOGENETIC RESPONSE in ~50% — likely via degradation of casein kinase 1α (CK1α), a kinase encoded in the deleted 5q region. The selective sensitivity arises because del(5q) cells already have decreased CK1α levels and are more vulnerable to further reduction. Other MDS therapies (for non-del(5q) MDS or higher-risk MDS): (1) ESAs for low-risk MDS with low EPO; (2) Luspatercept for MDS-RS or after ESA failure; (3) HYPOMETHYLATING AGENTS (azacitidine, decitabine) for higher-risk MDS or as bridge to transplant; (4) Allogeneic SCT for younger fit patients with high-risk disease. Supportive care: transfusions, iron chelation if chronic transfusions (>20-30 units lifetime risk of iron overload), infection management." },
      { "text": "Aggressive iron chelation with deferasirox alone", "explanation": "Incorrect. While iron chelation IS indicated in MDS patients who have received many transfusions (typically >20-30 units) to prevent iron overload, it does not address the underlying disease or anemia. Lenalidomide is the disease-targeted therapy for del(5q) MDS. This would be the correct answer for transfusion-dependent MDS with iron overload after disease-directed therapy." },
      { "text": "Allogeneic stem cell transplant immediately as first-line", "explanation": "Incorrect. Allogeneic SCT in del(5q) MDS is generally not first-line because: (1) prognosis is relatively good, (2) the patient is 72 years old (transplant tolerability decreasing with age), (3) lenalidomide produces excellent responses. SCT is reserved for higher-risk MDS in younger fit patients with matched donors. This would be the correct answer in younger patient (<65-70) with higher-risk MDS and matched donor." },
      { "text": "Watchful waiting only — MDS is incurable", "explanation": "Incorrect. The patient is transfusion-dependent and symptomatic with significant anemia — active management is indicated to reduce transfusion burden and improve quality of life. Lenalidomide can achieve transfusion independence. This would be the correct answer in asymptomatic, transfusion-independent low-risk MDS without significant cytopenias." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Del(5q) MDS ('5q minus syndrome') = macrocytic anemia + normal/elevated platelets + isolated del(5q). LENALIDOMIDE produces transfusion independence in ~67% via CK1α degradation. Older women predominant; better prognosis than other MDS.",
    "pdfPage": 3,
    "pdfQuote": "MDS"
  },
  {
    "id": 13,
    "category": "Hematology: AML Tumor Lysis Syndrome",
    "questionText": "A 35-year-old man with newly diagnosed AML (WBC 95,000 at presentation, 80% blasts) is admitted for 7+3 induction chemotherapy. Pre-treatment labs: LDH 3,200 (markedly elevated), uric acid 12, K 4.8, phosphorus 5.2, calcium 8.4, creatinine 1.1. He is started on cytarabine + idarubicin. On day 2 of chemotherapy: K 6.2, phosphorus 8.5, calcium 7.2, uric acid 16, creatinine 2.4, LDH 5,500, urine output 25 mL/hour. ECG shows peaked T waves. Which is the most appropriate management?",
    "options": [
      { "text": "Continue chemotherapy without modification; supportive observation only", "explanation": "Incorrect. The patient is developing ACUTE TUMOR LYSIS SYNDROME (TLS) — a life-threatening complication. Without aggressive intervention, hyperkalemia can cause fatal arrhythmia and acute kidney injury can become irreversible. This would be the correct answer in a patient without TLS features (which is NOT this patient)." },
      { "text": "AGGRESSIVE IV HYDRATION (200-300 mL/hour), RASBURICASE (recombinant urate oxidase) to rapidly reduce uric acid, MANAGEMENT of HYPERKALEMIA (calcium gluconate for membrane stabilization, insulin+dextrose, kayexalate or patiromer, urgent hemodialysis if persistent), phosphate binders, IV calcium replacement if symptomatic hypocalcemia; consult nephrology for possible CRRT/hemodialysis", "explanation": "Correct. ACUTE TUMOR LYSIS SYNDROME (TLS) is a metabolic emergency from rapid malignant cell lysis (spontaneous or chemotherapy-induced) releasing intracellular contents: (1) HYPERURICEMIA (purine breakdown → urate nephropathy → AKI), (2) HYPERKALEMIA (cardiac arrhythmia risk — peaked T waves, then widened QRS, then sine wave, ultimately VF/asystole), (3) HYPERPHOSPHATEMIA (calcium phosphate precipitation in tubules → AKI, also binds calcium → HYPOCALCEMIA → tetany, seizures), (4) AKI (multifactorial: urate nephropathy, calcium phosphate precipitation, volume depletion). HIGH-RISK FOR TLS: high tumor burden (Burkitt lymphoma, ALL, AML with high WBC, bulky lymphoma), high LDH, baseline elevated uric acid, baseline renal dysfunction. MANAGEMENT: (1) AGGRESSIVE IV HYDRATION (200-300 mL/hour) — most important; (2) RASBURICASE for established TLS or high risk (recombinant urate oxidase converts uric acid to allantoin, rapidly reducing uric acid; AVOID in G6PD deficiency due to hemolysis risk); (3) HYPERKALEMIA management: calcium gluconate (membrane stabilization), insulin+dextrose (shift K+ intracellular), kayexalate/patiromer (remove K+), urgent dialysis if refractory/severe; (4) PHOSPHATE BINDERS (sevelamer, calcium carbonate); (5) IV calcium replacement only if symptomatic hypocalcemia (giving Ca with hyperphosphatemia can worsen calcium phosphate precipitation in tissues); (6) URGENT HEMODIALYSIS or CRRT for: severe hyperkalemia not responsive to medical therapy, severe acidosis, severe AKI with oliguria, severe symptomatic hypocalcemia, fluid overload. PROPHYLAXIS: in high-risk patients, allopurinol or rasburicase + IV hydration BEFORE starting chemotherapy. (Note: alkalinization of urine with bicarb is NO LONGER routinely recommended — can precipitate calcium phosphate.)" },
      { "text": "Hold chemotherapy and observe for 1 week to allow tumor lysis to resolve spontaneously", "explanation": "Incorrect. Acute leukemia is rapidly progressive; holding chemotherapy for a week risks disease progression and death. TLS is managed concurrently with continued chemotherapy and aggressive supportive care. This would be the correct answer NEVER in acute leukemia." },
      { "text": "Start broad-spectrum antibiotics for presumed sepsis", "explanation": "Incorrect. The patient has clear metabolic derangements diagnostic of TLS, not infection. Antibiotics would not address the metabolic emergency. This would be the correct answer in concurrent febrile neutropenia, but TLS still needs the above management." },
      { "text": "Initiate red blood cell transfusion to improve oxygen delivery", "explanation": "Incorrect. Transfusion does not address the metabolic emergency of TLS. The patient has acute hyperkalemia and AKI requiring urgent management. This would be the correct answer for symptomatic anemia." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: TLS = hyperK + hyperphos + hyperuricemia + hypoCa + AKI from rapid cell lysis. Treat: aggressive IV hydration + RASBURICASE + manage hyperK (Ca gluconate, insulin+D, dialysis if needed) + phos binders. PROPHYLAX in high-risk patients (Burkitt, ALL, AML w/ hyperleukocytosis).",
    "pdfPage": 1,
    "pdfQuote": "blasts"
  },
  {
    "id": 14,
    "category": "Hematology: Adult T-cell Leukemia/Lymphoma (HTLV-1)",
    "questionText": "A 50-year-old man originally from Kyushu, Japan presents with skin lesions (papules and plaques on the trunk), generalized lymphadenopathy, hepatosplenomegaly, and bone pain. Vitals: T 37.8°C, BP 130/78, HR 88. Exam: confluent skin plaques on trunk, lymphadenopathy in multiple stations, hepatosplenomegaly. Labs: WBC 35,000 (60% atypical lymphocytes with MULTI-LOBED 'FLOWER CELL' nuclei), Hgb 10.5, platelets 250K, calcium 13.5 (HYPERCALCEMIA), LDH 1,800. Bone X-rays show multiple LYTIC LESIONS. Flow cytometry: CD4+ CD25+ T-cell phenotype. Which serologic test would confirm the underlying viral cause?",
    "options": [
      { "text": "Epstein-Barr virus (EBV) serology with VCA-IgM, VCA-IgG, EBNA", "explanation": "Incorrect. EBV is associated with Burkitt lymphoma (endemic African), Hodgkin lymphoma (mixed cellularity), primary CNS lymphoma in HIV, nasopharyngeal carcinoma, and PTLD — but NOT ATLL. This would be the correct answer in Burkitt or EBV-driven HL." },
      { "text": "HTLV-1 (human T-lymphotropic virus type 1) serology", "explanation": "Correct. ADULT T-CELL LEUKEMIA/LYMPHOMA (ATLL) is caused by HUMAN T-CELL LYMPHOTROPIC VIRUS TYPE 1 (HTLV-1) — a retrovirus endemic in Japan (especially Kyushu and Okinawa), the Caribbean, parts of West Africa, and Central/South America. Most HTLV-1-infected individuals are asymptomatic carriers; ~3-5% lifetime risk of ATLL after decades of infection. CLINICAL FEATURES (classic): (1) MIDDLE-AGED ADULT from endemic region; (2) LEUKOCYTOSIS with characteristic FLOWER CELLS (multi-lobed/polylobated lymphocyte nuclei — distinctive); (3) HYPERCALCEMIA (from PTHrP and RANKL produced by malignant cells) — sometimes severe; (4) LYTIC BONE LESIONS (from osteoclast activation); (5) SKIN INVOLVEMENT (papules, plaques, tumors); (6) LYMPHADENOPATHY, HEPATOSPLENOMEGALY; (7) OPPORTUNISTIC INFECTIONS from CD4+ T-cell dysfunction (Strongyloides hyperinfection is classically associated — HTLV-1 carriers should be screened for Strongyloides before immunosuppression). DIAGNOSIS: serology for HTLV-1, flow cytometry showing CD4+CD25+ T-cell phenotype (sometimes loss of CD7), characteristic morphology (flower cells). CLINICAL VARIANTS: acute (most aggressive, ~6-month median survival), lymphomatous (similar prognosis), chronic, smoldering. TREATMENT: aggressive disease — combination chemotherapy (CHOP-like), zidovudine + interferon-alpha (somewhat unusual combination effective in this disease), allogeneic SCT for selected younger patients. Mogamulizumab (anti-CCR4 mAb) is approved for relapsed ATLL. Other HTLV-1 manifestations: HTLV-1-associated myelopathy/tropical spastic paraparesis (HAM/TSP)." },
      { "text": "HIV-1 and HIV-2 serology", "explanation": "Incorrect. HIV is associated with various lymphomas (primary CNS lymphoma, DLBCL, Burkitt) but NOT classically with ATLL. The clinical picture (flower cells, hypercalcemia, lytic bone lesions) is highly specific for HTLV-1-related ATLL. This would be the correct answer in HIV-related lymphoma context." },
      { "text": "Human herpesvirus 8 (HHV-8) PCR", "explanation": "Incorrect. HHV-8 (KSHV) is associated with Kaposi sarcoma, primary effusion lymphoma (in HIV), and multicentric Castleman disease — not ATLL. This would be the correct answer in Kaposi sarcoma or PEL." },
      { "text": "Hepatitis C virus (HCV) RNA", "explanation": "Incorrect. HCV is associated with hepatocellular carcinoma, splenic marginal zone lymphoma, mixed cryoglobulinemia — not ATLL. This would be the correct answer in HCV-associated lymphoma context." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: ATLL = HTLV-1 (endemic Japan, Caribbean) + FLOWER CELLS + HYPERCALCEMIA + LYTIC BONE LESIONS + skin + LAD. CD4+CD25+ T cells. Tx: chemo, AZT+IFN-α, mogamulizumab, allogeneic SCT. Screen Strongyloides before immunosuppression.",
    "pdfPage": 3,
    "pdfQuote": "HTLV"
  },
  {
    "id": 15,
    "category": "Hematology: CML Blast Crisis",
    "questionText": "A 60-year-old man with a 4-year history of CML in chronic phase on imatinib has been doing well. Recently, his BCR-ABL transcript level has been rising, and his CBC now shows: WBC 95,000 with 28% myeloblasts (up from <5%), 8% basophils, anemia (Hgb 8), and thrombocytopenia (platelets 50K). Bone marrow biopsy shows 32% blasts, with the cytogenetics showing additional clonal abnormalities besides t(9;22). Flow cytometry of the blasts shows MPO+, CD33+, CD13+ (MYELOID phenotype). Which is the most appropriate management?",
    "options": [
      { "text": "Continue imatinib monotherapy at the same dose and reassess in 3 months", "explanation": "Incorrect. The patient has progressed to BLAST PHASE/CRISIS of CML (≥20% blasts), which is a different and far more aggressive disease state. Imatinib monotherapy alone is inadequate; intensified therapy is required, often as a bridge to allogeneic SCT. This would be the correct answer in stable chronic phase CML responding well to imatinib." },
      { "text": "Transition to a SECOND- OR THIRD-GENERATION TKI (dasatinib, nilotinib, or PONATINIB) PLUS combination chemotherapy appropriate for the blast phenotype (myeloid blast crisis → AML-like induction with cytarabine + anthracycline; lymphoid blast crisis → ALL-like induction), with goal of returning to chronic phase as a bridge to ALLOGENEIC STEM CELL TRANSPLANT in eligible patients", "explanation": "Correct. CML BLAST PHASE/CRISIS is defined by ≥20% blasts in blood or marrow (or extramedullary blast infiltrate) and represents transformation of CML into acute leukemia (most commonly myeloid, ~70%; less commonly lymphoid, ~30%; rarely mixed phenotype). Median survival without transplant is short (~6-12 months). Management: (1) MOLECULAR ASSESSMENT — check BCR-ABL kinase domain mutations to guide TKI choice; T315I requires ponatinib or asciminib; (2) INTENSIFIED TKI — switch to second- or third-generation TKI (dasatinib has good CNS penetration for lymphoid blast crisis); (3) COMBINATION CHEMOTHERAPY based on blast lineage: MYELOID BLAST CRISIS → AML-like induction (7+3 with cytarabine + anthracycline) PLUS the TKI; LYMPHOID BLAST CRISIS → ALL-like induction (vincristine + steroids + L-asparaginase + anthracycline + intrathecal MTX for CNS) PLUS the TKI; (4) IF chronic phase response achieved, urgent ALLOGENEIC SCT in eligible patients (only curative option). (5) Donor search should begin immediately. Without transplant, response to chemo + TKI is typically brief. ACCELERATED PHASE (intermediate stage between chronic and blast: 10-19% blasts, or other criteria) — similar approach with TKI escalation and transplant consideration. Note: the lecturer's overall message is that the modern TKI era has dramatically reduced progression to blast crisis (occurring in <2-3% per year on optimal TKI), but it still occurs in patients with poor adherence, resistance mutations, or aggressive disease." },
      { "text": "Increase imatinib dose to 800 mg daily as a standalone strategy", "explanation": "Incorrect. Imatinib alone, even at higher doses, is inadequate for blast crisis. Dose escalation might be considered in some accelerated phase scenarios with intolerance to other TKIs, but blast crisis requires combination therapy. This would be the correct answer in early loss of response without overt blast crisis, where dose escalation may temporize." },
      { "text": "Initiate ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is specific to APL with t(15;17) PML-RARA — not generic to AML or to blast crisis of CML. The patient does not have APL. This would be the correct answer in confirmed APL." },
      { "text": "Discontinue all therapy and refer to hospice", "explanation": "Incorrect. While blast crisis carries a poor prognosis, intensified therapy can produce responses and bridge to potentially curative transplant. Hospice is appropriate only after careful discussion of prognosis and patient preferences, typically after therapy attempts have failed. This would be the correct answer in a patient who chooses hospice after counseling about prognosis and treatment options." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: CML blast crisis = ≥20% blasts (myeloid 70%, lymphoid 30%). Intensified TKI (2nd/3rd gen) + combination chemo (AML- or ALL-like based on phenotype) + ALLOGENEIC SCT for cure in eligible patients. Median survival without SCT is short.",
    "pdfPage": 2,
    "pdfQuote": "CML"
  },
  {
    "id": 16,
    "category": "Hematology: Ph+ B-cell ALL Adult",
    "questionText": "A 45-year-old man presents with fatigue, fever, easy bruising, and a 2-cm right cervical lymph node. Vitals: T 38.0°C, HR 96, BP 122/74. Exam: pale, scattered bruising, palpable cervical node, mild splenomegaly. Labs: WBC 65,000 (75% blasts), Hgb 8.0, platelets 25K, LDH 1,800. Bone marrow: 90% blasts, TdT POSITIVE, CD19+ CD22+ CD10+ (B-ALL), MPO negative. Cytogenetics show t(9;22) BCR-ABL POSITIVE (Philadelphia chromosome). Which is the most appropriate treatment plan?",
    "options": [
      { "text": "Standard pediatric-style ALL induction (vincristine + steroids + L-asparaginase + anthracycline) alone, without addition of TKI", "explanation": "Incorrect. Ph+ (BCR-ABL positive) adult ALL has historically had a VERY POOR prognosis with chemotherapy alone. ADDING A TKI (imatinib or 2nd/3rd-generation) DRAMATICALLY IMPROVES OUTCOMES and is now standard of care. Pediatric-style induction is appropriate but a TKI must be added. This would be the correct answer in Ph-NEGATIVE B-ALL." },
      { "text": "Standard ALL induction chemotherapy PLUS a BCR-ABL TKI (imatinib, dasatinib, or ponatinib) + intrathecal CNS prophylaxis; followed by consolidation and consideration of ALLOGENEIC STEM CELL TRANSPLANT in first complete remission; CD19-directed therapies (blinatumomab, CAR-T) are valuable for MRD or relapse", "explanation": "Correct. Ph+ (BCR-ABL POSITIVE) B-ALL is found in ~25% of adult B-ALL (vs only ~3% in pediatric B-ALL) and historically had a particularly poor prognosis. Modern management has transformed outcomes: (1) ADD A TKI to standard ALL chemotherapy: imatinib was the original; dasatinib or PONATINIB (better CNS penetration, more potent, ponatinib effective against T315I) are increasingly preferred. (2) STANDARD ALL CHEMOTHERAPY backbone: induction with vincristine + corticosteroids + anthracycline + L-asparaginase (HyperCVAD or pediatric-inspired regimens). (3) INTRATHECAL CNS PROPHYLAXIS critical (ALL has CNS tropism; dasatinib/ponatinib have better CNS penetration than imatinib). (4) BLINATUMOMAB (anti-CD19/CD3 bispecific T-cell engager — BiTE) is highly effective for MRD-positive disease after induction or for relapsed/refractory B-ALL — produces deep MRD-negative remissions. (5) INOTUZUMAB OZOGAMICIN (anti-CD22 ADC) is approved for relapsed B-ALL. (6) CD19-DIRECTED CAR-T CELLS (tisagenlecleucel approved for pediatric/young adult relapsed B-ALL; brexucabtagene approved for adult relapsed B-ALL). (7) ALLOGENEIC SCT in first complete remission in eligible patients with matched donor (debated in modern era given improving outcomes with TKI + chemo + immunotherapy). (8) MRD monitoring guides treatment intensification. Maintenance: 2-3 years of mercaptopurine + methotrexate + TKI." },
      { "text": "ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is specific to APL (M3 AML), not B-ALL. The patient has ALL with TdT+ B-cell phenotype, not APL. This would be the correct answer in APL." },
      { "text": "Single-agent imatinib monotherapy", "explanation": "Incorrect. TKI monotherapy is inadequate for B-ALL induction; the TKI must be combined with chemotherapy. Modern regimens combine TKI + chemo + immunotherapy + transplant consideration. This would be the correct answer in chronic phase CML." },
      { "text": "Watchful waiting until symptoms progress", "explanation": "Incorrect. Acute leukemia requires immediate treatment — observation risks death within weeks. This would be the correct answer NEVER in acute leukemia." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Adult Ph+ B-ALL (BCR-ABL+) = chemotherapy + TKI (imatinib, dasatinib, or PONATINIB) + intrathecal CNS prophylaxis ± allogeneic SCT in CR1. BLINATUMOMAB, INOTUZUMAB, CAR-T for MRD/relapse.",
    "pdfPage": 2,
    "pdfQuote": "Philadelphia chromosome"
  },
  {
    "id": 17,
    "category": "Hematology: AML Hyperleukocytosis with Leukostasis",
    "questionText": "A 38-year-old man with newly diagnosed AML presents to the ED with confusion, headache, dyspnea, and visual changes. Vitals: T 37.6°C, BP 140/90, HR 110, RR 28, O2 sat 88% on room air. Exam: confused (CAM positive), retinal hemorrhages on funduscopy, scattered crackles bilaterally. Labs: WBC 280,000 (95% blasts — HYPERLEUKOCYTOSIS), Hgb 8.5, platelets 35K, LDH 4,500. Chest X-ray: bilateral patchy infiltrates. Coagulation: PT/PTT normal. Which is the most appropriate IMMEDIATE management?",
    "options": [
      { "text": "Transfuse packed red blood cells to keep Hgb >10", "explanation": "Incorrect. RBC TRANSFUSION IN HYPERLEUKOCYTOSIS WITH LEUKOSTASIS CAN BE HARMFUL — it increases blood viscosity and can WORSEN leukostasis-related organ ischemia. RBC transfusion should be MINIMIZED or AVOIDED until WBC is reduced. Only if Hgb is critically low (<7-8) and symptomatic should small-volume transfusion be considered. This would be the correct answer with severe symptomatic anemia and controlled WBC." },
      { "text": "EMERGENT cytoreductive therapy: leukapheresis (rapid mechanical WBC reduction) AND/OR initiate hydroxyurea +/- low-dose cytarabine while planning induction chemotherapy; aggressive IV hydration with TLS prophylaxis (rasburicase + IV fluids); supportive care; AVOID/minimize RBC transfusion until WBC reduced", "explanation": "Correct. HYPERLEUKOCYTOSIS in AML (WBC >100,000) with symptomatic LEUKOSTASIS is a HEMATOLOGIC EMERGENCY. Leukostasis occurs when masses of large myeloblasts (less deformable than mature WBCs) clump in microvasculature → tissue ischemia. Classic organ involvement: PULMONARY (dyspnea, hypoxia, infiltrates), CNS (confusion, headache, visual changes, stroke-like symptoms, retinal hemorrhages), priapism, peripheral ischemia. Mortality up to 40% in first week if untreated. MANAGEMENT: (1) EMERGENT LEUKAPHERESIS — rapid mechanical removal of WBCs through a centrifugation circuit (specialized blood center); particularly useful for symptomatic leukostasis as a bridge while initiating chemotherapy. May contraindicated in APL (worsens DIC) — see below. (2) HYDROXYUREA — fast oral cytoreduction (start within hours), 2-4 g/day, lowers WBC over 24-48 hours. (3) INITIATE INDUCTION CHEMOTHERAPY (cytarabine + anthracycline) once the patient is stabilized — chemotherapy is the definitive treatment. (4) TLS PROPHYLAXIS — aggressive IV hydration + rasburicase (or allopurinol) BEFORE chemotherapy initiation; high tumor burden = high TLS risk. (5) AVOID/MINIMIZE RBC TRANSFUSION — can worsen viscosity and leukostasis (only if Hgb critically low). (6) Platelet transfusion if needed for bleeding or invasive procedures (often used liberally in this setting because of bleeding risk). (7) Supportive care: oxygen for hypoxia, neurology assessment, ICU monitoring. (8) AVOID leukapheresis in APL — promyelocyte release of granule contents during apheresis can worsen DIC; instead, start ATRA + ATO promptly." },
      { "text": "Hold all interventions and observe for 24 hours to allow patient to stabilize", "explanation": "Incorrect. Symptomatic leukostasis has rapidly evolving organ damage and high mortality if untreated. Immediate intervention is mandatory. This would be the correct answer NEVER in symptomatic hyperleukocytosis." },
      { "text": "Initiate ATRA + arsenic trioxide based on the high WBC", "explanation": "Incorrect. ATRA + ATO is specific to APL (M3 AML with t(15;17)). This patient has AML with hyperleukocytosis but no indication that this is APL. APL typically presents with leukopenia/normal WBC and DIC, not hyperleukocytosis. This would be the correct answer in confirmed APL." },
      { "text": "Broad-spectrum antibiotics for presumed sepsis as the cause of symptoms", "explanation": "Incorrect. While the patient should be evaluated for concurrent infection (and started on broad-spectrum antibiotics if febrile or neutropenic), the dominant clinical picture (very high WBC, multi-organ leukostasis findings) requires urgent cytoreduction. This would be the correct answer in concurrent febrile neutropenia, but cytoreduction is still essential." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: AML hyperleukocytosis with leukostasis (WBC >100K + organ symptoms) = EMERGENCY. Leukapheresis + hydroxyurea + induction chemo + TLS prophylaxis (rasburicase). AVOID/minimize RBC transfusion (worsens viscosity). NOT leukapheresis in APL (worsens DIC).",
    "pdfPage": 1,
    "pdfQuote": "blasts"
  },
  {
    "id": 18,
    "category": "Hematology: HIT Recognition and Management",
    "questionText": "A 65-year-old man underwent elective right total knee arthroplasty 7 days ago. He has been on prophylactic unfractionated heparin since postoperative day 1. Today he develops sudden left calf pain, swelling, and a new platelet count of 55,000 (baseline 280K, declining over 3 days). Vitals: T 37.5°C, BP 132/80, HR 92. Exam: tender swollen left calf, no rash or bleeding, fistula intact. Labs: platelets 55K (down from 280K), Hgb 12, WBC 8.0, PT/PTT mildly elevated. Doppler ultrasound confirms new LEFT lower extremity DVT. 4T score: 8 (high probability). Heparin-platelet factor 4 (PF4) ELISA strongly positive; serotonin release assay confirms HIT. Which is the most appropriate management?",
    "options": [
      { "text": "Continue heparin and add warfarin for the DVT treatment", "explanation": "Incorrect. HEPARIN MUST BE STOPPED — continuing it will worsen the HIT and risk further life- or limb-threatening thrombosis. Also, warfarin should NOT be started while HIT is active because (1) protein C depletion (faster than protein S) can paradoxically cause warfarin-induced skin necrosis or venous limb gangrene in HIT, and (2) warfarin does not address acute HIT. This would be the correct answer in a non-HIT DVT context." },
      { "text": "Immediately STOP ALL heparin (UFH and LMWH); start a non-heparin anticoagulant such as ARGATROBAN, BIVALIRUDIN, FONDAPARINUX (off-label), or a DOAC (rivaroxaban, apixaban — increasingly used in stable HIT); AVOID warfarin until platelets recover (>150K); avoid platelet transfusion unless severe bleeding", "explanation": "Correct. HEPARIN-INDUCED THROMBOCYTOPENIA (HIT) Type II is an immune-mediated reaction (IgG against heparin-PF4 complexes → platelet activation → consumption + thrombosis). Classic features: (1) PLATELET DROP of >50% from baseline OR new platelets <100K, typically occurring 5-14 days after heparin exposure (or sooner if recent prior exposure); (2) PARADOXICAL THROMBOSIS (both arterial and venous) — DVT/PE most common, but also stroke, MI, limb ischemia, skin necrosis at injection sites, adrenal hemorrhage; (3) Bleeding is UNCOMMON despite low platelets — this is a PROTHROMBOTIC, not bleeding, disorder. The 4T SCORE (Thrombocytopenia magnitude, Timing, Thrombosis or other sequelae, oTher causes) estimates pretest probability. CONFIRMATORY TESTING: heparin-PF4 ELISA (sensitive but less specific) → confirmed by SEROTONIN RELEASE ASSAY (gold standard, more specific). MANAGEMENT: (1) STOP ALL HEPARIN immediately (UFH, LMWH, heparin flushes, heparin-coated catheters); (2) START NON-HEPARIN ANTICOAGULANT: ARGATROBAN (direct thrombin inhibitor, hepatic metabolism — preferred in renal failure), BIVALIRUDIN (DTI), FONDAPARINUX (synthetic factor Xa inhibitor, no PF4 binding — off-label use), or DOACs (rivaroxaban, apixaban — increasingly used in stable HIT without active limb-threatening thrombosis); (3) AVOID WARFARIN until platelets recover above 150K (warfarin can cause skin necrosis or venous limb gangrene in HIT due to early protein C drop); when platelets recover, can transition to warfarin or DOAC for ongoing anticoagulation; (4) Continue anticoagulation for at least 4 weeks (or longer if thrombosis confirmed — typically 3-6 months); (5) AVOID platelet transfusion (can worsen thrombosis) unless severe bleeding; (6) Document HIT in patient's records — future heparin exposure should be avoided lifelong; (7) Investigate for occult thrombosis (Doppler imaging) even in 'isolated' HIT." },
      { "text": "Stop heparin and switch to LMWH (enoxaparin) at therapeutic dose for the DVT", "explanation": "Incorrect. LMWH (enoxaparin, dalteparin) CROSS-REACTS with HIT antibodies and must be AVOIDED. All heparin products are contraindicated in HIT. This would be the correct answer in non-HIT DVT or HIT mimics without true antibody confirmation." },
      { "text": "Transfuse platelets to raise count above 100K", "explanation": "Incorrect. Platelet transfusion in HIT can paradoxically worsen thrombosis (more platelets to activate). Reserve for active life-threatening bleeding only. This would be the correct answer in ITP with active bleeding, NEVER in HIT without bleeding." },
      { "text": "Discontinue heparin and observe for spontaneous platelet recovery; no anticoagulation", "explanation": "Incorrect. The patient already has thrombosis (DVT) and ongoing HIT risk of further thrombosis. Anticoagulation with a non-heparin agent is mandatory. Without anticoagulation, further life- or limb-threatening thrombosis is highly likely. This would be the correct answer NEVER in HIT with thrombosis." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HIT = IgG vs heparin-PF4 → platelet drop >50% (or <100K) 5-14 days post-heparin + PARADOXICAL THROMBOSIS. STOP all heparin (including LMWH) + start argatroban/bivalirudin/fondaparinux/DOAC. AVOID warfarin until plt >150K, AVOID platelet transfusion.",
    "pdfPage": 2,
    "pdfQuote": "thrombocytopenia"
  },
  {
    "id": 19,
    "category": "Hematology: Tumor Lysis Prophylaxis Stratification",
    "questionText": "Four patients are being admitted for chemotherapy. Which patient has the HIGHEST risk for clinically significant tumor lysis syndrome (TLS) and requires the most aggressive prophylaxis (IV hydration + rasburicase + close monitoring)?",
    "options": [
      { "text": "A 65-year-old with stable chronic lymphocytic leukemia (Rai stage 1) starting first-line obinutuzumab + venetoclax with WBC 35K", "explanation": "Incorrect. While CLL with venetoclax has known TLS risk and requires ramp-up dosing and prophylaxis, the modest WBC and stable Rai stage make this MODERATE risk. The venetoclax weekly ramp-up + close monitoring + hydration + allopurinol is appropriate; rasburicase is reserved for high-risk presentations. This would be the correct answer if asked about a clear moderate-risk case." },
      { "text": "A 9-year-old boy with bulky abdominal Burkitt lymphoma (15 cm mesenteric mass), LDH 7,500 (markedly elevated), uric acid 11, mild AKI (creatinine 1.4), starting DA-EPOCH-R chemotherapy", "explanation": "Correct. BURKITT LYMPHOMA is the highest-risk lymphoma for TLS because of its EXTREMELY HIGH PROLIFERATION RATE (Ki-67 nearly 100%, the fastest-growing human tumor). High tumor burden, very elevated LDH, baseline hyperuricemia, and baseline AKI all compound the risk. TLS RISK STRATIFICATION (per Cairo-Bishop): (1) HIGH RISK — Burkitt lymphoma, ALL with WBC >100K, AML with WBC >100K, advanced bulky lymphomas with elevated LDH (>2x ULN), baseline AKI, baseline hyperuricemia → use aggressive PROPHYLAXIS: IV HYDRATION + RASBURICASE + close monitoring (frequent labs every 4-6 hours during cytoreduction); (2) INTERMEDIATE RISK — most acute leukemias without hyperleukocytosis, aggressive lymphomas without bulk → IV hydration + allopurinol (or rasburicase if baseline uric acid elevated); (3) LOW RISK — solid tumors, indolent lymphomas without bulk, most chronic leukemias → standard hydration ± allopurinol. RASBURICASE (recombinant urate oxidase) rapidly reduces uric acid by converting it to soluble allantoin; AVOID in G6PD deficiency (causes hemolysis from H2O2 byproduct). PREVENTION priorities: aggressive IV hydration, manage electrolytes proactively, hold nephrotoxic drugs, ensure adequate urine output (>100 mL/hour), nephrology consult if AKI develops, avoid alkalinization (no longer routinely recommended)." },
      { "text": "A 50-year-old with indolent follicular lymphoma, small-volume disease, starting rituximab monotherapy", "explanation": "Incorrect. Indolent follicular lymphoma with rituximab monotherapy is LOW TLS risk — slow-growing disease with low proliferative rate, single-agent immunotherapy. This would be the correct answer for a LOW-risk case." },
      { "text": "A 70-year-old with metastatic prostate adenocarcinoma starting docetaxel chemotherapy", "explanation": "Incorrect. Solid tumors are generally LOW TLS risk because of lower proliferation rates and less responsive to acute cytoreduction. Prostate cancer is very low TLS risk. This would be the correct answer for the lowest-risk category." },
      { "text": "A 60-year-old with stable polycythemia vera on hydroxyurea for 2 years with controlled WBC and Hgb", "explanation": "Incorrect. PV on chronic hydroxyurea is not a TLS scenario — there is no acute cytoreduction event. This would be the correct answer if asking about chronic indolent disease." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: TLS risk stratification: HIGH risk = Burkitt, ALL/AML with WBC >100K, bulky aggressive lymphoma with high LDH, baseline AKI/hyperuricemia → aggressive prophylaxis (hydration + RASBURICASE). Avoid rasburicase in G6PD deficiency.",
    "pdfPage": 1,
    "pdfQuote": "blasts"
  },
  {
    "id": 20,
    "category": "Hematology: CAR-T for Refractory B-ALL",
    "questionText": "A 22-year-old man with B-cell acute lymphoblastic leukemia (CD19+) has relapsed after 2 prior lines of therapy (initial pediatric-style induction with consolidation, then blinatumomab). His bone marrow now shows 40% blasts again. He has good performance status (ECOG 1), preserved organ function, no significant infection. Which is the most appropriate next-line therapy?",
    "options": [
      { "text": "Repeat induction chemotherapy with same regimen as initial treatment", "explanation": "Incorrect. Repeating the same induction in second relapse is unlikely to provide durable remission. The patient is highly refractory and needs more active novel therapies. This would be the correct answer in first relapse with delayed onset (>2 years), where same regimen might be re-tried." },
      { "text": "CD19-DIRECTED CHIMERIC ANTIGEN RECEPTOR T-CELL (CAR-T) THERAPY: TISAGENLECLEUCEL (Kymriah) or BREXUCABTAGENE AUTOLEUCEL (Tecartus) — autologous T cells engineered to express anti-CD19 CAR; can produce durable remissions in 60-80% of refractory B-ALL; high risk for CYTOKINE RELEASE SYNDROME and NEUROLOGIC TOXICITY (ICANS), managed with tocilizumab and steroids", "explanation": "Correct. CD19-DIRECTED CAR-T CELL THERAPY has revolutionized treatment of relapsed/refractory B-cell malignancies. For pediatric/young adult B-ALL: TISAGENLECLEUCEL (Kymriah, FDA-approved 2017). For adult B-ALL: BREXUCABTAGENE AUTOLEUCEL (Tecartus, FDA-approved 2021). PROCESS: (1) Autologous T cells are collected by leukapheresis from the patient; (2) Genetically engineered to express a CHIMERIC ANTIGEN RECEPTOR with an extracellular anti-CD19 single-chain antibody fragment fused to intracellular T-cell costimulatory (CD28 or 4-1BB) and CD3-ζ signaling domains; (3) Expanded ex vivo; (4) Patient receives LYMPHODEPLETING CHEMOTHERAPY (typically fludarabine + cyclophosphamide) to enable engraftment; (5) CAR-T cells re-infused — they recognize CD19+ B cells (including leukemic blasts and normal B cells), triggering massive T-cell activation and tumor killing. EFFICACY: Complete remission rates 60-80% in refractory B-ALL; many patients achieve durable remissions. KEY TOXICITIES: (1) CYTOKINE RELEASE SYNDROME (CRS) — fever, hypotension, hypoxia, multi-organ dysfunction from massive cytokine release (IL-6 central). Severity graded 1-4. Treatment: TOCILIZUMAB (anti-IL-6 receptor mAb) for severe CRS ± corticosteroids. Onset typically days 1-14. (2) IMMUNE EFFECTOR CELL-ASSOCIATED NEUROTOXICITY SYNDROME (ICANS) — encephalopathy, aphasia, seizures, cerebral edema, can be fatal. Treatment: corticosteroids (tocilizumab less effective for ICANS, as it doesn't cross BBB well). (3) HYPOGAMMAGLOBULINEMIA from B-cell aplasia — requires IVIG. (4) Prolonged cytopenias. Other CAR-T applications: DLBCL (axicabtagene, tisagenlecleucel, lisocabtagene), MCL (brexucabtagene), follicular lymphoma, multiple myeloma (BCMA-directed: idecabtagene, ciltacabtagene). Allogeneic SCT remains an option after CAR-T remission in some cases." },
      { "text": "Allogeneic stem cell transplant immediately without further therapy", "explanation": "Incorrect. Allogeneic SCT in active disease (with high blast burden) has poor outcomes because SCT requires DISEASE CONTROL/COMPLETE REMISSION as a bridge. The patient needs to achieve remission first (with CAR-T, blinatumomab if not previously failed, inotuzumab, or other regimen) before SCT. CAR-T can serve as both definitive therapy or a bridge to SCT. This would be the correct answer after CR is achieved with active CAR-T or other induction." },
      { "text": "Switch to AML-directed chemotherapy (cytarabine + anthracycline) since standard ALL chemo has failed", "explanation": "Incorrect. The patient has B-ALL (TdT+, CD19+, CD22+, CD10+, MPO negative) — switching to AML chemotherapy would not target the disease appropriately and would expose to unnecessary toxicity. This would be the correct answer if the disease had transformed to AML or if mixed phenotype acute leukemia was diagnosed." },
      { "text": "Discontinue all therapy and transition to hospice", "explanation": "Incorrect. The patient is young, has good performance status, and has highly effective novel therapies (CAR-T) available with potential for durable remission. Hospice transition is premature without trying active therapy. This would be the correct answer in a patient who has failed multiple lines including CAR-T or who chooses hospice after counseling." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Refractory B-ALL (after induction, blinatumomab, etc.) → CD19-directed CAR-T (tisagenlecleucel for pediatric/young adult; brexucabtagene for adult). Watch for CYTOKINE RELEASE SYNDROME (treat with tocilizumab) and ICANS (treat with steroids).",
    "pdfPage": 1,
    "pdfQuote": "B-ALL"
  }
];

window.Test_L154_Part2 = Test_L154_Part2;
