const Test_CV22 = [
  {
    "id": 1,
    "category": "Cardiac Electrophysiology: Action Potential Types",
    "questionText": "A physiologist isolates single cells from several regions of a mammalian heart and records their transmembrane potentials. In one group of cells, the upstroke of the action potential is abolished by a selective L-type calcium channel antagonist but is entirely unaffected by a concentration of tetrodotoxin sufficient to block voltage-gated fast sodium channels. The maximum rate of rise in these cells is approximately 10 V/s. From which regions were these cells most likely harvested?",
    "options": [
      {
        "text": "Ordinary atrial working myocardium",
        "explanation": "Incorrect. Atrial working myocytes generate fast-response action potentials in which phase 0 depends on the fast sodium channel, so their upstroke would be abolished by tetrodotoxin and largely preserved with L-type calcium blockade. Their upstroke velocity also greatly exceeds 10 V/s. This would be the correct answer if the recorded cells had shown a rapid upstroke that was sodium-dependent."
      },
      {
        "text": "Purkinje fiber network of the ventricle",
        "explanation": "Incorrect. Purkinje fibers generate fast-response action potentials with the highest upstroke velocity in the heart, driven by a robust fast sodium current. Blocking L-type calcium channels would not eliminate their phase 0. This would be the correct answer if the question described cells with an exceptionally rapid, sodium-dependent upstroke."
      },
      {
        "text": "Sinoatrial and atrioventricular nodes",
        "explanation": "Correct. Only the sinoatrial and atrioventricular nodes generate slow-response action potentials, in which phase 0 depolarization results from opening of L-type calcium channels rather than fast sodium channels. These fibers lack functional voltage-gated fast sodium channels, which is precisely why tetrodotoxin has no effect while an L-type calcium antagonist abolishes the upstroke. The slow rate of rise (~10 V/s) is the defining feature from which the term 'slow response' derives, in contrast to the >100 V/s seen in fast-response tissue. This distinction underlies why calcium channel blockers preferentially act on nodal tissue."
      },
      {
        "text": "Ventricular subendocardial myocardium",
        "explanation": "Incorrect. Ventricular myocytes are fast-response cells whose phase 0 is generated by fast sodium channel opening. Their action potential also displays a prominent plateau phase absent from the description. This would be the correct answer if the recorded upstroke had been sodium-dependent with a rapid dV/dt."
      },
      {
        "text": "Bundle of His and proximal bundle branches",
        "explanation": "Incorrect. The His bundle and bundle branches are part of the fast-response conduction system and depolarize via fast sodium channels. This would be the correct answer if the pharmacologic profile had shown sodium dependence rather than calcium dependence."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Only the SA node and AV node generate slow-response action potentials (phase 0 = L-type Ca²⁺ current); all other cardiac cells are fast-response (phase 0 = fast Na⁺ current).",
    "pdfPage": 7,
    "pdfQuote": "Cardiac myocytes and 2 types of cardiac action potentials... Sinus (SA) node... AV node... Slow response Action potential"
  },
  {
    "id": 2,
    "category": "Cardiac Electrophysiology: Resting Membrane Potential",
    "questionText": "A student is asked why the resting membrane potential of a ventricular myocyte sits at approximately -90 mV, very close to the calculated equilibrium potential for potassium of -96 mV. Which of the following best accounts for this relationship during phase 4?",
    "options": [
      {
        "text": "Voltage-gated sodium channels remain partially open at rest, offsetting ongoing potassium efflux",
        "explanation": "Incorrect. During phase 4 the fast sodium channels are closed; if they were appreciably open the membrane potential would be driven toward the sodium equilibrium potential of +52 mV, far from the observed value. This would be the correct answer if the cell were in phase 0 rather than phase 4."
      },
      {
        "text": "The sodium-calcium exchanger generates a large outward current at rest",
        "explanation": "Incorrect. In its forward mode the sodium-calcium exchanger brings in three sodium ions for each calcium extruded, producing a net inward (depolarizing) current rather than one that would hold the cell near the potassium equilibrium potential. This would be the correct answer if the question asked which current can depolarize cells and promote arrhythmia."
      },
      {
        "text": "The inward rectifier potassium channel remains open while sodium and calcium channels are closed",
        "explanation": "Correct. In phase 4 the sodium and calcium channels are closed, and the inward rectifier potassium channel (I_K1) is the channel that remains open at resting potential. Because membrane potential is determined by the weighted conductance of each ion times its equilibrium potential, a membrane permeable essentially only to potassium settles near the potassium equilibrium potential. The small discrepancy between the theoretical -96 mV and the measured -90 mV reflects variation in intracellular potassium concentration and background leak currents."
      },
      {
        "text": "L-type calcium channels provide a steady inward leak balancing potassium",
        "explanation": "Incorrect. L-type calcium channels are closed at resting membrane potential and open only with depolarization; a standing calcium influx would pull the potential toward +134 mV. This would be the correct answer if the cell were in the plateau phase."
      },
      {
        "text": "The sodium-potassium ATPase directly clamps the potential at the potassium equilibrium value",
        "explanation": "Incorrect. Although the pump is electrogenic and contributes modestly to negativity by exporting three sodium for two potassium, it does not set the resting potential; ionic conductance does. This would be the correct answer if the question concerned long-term maintenance of ion gradients rather than the instantaneous determinant of membrane potential."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "At rest, essentially only I_K1 potassium channels are open, so the resting membrane potential (~ -90 mV) approximates the potassium equilibrium potential (~ -96 mV).",
    "pdfPage": 21,
    "pdfQuote": "Resting Membrane Potential Phase 4... Only IK1 channel remains open"
  },
  {
    "id": 3,
    "category": "Cardiac Electrophysiology: Ionic Gradients",
    "questionText": "During a lecture on ionic gradients, a student is told that when potassium channels open, potassium ions do not continue to leave the cell until intracellular and extracellular concentrations equalize. Which of the following best explains why net potassium movement ceases before concentrations equilibrate?",
    "options": [
      {
        "text": "Potassium channels inactivate within milliseconds of opening",
        "explanation": "Incorrect. The cessation of net flux described here occurs even when channels remain open; it is an electrochemical equilibrium, not a gating phenomenon. This would be the correct answer if the question described the transient outward current, which does inactivate rapidly."
      },
      {
        "text": "The sodium-potassium ATPase immediately returns all lost potassium",
        "explanation": "Incorrect. The pump does restore gradients over time using ATP, but the equilibrium described arises from opposing electrical and chemical forces rather than from active transport. This would be the correct answer if the question asked how gradients are maintained across many cardiac cycles."
      },
      {
        "text": "Extracellular potassium accumulation reverses the chemical gradient",
        "explanation": "Incorrect. The extracellular potassium concentration (~4 mM) remains far below the intracellular value (140-150 mM); the chemical gradient continues to favor efflux even at equilibrium. This would be the correct answer if massive extracellular potassium accumulation had actually inverted the gradient."
      },
      {
        "text": "Extracellular potassium progressively accumulates until it fully reverses the chemical gradient",
        "explanation": "Correct. Each potassium ion that leaves carries positive charge out of the cell, progressively building a negative intracellular potential. This developing electrical force attracts the positively charged potassium back inward, opposing the chemical gradient that drives it out. When the two opposing forces become equal in magnitude, there is no further net movement, and the transmembrane voltage at that point is the equilibrium potential, calculable with the Nernst equation. For potassium at these concentrations it is approximately -96 mV."
      },
      {
        "text": "Osmotic water movement follows potassium out of the cell, progressively diluting the transmembrane gradient",
        "explanation": "Incorrect. Osmotic water movement does not account for the abrupt cessation of net ion flux, which is governed by the balance of chemical and electrical driving forces. This would be the correct answer if the question addressed cell volume regulation."
      }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "The equilibrium potential is the voltage at which the electrical force exactly opposes the chemical gradient, producing zero net ion flux; it is calculated with the Nernst equation.",
    "pdfPage": 10,
    "pdfQuote": "Potassium Diffusion Potential... (-96 mV) Equilibrium potential for K+ (EK) Nernst Equation"
  },
  {
    "id": 4,
    "category": "Cardiac Electrophysiology: Phase 0 Depolarization",
    "questionText": "A ventricular myocyte at its resting potential receives a propagating impulse from neighboring tissue. Its membrane potential rises progressively until, at approximately -55 mV, a rapid regenerative upstroke occurs. Which event occurs at this specific voltage?",
    "options": [
      {
        "text": "The inward rectifier potassium channel opens fully",
        "explanation": "Incorrect. The inward rectifier is open at rest and contributes to terminal repolarization once potential falls below approximately -30 mV; it does not generate the depolarizing upstroke. This would be the correct answer if the question described the transition through late phase 3."
      },
      {
        "text": "The delayed rectifier potassium current reaches maximal activation",
        "explanation": "Incorrect. The delayed rectifier opens slowly and peaks at the end of phase 2 or beginning of phase 3, driving repolarization rather than depolarization. This would be the correct answer if the question described the onset of rapid repolarization."
      },
      {
        "text": "The activation gate of the fast sodium channel opens rapidly",
        "explanation": "Correct. The voltage-gated fast sodium channel possesses an outer activation (fast) gate and an inner inactivation (slow) gate. At rest the activation gate is closed while the inactivation gate is open. When depolarization reaches the threshold of approximately -55 mV, the activation gate opens very rapidly while the inactivation gate simultaneously begins to close slowly. For a brief fraction of a millisecond both gates are open, allowing a large sodium influx that produces the regenerative phase 0 upstroke."
      },
      {
        "text": "The pacemaker (funny) channel begins carrying inward current",
        "explanation": "Incorrect. The funny current is activated by hyperpolarization in nodal tissue to generate spontaneous phase 4 depolarization; working ventricular myocytes are driven by propagated impulses rather than by intrinsic automaticity. This would be the correct answer if the cell described were a sinoatrial nodal cell."
      },
      {
        "text": "The sodium-potassium ATPase transiently reverses direction",
        "explanation": "Incorrect. The pump does not reverse to generate the upstroke; phase 0 is a channel-mediated, not pump-mediated, event. This would be the correct answer if the question concerned restoration of ionic gradients during phase 4."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Threshold for the cardiac fast sodium channel is approximately -55 mV; the activation gate opens quickly while the inactivation gate closes slowly, creating a brief window of sodium influx.",
    "pdfPage": 17,
    "pdfQuote": "Na+ channel status in different phases: Fast gate, Slow gate... Threshold"
  },
  {
    "id": 5,
    "category": "Cardiac Electrophysiology: Phase 1 Repolarization",
    "questionText": "Immediately after the peak of a ventricular action potential, the membrane potential falls modestly from about +25 mV toward 0 mV before entering a prolonged plateau. Which current is chiefly responsible for this brief early repolarization?",
    "options": [
      {
        "text": "Inward rectifier potassium current",
        "explanation": "Incorrect. The inward rectifier contributes principally to terminal repolarization below approximately -30 mV and to maintenance of the resting potential, not to the notch immediately following the peak. This would be the correct answer if the described change occurred late in phase 3."
      },
      {
        "text": "Delayed rectifier potassium current",
        "explanation": "Incorrect. The delayed rectifier activates slowly and reaches maximum opening near the end of the plateau; its name reflects precisely this delayed activation. This would be the correct answer if the question described the transition from phase 2 into phase 3."
      },
      {
        "text": "L-type calcium current",
        "explanation": "Incorrect. The L-type calcium current is inward and depolarizing, sustaining the plateau rather than producing the repolarizing notch. This would be the correct answer if the question asked what maintains phase 2."
      },
      {
        "text": "Sodium-calcium exchanger current in forward mode",
        "explanation": "Incorrect. Forward-mode exchange produces a net inward, depolarizing current and is not the mechanism of the phase 1 notch. This would be the correct answer if the question concerned a depolarizing current capable of triggering afterdepolarizations."
      },
      {
        "text": "Transient outward potassium current",
        "explanation": "Correct. Phase 1 is produced by opening of the transient outward potassium channel, which carries potassium out of the cell and drops the potential from its peak toward the level at which the plateau begins. Because this channel opens only briefly, its closure terminates phase 1 repolarization and permits the plateau to develop. The magnitude of this notch varies across the ventricular wall, being most prominent in epicardial myocytes."
      }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Phase 1 is generated by the transient outward potassium current (I_to); its brief opening and rapid closure create the notch between the peak and the plateau.",
    "pdfPage": 18,
    "pdfQuote": "Early repolarization Phase 1... transient outward K+ channel"
  },
  {
    "id": 6,
    "category": "Cardiac Electrophysiology: Plateau Phase",
    "questionText": "The plateau phase of the ventricular action potential is unique among excitable tissues. Which statement best describes the ionic basis of this phase?",
    "options": [
      {
        "text": "Sodium influx continues unopposed throughout the plateau",
        "explanation": "Incorrect. Fast sodium channels are inactivated well before the plateau; sustained sodium influx would drive the potential toward +52 mV rather than holding it near 0 mV. This would be the correct answer if the question described phase 0."
      },
      {
        "text": "All voltage-gated channels are closed, producing electrical silence",
        "explanation": "Incorrect. The plateau is a state of active, balanced current flow rather than absence of conductance. This would be the correct answer if the question described a fully repolarized cell in late phase 4."
      },
      {
        "text": "Inward L-type calcium current is nearly balanced by outward delayed rectifier potassium current",
        "explanation": "Correct. Depolarization opens L-type calcium channels, which activate slowly and remain open for a prolonged period, providing sustained inward current throughout phase 2. This is opposed by outward potassium movement through the delayed rectifier channels, which comprise rapid, slow, and ultra-rapid components. Because these opposing currents are nearly equal, the potential changes very little; the small excess of outward current explains why the plateau gradually declines rather than remaining perfectly flat."
      },
      {
        "text": "Chloride influx offsets potassium efflux to maintain the plateau",
        "explanation": "Incorrect. The lecture identifies calcium and potassium as the principal currents of phase 2; chloride plays only a minor role in the framework presented. This would be the correct answer if the plateau depended chiefly on anion movement."
      },
      {
        "text": "The sodium-potassium ATPase actively maintains the plateau through sustained electrogenic transport",
        "explanation": "Incorrect. The pump's electrogenic contribution is small and hyperpolarizing, and it operates chiefly to restore gradients during phase 4. This would be the correct answer if the question asked which mechanism restores ionic homeostasis between beats."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "The plateau reflects balance between inward L-type calcium current and outward delayed rectifier potassium current (I_Kr, I_Ks, I_Kur); slight net outward current causes the gentle downslope.",
    "pdfPage": 19,
    "pdfQuote": "Plateau Phase Phase 2 Ica(L), Ik+ ... Delayed rectifier K+ Channel (Ikr, Iks, Ikur)"
  },
  {
    "id": 7,
    "category": "Cardiac Electrophysiology: Phase 3 Repolarization",
    "questionText": "As a ventricular action potential transitions from the plateau to rapid repolarization, a second potassium channel opens once the membrane potential falls below approximately -30 mV, accelerating the return to resting potential. Which channel is this, and what distinguishes it?",
    "options": [
      {
        "text": "Transient outward potassium channel, which reopens late in repolarization",
        "explanation": "Incorrect. The transient outward channel operates in phase 1 and closes quickly; it does not reopen to complete phase 3. This would be the correct answer if the question described the notch immediately after the peak."
      },
      {
        "text": "Acetylcholine-sensitive potassium channel, activated by muscarinic stimulation",
        "explanation": "Incorrect. This ligand-gated channel mediates vagal slowing of nodal tissue and is not the voltage-dependent channel completing ventricular phase 3. This would be the correct answer if the question involved parasympathetic effects on the sinoatrial node."
      },
      {
        "text": "ATP-sensitive potassium channel, activated during ischemia",
        "explanation": "Incorrect. Although important in ischemia, this channel is not the one described as opening below -30 mV during normal phase 3 repolarization. This would be the correct answer if the vignette described metabolic stress with falling intracellular ATP."
      },
      {
        "text": "Pacemaker channel, activated by hyperpolarization",
        "explanation": "Incorrect. The pacemaker channel is a nonselective cation channel that produces depolarizing current in nodal cells, not a repolarizing potassium current in ventricular tissue. This would be the correct answer if the question described phase 4 automaticity in the sinoatrial node."
      },
      {
        "text": "Inward rectifier potassium channel, which remains open at resting potential",
        "explanation": "Correct. As L-type calcium channels close and the delayed rectifier reaches maximal opening, phase 3 begins. Once membrane potential falls below approximately -30 mV, the inward rectifier potassium channel (I_K1) opens and helps drive the potential down to its resting level. Its distinguishing property is that, unlike most potassium channels which close as the cell approaches rest, I_K1 remains open at the resting membrane potential, which is why the resting potential sits so close to the potassium equilibrium potential."
      }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "I_K1 (inward rectifier) opens below about -30 mV to complete phase 3 and uniquely stays open at rest, anchoring the resting potential near E(K⁺).",
    "pdfPage": 20,
    "pdfQuote": "Rapid repolarization Phase 3... Inward rectifying K+ channel (IK1)"
  },
  {
    "id": 8,
    "category": "Cardiac Physiology: Ion Pumps",
    "questionText": "A cardiac physiologist notes that one membrane transporter exports three sodium ions for every two potassium ions imported. What is the direct electrophysiologic consequence of this transporter's activity?",
    "options": [
      {
        "text": "It produces net inward current, depolarizing the cell",
        "explanation": "Incorrect. Exporting three positive charges while importing two produces net outward movement of positive charge, which hyperpolarizes rather than depolarizes. This would be the correct answer if the transporter described were the sodium-calcium exchanger operating in forward mode."
      },
      {
        "text": "It has no net effect on membrane potential because it is electroneutral",
        "explanation": "Incorrect. A 3:2 stoichiometry is inherently electrogenic; only a 1:1 exchange would be electroneutral. This would be the correct answer if the pump exchanged equal charges in each direction."
      },
      {
        "text": "It directly triggers calcium release from the sarcoplasmic reticulum",
        "explanation": "Incorrect. Sarcoplasmic reticulum calcium release is triggered by calcium binding to the ryanodine receptor, not by sodium-potassium exchange. This would be the correct answer if the question described calcium-induced calcium release."
      },
      {
        "text": "It directly generates the spontaneous pacemaker upstroke that initiates each sinoatrial nodal discharge",
        "explanation": "Incorrect. Phase 4 spontaneous depolarization is driven principally by the funny current through HCN channels. This would be the correct answer if the question concerned nodal automaticity."
      },
      {
        "text": "It directly generates the spontaneous upstroke of the nodal pacemaker potential during phase 4",
        "explanation": "Correct. Because the sodium-potassium ATPase exports three sodium ions for every two potassium ions it imports, each cycle removes a net positive charge from the cell. This electrogenic action drives the membrane potential in a more negative (hyperpolarizing) direction. The pump requires ATP, as its name indicates, and its principal role is restoring the sodium and potassium gradients consumed during each cardiac cycle."
      }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "The Na⁺/K⁺-ATPase is electrogenic (3 Na⁺ out : 2 K⁺ in), so its activity contributes a small hyperpolarizing influence while restoring ionic gradients.",
    "pdfPage": 14,
    "pdfQuote": "Electrolytes Homeostasis... Na+/K+ ATPase... 3:2"
  },
  {
    "id": 9,
    "category": "Cardiac Physiology: Sodium-Calcium Exchange",
    "questionText": "The sodium-calcium exchanger normally transports three sodium ions into the cell for each calcium ion extruded. Which statement about this transporter is most accurate?",
    "options": [
      {
        "text": "It operates exclusively in one direction regardless of ionic conditions",
        "explanation": "Incorrect. The direction of exchange depends on intracellular sodium and calcium concentrations; it can run in reverse when intracellular sodium rises. This would be the correct answer if the exchanger were an ATP-driven pump with fixed directionality."
      },
      {
        "text": "It operates exclusively in a single fixed direction regardless of prevailing intracellular ionic conditions",
        "explanation": "Correct. In forward mode the exchanger imports three sodium ions while exporting one calcium ion, so each cycle carries net positive charge into the cell. This produces an inward, depolarizing current known as the sodium-calcium exchanger current. Because it depolarizes the membrane, this current can contribute to arrhythmia formation, a concept the lecturer explicitly flags for later study of afterdepolarizations."
      },
      {
        "text": "It requires direct ATP hydrolysis to move calcium against its gradient",
        "explanation": "Incorrect. Unlike the calcium ATPase, the exchanger is driven by the sodium electrochemical gradient rather than by direct ATP hydrolysis. This would be the correct answer if the transporter described were SERCA or the plasma membrane calcium ATPase."
      },
      {
        "text": "It is located principally on the sarcoplasmic reticulum membrane",
        "explanation": "Incorrect. The exchanger resides on the cell membrane; it is the calcium ATPase that is chiefly located on the sarcoplasmic reticulum. This would be the correct answer if the question described SERCA."
      },
      {
        "text": "Its ongoing transport activity hyperpolarizes the myocyte throughout diastole and stabilizes resting potential",
        "explanation": "Incorrect. Net inward positive charge depolarizes rather than hyperpolarizes the membrane. This would be the correct answer if the transporter exported more positive charge than it imported, as the sodium-potassium ATPase does."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Forward-mode Na⁺/Ca²⁺ exchange (3 Na⁺ in : 1 Ca²⁺ out) is electrogenic and depolarizing — a current implicated in triggered arrhythmias.",
    "pdfPage": 14,
    "pdfQuote": "Electrolytes Homeostasis... Na+/Ca++ exchanger"
  },
  {
    "id": 10,
    "category": "Cardiac Electrophysiology: Refractory Periods",
    "questionText": "During a specific interval of the ventricular action potential, no stimulus, regardless of strength, can evoke a second action potential. Which factor determines this interval in fast-response fibers?",
    "options": [
      {
        "text": "The time required for L-type calcium channels to regain their resting conformation",
        "explanation": "Incorrect. Calcium channel recovery determines the effective refractory period in slow-response nodal fibers, not in fast-response tissue. This would be the correct answer if the fiber described were from the sinoatrial or atrioventricular node."
      },
      {
        "text": "The duration of delayed rectifier potassium channel activation",
        "explanation": "Incorrect. Although potassium currents shape action potential duration and thereby influence refractoriness indirectly, the absolute inability to generate a new action potential is dictated by sodium channel availability. This would be the correct answer if the question asked which current terminates the plateau."
      },
      {
        "text": "The activity of the sodium-potassium ATPase in restoring gradients",
        "explanation": "Incorrect. Pump activity restores ionic concentrations over many beats but does not set the millisecond-scale refractory interval. This would be the correct answer if the question addressed long-term maintenance of excitability."
      },
      {
        "text": "The magnitude of the transient outward potassium current",
        "explanation": "Incorrect. The transient outward current shapes the phase 1 notch and influences plateau height but does not define absolute refractoriness. This would be the correct answer if the question concerned early repolarization morphology."
      },
      {
        "text": "The proportion of fast sodium channels remaining in the inactivated state",
        "explanation": "Correct. In fast-response fibers the effective refractory period is governed by the status of the fast sodium channel. Following phase 0, the inactivation gate closes and the channel enters an inactivated state from which it cannot reopen. Recovery requires the membrane potential to fall below threshold, which occurs near the end of phase 3. Until enough channels have recovered, no stimulus of any strength can elicit a propagated response, defining the effective (absolute) refractory period."
      }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "In fast-response fibers, the effective refractory period is set by fast sodium channel inactivation and lasts from phase 0 until membrane potential falls below threshold in phase 3.",
    "pdfPage": 35,
    "pdfQuote": "Effective refractory period (ERP) (Absolute refractory period) No AP can be generated. Na+ channels: inactivated"
  },
  {
    "id": 11,
    "category": "Cardiac Electrophysiology: Pacemaker Activity",
    "questionText": "A recording from a sinoatrial nodal cell shows that phase 4 is not flat but instead drifts progressively upward until threshold is reached and a new action potential fires. Which current is chiefly responsible for this spontaneous drift?",
    "options": [
      {
        "text": "Inward rectifier potassium current",
        "explanation": "Incorrect. Deactivation of the inward rectifier contributes to phase 4 depolarization, but it is a secondary contributor rather than the principal driver, and an active inward rectifier current would oppose depolarization. This would be the correct answer if the question asked what stabilizes the resting potential in ventricular myocytes."
      },
      {
        "text": "Pacemaker (funny) current through HCN channels",
        "explanation": "Correct. Spontaneous phase 4 depolarization is initiated chiefly by the pacemaker channel, also called the hyperpolarization-activated cyclic nucleotide-gated (HCN) channel or funny channel. The current it carries, designated I_f, is a nonselective inward cation current activated by hyperpolarization. Deactivation of I_K1 and activation of T-type calcium channels also contribute, making automaticity multifactorial, but the funny current is the major force."
      },
      {
        "text": "Transient outward potassium current",
        "explanation": "Incorrect. This outward current repolarizes rather than depolarizes and operates in phase 1 of fast-response cells. This would be the correct answer if the question described the notch of a ventricular action potential."
      },
      {
        "text": "Voltage-gated fast sodium current carried by tetrodotoxin-sensitive channels of the working myocardium",
        "explanation": "Incorrect. Slow-response nodal fibers lack functional voltage-gated fast sodium channels; the pacemaker channel is distinct from the fast sodium channel. This would be the correct answer if the cell described were a Purkinje fiber."
      },
      {
        "text": "Delayed rectifier potassium current",
        "explanation": "Incorrect. The delayed rectifier mediates phase 3 repolarization; its outward current would hyperpolarize rather than produce the upward drift. This would be the correct answer if the question described repolarization of the nodal action potential."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Phase 4 spontaneous depolarization is driven primarily by the funny current (I_f) through HCN channels, with contributions from I_K1 deactivation and T-type calcium channels.",
    "pdfPage": 32,
    "pdfQuote": "No true resting membrane potential... 1. Pacemaker (funny) channel 2. Deactivation of Ik1 3. T-type Ca channel"
  },
  {
    "id": 12,
    "category": "Cardiac Physiology: Excitation-Contraction Coupling",
    "questionText": "In cardiac excitation-contraction coupling, calcium entering through L-type channels on the T-tubules binds to a receptor on the sarcoplasmic reticulum, causing a much larger release of calcium into the cytosol. What is this receptor, and what is the process called?",
    "options": [
      {
        "text": "Dihydropyridine receptor; voltage-gated calcium entry",
        "explanation": "Incorrect. The dihydropyridine receptor is the L-type calcium channel on the T-tubule that admits the trigger calcium; it is not the sarcoplasmic reticulum release channel. This would be the correct answer if the question asked to name the T-tubular voltage sensor."
      },
      {
        "text": "SERCA; calcium reuptake into the sarcoplasmic reticulum",
        "explanation": "Incorrect. SERCA pumps calcium back into the sarcoplasmic reticulum during diastole to produce relaxation; it does not mediate release. This would be the correct answer if the question described the mechanism terminating contraction."
      },
      {
        "text": "Ryanodine receptor; calcium-induced calcium release",
        "explanation": "Correct. Calcium entering through the L-type calcium channel (dihydropyridine receptor) on the T-tubule binds the calcium release channel of the sarcoplasmic reticulum, known as the ryanodine receptor. This binding opens the channel and permits a large efflux of stored calcium into the cytoplasm. The process is termed calcium-induced calcium release, and the sarcoplasmic reticulum, not transsarcolemmal influx, supplies the major share of the calcium that triggers systolic contraction."
      },
      {
        "text": "Sodium-calcium exchanger; reverse-mode calcium loading",
        "explanation": "Incorrect. The exchanger resides on the sarcolemma and normally extrudes calcium; it is not the sarcoplasmic reticulum release channel. This would be the correct answer if the question concerned digoxin's mechanism of increasing intracellular calcium."
      },
      {
        "text": "Phospholamban; disinhibition of calcium uptake",
        "explanation": "Incorrect. Phospholamban regulates SERCA activity rather than serving as the release channel. This would be the correct answer if the question addressed regulation of calcium reuptake."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Calcium-induced calcium release: L-type (dihydropyridine receptor) calcium entry triggers ryanodine receptor opening; SR-released calcium is the major source of systolic calcium.",
    "pdfPage": 28,
    "pdfQuote": "Excitation-Contraction Coupling Calcium-induced Ca++ release (CICR)... Ca++ release channel Ryanodine receptor"
  },
  {
    "id": 13,
    "category": "Cardiac Electrophysiology: Potassium Disorders",
    "questionText": "A patient's serum potassium rises substantially above normal. According to the mechanisms discussed, which pair of changes occurs in the ventricular myocyte?",
    "options": [
      {
        "text": "Membrane potential becomes more negative and potassium permeability falls",
        "explanation": "Incorrect. These are the changes of hypokalemia, not hyperkalemia. Raising extracellular potassium makes the equilibrium potential less negative and opens more potassium channels. This would be the correct answer if the serum potassium had fallen below normal."
      },
      {
        "text": "Membrane potential is unchanged while calcium permeability rises",
        "explanation": "Incorrect. Extracellular potassium directly determines the potassium equilibrium potential and therefore alters resting membrane potential; calcium permeability is not the primary variable here. This would be the correct answer if the disturbance involved extracellular calcium."
      },
      {
        "text": "Membrane potential becomes more negative and sodium permeability rises",
        "explanation": "Incorrect. Hyperkalemia depolarizes rather than hyperpolarizes the cell, and it impairs rather than enhances sodium channel availability. This would be the correct answer if the question described a condition that both hyperpolarized the cell and increased sodium conductance, which hyperkalemia does not."
      },
      {
        "text": "Membrane potential becomes less negative and potassium permeability rises",
        "explanation": "Correct. By the Nernst relationship, increasing extracellular potassium raises the potassium equilibrium potential, so the resting membrane potential becomes less negative. Hyperkalemia additionally opens more potassium channels, increasing potassium permeability and thereby speeding repolarization. The first change shortens the distance to threshold initially but impairs sodium channel recovery, while the second accelerates repolarization and produces peaked T waves."
      },
      {
        "text": "Membrane potential becomes less negative and potassium permeability falls",
        "explanation": "Incorrect. The direction of the voltage change is right, but hyperkalemia increases rather than decreases potassium conductance; decreased conductance is the hallmark of hypokalemia. This would be the correct answer if only the voltage change occurred without any change in channel opening."
      }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Hyperkalemia does two things: raises (less negative) the resting potential and increases potassium permeability, producing peaked T waves and eventually a widened QRS.",
    "pdfPage": 24,
    "pdfQuote": "1. Membrane potential becomes more positive... 2. Increases K+ permeability (by open more K channels)"
  },
  {
    "id": 14,
    "category": "Cardiac Electrophysiology: Action Potential Duration",
    "questionText": "A comparison of action potential durations shows that a nerve action potential lasts approximately one millisecond while a ventricular action potential lasts 300 to 400 milliseconds. What is the principal functional consequence of this prolonged cardiac action potential?",
    "options": [
      {
        "text": "It permits summation of contractions to increase force",
        "explanation": "Incorrect. The prolonged action potential specifically prevents summation; summation and tetanus are features of skeletal muscle, whose brief action potential ends long before contraction peaks. This would be the correct answer if the tissue described were skeletal muscle."
      },
      {
        "text": "It produces a long effective refractory period that prevents tetanic contraction",
        "explanation": "Correct. Action potential duration is directly related to the effective refractory period: the longer the action potential, the longer the interval during which no new action potential can be generated. In cardiac muscle the long plateau and resulting refractory period span contraction and much of relaxation, so a second action potential cannot occur during contraction. This prevents the summation seen in skeletal muscle and is why cardiac muscle cannot develop tetanus, which is essential for the heart to alternately fill and eject."
      },
      {
        "text": "It allows the heart to conduct impulses more rapidly",
        "explanation": "Incorrect. Conduction velocity depends on upstroke velocity, cell size, and gap junction conductance rather than on total action potential duration. This would be the correct answer if the question asked why Purkinje fibers conduct fastest."
      },
      {
        "text": "It substantially reduces the total metabolic energy cost associated with each individual heartbeat",
        "explanation": "Incorrect. A prolonged plateau with sustained calcium entry increases rather than decreases the ionic load that pumps must subsequently restore. This would be the correct answer if the question concerned energy efficiency, which was not the stated rationale."
      },
      {
        "text": "It enables spontaneous automaticity in working myocardium",
        "explanation": "Incorrect. Automaticity arises from phase 4 spontaneous depolarization in pacemaker tissue, not from action potential duration in working myocytes. This would be the correct answer if the question described nodal pacemaker function."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Long cardiac action potential (300-400 ms) → long effective refractory period → no summation or tetanus, allowing alternating filling and ejection.",
    "pdfPage": 39,
    "pdfQuote": "long plateau phase and the long effective refractory period prevent... a second action potential during cardiac contraction"
  },
  {
    "id": 15,
    "category": "Cardiac Pharmacology: Antiarrhythmic Principles",
    "questionText": "A class of antiarrhythmic medication acts by blocking potassium channels in cardiac myocytes. Based on the relationship between repolarizing currents and refractoriness, what is the expected electrophysiologic effect?",
    "options": [
      {
        "text": "Shortened action potential duration and shortened effective refractory period",
        "explanation": "Incorrect. Blocking the outward current responsible for repolarization delays rather than accelerates repolarization, lengthening the action potential. This would be the correct answer if the agent enhanced potassium conductance."
      },
      {
        "text": "Unchanged action potential duration with slowed conduction velocity",
        "explanation": "Incorrect. Conduction velocity is chiefly a function of phase 0 upstroke and gap junction properties, which are targets of sodium channel blockade rather than potassium blockade. This would be the correct answer if the drug blocked fast sodium channels."
      },
      {
        "text": "Abolition of phase 4 spontaneous depolarization in ventricular myocytes",
        "explanation": "Incorrect. Working ventricular myocytes do not normally exhibit phase 4 spontaneous depolarization, and potassium channel blockade does not target the funny current that drives nodal automaticity. This would be the correct answer if the agent specifically inhibited HCN channels."
      },
      {
        "text": "Prolonged action potential duration and prolonged effective refractory period",
        "explanation": "Correct. Repolarization depends on outward potassium current, so blocking potassium channels delays repolarization and prolongs action potential duration. Because the effective refractory period is directly related to action potential duration, it is prolonged as well. Lengthening refractoriness is a principal antiarrhythmic strategy, as it prevents premature reexcitation and can interrupt reentrant circuits."
      },
      {
        "text": "Conversion of fast-response fibers into slow-response fibers",
        "explanation": "Incorrect. The response type is determined by which channel carries phase 0; potassium channel blockade does not remove fast sodium channels. This would be the correct answer if the intervention had eliminated sodium channel function entirely."
      }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Potassium channel blockers prolong action potential duration and therefore the effective refractory period — the basis of their antiarrhythmic action.",
    "pdfPage": 37,
    "pdfQuote": "a type of antiarrhythmic medication, known as the potassium channel blockers, can increase AP duration and ERP"
  },
  {
    "id": 16,
    "category": "Nephrology-Cardiology: Hyperkalemia Management",
    "questionText": "A 62-year-old man with end-stage renal disease misses two dialysis sessions and presents with generalized weakness and palpitations. Temperature is 36.8°C (98.2°F), blood pressure 148/86 mmHg, pulse 54/min and regular, respirations 16/min, and oxygen saturation 97% on room air. Physical examination reveals diffuse muscle weakness without focal deficits. Serum potassium is 7.9 mEq/L. The electrocardiogram demonstrates tall, narrow, symmetrically peaked T waves and a QRS duration of 148 ms. Which cellular derangement best accounts for the widened QRS specifically?",
    "options": [
      {
        "text": "Markedly accelerated ventricular repolarization resulting from a rise in open potassium channel number",
        "explanation": "Correct. The QRS complex reflects ventricular depolarization, which depends on the fast sodium current of phase 0. Recovery of the fast sodium channel from its inactivated state requires the membrane potential to fall below threshold. Hyperkalemia raises the resting potential toward threshold, so fewer sodium channels recover between beats. With fewer available channels, phase 0 depolarization is slowed and ventricular depolarization is delayed, widening the QRS complex. If the potential remains above threshold entirely, sodium channels cannot recover at all and cardiac arrest ensues."
      },
      {
        "text": "Accelerated repolarization from increased potassium channel opening",
        "explanation": "Incorrect. Increased potassium conductance does occur in hyperkalemia and does accelerate repolarization, but this change produces the peaked T waves rather than the widened QRS. The QRS represents ventricular depolarization, not repolarization, so a repolarization change cannot explain its widening. This would be the correct answer if the question had asked about the origin of the peaked T waves."
      },
      {
        "text": "Prolongation of the plateau by enhanced L-type calcium current",
        "explanation": "Incorrect. Plateau prolongation would lengthen the QT interval rather than widen the QRS, and hyperkalemia is not described as enhancing calcium current. This would be the correct answer if the patient had a condition that prolonged phase 2 and produced QT prolongation."
      },
      {
        "text": "Markedly increased automaticity of His-Purkinje pacemaker channels driving accelerated ventricular escape",
        "explanation": "Incorrect. Enhanced automaticity would produce ectopic beats or an accelerated escape rhythm, not a uniformly widened QRS with a regular rhythm at 54/min. This would be the correct answer if the tracing had shown a wide-complex escape rhythm arising independently of atrial activity."
      },
      {
        "text": "Reversal of the sodium-calcium exchanger raising cytosolic calcium",
        "explanation": "Incorrect. Exchanger reversal increases contractility and is characteristic of digitalis effect rather than of hyperkalemia, and it does not slow ventricular depolarization. This would be the correct answer if the patient were describing digoxin toxicity with increased inotropy."
      }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "In hyperkalemia the widened QRS results from impaired fast sodium channel recovery (depolarized resting potential), whereas peaked T waves result from increased potassium conductance.",
    "pdfPage": 24,
    "pdfQuote": "↑membrane potential slows Na channel recovery (slows phase 0 depolarization, widens QRS on ECG)"
  },
  {
    "id": 17,
    "category": "Cardiothoracic Surgery: Cardioplegia",
    "questionText": "A 68-year-old woman undergoes coronary artery bypass grafting. After aortic cross-clamping, the surgical team infuses a solution into the coronary circulation, and the heart promptly ceases contracting and remains motionless throughout the anastomoses. Which mechanism explains the arrest produced by this solution?",
    "options": [
      {
        "text": "Blockade of L-type calcium channels preventing excitation-contraction coupling",
        "explanation": "Incorrect. While preventing calcium entry would impair contraction, the standard cardioplegia mechanism described in the lecture relies on potassium-induced depolarization rather than direct calcium channel blockade. This would be the correct answer if the solution's active component were a dihydropyridine or non-dihydropyridine calcium antagonist."
      },
      {
        "text": "Sustained depolarization that holds fast sodium channels inactivated",
        "explanation": "Correct. Cardioplegia solutions contain a high potassium concentration. By the Nernst relationship, markedly elevated extracellular potassium raises the resting membrane potential so that it no longer falls below the threshold required for fast sodium channel recovery. With sodium channels locked in the inactivated state, no phase 0 depolarization can be generated, so the heart cannot be excited and remains arrested in diastole. This is the deliberate clinical application of the same mechanism that makes severe hyperkalemia lethal."
      },
      {
        "text": "Hyperpolarization of myocytes below the range of pacemaker activation",
        "explanation": "Incorrect. High potassium depolarizes rather than hyperpolarizes cardiac cells; hyperpolarization would result from lowering extracellular potassium. This would be the correct answer if the solution produced a markedly more negative resting potential."
      },
      {
        "text": "Irreversible inhibition of the sodium-potassium ATPase",
        "explanation": "Incorrect. Pump inhibition is the mechanism of digitalis and increases contractility rather than producing immediate arrest. This would be the correct answer if the vignette described a patient with digoxin toxicity."
      },
      {
        "text": "Depletion of sarcoplasmic reticulum calcium stores by ryanodine receptor blockade",
        "explanation": "Incorrect. Cardioplegic arrest is an electrical phenomenon that prevents action potential generation, not a primary failure of calcium storage. This would be the correct answer if an agent had specifically locked ryanodine receptors closed."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "High-potassium cardioplegia arrests the heart by depolarizing myocytes so that fast sodium channels cannot recover — the therapeutic use of hyperkalemic arrest.",
    "pdfPage": 25,
    "pdfQuote": "utilized clinically to arrest the heart during open heart surgery or heart transplantation by applying the cardioplegia solution"
  },
  {
    "id": 18,
    "category": "Cardiology: Hypokalemia and Repolarization",
    "questionText": "A 44-year-old woman with bulimia nervosa presents with fatigue and palpitations. Temperature is 36.6°C (97.9°F), blood pressure 104/68 mmHg, pulse 92/min, and respirations 14/min. Examination shows dry mucous membranes and diminished deep tendon reflexes. Serum potassium is 2.4 mEq/L and magnesium is normal. Her electrocardiogram shows flattened T waves and a corrected QT interval of 520 ms. Which cellular change is most directly responsible for her prolonged QT interval?",
    "options": [
      {
        "text": "A more negative resting potential increasing the distance to threshold",
        "explanation": "Incorrect. Low extracellular potassium does make the resting potential more negative, and this would theoretically decrease excitability, but the lecturer explicitly states that the major risk in hypokalemia is not the voltage change. The QT interval reflects the duration of depolarization plus repolarization, which is governed by conductance. This would be the correct answer if the question had asked why hypokalemia theoretically reduces excitability."
      },
      {
        "text": "A considerably more negative resting potential that increases the voltage distance to threshold",
        "explanation": "Incorrect. Hypokalemia acts on potassium conductance rather than augmenting calcium entry; an increase in calcium current is not the described mechanism. This would be the correct answer if the patient had a channelopathy causing gain of function in L-type calcium channels."
      },
      {
        "text": "Accelerated inactivation of fast sodium channels shortening phase 0",
        "explanation": "Incorrect. Changes in sodium channel availability alter QRS duration rather than QT interval, and hypokalemia does not accelerate sodium channel inactivation. This would be the correct answer if the electrocardiogram had shown QRS widening from impaired sodium channel function."
      },
      {
        "text": "Enhanced funny current increasing ventricular automaticity",
        "explanation": "Incorrect. Working ventricular myocytes do not normally rely on funny current, and increased automaticity would alter rate rather than repolarization duration. This would be the correct answer if the finding were an accelerated idioventricular rhythm."
      },
      {
        "text": "Reduced potassium conductance slowing repolarization and prolonging action potential duration",
        "explanation": "Correct. In hypokalemia fewer potassium channels are open, so potassium conductance falls. Because repolarization depends on outward potassium current, this slows phases 2 and 3 and prolongs total action potential duration. On the surface electrocardiogram the lengthened repolarization appears as a flattened T wave and a prolonged QT interval. The clinical importance is that prolonged repolarization creates vulnerability to ventricular tachyarrhythmias, which is why serum potassium is monitored closely."
      }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Hypokalemia's dominant risk is decreased potassium conductance → delayed repolarization → prolonged action potential, flattened T waves, long QT, and ventricular tachyarrhythmia risk.",
    "pdfPage": 26,
    "pdfQuote": "2. Decrease K+ permeability (fewer channels open) Delays repolarization (increases AP duration, prolonged Q-T interval...)"
  },
  {
    "id": 19,
    "category": "Cardiac Pharmacology: Digitalis Mechanism",
    "questionText": "A 76-year-old man with heart failure and atrial fibrillation is treated with a medication that increases the force of ventricular contraction. Studies of his myocytes reveal elevated intracellular sodium concentration and elevated cytosolic calcium during systole. Which sequence best explains the increase in contractility?",
    "options": [
      {
        "text": "Sodium-potassium ATPase inhibition raises intracellular sodium, driving the sodium-calcium exchanger toward calcium entry",
        "explanation": "Correct. Inhibition of the sodium-potassium ATPase prevents normal sodium extrusion, so intracellular sodium rises. The sodium-calcium exchanger depends on the transsarcolemmal sodium gradient; when intracellular sodium is elevated, the exchanger favors its reverse mode, exporting sodium and importing calcium. The resulting increase in intracellular calcium enhances calcium available for contraction, producing positive inotropy. This is the mechanism explicitly linked to digitalis in the lecture."
      },
      {
        "text": "Direct agonism at beta-1 adrenergic receptors increasing cyclic AMP",
        "explanation": "Incorrect. Beta-adrenergic stimulation does increase contractility, but it would not produce the elevated intracellular sodium described, and it acts through a signaling cascade rather than through pump inhibition. This would be the correct answer if the patient were receiving dobutamine or a similar catecholamine."
      },
      {
        "text": "Blockade of L-type calcium channels that substantially reduces calcium efflux from the myocyte cytosol",
        "explanation": "Incorrect. Blocking L-type channels decreases calcium entry and reduces contractility; these channels mediate influx rather than efflux. This would be the correct answer if the patient were experiencing negative inotropy from verapamil."
      },
      {
        "text": "Enhanced SERCA activity accelerating calcium reuptake into the sarcoplasmic reticulum",
        "explanation": "Incorrect. Accelerating reuptake lowers cytosolic calcium and hastens relaxation rather than raising systolic calcium, and it would not elevate intracellular sodium. This would be the correct answer if the question described a lusitropic (relaxation-enhancing) effect."
      },
      {
        "text": "Increased pacemaker funny current progressively shortening the diastolic interval between successive beats",
        "explanation": "Incorrect. The funny current governs rate rather than force of contraction and is not affected by sodium pump inhibition. This would be the correct answer if the drug had produced sinus tachycardia through HCN channel activation."
      }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Digitalis: Na⁺/K⁺-ATPase inhibition → ↑ intracellular Na⁺ → Na⁺/Ca²⁺ exchanger reverse mode → ↑ intracellular Ca²⁺ → increased contractility.",
    "pdfPage": 14,
    "pdfQuote": "In condition of increased intracellular sodium concentration, such as in the condition of digitalis treatment, the exchanger will try to pump out sodium and let in calcium"
  },
  {
    "id": 20,
    "category": "Patient Safety: Potassium Administration",
    "questionText": "A hospitalized patient with a serum potassium of 2.9 mEq/L requires repletion. A trainee proposes giving the entire dose as a rapid intravenous bolus to correct the deficit quickly. Which physiologic principle most directly explains why this must not be done?",
    "options": [
      {
        "text": "Rapid potassium delivery produces immediate membrane hyperpolarization followed promptly by asystole",
        "explanation": "Incorrect. Elevated extracellular potassium depolarizes cardiac cells by raising the potassium equilibrium potential; it does not hyperpolarize them. The danger is real but the direction of the voltage change stated here is wrong. This would be the correct answer if administration produced a markedly more negative resting potential."
      },
      {
        "text": "An abrupt rise in extracellular potassium depolarizes myocytes so sodium channels cannot recover, risking arrest",
        "explanation": "Correct. Because extracellular potassium determines the potassium equilibrium potential, a sudden large increase in serum potassium rapidly raises the resting membrane potential. If the potential no longer falls below the threshold of approximately -55 mV, the fast sodium channels remain inactivated and cannot reopen, so no action potential can be generated and the heart arrests. This is why potassium must be given as a controlled infusion rather than as a bolus, allowing distribution and avoiding a transient lethal concentration spike."
      },
      {
        "text": "Bolus potassium precipitates with serum calcium, causing embolic obstruction",
        "explanation": "Incorrect. The hazard is electrophysiologic rather than a precipitation or embolic phenomenon. This would be the correct answer if the concern involved co-administration of incompatible solutions forming precipitates."
      },
      {
        "text": "Rapid potassium administration shortens the QT interval to a dangerous degree",
        "explanation": "Incorrect. Although hyperkalemia does accelerate repolarization, the life-threatening consequence is failure of depolarization and arrest, not QT shortening per se. This would be the correct answer if the primary danger of hyperkalemia were repolarization abnormality alone."
      },
      {
        "text": "Sudden potassium loading irreversibly inhibits the sodium-potassium ATPase throughout the entire myocardium",
        "explanation": "Incorrect. The pump is not irreversibly inhibited by extracellular potassium; indeed potassium is its substrate for import. This would be the correct answer if the agent administered were a cardiac glycoside."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Never give potassium as a rapid IV bolus: an abrupt rise depolarizes myocytes above the sodium channel recovery threshold and can cause cardiac arrest.",
    "pdfPage": 25,
    "pdfQuote": "to avoid rapid increase in blood K concentration, K cannot be given as a bolus IV injection in patients"
  },
  {
    "id": 21,
    "category": "Cardiac Electrophysiology: Refractoriness in Nodal Tissue",
    "questionText": "An electrophysiologist compares refractory behavior in atrioventricular nodal fibers with that in ventricular myocardium. In the nodal fibers, refractoriness persists well beyond the end of repolarization and extends into phase 4. Which explanation best accounts for this difference?",
    "options": [
      {
        "text": "Nodal fibers possess a substantially longer plateau phase than ordinary working ventricular myocytes do",
        "explanation": "Incorrect. Slow-response action potentials have only three phases and lack a plateau entirely; the plateau is a feature of fast-response cells. This would be the correct answer if nodal cells possessed a prolonged phase 2, which they do not."
      },
      {
        "text": "Fast sodium channels in nodal tissue recover more slowly than in ventricle",
        "explanation": "Incorrect. Slow-response nodal fibers do not possess functional voltage-gated fast sodium channels, so sodium channel recovery cannot govern their refractoriness. This would be the correct answer if nodal cells were fast-response fibers with unusually slow sodium recovery kinetics."
      },
      {
        "text": "Fast sodium channels within nodal tissue recover considerably more slowly than those in the ventricle",
        "explanation": "Incorrect. Nodal cells have a less negative maximum diastolic potential (about -60 mV) than ventricular myocytes, and they lack a true stable resting potential. This would be the correct answer if the premise about their voltage were reversed."
      },
      {
        "text": "Nodal refractoriness reflects the time required for calcium channels to return to their resting conformation",
        "explanation": "Correct. In slow-response fibers phase 0 is generated by L-type calcium channels rather than fast sodium channels, so the effective refractory period is determined by the time these calcium channels need to recover their resting conformation. Because calcium channel recovery is comparatively slow, the relative refractory period typically extends well into phase 4, rather than ending at the beginning of phase 4 as it does in fast-response fibers. This property allows the atrioventricular node to filter rapid atrial impulses."
      },
      {
        "text": "The transient outward current in nodal cells prolongs the refractory state",
        "explanation": "Incorrect. The transient outward current shapes phase 1 of fast-response action potentials, which nodal cells do not exhibit. This would be the correct answer if the tissue in question were epicardial ventricular myocardium with prominent I_to."
      }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "In slow-response (nodal) fibers, the effective refractory period depends on L-type calcium channel recovery, and relative refractoriness extends into phase 4 — enabling AV nodal filtering.",
    "pdfPage": 36,
    "pdfQuote": "The cause of effective refractory period in slow response fibers is the time required for calcium channels to return to their resting conformation"
  },
  {
    "id": 22,
    "category": "Cardiac Electrophysiology: Stimulus Timing",
    "questionText": "During an electrophysiology study, a premature stimulus is delivered to the ventricle late in phase 3, after the membrane potential has fallen below threshold but before phase 4 begins. A stimulus of greater than normal strength elicits a propagated but smaller-than-normal action potential. Which statement best explains this observation?",
    "options": [
      {
        "text": "Sodium channels are partially recovered, so a stronger stimulus produces a smaller action potential",
        "explanation": "Correct. Once the membrane potential falls below threshold at the end of phase 3, fast sodium channels begin recovering from inactivation, marking the start of the relative refractory period. Because only a fraction of channels have recovered, a stimulus stronger than normal is required, and the resulting upstroke is generated by fewer available channels, producing an action potential of reduced amplitude. The relative refractory period ends at the beginning of phase 4, when recovery is complete."
      },
      {
        "text": "All fast sodium channels have fully recovered, so a normal response is generated",
        "explanation": "Incorrect. If all channels had recovered, the resulting action potential would be of normal amplitude and a normal-strength stimulus would suffice. The reduced amplitude and increased stimulus requirement indicate incomplete recovery. This would be the correct answer if the stimulus had been delivered during phase 4."
      },
      {
        "text": "The cell is in its effective refractory period, and the response is purely local",
        "explanation": "Incorrect. During the effective refractory period no propagated action potential can be elicited regardless of stimulus strength; the fact that a propagated response occurred excludes this state. This would be the correct answer if the stimulus had been applied during the plateau."
      },
      {
        "text": "Calcium channels have replaced sodium channels as the depolarizing current",
        "explanation": "Incorrect. Ventricular myocytes remain fast-response cells; calcium does not substitute for sodium as the phase 0 charge carrier in this setting. This would be the correct answer if the tissue described were nodal."
      },
      {
        "text": "The transient outward potassium current has actively prevented the cell from depolarizing completely",
        "explanation": "Incorrect. The reduced amplitude reflects limited sodium channel availability rather than opposition by the phase 1 current. This would be the correct answer if the question concerned the depth of the phase 1 notch."
      }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "The relative refractory period begins when membrane potential falls below threshold and sodium channels start recovering; stronger stimuli evoke smaller action potentials.",
    "pdfPage": 35,
    "pdfQuote": "2. Relative refractory period (RRP) Stronger than normal stimulation can generate a second, but smaller AP. Na+ channels: partially recovering"
  },
  {
    "id": 23,
    "category": "Cardiac Physiology: Diastolic Calcium Removal",
    "questionText": "A researcher studying myocardial relaxation selectively inhibits the transporter on the sarcoplasmic reticulum responsible for sequestering cytosolic calcium during diastole. Which functional consequence is most expected?",
    "options": [
      {
        "text": "Faster relaxation with reduced diastolic calcium",
        "explanation": "Incorrect. Inhibiting the pump that removes calcium from the cytosol would raise, not lower, diastolic calcium and would impair rather than accelerate relaxation. This would be the correct answer if the intervention had enhanced pump activity."
      },
      {
        "text": "Complete abolition of contraction due to absent trigger calcium",
        "explanation": "Incorrect. Trigger calcium enters through L-type channels on the T-tubules and is unaffected by blocking the reuptake pump; contraction would still be initiated. This would be the correct answer if L-type calcium channels had been blocked."
      },
      {
        "text": "Conversion of the ventricular action potential into a slow-response type",
        "explanation": "Incorrect. Action potential type is determined by the channel carrying phase 0, which is unchanged by inhibiting a calcium reuptake pump. This would be the correct answer if fast sodium channels had been eliminated."
      },
      {
        "text": "Impaired relaxation with elevated diastolic cytosolic calcium",
        "explanation": "Correct. Calcium is removed from the cytosol during diastole by two mechanisms: the calcium ATPase of the sarcoplasmic reticulum, known as SERCA, which pumps calcium back into the sarcoplasmic reticulum, and the sodium-calcium exchanger, which extrudes calcium across the sarcolemma. Blocking SERCA leaves calcium in the cytosol longer, so cross-bridge cycling persists and relaxation is impaired, with elevated diastolic calcium. Over time, depletion of sarcoplasmic reticulum stores would also blunt subsequent contractions."
      },
      {
        "text": "Loss of the effective refractory period",
        "explanation": "Incorrect. Refractoriness is determined by ion channel recovery rather than by calcium sequestration into the sarcoplasmic reticulum. This would be the correct answer if the intervention had altered sodium channel gating."
      }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Diastolic calcium removal occurs via SERCA (into the SR) and the Na⁺/Ca²⁺ exchanger (out of the cell); impairing either delays relaxation.",
    "pdfPage": 28,
    "pdfQuote": "Sarco(endo)plasmic reticulum Ca++ ATPase, SERCA"
  },
  {
    "id": 24,
    "category": "Cardiac Pharmacology: Nodal Selectivity",
    "questionText": "A 58-year-old woman with rapid atrial fibrillation requires slowing of ventricular response by inhibiting conduction through the atrioventricular node. Based on the ionic basis of nodal depolarization, which drug class targets the current responsible for phase 0 in that tissue?",
    "options": [
      {
        "text": "L-type calcium channel blockers",
        "explanation": "Correct. Phase 0 depolarization in the atrioventricular node is generated by opening of L-type calcium channels rather than fast sodium channels, because slow-response fibers lack functional voltage-gated fast sodium channels. Blocking L-type calcium channels therefore directly reduces the upstroke of the nodal action potential, slowing conduction through the node and reducing the ventricular rate during atrial fibrillation. This is exactly the reasoning the lecturer poses as a sample question."
      },
      {
        "text": "Fast sodium channel blockers",
        "explanation": "Incorrect. Sodium channel blockade principally affects fast-response tissue such as atrial and ventricular myocardium and the His-Purkinje system. Nodal fibers lack functional fast sodium channels, so this class does not directly target nodal phase 0. This would be the correct answer if the goal were to slow conduction through ventricular myocardium or accessory pathway tissue."
      },
      {
        "text": "Transient outward potassium channel blockers",
        "explanation": "Incorrect. The transient outward current shapes phase 1 of fast-response action potentials and is not present in the three-phase nodal action potential. This would be the correct answer if the target were the early repolarization notch of ventricular epicardium."
      },
      {
        "text": "HCN (funny channel) blockers",
        "explanation": "Incorrect. Funny channel blockade slows sinoatrial rate by reducing phase 4 spontaneous depolarization but does not directly inhibit atrioventricular nodal phase 0 conduction. This would be the correct answer if the therapeutic goal were sinus rate reduction without affecting conduction, as with ivabradine."
      },
      {
        "text": "Inward rectifier potassium channel blockers",
        "explanation": "Incorrect. The inward rectifier stabilizes resting potential in fast-response cells and does not generate nodal phase 0. This would be the correct answer if the aim were to destabilize the ventricular resting potential."
      }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Because nodal phase 0 depends on L-type calcium current, calcium channel blockers selectively slow AV nodal conduction — sodium channel blockers act on fast-response tissue instead.",
    "pdfPage": 8,
    "pdfQuote": "Fast versus Slow APs... Cause of Phase 0 Depolarization: Opening of Na+ Channel / Opening of Ca2+ (L) Channel"
  },
  {
    "id": 25,
    "category": "Cardiac Electrophysiology: Comparative Physiology",
    "questionText": "A student compares a skeletal muscle twitch with a cardiac contraction. In skeletal muscle the action potential lasts only a few milliseconds and contraction occurs largely after the refractory period has ended, permitting repeated stimulation to fuse contractions. Which consequence follows from this timing relationship?",
    "options": [
      {
        "text": "Skeletal muscle contraction is limited to a single twitch regardless of stimulation frequency",
        "explanation": "Incorrect. This describes cardiac rather than skeletal behavior; the entire point of the brief skeletal action potential is that repeated stimulation is possible during contraction. This would be the correct answer if the tissue described had a refractory period spanning contraction."
      },
      {
        "text": "Skeletal muscle relies on calcium-induced calcium release identical to cardiac muscle",
        "explanation": "Incorrect. Although both tissues use sarcoplasmic reticulum calcium, the question concerns the timing of action potentials relative to contraction, not the coupling mechanism. This would be the correct answer if the question asked about the source of activator calcium."
      },
      {
        "text": "Skeletal muscle can undergo tetanic contraction because additional action potentials occur during contraction",
        "explanation": "Correct. Because the skeletal muscle action potential is brief and its refractory period ends well before mechanical contraction peaks, additional action potentials can be generated while the muscle is still contracting. These summate, producing progressively greater force and ultimately fused, tetanic contraction. Cardiac muscle avoids this because its long plateau and correspondingly long effective refractory period span contraction and much of relaxation, preventing summation."
      },
      {
        "text": "Skeletal muscle fibers exhibit spontaneous automaticity in the intervals between successive stimuli",
        "explanation": "Incorrect. Automaticity is a property of cardiac pacemaker tissue with phase 4 spontaneous depolarization, not skeletal muscle. This would be the correct answer if the tissue were sinoatrial nodal."
      },
      {
        "text": "Skeletal muscle action potentials display a prominent and sustained plateau phase much like cardiac tissue",
        "explanation": "Incorrect. The plateau is unique to cardiac fast-response cells; skeletal muscle action potentials are brief and lack this feature. This would be the correct answer if the tissue described were ventricular myocardium."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Skeletal muscle tetanizes because its brief action potential allows repeat firing during contraction; cardiac muscle cannot, owing to its long plateau and refractory period.",
    "pdfPage": 38,
    "pdfQuote": "The muscle contraction occurs well after the effective refractory period... this is the reason tetanus contraction can occur in skeletal muscle"
  },
  {
    "id": 26,
    "category": "Cardiac Electrophysiology: Membrane Potential Determinants",
    "questionText": "An investigator applies the chord conductance equation, in which membrane potential equals the sum of each ion's relative conductance multiplied by its equilibrium potential. During phase 4 of a ventricular myocyte, sodium and calcium conductances are effectively zero. What does the equation predict, and how does this compare with measurement?",
    "options": [
      {
        "text": "Potential should approximate the sodium equilibrium potential and measures near +52 mV",
        "explanation": "Incorrect. With sodium conductance effectively zero during phase 4, the sodium equilibrium potential contributes essentially nothing to the weighted sum. Measured resting potential is near -90 mV, not positive. This would be the correct answer if sodium conductance were dominant, as occurs transiently in phase 0."
      },
      {
        "text": "Potential should approximate the calcium equilibrium potential and measures near +134 mV",
        "explanation": "Incorrect. Calcium conductance is negligible during phase 4, so its equilibrium potential does not determine resting voltage. This would be the correct answer if the cell were in the plateau phase with substantial calcium conductance."
      },
      {
        "text": "Potential should approximate the calcium equilibrium potential and measures close to positive 134 mV",
        "explanation": "Incorrect. The conductances do not cancel; potassium conductance dominates and drives the potential toward the potassium equilibrium value. This would be the correct answer if all ionic conductances were equal and gradients symmetric."
      },
      {
        "text": "Potential should approximate the potassium equilibrium potential and measures slightly less negative",
        "explanation": "Correct. When only potassium conductance is appreciable, the weighted sum reduces to the potassium equilibrium potential, predicting approximately -96 mV. Measured resting potential is about -90 mV, slightly less negative than predicted. The lecturer attributes this small discrepancy to variation in the assumed intracellular potassium concentration and to background leak currents carried by other ions, which pull the potential marginally away from the pure potassium value."
      },
      {
        "text": "Potential is indeterminate because the equation applies only during depolarization",
        "explanation": "Incorrect. The relationship applies at any instant, including rest; that is precisely why it predicts the resting potential accurately. This would be the correct answer if the equation were valid only for dynamic states."
      }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "With only potassium conductance appreciable at rest, membrane potential approximates E(K⁺) (~ -96 mV); the measured -90 mV reflects leak currents and concentration variation.",
    "pdfPage": 13,
    "pdfQuote": "membrane potential equals relative conductance of potassium times its equilibrium potential..."
  },
  {
    "id": 27,
    "category": "Cardiology: Transmural Repolarization",
    "questionText": "Recordings from ventricular myocytes isolated from the epicardial, midmyocardial, and endocardial layers demonstrate that action potential duration differs among these layers. What is the significance of this observation for the surface electrocardiogram?",
    "options": [
      {
        "text": "It creates transmural dispersion of repolarization, shaping the T wave",
        "explanation": "Correct. Because midmyocardial, endocardial, and epicardial myocytes have different action potential durations, they complete repolarization at different times. This transmural dispersion of repolarization generates the voltage gradients recorded as the T wave. The lecture notes these interlayer differences explicitly and flags them for further discussion, and clinically, exaggerated dispersion is a substrate for reentrant ventricular arrhythmias."
      },
      {
        "text": "It abolishes the T wave because opposing vectors cancel",
        "explanation": "Incorrect. Heterogeneity of repolarization contributes to the T wave rather than eliminating it; complete cancellation would leave no repolarization deflection at all. This would be the correct answer if all layers repolarized simultaneously and symmetrically."
      },
      {
        "text": "It determines the width of the QRS complex",
        "explanation": "Incorrect. The QRS reflects ventricular depolarization, which depends on the fast sodium current and conduction through the His-Purkinje system, not on differences in repolarization duration. This would be the correct answer if the question concerned conduction delay or bundle branch block."
      },
      {
        "text": "It directly determines the total width and morphology of the QRS complex on the surface tracing",
        "explanation": "Incorrect. The PR interval reflects atrial depolarization plus atrioventricular nodal conduction delay and is unrelated to ventricular transmural repolarization. This would be the correct answer if the question addressed AV nodal conduction time."
      },
      {
        "text": "It causes the P wave to become biphasic",
        "explanation": "Incorrect. The P wave arises from atrial depolarization, not ventricular repolarization heterogeneity. This would be the correct answer if the question concerned atrial activation sequence."
      }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Epicardial, midmyocardial, and endocardial myocytes differ in action potential duration; this transmural dispersion of repolarization underlies T wave morphology.",
    "pdfPage": 27,
    "pdfQuote": "ventricular myocytes from epicardial, endocardial and mid-layer have different action potential duration"
  },
  {
    "id": 28,
    "category": "Cardiac Electrophysiology: Sodium Channel States",
    "questionText": "A researcher clamps a ventricular myocyte at a maintained membrane potential of -40 mV, preventing it from repolarizing below threshold. Repeated suprathreshold stimuli fail to elicit any action potential. In which state are the fast sodium channels being held?",
    "options": [
      {
        "text": "Resting state with activation gate closed and inactivation gate open",
        "explanation": "Incorrect. In the resting state the channel is available to open, so a suprathreshold stimulus would successfully elicit an action potential. The failure to respond indicates unavailability. This would be the correct answer if the cell had been clamped at a normal resting potential near -90 mV."
      },
      {
        "text": "Inactivated state with the inactivation gate closed",
        "explanation": "Correct. After phase 0 the slow inactivation gate closes, placing the channel in the inactivated state, from which it cannot reopen. Recovery to the resting state requires the membrane potential to fall below threshold, at which point the activation gate closes and the inactivation gate slowly reopens. By clamping the cell at -40 mV, above the threshold of approximately -55 mV, the investigator prevents this recovery, so the channels remain inactivated and no stimulus can elicit an action potential."
      },
      {
        "text": "Activated state with both gates open",
        "explanation": "Incorrect. The activated state is transient, lasting a fraction of a millisecond, and it produces rather than prevents depolarization. This would be the correct answer if the question described the instant of the phase 0 upstroke."
      },
      {
        "text": "Open state stabilized by persistent depolarization",
        "explanation": "Incorrect. Persistent depolarization promotes inactivation rather than stabilizing the open state; a stabilized open channel would produce sustained sodium influx. This would be the correct answer if the intervention were a toxin that prevents inactivation."
      },
      {
        "text": "Closed state with both gates closed and available for activation",
        "explanation": "Incorrect. A channel available for activation would respond to a suprathreshold stimulus, which is not observed here. This would be the correct answer if the membrane had been repolarized fully before stimulation."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Fast sodium channels held above threshold remain inactivated and cannot reopen; recovery requires repolarization below threshold — the basis of hyperkalemic arrest.",
    "pdfPage": 17,
    "pdfQuote": "the sodium channel will stay in inactivated state until member potential drops below the threshold level at the end of phase 3"
  },
  {
    "id": 29,
    "category": "Cardiac Electrophysiology: Nodal Action Potential Features",
    "questionText": "An action potential recorded from a sinoatrial nodal fiber is compared with one from a ventricular myocyte. Which combination of findings would be expected in the nodal recording?",
    "options": [
      {
        "text": "Maximum diastolic potential near -60 mV, peak near 0 mV, and absent plateau",
        "explanation": "Correct. Slow-response nodal action potentials differ from fast-response ventricular action potentials in several linked ways. Their maximum diastolic potential is less negative, approximately -60 mV rather than -90 mV. Their peak reaches only about 0 mV instead of the +20 to +30 mV seen in ventricular cells. They comprise only three phases, phases 0, 3, and 4, with no phase 1 or plateau, and phase 4 is not flat but shows spontaneous depolarization."
      },
      {
        "text": "Resting potential near -90 mV with a prominent plateau phase",
        "explanation": "Incorrect. These are features of fast-response ventricular myocytes; nodal cells have a less negative potential and lack a plateau entirely. This would be the correct answer if the recording had come from working ventricular myocardium."
      },
      {
        "text": "Peak potential near positive 30 mV together with a characteristically rapid phase 0 upstroke velocity",
        "explanation": "Incorrect. A high peak and rapid upstroke characterize fast-response tissue driven by sodium current; nodal cells peak near 0 mV with a slow calcium-driven upstroke. This would be the correct answer if the fiber recorded were a Purkinje fiber."
      },
      {
        "text": "Flat phase 4 with stable resting potential maintained by I_K1",
        "explanation": "Incorrect. Nodal fibers have no true resting potential; phase 4 drifts upward via spontaneous depolarization, which is the basis of automaticity. This would be the correct answer if the cell were an atrial or ventricular myocyte."
      },
      {
        "text": "Five distinct phases with a prominent phase 1 notch",
        "explanation": "Incorrect. Five phases including a phase 1 notch describe the fast-response action potential; the nodal action potential has three phases. This would be the correct answer if the recording came from epicardial ventricular tissue."
      }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Nodal (slow-response) action potentials: 3 phases, maximum diastolic potential ~ -60 mV, peak ~0 mV, no plateau, and spontaneously depolarizing phase 4.",
    "pdfPage": 29,
    "pdfQuote": "slow response action potential has lesser negative member potential, around -60 millivolts"
  },
  {
    "id": 30,
    "category": "Cardiac Electrophysiology: Integrated Ionic Reasoning",
    "questionText": "A 70-year-old man taking a diuretic presents with palpitations. His serum potassium is 2.6 mEq/L. Telemetry shows frequent premature ventricular beats and an episode of polymorphic ventricular tachycardia. Which sequence of cellular events best links his electrolyte abnormality to this arrhythmia?",
    "options": [
      {
        "text": "Increased potassium conductance markedly shortens repolarization, creating a short QT and reentry",
        "explanation": "Incorrect. This describes hyperkalemia, in which more potassium channels open and repolarization accelerates. This patient has hypokalemia, in which the opposite occurs. This would be the correct answer if his serum potassium were markedly elevated with peaked T waves on telemetry."
      },
      {
        "text": "Sodium channel inactivation from a depolarized resting potential slows phase 0 and widens the QRS",
        "explanation": "Incorrect. This mechanism describes hyperkalemia, where the resting potential rises toward threshold. In hypokalemia the resting potential becomes more negative, and the characteristic electrocardiographic change is QT prolongation rather than QRS widening. This would be the correct answer if the patient were hyperkalemic with a wide-complex rhythm."
      },
      {
        "text": "Reverse-mode sodium-calcium exchange progressively raises intracellular calcium and augments contractile force generation",
        "explanation": "Incorrect. Exchanger reversal characterizes digitalis effect and produces inotropic changes; it is not the mechanism by which hypokalemia produces polymorphic ventricular tachycardia. This would be the correct answer if the patient had digoxin toxicity."
      },
      {
        "text": "Loss of funny current in ventricular myocytes abolishes automaticity and causes escape rhythms",
        "explanation": "Incorrect. Working ventricular myocytes do not depend on funny current, and the arrhythmia described is a tachyarrhythmia rather than an escape rhythm. This would be the correct answer if the presentation were profound bradycardia from sinus node dysfunction."
      },
      {
        "text": "Reduced potassium conductance prolongs repolarization and action potential duration, lengthening the QT and predisposing to ventricular tachyarrhythmia",
        "explanation": "Correct. Low extracellular potassium reduces the number of open potassium channels, decreasing conductance. Because repolarization depends on outward potassium current, phases 2 and 3 are slowed and action potential duration lengthens, manifesting on the surface tracing as a prolonged QT interval with flattened T waves. Prolonged and heterogeneous repolarization creates the substrate for triggered activity and reentry, producing polymorphic ventricular tachycardia. This is why potassium is monitored closely in patients on diuretics."
      }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Hypokalemia reduces potassium conductance, prolonging repolarization and QT — the substrate for polymorphic ventricular tachycardia in patients on diuretics.",
    "pdfPage": 26,
    "pdfQuote": "Delays repolarization (increases AP duration, prolonged Q-T interval, increased risk of ventricular arrhythmia)"
  }
];

window.Test_CV22 = Test_CV22;
