window.Test_L169 = [
  {
    "id": 1,
    "category": "Microbiology: Opportunistic Infection Definition",
    "questionText": "Which best defines an opportunistic infection?",
    "options": [
      { "text": "Any infection occurring in any patient regardless of immune status.", "explanation": "Incorrect. By definition, opportunistic infections are limited to immunocompromised hosts. This would be the correct answer in a misframed definition." },
      { "text": "Infections caused only by exotic, imported pathogens.", "explanation": "Incorrect. Opportunistic infections are caused by routine commensals or environmental organisms in immunocompromised hosts, not exotic pathogens. This would be the correct answer if asking about tropical disease in returning travelers." },
      { "text": "An infection that does not typically occur in a person with an intact immune system", "explanation": "Correct. The lecturer specified that an opportunistic infection is one that does not typically occur in a person with an intact immune system. They are caused by various mechanisms: commensal organisms (e.g., Staph epidermidis in central venous catheter infections, C. difficile after antibiotic-induced microbiome disruption), pharmaceutical-related (Lactobacillus septicemia in stem cell transplant recipients who took probiotics), tap water organisms (Mycobacterium avium, Pseudomonas, Legionella in advanced AIDS or structural lung disease), and reactivation of latent infections (HSV, VZV, CMV, EBV, Toxoplasma, M. tuberculosis). Examples of immune deficient hosts include those with breached natural barriers (severe burns, surgical wounds), advanced HIV/AIDS, myelosuppressive chemotherapy recipients, immune-suppressed transplant recipients, and patients on chronic corticosteroids (≥20 mg/day prednisone equivalent for ≥4 weeks)." },
      { "text": "Sexually transmitted infections only.", "explanation": "Incorrect. Opportunistic infections are NOT limited to STIs. This would be the correct answer if asking about gonorrhea or chlamydia." },
      { "text": "Infections always requiring hospital admission.", "explanation": "Incorrect. Hospitalization is not part of the definition. This would be the correct answer in a misframed criterion." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Opportunistic infection = does not occur in immunocompetent host; from commensals (Staph epi via CVC), microbiome disruption (C. diff), tap water (MAC/Pseudo), or reactivation (HSV, VZV, CMV, Toxo, TB). Includes burns, transplant, AIDS, chemo, chronic steroids.",
    "pdfPage": 7,
    "pdfQuote": "infection that does not typically occur"
  },
  {
    "id": 2,
    "category": "Microbiology: PCP Transmission",
    "questionText": "How is Pneumocystis jirovecii transmitted?",
    "options": [
      { "text": "Mosquito bite from Aedes mosquito.", "explanation": "Incorrect. PCP is not mosquito-transmitted. This would be the correct answer if asking about flavivirus transmission." },
      { "text": "Person-to-person via inhalation of airborne particles", "explanation": "Correct. The lecturer specified that Pneumocystis jirovecii is transmitted person-to-person via inhalation of airborne particles. While it produces widespread asymptomatic colonization in mammals (and is detectable in many healthy individuals' lungs), it is NOT a commensal — clinical disease develops only in those with cell-mediated immune deficiency. The most common immune-deficient hosts who develop PCP are: (1) HIV/AIDS patients with CD4 <200 — PCP is the most common opportunistic infection presenting in untreated/poorly-treated HIV patients; (2) patients on prolonged systemic corticosteroids (typically ≥20 mg prednisone-equivalent daily for ≥4 weeks); (3) post-stem cell transplant patients (3-week to 3-month period); (4) solid organ transplant recipients on cellular immunosuppression. PCP prophylaxis with TMP/SMX is given when these risk thresholds are met." },
      { "text": "Fecal-oral via contaminated water.", "explanation": "Incorrect. PCP is not fecal-oral transmitted. This would be the correct answer if asking about hepatitis A or norovirus." },
      { "text": "Sexual transmission.", "explanation": "Incorrect. PCP is not sexually transmitted. This would be the correct answer if asking about HIV, syphilis, or gonorrhea." },
      { "text": "Tick bite.", "explanation": "Incorrect. PCP is not tick-transmitted. This would be the correct answer if asking about Lyme disease or babesiosis." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Pneumocystis jirovecii = fungal, transmitted person-to-person via inhalation; widespread asymptomatic colonization in mammals; clinical PCP disease in cell-mediated immune deficiency (AIDS CD4 <200, prolonged steroids, transplant recipients).",
    "pdfPage": 28,
    "pdfQuote": "inhalation person-to-person"
  },
  {
    "id": 3,
    "category": "Microbiology: PCP Imaging",
    "questionText": "Which is the classic chest imaging finding in Pneumocystis jirovecii pneumonia?",
    "options": [
      { "text": "Dense lobar consolidation with prominent air bronchograms confined to a single lobe, often with parapneumonic effusion and a 'silhouette sign' obscuring the cardiac or diaphragmatic border on plain radiographs.", "explanation": "Incorrect. Lobar consolidation is more typical of bacterial pneumonia (e.g., Streptococcus pneumoniae). PCP shows diffuse interstitial pattern, not lobar consolidation. This would be the correct answer if asking about typical bacterial pneumonia." },
      { "text": "Apical/posterior upper lobe cavitary lesions with surrounding fibronodular infiltrates and tree-in-bud micronodules; often accompanied by hilar/mediastinal lymphadenopathy and a positive interferon-gamma release assay (IGRA).", "explanation": "Incorrect. Cavitary upper lobe lesions are typical of reactivation tuberculosis or aspergillus, not PCP. This would be the correct answer if asking about tuberculosis." },
      { "text": "Large unilateral pleural effusion with passive atelectasis of the underlying lung, blunting of the costophrenic angle, and meniscus sign on upright PA chest radiograph — often requiring thoracentesis for both diagnosis and symptomatic relief.", "explanation": "Incorrect. PCP very rarely causes pleural effusions; this is one of the distinguishing features. This would be the correct answer if asking about complicated bacterial pneumonia." },
      { "text": "Bilateral interstitial 'ground-glass' opacities, typically without pleural effusion (effusions are very rare in PCP); the chest exam is often QUIET despite the severity of the radiographic findings — disproportionately mild exam findings vs severe imaging is a classic PCP clue.", "explanation": "Correct. The lecturer specified that the classic chest imaging finding in PCP is bilateral interstitial ground-glass opacities, typically without pleural effusion. Effusions are very rare in PCP and their presence should make you think of an alternative diagnosis. The pulmonary exam is often QUIET despite the severity of imaging findings — this disproportion (mild exam, severe CXR/CT) is a classic clue. Other PCP findings: subacute pulmonary symptoms (non-productive cough → fever → progressively worsening dyspnea over weeks), markedly elevated LDH (often >500), positive serum β-D-glucan (although can be negative in some confirmed cases), and bilateral ground-glass on CXR/CT. PCP is one of those 'atypical pneumonias' but causes very severe disease in immunocompromised hosts." },
      { "text": "Solitary well-circumscribed round pulmonary nodule with central laminated 'target' calcification, typically <3 cm and clinically stable over years — a benign healed granuloma classically found in patients from the Ohio/Mississippi River valleys.", "explanation": "Incorrect. This describes histoplasmosis or other granulomatous diseases, not PCP. This would be the correct answer if asking about a histoplasmoma." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: PCP CXR/CT = bilateral interstitial ground-glass opacities, typically WITHOUT effusion. Quiet exam despite severe imaging = classic clue. Effusion suggests alternative diagnosis. Elevated LDH + positive β-D-glucan support diagnosis.",
    "pdfPage": 28,
    "pdfQuote": "bilateral interstitial ground glass opacities"
  },
  {
    "id": 4,
    "category": "Microbiology: PCP Diagnosis",
    "questionText": "What is the gold-standard histopathologic finding for Pneumocystis jirovecii pneumonia?",
    "options": [
      { "text": "Methenamine silver staining of bronchoalveolar lavage or tissue showing the classic Pneumocystis cysts ('crushed ping-pong ball' appearance); pathology shows characteristic FOAMY MACROPHAGES; alternative diagnostic methods include PCR or antigen testing of saliva/BAL fluid, β-D-glucan in blood, and elevated LDH (supportive but not specific).", "explanation": "Correct. The lecturer specified that the classic histopathologic finding for PCP is methenamine silver staining of bronchoalveolar lavage (BAL) fluid or lung tissue showing the characteristic Pneumocystis cysts. The pathology shows FOAMY MACROPHAGES — a buzzword and pathognomonic finding. Alternative diagnostic methods: (1) PCR or antigen testing of saliva/BAL — increasingly common; (2) β-D-glucan blood test (a fungal cell wall component) — usually positive in PCP but can be negative in some confirmed cases (as in 'Bobby's case' from the lecture); (3) elevated serum LDH — supportive but not specific. Bronchoscopy with BAL is the typical diagnostic procedure when the diagnosis is uncertain. Treatment is high-dose TMP/SMX (Bactrim); in severe cases (PaO2 <70, A-a gradient ≥35), prednisone is added because the dying organisms release antigens that produce a hypersensitivity-like inflammatory response that can worsen oxygenation." },
      { "text": "Gram stain of CSF or urethral exudate demonstrating intracellular gram-negative diplococci within polymorphonuclear leukocytes ('kidney bean'-shaped pairs); confirmed by chocolate agar growth and oxidase positivity; classically associated with Neisseria meningitidis meningitis or Neisseria gonorrhoeae urethritis.", "explanation": "Incorrect. Pneumocystis is a fungus and does not show on Gram stain. This would be the correct answer if asking about Neisseria meningitidis or gonorrhea." },
      { "text": "Ziehl-Neelsen acid-fast staining of sputum showing slender beaded red rods that retain carbol fuchsin against the methylene blue counterstain due to a mycolic acid-rich cell wall; supportive findings include caseating granulomas and a positive interferon-gamma release assay for Mycobacterium tuberculosis.", "explanation": "Incorrect. Pneumocystis is not acid-fast; that staining is for mycobacteria. This would be the correct answer if asking about TB diagnosis." },
      { "text": "Tzanck smear of scraped vesicle base showing multinucleated giant cells with molded nuclei and intranuclear eosinophilic Cowdry type A inclusion bodies — the classic cytopathic effect of alpha-herpesviruses (HSV-1, HSV-2, VZV); cannot distinguish between these viruses, so PCR is the modern gold standard.", "explanation": "Incorrect. The Tzanck smear is for HSV/VZV, not Pneumocystis. This would be the correct answer if asking about HSV diagnosis." },
      { "text": "Periodic acid-Schiff (PAS) or KOH wet mount showing budding yeast forming pseudohyphae and true germ tubes after 2-hour serum incubation at 37°C — a rapid identification method specific for Candida albicans; supportive findings include growth on Sabouraud dextrose agar and a positive serum beta-D-glucan.", "explanation": "Incorrect. PAS with germ tubes is characteristic of Candida, not Pneumocystis. This would be the correct answer if asking about Candida diagnosis." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: PCP = methenamine silver stain on BAL/tissue showing Pneumocystis cysts ('crushed ping-pong balls') + foamy macrophages on pathology (buzzword). Adjunct: PCR/antigen, β-D-glucan, elevated LDH. Treatment: high-dose TMP/SMX ± prednisone if severe (PaO2 <70).",
    "pdfPage": 28,
    "pdfQuote": "Methenamine silver stain"
  },
  {
    "id": 5,
    "category": "Microbiology: PCP Treatment",
    "questionText": "What is the first-line treatment for Pneumocystis jirovecii pneumonia in a patient with severe disease (PaO2 <70 mmHg)?",
    "options": [
      { "text": "Vancomycin + meropenem + cefepime broad-spectrum antibiotics.", "explanation": "Incorrect. PCP is a fungal infection; broad-spectrum antibacterial coverage is not the targeted treatment. This would be the correct answer for empiric coverage of complicated bacterial pneumonia." },
      { "text": "Fluconazole monotherapy.", "explanation": "Incorrect. Fluconazole is for Candida and Cryptococcus, not Pneumocystis. This would be the correct answer for esophageal candidiasis or oral thrush." },
      { "text": "Pentamidine inhaled monotherapy.", "explanation": "Incorrect. Inhaled pentamidine is occasionally used for prophylaxis in severely sulfa-allergic patients but is less effective than IV pentamidine for active disease, and TMP/SMX remains first-line. This would be the correct answer if asking about an alternative for severe sulfa allergy." },
      { "text": "Acyclovir.", "explanation": "Incorrect. Acyclovir is for HSV/VZV, not Pneumocystis. This would be the correct answer if asking about herpes zoster or chickenpox." },
      { "text": "High-dose TMP/SMX (Bactrim) plus prednisone.", "explanation": "Correct. The lecturer specified that the first-line treatment for PCP is high-dose TMP/SMX (Bactrim), with the addition of PREDNISONE for severe disease (PaO2 <70 mmHg or A-a gradient ≥35). Alternatives for sulfa-allergic patients include IV pentamidine (severe disease, difficult drug to give due to side effects) or atovaquone/dapsone (mild-moderate outpatient disease); treatment course is typically 21 days. The mechanism of steroid benefit: when TMP/SMX kills Pneumocystis organisms, the dying organisms release antigens that provoke a hypersensitivity-like inflammatory response in the lungs, which can transiently worsen oxygenation; pre-treatment with steroids dampens this response and improves outcomes. Treatment course is typically 21 days. For sulfa-allergic patients: IV pentamidine for severe disease (a difficult drug to give due to nephrotoxicity, hypotension, hyperglycemia, and pancreatitis); atovaquone or dapsone for mild-moderate outpatient disease (requires G6PD testing for dapsone). Prophylaxis at CD4 <200 is TMP/SMX (or alternatives for allergic patients) and is discontinued when CD4 sustained >200 for 6+ months on ART." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: PCP first-line = high-dose TMP/SMX + prednisone if severe (PaO2 <70 or A-a gradient ≥35). Alternatives: IV pentamidine (severe sulfa allergy, hard to give), atovaquone/dapsone (mild-mod outpatient). 21-day course. Prophylaxis at CD4 <200.",
    "pdfPage": 28,
    "pdfQuote": "TMP/SMZ, prednisone"
  },
  {
    "id": 6,
    "category": "Microbiology: CMV CD4 Threshold",
    "questionText": "At what CD4 cell count does CMV reactivation disease (especially CMV retinitis) typically occur in untreated HIV/AIDS patients?",
    "options": [
      { "text": "CD4 <500 cells/uL.", "explanation": "Incorrect. CD4 <500 is associated with thrush, EBV oral hairy leukoplakia, Bartonella, HHV-8, and HPV, but not CMV. This would be the correct answer if asking about thrush risk." },
      { "text": "CD4 <350 cells/uL.", "explanation": "Incorrect. <350 is associated with TB and lymphoma risk, not CMV. This would be the correct answer if asking about TB or lymphoma risk." },
      { "text": "CD4 <50 cells/uL", "explanation": "Correct. The lecturer specified the CD4-stratified opportunistic infections in HIV/AIDS: <500 (thrush, EBV oral hairy leukoplakia, Bartonella, HHV-8, HPV); <200 (PCP, histoplasma, PML); <100 (cerebral toxoplasmosis, aspergillus, cryptosporidium, EBV B-cell lymphoma); <50 (CMV retinitis, cryptococcal meningitis, esophageal candidiasis, MAC). CMV reactivation disease typically occurs at CD4 <50. Classic CMV findings: retinitis with cotton wool spots, flame hemorrhages, visual loss, floaters, and flashing lights — emergent and can lead to blindness; pneumonitis (similar bilateral ground-glass to PCP); ulcerative esophagitis with classic LONG, DEEP, LINEAR ulcers (vs. shallow crops in HSV); colitis with diarrhea; disseminated disease. Diagnosis: clinical retinal exam, blood/tissue PCR, tissue biopsy showing classic owl's eye inclusion bodies. Treatment: IV ganciclovir or oral valganciclovir; intravitreal ganciclovir injections for severe retinitis." },
      { "text": "CD4 <200 cells/uL.", "explanation": "Incorrect. <200 is for PCP, histoplasma, and PML risk. This would be the correct answer if asking about PCP risk." },
      { "text": "CD4 <100 cells/uL.", "explanation": "Incorrect. <100 is for cerebral toxoplasmosis, aspergillus, cryptosporidium, and EBV B-cell lymphoma. This would be the correct answer if asking about cerebral toxoplasmosis risk." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: CMV reactivation in AIDS at CD4 <50 (also cryptococcal meningitis, esophageal candidiasis, MAC). CMV: retinitis (cotton wool + flame hemorrhages + visual loss), long deep linear esophageal ulcers, owl's eye inclusion bodies. Treat with ganciclovir/valganciclovir.",
    "pdfPage": 23,
    "pdfQuote": "<50"
  },
  {
    "id": 7,
    "category": "Microbiology: CMV Retinitis Findings",
    "questionText": "Which retinal exam findings are most characteristic of CMV retinitis?",
    "options": [
      { "text": "Pale peripheral lesions with central necrosis.", "explanation": "Incorrect. This describes HSV retinitis or acute retinal necrosis (VZV), not CMV. This would be the correct answer if asking about HSV or VZV retinitis." },
      { "text": "Cotton wool spots and flame hemorrhages", "explanation": "Correct. The lecturer specified that CMV retinitis classically shows cotton wool spots and flame hemorrhages on funduscopic exam — sometimes called the 'pizza pie' or 'crumbled cheese with ketchup' appearance. The cotton wool spots represent infarcted nerve fiber layer (yellow-white fluffy patches), and the flame hemorrhages represent superficial hemorrhages along nerve fibers. The typical clinical presentation: floaters, flashing lights, decreased visual acuity, and progressive painless visual loss. CMV retinitis is an emergency in AIDS patients (CD4 <50) and requires immediate treatment with IV ganciclovir, often supplemented with intravitreal ganciclovir injections (especially for sight-threatening lesions). Without treatment, progression to blindness is the rule. Maintenance therapy with valganciclovir is needed until CD4 sustains >100 on ART. Differential diagnosis includes HSV retinitis (pale peripheral lesions with central necrosis) and VZV acute retinal necrosis (rapidly progressive diffuse retinal necrosis with hemorrhages)." },
      { "text": "Roth spots with central white area.", "explanation": "Incorrect. Roth spots are seen in infective endocarditis, not CMV. This would be the correct answer if asking about endocarditis ophthalmologic findings." },
      { "text": "Salt-and-pepper retinopathy.", "explanation": "Incorrect. Salt-and-pepper retinopathy is seen in congenital rubella syndrome, not CMV. This would be the correct answer if asking about TORCH infections." },
      { "text": "Bull's eye maculopathy with concentric rings.", "explanation": "Incorrect. Bull's eye maculopathy is seen in hydroxychloroquine toxicity and certain inherited retinal dystrophies. This would be the correct answer if asking about hydroxychloroquine retinopathy." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: CMV retinitis = cotton wool spots + flame hemorrhages ('pizza pie'/'crumbled cheese with ketchup'); floaters/flashing lights/painless visual loss; CD4 <50 in AIDS. Emergency = IV ganciclovir + intravitreal injections. Maintenance valganciclovir.",
    "pdfPage": 30,
    "pdfQuote": "cotton wool spots"
  },
  {
    "id": 8,
    "category": "Microbiology: CMV Esophagitis",
    "questionText": "On esophagogastroduodenoscopy (EGD), what is the characteristic appearance of CMV esophagitis?",
    "options": [
      { "text": "Cottage cheese-like white plaques covering the mucosa.", "explanation": "Incorrect. White plaques describe Candida esophagitis, not CMV. This would be the correct answer if asking about Candida esophagitis." },
      { "text": "Crops of small, shallow, well-demarcated ulcers.", "explanation": "Incorrect. Crops of shallow ulcers describe HSV esophagitis, not CMV. This would be the correct answer if asking about HSV esophagitis." },
      { "text": "Severe stricture with fixed narrowing.", "explanation": "Incorrect. Esophageal strictures are typically due to chronic GERD, eosinophilic esophagitis, or radiation, not CMV. This would be the correct answer if asking about GERD complications." },
      { "text": "Long, deep, LINEAR ulcers", "explanation": "Correct. The lecturer specifically described CMV esophagitis as showing long, deep, LINEAR ulcers on EGD — large, well-defined ulcers extending along the long axis of the esophagus, typically in the mid-distal esophagus. This is the characteristic CMV finding distinguishing it from HSV esophagitis (crops of small, shallow ulcers) and Candida esophagitis (cottage cheese-like white plaques). Diagnosis is confirmed by biopsy showing the classic 'owl's eye' intranuclear inclusion bodies (large basophilic intranuclear inclusions surrounded by clear halos). Treatment: IV ganciclovir for induction, then oral valganciclovir for maintenance (often indefinite in advanced AIDS until CD4 recovers on ART). Patients present with odynophagia (painful swallowing), often without prominent dysphagia, and may have weight loss. CMV esophagitis typically occurs at CD4 <50." },
      { "text": "Bull's-eye polyp with central depression.", "explanation": "Incorrect. Bull's-eye polyp is a metastatic appearance, not CMV esophagitis. This would be the correct answer if asking about metastatic disease patterns." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Esophageal ulcers in AIDS — Candida (cottage cheese plaques, fluconazole), HSV (crops of shallow, Tzanck multinucleated giant cells, acyclovir), CMV (long deep LINEAR, owl's eye inclusions, ganciclovir/valganciclovir).",
    "pdfPage": 30,
    "pdfQuote": "Long, deep, linear ulcers"
  },
  {
    "id": 9,
    "category": "Microbiology: CMV Histopathology",
    "questionText": "What is the pathognomonic histopathologic finding on biopsy of tissue infected with CMV?",
    "options": [
      { "text": "Acid-fast bacilli on Ziehl-Neelsen stain.", "explanation": "Incorrect. Acid-fast bacilli indicate mycobacterial infection (TB or NTM), not CMV. This would be the correct answer if asking about TB histology." },
      { "text": "Granulomas with central caseating necrosis.", "explanation": "Incorrect. Caseating granulomas are typical of TB; CMV produces a different histologic pattern. This would be the correct answer if asking about TB histology." },
      { "text": "Tzanck-positive multinucleated giant cells.", "explanation": "Incorrect. Tzanck-positive multinucleated giant cells are seen in HSV/VZV infections, not CMV. This would be the correct answer if asking about HSV histology." },
      { "text": "Foamy macrophages without specific viral inclusions.", "explanation": "Incorrect. Foamy macrophages are seen in Pneumocystis pneumonia, not CMV. This would be the correct answer if asking about PCP histology." },
      { "text": "'Owl's eye' intranuclear inclusion bodies", "explanation": "Correct. The lecturer specified that CMV's pathognomonic histopathologic finding is the 'owl's eye' intranuclear inclusion body — a large basophilic intranuclear inclusion surrounded by a clear halo. The infected cells show cytomegaly (enlarged cells; the prefix 'cyto-mega-' literally means 'cell-large'), with both intranuclear and intracytoplasmic inclusions. The intranuclear inclusion is the larger, more prominent one with the classic 'owl's eye' appearance. CMV can be detected histologically in any infected tissue: lung (pneumonitis), GI tract (esophagitis, colitis), retina (CMV retinitis can be diagnosed clinically without biopsy), kidney/transplanted organs, etc. Diagnosis is also supported by positive blood or tissue PCR and culture, and by clinical features (especially in AIDS patients with CD4 <50 or transplant recipients)." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: CMV histology = 'owl's eye' intranuclear inclusion bodies (basophilic with clear halo) + cytomegaly + intracytoplasmic inclusions. Pathognomonic. PCR and culture support.",
    "pdfPage": 30,
    "pdfQuote": "Owl's eye inclusion bodies"
  },
  {
    "id": 10,
    "category": "Microbiology: HSV Esophagitis",
    "questionText": "On EGD, what is the characteristic appearance of HSV esophagitis?",
    "options": [
      { "text": "Crops of small, shallow, well-demarcated round/punched-out ulcers in the mid-esophagus — very different from CMV's long deep linear ulcers; biopsy or Tzanck smear shows multinucleated giant cells with intranuclear inclusions; treatment with IV acyclovir for severe disease, oral acyclovir/valacyclovir/famciclovir for mild-moderate; foscarnet for resistant cases.", "explanation": "Correct. The lecturer specified that HSV esophagitis presents on EGD as crops of small, shallow, well-demarcated, often round or 'punched-out' ulcers in the mid-esophagus. This is very different from CMV (long, deep, linear ulcers) and Candida (cottage cheese-like white plaques). Diagnosis: biopsy of ulcer base showing multinucleated giant cells with intranuclear inclusions (HSV cytopathic effect) on H&E or by Tzanck smear (a cytology technique that can also be done on skin lesions); confirmation by PCR. Treatment: IV acyclovir for severe disease; oral acyclovir, valacyclovir (better bioavailability), or famciclovir for mild-moderate disease. Foscarnet is used for acyclovir-resistant strains. HSV esophagitis can occur at relatively higher CD4 counts than CMV (which requires CD4 <50)." },
      { "text": "Long, deep, well-demarcated LINEAR ulcers extending along the long axis of the mid-distal esophagus, with biopsy showing pathognomonic 'owl's eye' intranuclear inclusion bodies and cytomegaly; treatment is IV ganciclovir for induction followed by oral valganciclovir for maintenance; typically occurs in advanced AIDS at CD4 <50.", "explanation": "Incorrect. This describes CMV esophagitis, not HSV. This would be the correct answer if asking about CMV esophagitis." },
      { "text": "Diffuse, raised, adherent cottage cheese-like white plaques covering the esophageal mucosa with friable underlying tissue when scraped; KOH wet mount and Gram stain reveal budding yeast and pseudohyphae; treatment is oral fluconazole (IV if odynophagia prevents intake), with echinocandins reserved for fluconazole-resistant strains.", "explanation": "Incorrect. This describes Candida esophagitis. This would be the correct answer if asking about Candida esophagitis." },
      { "text": "Diffuse fibrotic luminal narrowing of the distal esophagus with fixed concentric stricture causing progressive solid-food dysphagia; barium swallow shows smooth tapered 'bird's beak'-like narrowing; classically a complication of long-standing chronic GERD with Barrett-associated peptic strictures, managed with endoscopic balloon dilation and PPI therapy.", "explanation": "Incorrect. Esophageal strictures are not typical of HSV. This would be the correct answer if asking about chronic GERD complications." },
      { "text": "Pseudopolypoid cobblestone appearance of the mucosa with intervening linear and serpiginous ulcerations, skip lesions, and transmural inflammation extending through the muscularis propria; biopsy may show non-caseating granulomas; classically described in Crohn disease with characteristic small bowel and ileocolonic involvement.", "explanation": "Incorrect. Cobblestone appearance is more typical of inflammatory bowel disease, not HSV esophagitis. This would be the correct answer if asking about Crohn disease findings." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: HSV esophagitis = crops of small, shallow, round/punched-out ulcers (vs. CMV long deep linear). Biopsy/Tzanck = multinucleated giant cells. Treatment: acyclovir/valacyclovir/famciclovir; IV for severe; foscarnet for resistance.",
    "pdfPage": 30,
    "pdfQuote": "shallow"
  },
  {
    "id": 11,
    "category": "Microbiology: HSV Tzanck Smear",
    "questionText": "Which histopathologic finding on a Tzanck smear is characteristic of HSV (and VZV) infection?",
    "options": [
      { "text": "Slender beaded acid-fast bacilli on Ziehl-Neelsen stain of sputum or tissue — retaining carbol fuchsin against a methylene blue counterstain due to a mycolic acid-rich cell wall; the classic finding in mycobacterial infections (Mycobacterium tuberculosis, MAC, and other non-tuberculous mycobacteria); culture on Lowenstein-Jensen medium and nucleic acid amplification testing are confirmatory.", "explanation": "Incorrect. Acid-fast bacilli are mycobacterial. This would be the correct answer if asking about TB or NTM diagnosis." },
      { "text": "Large basophilic 'owl's eye' intranuclear inclusion bodies surrounded by clear halos within markedly enlarged (cytomegalic) cells, also with smaller intracytoplasmic inclusions — the pathognomonic histologic finding of cytomegalovirus (CMV) infection, classically seen in CMV retinitis, esophagitis, colitis, or pneumonitis in AIDS patients with CD4 <50.", "explanation": "Incorrect. Owl's eye inclusions are characteristic of CMV, not HSV. This would be the correct answer if asking about CMV diagnosis." },
      { "text": "Multinucleated giant cells with intranuclear inclusions — characteristic of HSV-1, HSV-2, and VZV (all alpha-herpesviruses); the Tzanck smear is a cytology technique performed on scrapings from the base of a vesicle or ulcer; sensitivity and specificity are limited compared to PCR (which is now the gold standard); the test cannot distinguish between HSV and VZV.", "explanation": "Correct. The lecturer specified that Tzanck smear shows multinucleated giant cells with intranuclear inclusions — the characteristic cytopathic effect of alpha-herpesviruses (HSV-1, HSV-2, and VZV). The Tzanck smear is a cytology technique performed on scrapings from the base of an active vesicle or ulcer. Limitations: it cannot distinguish between HSV-1, HSV-2, and VZV; sensitivity and specificity are limited compared to PCR (which is now the gold standard for definitive identification); requires an active lesion. PCR has largely replaced Tzanck smears in modern practice for definitive diagnosis but the multinucleated giant cell finding remains a classic pathology buzzword. Treatment of HSV: acyclovir, valacyclovir (better bioavailability), or famciclovir; IV acyclovir for severe disease; foscarnet for acyclovir-resistant strains. Treatment of VZV (both herpes zoster and disseminated disease): same drugs at higher doses." },
      { "text": "Sheets of foamy alveolar macrophages within frothy intra-alveolar eosinophilic exudate on H&E, with methenamine silver stain highlighting clusters of disc-shaped 'crushed ping-pong ball' cysts in BAL or lung tissue — the characteristic histopathologic finding of Pneumocystis jirovecii pneumonia (PCP), supported by elevated serum LDH and a positive beta-D-glucan assay.", "explanation": "Incorrect. Foamy macrophages are characteristic of Pneumocystis pneumonia. This would be the correct answer if asking about PCP." },
      { "text": "Eosinophilic cytoplasmic Negri body inclusions within hippocampal pyramidal and cerebellar Purkinje neurons on H&E staining of brain biopsy — the pathognomonic finding of rabies virus encephalitis; antemortem diagnosis can also be made by direct fluorescent antibody (DFA) testing of nuchal skin biopsy or saliva PCR.", "explanation": "Incorrect. Negri bodies are characteristic of rabies virus. This would be the correct answer if asking about rabies." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Tzanck smear = multinucleated giant cells with intranuclear inclusions in HSV-1, HSV-2, VZV (alpha-herpes); cannot distinguish between them. PCR is gold standard for identification.",
    "pdfPage": 30,
    "pdfQuote": "multinucleotegiate cells"
  },
  {
    "id": 12,
    "category": "Microbiology: Candida Esophagitis",
    "questionText": "An AIDS patient with CD4 count 35 cells/uL presents with odynophagia and weight loss. EGD shows white, raised, cottage cheese-like plaques covering the esophageal mucosa. Which is the most appropriate first-line treatment?",
    "options": [
      { "text": "IV acyclovir for HSV esophagitis.", "explanation": "Incorrect. The white cottage-cheese plaques describe Candida, not HSV (which produces crops of shallow ulcers). This would be the correct answer for HSV esophagitis with characteristic shallow ulcers." },
      { "text": "Fluconazole — high-dose", "explanation": "Correct. The lecturer specified that the cottage cheese-like white plaques visible on EGD describe Candida esophagitis (most commonly Candida albicans). Treatment of choice is fluconazole, taken orally if the patient can tolerate, or IV if odynophagia prevents oral intake. Confirmation: Gram stain shows budding yeast and pseudohyphae; germ tube formation in culture is highly suggestive of C. albicans. Refractory cases or fluconazole-resistant Candida (more common in AIDS patients with prior fluconazole exposure or prophylaxis) may require echinocandins (caspofungin, micafungin) or amphotericin B. The patient also needs aggressive ART optimization — esophageal candidiasis is an AIDS-defining illness, and CD4 recovery on ART is the durable solution. Other Candida diseases in advanced AIDS: oral thrush (fluconazole 100-200 mg/day or topical agents), vaginal candidiasis (topical or fluconazole), and disseminated/invasive disease (echinocandins or amphotericin B)." },
      { "text": "IV ganciclovir for CMV esophagitis.", "explanation": "Incorrect. The cottage cheese plaques are characteristic of Candida; CMV produces long, deep, linear ulcers. This would be the correct answer if EGD showed long deep linear ulcers." },
      { "text": "TMP/SMX for Pneumocystis-related disease.", "explanation": "Incorrect. TMP/SMX is for PCP pneumonia, not Candida esophagitis. This would be the correct answer if asking about PCP treatment." },
      { "text": "Discontinue all antiretroviral therapy until esophagitis resolves.", "explanation": "Incorrect. ART continuation/optimization is essential for sustained immune recovery. This would be the correct answer in a fundamentally misframed protocol." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Candida esophagitis (AIDS, CD4 <50) = white cottage cheese plaques; treat with fluconazole; refractory → echinocandins or amphotericin B; optimize ART.",
    "pdfPage": 28,
    "pdfQuote": "cottage cheese"
  },
  {
    "id": 13,
    "category": "Microbiology: MAC Labs",
    "questionText": "A 45-year-old man with AIDS (CD4 28) presents with fever, weight loss of 30 lbs over 3 months, drenching night sweats, watery diarrhea, generalized lymphadenopathy, and elevated alkaline phosphatase 4× the upper limit of normal. His CBC shows anemia and thrombocytopenia. Which infection is most likely?",
    "options": [
      { "text": "Pneumocystis jirovecii pneumonia.", "explanation": "Incorrect. PCP is a respiratory infection, not the systemic fever + weight loss + alkaline phosphatase elevation pattern described. This would be the correct answer if the patient had hypoxia and bilateral ground-glass infiltrates." },
      { "text": "Cryptococcal meningitis.", "explanation": "Incorrect. Cryptococcal meningitis presents with headache, fever, photophobia, and increased intracranial pressure — not the systemic disseminated MAC picture. This would be the correct answer if the patient had headache and meningeal signs with positive India ink/cryptococcal antigen." },
      { "text": "Cytomegalovirus retinitis.", "explanation": "Incorrect. CMV retinitis presents with visual changes and characteristic retinal findings, not the systemic MAC picture. This would be the correct answer if asking about retinitis with cotton wool spots." },
      { "text": "Disseminated Mycobacterium avium complex (MAC)", "explanation": "Correct. The clinical picture is classic disseminated Mycobacterium avium complex (MAC) — caused by M. avium and M. intracellulare (rapidly growing non-tuberculous mycobacteria, ubiquitous waterborne organisms). MAC was very common in advanced AIDS in the pre-ART era (CD4 <50) but is now rare because effective ART prevents CD4 from dropping that low. The lecturer specified the classic MAC presentation: fever, weight loss, drenching night sweats, diarrhea, generalized lymphadenopathy, ELEVATED ALKALINE PHOSPHATASE (4× upper limit is highly suggestive — reflecting hepatic and bone involvement), and cytopenias (especially anemia). Diagnosis: mycobacterial blood culture (special handling required, slow growth), bone marrow biopsy, PCR, or modified acid-fast (Ziehl-Neelsen) stain showing the characteristic organisms in tissue. Treatment: clarithromycin OR azithromycin combined with ethambutol; macrolide resistance is increasing, so testing is critical, and additional drugs (e.g., rifabutin) may be added. MAC prophylaxis at CD4 <100 was historically common but is no longer routinely given because the entity has become so rare. The lecturer also noted Lady Windermere syndrome — pulmonary MAC in elderly thin women without typical risk factors, now linked to a genetic susceptibility." },
      { "text": "Toxoplasma gondii cerebral disease.", "explanation": "Incorrect. Cerebral toxoplasmosis presents with focal neurologic deficits and ring-enhancing brain lesions, not the systemic MAC picture. This would be the correct answer if asking about cerebral toxoplasmosis." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Disseminated MAC (CD4 <50, less common in modern era) = fever + weight loss + drenching night sweats + diarrhea + lymphadenopathy + ELEVATED alkaline phosphatase + cytopenias. Mycobacterial blood culture or bone marrow biopsy. Clarithromycin/azithromycin + ethambutol. Lady Windermere = pulmonary MAC in thin elderly women.",
    "pdfPage": 23,
    "pdfQuote": "alkaline phosphatase"
  },
  {
    "id": 14,
    "category": "Microbiology: MAC Treatment",
    "questionText": "What is the standard treatment regimen for disseminated Mycobacterium avium complex (MAC) infection?",
    "options": [
      { "text": "Vancomycin + ceftriaxone for 6 weeks.", "explanation": "Incorrect. Vancomycin and ceftriaxone are for bacterial infections, not mycobacterial. This would be the correct answer for severe bacterial sepsis." },
      { "text": "Isoniazid + rifampin + pyrazinamide + ethambutol (RIPE) for 2 months, then INH + rifampin for 4 more months.", "explanation": "Incorrect. RIPE is the regimen for Mycobacterium tuberculosis, not MAC. MAC is a non-tuberculous mycobacterium with different drug susceptibilities. This would be the correct answer if asking about TB treatment." },
      { "text": "Acyclovir + valacyclovir for HSV.", "explanation": "Incorrect. These are for HSV/VZV infections, not mycobacterial. This would be the correct answer if asking about genital herpes treatment." },
      { "text": "TMP/SMX for PCP.", "explanation": "Incorrect. TMP/SMX is for Pneumocystis, not MAC. This would be the correct answer if asking about PCP treatment." },
      { "text": "Clarithromycin OR azithromycin PLUS ethambutol", "explanation": "Correct. The lecturer specified that disseminated MAC treatment is a macrolide (clarithromycin OR azithromycin) PLUS ethambutol. Macrolide alone is insufficient because resistance develops rapidly; ethambutol alone is also inadequate (monotherapy fails). The combination provides synergy and reduces resistance development. Duration is at least 12 months and continues until CD4 is sustained >100 for 6 months on ART (chronic suppression). Macrolide resistance testing is critical because clarithromycin/azithromycin resistance is increasingly common, especially in patients with prior macrolide exposure (e.g., azithromycin prophylaxis at CD4 <100, which is no longer routinely given). When resistance is present or in severe disease, additional drugs are added: rifabutin (preferred over rifampin due to better profile in HIV patients), fluoroquinolones, amikacin (parenteral), or linezolid. ART optimization is essential — without immune recovery, MAC treatment is essentially lifelong." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: Disseminated MAC = macrolide (clarithro/azithro) + ethambutol. Test for macrolide resistance. Severe/resistant: add rifabutin/fluoroquinolone/amikacin/linezolid. Continue ≥12 months and until CD4 >100 sustained 6 months on ART.",
    "pdfPage": 33,
    "pdfQuote": "clarithromycin or azithromycin"
  },
  {
    "id": 15,
    "category": "Microbiology: Cryptococcus Reservoir",
    "questionText": "Cryptococcus neoformans, the most common cause of meningitis in advanced AIDS, has which environmental reservoir?",
    "options": [
      { "text": "Soil with avian (pigeon) droppings.", "explanation": "Correct. The lecturer specified that Cryptococcus neoformans (the most common species causing cryptococcal meningitis in AIDS) has its environmental reservoir in soil contaminated with avian droppings, especially pigeon droppings. Humans acquire infection through inhalation of yeast cells from soil dust; Cryptococcus gattii has a slightly different ecology, associated with arboreal environments and certain tree species (eucalyptus, Douglas fir); the antiphagocytic polysaccharide capsule is the key virulence factor. Humans acquire infection through inhalation of dried yeast cells from contaminated dust. Cryptococcus gattii has a slightly different ecology, associated with arboreal environments and specific tree species (eucalyptus, Douglas fir, oak); it has emerged in the Pacific Northwest of North America. The pathogenesis: inhaled yeasts initially infect the lungs (often asymptomatic in immunocompetent hosts) and somehow disseminate hematogenously to the CNS, where they cause meningitis. The antiphagocytic polysaccharide capsule is the key virulence factor — it prevents phagocytic uptake and immune clearance, allowing the organism to replicate freely in the immunocompromised host. The capsular polysaccharide accumulates in CSF and causes the increased opening pressure that is a characteristic finding in cryptococcal meningitis." },
      { "text": "Cattle and other livestock.", "explanation": "Incorrect. Cryptococcus is not livestock-associated. This would be the correct answer if asking about Brucella or Mycobacterium bovis." },
      { "text": "Brackish coastal water.", "explanation": "Incorrect. Cryptococcus is soil-associated, not water-associated. This would be the correct answer if asking about Vibrio infections." },
      { "text": "Tropical fruits.", "explanation": "Incorrect. Cryptococcus is not associated with tropical fruits. This would be the correct answer in a misframed reservoir." },
      { "text": "Decaying organic matter in compost.", "explanation": "Incorrect. While Cryptococcus is soil-associated, the specific association is with avian droppings, not generic compost. This would be the correct answer if asking about Aspergillus or other environmental fungi." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: Cryptococcus neoformans = soil contaminated with avian (pigeon) droppings; inhaled into lungs → CNS dissemination. C. gattii = arboreal (eucalyptus, Douglas fir). Antiphagocytic polysaccharide capsule = key virulence factor.",
    "pdfPage": 28,
    "pdfQuote": "avian droppings"
  },
  {
    "id": 16,
    "category": "Microbiology: PCP Vignette",
    "questionText": "A 38-year-old man with poorly controlled HIV (CD4 4) and advanced AIDS presents with 3 weeks of progressive non-productive cough, low-grade fever rising to 39.4°C, night sweats, and severe dyspnea now at rest. Vitals: HR 124, RR 28, BP 93/58, SpO2 78% on room air. Lung exam is surprisingly clear. CBC: pancytopenia. CXR: bilateral interstitial ground-glass opacities without effusions. He is intubated and ventilated. Which procedure is most appropriate to confirm the diagnosis?",
    "options": [
      { "text": "Empirically discharge home with oral azithromycin and outpatient ID follow-up.", "explanation": "Incorrect. The patient has severe respiratory failure requiring intubation; outpatient management is unsafe. This would be the correct answer in a stable outpatient." },
      { "text": "Surgical thoracotomy with open lung biopsy.", "explanation": "Incorrect. Surgical lung biopsy is invasive and risky; bronchoscopy with BAL is much less invasive and adequate for diagnosis. This would be the correct answer if BAL had been non-diagnostic and the patient had a focal lesion accessible to surgery." },
      { "text": "Bronchoscopy with bronchoalveolar lavage (BAL) and possibly transbronchial biopsy", "explanation": "Correct. The clinical picture (advanced AIDS, CD4 4, subacute respiratory illness, bilateral ground-glass opacities without effusion, profound hypoxia despite quiet exam) is the classic PCP presentation. Bronchoscopy with BAL is the appropriate diagnostic procedure: send the lavage fluid for methenamine silver staining (the gold standard for Pneumocystis cyst identification), PCR/antigen testing of BAL, bacterial/fungal/mycobacterial cultures, respiratory viral panel, and CMV PCR. β-D-glucan in serum is also useful (often elevated but can be negative as in 'Bobby's case'). Pathology should show foamy macrophages — a buzzword. While awaiting confirmation, empiric high-dose IV TMP/SMX is initiated with adjunctive prednisone (severe disease with PaO2 <70 mmHg or A-a gradient ≥35 benefits from steroids). Differential includes other AIDS pulmonary opportunistic infections (TB, MAC, CMV pneumonitis, Cryptococcus, histoplasmosis), so broad workup is needed alongside empiric treatment." },
      { "text": "Routine sputum culture without bronchoscopy.", "explanation": "Incorrect. Sputum culture is less sensitive than BAL for Pneumocystis, especially in critically ill patients who cannot expectorate effectively. This would be the correct answer in less severe disease where induced sputum could be obtained." },
      { "text": "CT angiogram of the pulmonary arteries to rule out PE.", "explanation": "Incorrect. While PE can be in the differential, the clinical and imaging picture strongly favors PCP, and CT angiogram does not establish the PCP diagnosis. This would be the correct answer if PE were the leading concern (e.g., unilateral leg swelling, normal CXR)." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Suspected PCP in AIDS = bronchoscopy with BAL → methenamine silver stain (gold standard) + PCR + β-D-glucan + LDH + foamy macrophages on pathology. Empiric IV TMP/SMX + prednisone (if PaO2 <70) while awaiting confirmation.",
    "pdfPage": 28,
    "pdfQuote": "bronchoscopy"
  },
  {
    "id": 17,
    "category": "Microbiology: CMV Retinitis Vignette",
    "questionText": "A 42-year-old woman with AIDS (CD4 30) presents with new floaters, flashing lights, and blurred vision in her right eye over the past 5 days. Ophthalmoscopy of the right eye shows yellow-white fluffy patches (cotton wool spots) with adjacent flame hemorrhages along the nerve fibers, often described as a 'pizza pie' appearance. Which is the most appropriate immediate management?",
    "options": [
      { "text": "Discharge home with topical artificial tears.", "explanation": "Incorrect. CMV retinitis is an emergency that progresses to blindness without treatment; topical lubrication is wholly inadequate. This would be the correct answer for dry eye syndrome." },
      { "text": "IV ganciclovir plus ophthalmology consult.", "explanation": "Correct. CMV retinitis is an ophthalmologic emergency in AIDS patients (CD4 <50) that requires immediate treatment to prevent blindness. Consider intravitreal ganciclovir injections for sight-threatening lesions; obtain blood and ocular fluid PCR for CMV; optimize ART; maintenance therapy with valganciclovir continues until CD4 sustained >100 on ART; monitor for adverse effects including bone marrow suppression. The lecturer specified treatment: IV ganciclovir for severe/sight-threatening disease (often combined with intravitreal injections directly into the affected eye for fastest response), or oral valganciclovir (good bioavailability, often used after IV induction for maintenance). Alternative agents for resistance or intolerance include cidofovir and foscarnet (but these are more difficult to use due to renal toxicity and electrolyte abnormalities). Maintenance therapy with valganciclovir continues until CD4 is sustained >100 for 6 months on ART. ART optimization is essential — sustained CD4 recovery is the durable solution. Monitor for ganciclovir adverse effects: bone marrow suppression (neutropenia, thrombocytopenia, anemia), nephrotoxicity, and renal monitoring. Ophthalmology consultation is essential for serial retinal exams, intravitreal therapy, and monitoring for retinal detachment (a known complication of CMV retinitis even after successful viral suppression)." },
      { "text": "Discontinue all ART and observe.", "explanation": "Incorrect. ART optimization (not discontinuation) is essential for sustained immune recovery. This would be the correct answer in a misframed protocol." },
      { "text": "Initiate empiric anti-toxoplasmosis therapy.", "explanation": "Incorrect. The retinal findings (cotton wool spots + flame hemorrhages) are characteristic of CMV, not toxoplasmosis. Cerebral toxoplasmosis presents with ring-enhancing brain lesions and focal neurologic deficits, not retinitis. This would be the correct answer if the patient had cerebral ring-enhancing lesions." },
      { "text": "Schedule routine ophthalmology follow-up in 3 months.", "explanation": "Incorrect. CMV retinitis is an emergency requiring immediate intervention; delay risks blindness. This would be the correct answer for a non-urgent ophthalmologic concern." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: CMV retinitis = AIDS CD4 <50 + cotton wool spots + flame hemorrhages ('pizza pie'); EMERGENCY (progressive blindness without treatment). IV ganciclovir or oral valganciclovir + intravitreal injections for sight-threatening lesions. Optimize ART. Continue maintenance until CD4 >100 sustained 6 months.",
    "pdfPage": 30,
    "pdfQuote": "Cytomegalovirus (CMV)"
  },
  {
    "id": 18,
    "category": "Microbiology: Esophagitis Differential",
    "questionText": "A 38-year-old man with advanced AIDS (CD4 22) presents with severe odynophagia. EGD findings would help distinguish among the three most common etiologies (Candida, HSV, CMV). Which finding is most specific for HSV esophagitis?",
    "options": [
      { "text": "Cottage cheese-like white plaques covering large areas of esophageal mucosa.", "explanation": "Incorrect. Cottage cheese plaques describe Candida esophagitis (most commonly C. albicans). This would be the correct answer if asking about Candida diagnosis." },
      { "text": "Long, deep, linear ulcers extending along the long axis of the esophagus.", "explanation": "Incorrect. Long, deep, linear ulcers describe CMV esophagitis. This would be the correct answer if asking about CMV diagnosis." },
      { "text": "Diffuse pseudopolypoid cobblestone appearance.", "explanation": "Incorrect. Cobblestone appearance is typical of inflammatory bowel disease, not infectious esophagitis. This would be the correct answer if asking about Crohn disease." },
      { "text": "Severe esophageal stricture with fixed narrowing.", "explanation": "Incorrect. Esophageal strictures are typically chronic GERD or radiation-related, not infectious. This would be the correct answer if asking about chronic GERD complications." },
      { "text": "Crops of small, shallow, well-demarcated round/punched-out ulcers", "explanation": "Correct. The lecturer specifically described the diagnostic distinctions among the three most common AIDS esophagitides: HSV — crops of small, shallow, well-demarcated round/punched-out ulcers; CMV — long, deep, LINEAR ulcers; Candida — white cottage cheese-like plaques. HSV's crops of shallow ulcers are confirmed by biopsy showing multinucleated giant cells with intranuclear inclusions on Tzanck smear or H&E (the alpha-herpesvirus cytopathic effect); PCR provides definitive confirmation. Treatment: IV acyclovir for severe disease; oral valacyclovir (better bioavailability), acyclovir, or famciclovir for mild-moderate disease; foscarnet for acyclovir-resistant strains. Distinguishing among the three by EGD appearance is the diagnostic key, and biopsy/PCR confirms. Note: co-infection is possible, so atypical presentations may need both anti-herpes and anti-Candida therapy until biopsy and PCR results return." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: AIDS esophagitis differentials by EGD — HSV: crops of small shallow ulcers + Tzanck multinucleated giant cells → acyclovir/valacyclovir; CMV: long deep linear ulcers + owl's eye inclusions → ganciclovir; Candida: cottage cheese plaques + germ tubes → fluconazole.",
    "pdfPage": 30,
    "pdfQuote": "shallow"
  },
  {
    "id": 19,
    "category": "Microbiology: Cryptococcal Meningitis Vignette",
    "questionText": "A 35-year-old man with AIDS (CD4 18) presents with 2 weeks of progressive headache, low-grade fever, photophobia, and now altered mental status. Lumbar puncture: opening pressure 28 cm H2O (high), glucose 12 mg/dL (low), protein 220 mg/dL (high), WBC 1,200 with 80% mononuclear cells. CSF India ink stain shows yeast cells with prominent capsules; cryptococcal antigen titer is 1:64. Which is the most appropriate immediate management?",
    "options": [
      { "text": "Initiate empiric ceftriaxone + vancomycin + ampicillin for bacterial meningitis.", "explanation": "Incorrect. The CSF profile and India ink + cryptococcal antigen confirm cryptococcal meningitis, not bacterial. Empiric bacterial coverage may be initiated initially while awaiting CSF results, but here the diagnosis is confirmed. This would be the correct answer if bacterial meningitis were the suspected etiology before CSF results returned." },
      { "text": "Initiate IV acyclovir for HSV encephalitis.", "explanation": "Incorrect. HSV encephalitis is a different entity (typically temporal lobe involvement on MRI, with PCR for HSV in CSF). The patient has cryptococcal meningitis. This would be the correct answer if MRI showed temporal lobe lesions and HSV PCR were positive." },
      { "text": "Initiate empiric broad-spectrum antibiotics + IV ribavirin.", "explanation": "Incorrect. Ribavirin is not used for cryptococcal meningitis. This would be the correct answer in a misframed antifungal regimen." },
      { "text": "Liposomal amphotericin B + flucytosine plus therapeutic LPs for ICP.", "explanation": "Correct. The clinical and laboratory picture is classic cryptococcal meningitis: AIDS patient with CD4 <50, subacute headache and fever, CSF pattern with low glucose and high protein, mononuclear pleocytosis, INCREASED OPENING PRESSURE (a key complication), positive India ink stain showing encapsulated yeasts, and positive cryptococcal antigen titer. Induction with liposomal amphotericin B + flucytosine for 2 weeks, followed by consolidation with high-dose oral fluconazole for 8 weeks, then chronic suppression with oral fluconazole until CD4 sustained >100 for 6 months on ART; THERAPEUTIC LUMBAR PUNCTURES to relieve increased intracranial pressure (the high opening pressure is a major source of morbidity and mortality); optimize ART; monitor for adverse effects of amphotericin (renal, electrolytes) and flucytosine (bone marrow suppression). The lecturer specified the standard treatment: induction with liposomal amphotericin B + flucytosine for 2 weeks (combination is more effective than amphotericin alone), followed by consolidation with high-dose oral fluconazole for 8 weeks, then chronic suppression with oral fluconazole until CD4 sustained >100 for 6 months on ART. CRITICAL adjunct: THERAPEUTIC LUMBAR PUNCTURES to relieve increased intracranial pressure — high opening pressure (>25 cm H2O) is a major source of morbidity and mortality, often leading to altered mental status, blindness, hearing loss, and death from herniation. Repeat lumbar punctures (or even ventriculostomy) may be needed daily until pressure normalizes. Optimize ART, but consider delay of ART start by 2-4 weeks to reduce risk of immune reconstitution inflammatory syndrome (IRIS). Monitor for adverse effects: amphotericin (renal toxicity, electrolyte abnormalities, fevers), flucytosine (bone marrow suppression, requires dose monitoring with serum levels)." },
      { "text": "Discharge home with oral fluconazole and outpatient follow-up.", "explanation": "Incorrect. Cryptococcal meningitis with altered mental status and high opening pressure requires inpatient ICU-level care with induction IV therapy. Outpatient management is unsafe. This would be the correct answer for very mild meningitis without altered mental status or severe ICP elevation." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Cryptococcal meningitis (AIDS, CD4 <50) = subacute HA + fever + low CSF glucose/high protein + mononuclear pleocytosis + INCREASED opening pressure + India ink/cryptococcal antigen. Treat: liposomal amphotericin B + flucytosine x 2 wk (induction) → high-dose fluconazole x 8 wk → chronic suppression. THERAPEUTIC LPs for ICP. Delay ART 2-4 wk to reduce IRIS.",
    "pdfPage": 28,
    "pdfQuote": "Cryptococcus"
  },
  {
    "id": 20,
    "category": "Microbiology: PML / Natalizumab",
    "questionText": "A 35-year-old woman with multiple sclerosis on natalizumab (an anti-α4-integrin monoclonal antibody) develops subacute progressive cognitive impairment, personality change, motor deficits, and seizures over 4 weeks. MRI shows multifocal areas of white matter hyperintensity without mass effect or contrast enhancement. CSF JC virus PCR is positive. Which is the most likely diagnosis?",
    "options": [
      { "text": "Progressive Multifocal Leukoencephalopathy (PML)", "explanation": "Correct. The clinical picture is classic Progressive Multifocal Leukoencephalopathy (PML): subacute cognitive decline, personality changes, focal motor deficits, seizures in an immunocompromised patient, with MRI showing multifocal WHITE MATTER demyelinating lesions WITHOUT mass effect or contrast enhancement, and positive CSF JC polyomavirus PCR. The lecturer specifically named natalizumab as a recognized cause of PML (it was temporarily withdrawn from market and re-introduced with risk mitigation). Other risk factors: advanced AIDS (CD4 <200; PML risk increases at CD4 <100), organ transplant recipients, certain monoclonal antibodies (rituximab, efalizumab — withdrawn). Pathophysiology: JC polyomavirus is widely prevalent (90% of adults are infected asymptomatically) but reactivates and produces oligodendrocyte demyelination only in profound cell-mediated immune deficiency. Treatment: remove immune-suppressing agent (stop natalizumab; in HIV, optimize ART; in transplant, reduce immunosuppression if feasible); plasmapheresis to clear natalizumab faster has been used. There is no specific antiviral therapy for JC virus. Outcomes vary — some patients improve substantially, others have persistent deficits. Differentiation from cerebral toxoplasmosis is critical: PML = WHITE MATTER, no contrast enhancement; toxoplasmosis = GRAY MATTER (especially basal ganglia), ring-enhancing lesions." },
      { "text": "Cerebral toxoplasmosis.", "explanation": "Incorrect. Cerebral toxoplasmosis produces ring-enhancing GRAY matter lesions (especially basal ganglia), not the multifocal white matter pattern. Also, JC virus PCR positivity confirms PML. This would be the correct answer if MRI showed ring-enhancing lesions and Toxoplasma serology were positive." },
      { "text": "Multiple sclerosis exacerbation.", "explanation": "Incorrect. While PML and MS can have similar MRI appearances, the JC virus positivity confirms PML. MS exacerbations typically show contrast-enhancing lesions, not non-enhancing demyelination. This would be the correct answer if JC virus PCR were negative and the imaging showed contrast-enhancing demyelination consistent with MS activity." },
      { "text": "Primary CNS lymphoma.", "explanation": "Incorrect. Primary CNS lymphoma typically shows contrast-enhancing GRAY matter or mass-like lesions on MRI; PML typically shows non-enhancing white matter demyelination. This would be the correct answer if MRI showed avidly contrast-enhancing mass-like lesions." },
      { "text": "HIV encephalopathy / AIDS dementia complex.", "explanation": "Incorrect. HIV encephalopathy produces global cognitive decline with diffuse atrophy, not focal demyelinating lesions. This would be the correct answer if MRI showed brain atrophy without focal demyelinating lesions and JC virus PCR were negative." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: PML = JC polyomavirus reactivation; immune-compromised host (advanced AIDS, natalizumab/rituximab, transplant); subacute cognitive/motor decline; MRI = multifocal WHITE MATTER demyelination, NO enhancement; CSF JC virus PCR. Treatment: remove immunosuppression, optimize ART. NO specific antiviral.",
    "pdfPage": 11,
    "pdfQuote": "natalizumab"
  },
  {
    "id": 21,
    "category": "Microbiology: Cerebral Toxoplasmosis",
    "questionText": "A 32-year-old man with AIDS (CD4 65) presents with 1 week of progressive right-sided weakness, headache, and a focal seizure. MRI brain shows multiple ring-enhancing lesions in the left basal ganglia and at gray-white junctions, with significant surrounding edema. Toxoplasma IgG serology is positive. Which is the most appropriate initial therapy?",
    "options": [
      { "text": "IV acyclovir for HSV encephalitis.", "explanation": "Incorrect. The MRI pattern (ring-enhancing gray matter lesions) is not characteristic of HSV encephalitis (typically temporal lobe). This would be the correct answer if MRI showed temporal lobe involvement and HSV PCR were positive." },
      { "text": "Pyrimethamine + sulfadiazine + leucovorin.", "explanation": "Correct. The clinical and imaging picture is classic cerebral toxoplasmosis in advanced AIDS: focal neurologic deficits, seizures, headache, with multiple ring-enhancing GRAY MATTER lesions on MRI (especially in the basal ganglia and gray-white junction) with surrounding edema. Leucovorin (folinic acid) prevents pyrimethamine bone marrow suppression. Induction for at least 6 weeks, followed by chronic suppression therapy until CD4 is sustained >200 for 6 months on ART; trimethoprim-sulfamethoxazole is an alternative; alternative for sulfa-allergic patients = pyrimethamine + clindamycin; if no improvement at re-imaging, brain biopsy is performed to evaluate for primary CNS lymphoma (the major differential); also optimize ART. The lecturer specified that the standard initial approach is empiric anti-toxoplasmosis treatment with re-imaging at 2-3 weeks: improvement supports toxoplasmosis and treatment is continued; no improvement prompts brain biopsy to evaluate for primary CNS lymphoma (the major differential, also EBV-associated). Standard regimen: pyrimethamine + sulfadiazine + leucovorin (folinic acid) for at least 6 weeks of induction, then chronic suppression with reduced doses until CD4 sustained >200 on ART. Trimethoprim-sulfamethoxazole is an acceptable alternative regimen. Pyrimethamine + clindamycin is the alternative for sulfa-allergic patients. ART optimization is essential. Differentiation from PML: cerebral toxoplasmosis = GRAY matter ring-enhancing; PML = WHITE matter non-enhancing." },
      { "text": "Liposomal amphotericin B + flucytosine for cryptococcal meningitis.", "explanation": "Incorrect. Cryptococcal meningitis typically presents with diffuse meningitis (headache, fever, photophobia, increased ICP), not multifocal ring-enhancing brain lesions. This would be the correct answer if the patient had positive India ink/cryptococcal antigen and increased opening pressure on LP." },
      { "text": "Empiric broad-spectrum antibiotics for bacterial brain abscess.", "explanation": "Incorrect. While bacterial brain abscess can produce ring-enhancing lesions, the multifocal pattern + HIV/AIDS context + positive Toxoplasma IgG strongly favor cerebral toxoplasmosis. This would be the correct answer if the patient had a single ring-enhancing lesion with sinusitis or otitis as a contiguous source." },
      { "text": "Whole-brain radiation therapy alone.", "explanation": "Incorrect. WBRT is reserved for primary CNS lymphoma, which is in the differential but only after empiric anti-toxoplasmosis therapy fails. This would be the correct answer after biopsy-confirmed primary CNS lymphoma." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Cerebral toxoplasmosis (AIDS, CD4 <100) = focal neuro deficits + seizures + ring-enhancing GRAY matter lesions (basal ganglia) + edema. Empiric pyrimethamine + sulfadiazine + leucovorin x 6 weeks induction → chronic suppression. Re-image at 2-3 weeks; non-responders → biopsy for primary CNS lymphoma. Alt: TMP/SMX or pyri + clindamycin.",
    "pdfPage": 23,
    "pdfQuote": "Cerebral toxoplasmosis"
  },
  {
    "id": 22,
    "category": "Microbiology: IRIS",
    "questionText": "A patient with AIDS (CD4 45 at start of ART) is begun on antiretroviral therapy. Two weeks later, he develops worsening pulmonary infiltrates with new fevers and increasing inflammatory markers. Cultures are negative for new infection. Which entity does this represent, and what is the management approach?",
    "options": [
      { "text": "Treatment failure due to antiretroviral resistance — discontinue ART immediately.", "explanation": "Incorrect. This is not treatment failure; it is IRIS, an inflammatory syndrome from immune recovery. Discontinuing ART would be inappropriate. This would be the correct answer with confirmed resistance on testing and clear treatment failure pattern (rising viral load)." },
      { "text": "Immune Reconstitution Inflammatory Syndrome (IRIS)", "explanation": "Correct. The lecturer specifically described IRIS as an inflammatory response that occurs when the immune system recovers on ART. The clinical picture in this patient — worsening pulmonary findings with new inflammatory markers shortly after ART initiation, in a patient with severe immune deficiency at baseline — is the classic IRIS presentation. Two types: (1) 'Unmasking' IRIS — reveals previously occult infection (e.g., undiagnosed CMV retinitis, TB, MAC, cryptococcal disease) that the immune system can now react to; (2) 'Paradoxical' IRIS — worsening of a known/treated infection from residual antigenic stimulation as immunity recovers. Typical timing: 1 week to 3-4 months after ART initiation. Risk increases in patients starting ART with CD4 <100 (or TB at CD4 <200). Management: CONTINUE ART (do not stop — the immune recovery is therapeutic); treat the underlying opportunistic infection; add corticosteroids (or NSAIDs in milder cases) for severe inflammation; supportive care. Prevention strategy: in patients with very low CD4 and active OI (especially cryptococcal meningitis, TB, or MAC), treat the OI for 2-4 weeks BEFORE initiating ART to reduce IRIS risk. The lecturer specified this exact prevention strategy as 'check for these infections and treat for at least 2-4 weeks before beginning antiretroviral therapy.'" },
      { "text": "Drug allergy to ART — switch to entirely different regimen.", "explanation": "Incorrect. This is not a drug allergy. Drug rashes are different in presentation and timing. This would be the correct answer if the patient developed a typical SJS/TEN-like reaction or DRESS syndrome." },
      { "text": "New superinfection — empirically treat for gram-negative pneumonia.", "explanation": "Incorrect. Empiric antibiotics may be appropriate while ruling out new infection, but the cultures are negative and the IRIS pattern fits better. Continue investigating but recognize IRIS as the likely entity. This would be the correct answer if blood cultures were positive for a new pathogen." },
      { "text": "Treatment-induced viral resistance.", "explanation": "Incorrect. Resistance would manifest as rising viral load over time and treatment failure, not as an inflammatory syndrome. This would be the correct answer with rising viral load and resistance testing showing emergence of mutations." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: IRIS = inflammatory recovery response on ART; unmasking (occult OI revealed) or paradoxical (existing OI worsens). 1 wk-3-4 mo after ART start; CD4 <100 high risk (TB <200). Management: continue ART + treat underlying OI + steroids/NSAIDs. Prevention: treat OI 2-4 weeks BEFORE starting ART.",
    "pdfPage": 35,
    "pdfQuote": "immune reconstitution inflammatory syndrome"
  },
  {
    "id": 23,
    "category": "Microbiology: CMV Transplant Risk",
    "questionText": "Among solid organ transplant recipients, which donor-recipient CMV serostatus combination represents the HIGHEST risk for post-transplant CMV disease?",
    "options": [
      { "text": "CMV-positive donor, CMV-positive recipient (D+/R+).", "explanation": "Incorrect. D+/R+ is intermediate risk — the recipient has prior immunity that provides some protection. This would be the correct answer if asking about an intermediate risk group." },
      { "text": "CMV-negative donor, CMV-negative recipient (D-/R-).", "explanation": "Incorrect. D-/R- is the LOWEST risk — neither donor nor recipient has CMV. This would be the correct answer if asking about the lowest risk." },
      { "text": "CMV-negative donor, CMV-positive recipient (D-/R+).", "explanation": "Incorrect. D-/R+ is intermediate risk — the recipient has prior immunity (which actually protects somewhat). This would be the correct answer if asking about an intermediate risk group." },
      { "text": "CMV-positive donor, CMV-positive recipient regardless of immunosuppression intensity.", "explanation": "Incorrect. While D+/R+ is intermediate, the highest risk group is the seronegative recipient receiving from a seropositive donor. This would be the correct answer in a misframed question." },
      { "text": "CMV-positive donor, CMV-negative recipient (D+/R-)", "explanation": "Correct. The lecturer specifically stratified the risk: HIGHEST = CMV-positive donor + CMV-negative recipient (D+/R-) because the recipient has no pre-existing immunity to CMV and is now exposed to the donor virus while immunosuppressed. INTERMEDIATE = D+/R+ or D-/R+ (the recipient has prior immunity, which provides some protection). LOWEST = D-/R- (no virus from either party). Without prophylaxis, the D+/R- group has very high rates of CMV disease — pneumonitis, hepatitis, colitis, retinitis, and transplant graft failure (CMV is a major cause of graft loss). Standard practice is valganciclovir prophylaxis for 3-6 months post-transplant in this high-risk group; surveillance with CMV PCR is also performed routinely. Pre-emptive therapy (treating when PCR rises before clinical disease) is an alternative strategy. The other key teaching: any CMV reactivation in a transplant recipient is a major risk for graft failure, and prevention/early treatment is essential." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: CMV transplant risk = D+/R- HIGHEST (no recipient immunity, donor virus, immunosuppression); D+/R+ and D-/R+ intermediate; D-/R- lowest. Valganciclovir prophylaxis 3-6 mo post-transplant in D+/R-. CMV is major cause of graft failure.",
    "pdfPage": 15,
    "pdfQuote": "CMV Ab (−) recipient, CMV Ab (+) donor"
  },
  {
    "id": 24,
    "category": "Microbiology: Eculizumab + Neisseria",
    "questionText": "A 28-year-old woman with paroxysmal nocturnal hemoglobinuria is being started on eculizumab (anti-C5 monoclonal antibody). Which infection prevention measure is most critical before initiating therapy?",
    "options": [
      { "text": "Vaccinate against Streptococcus pneumoniae (PCV13 + PPSV23).", "explanation": "Incorrect. While pneumococcal vaccination is beneficial in many immunocompromised patients, the SPECIFIC concern with eculizumab is Neisseria meningitidis infection. This would be the correct answer if asking about asplenia or general pneumococcal vaccination." },
      { "text": "Vaccinate against Haemophilus influenzae type b (Hib).", "explanation": "Incorrect. Hib vaccination is important for asplenic patients but is not the SPECIFIC concern with eculizumab. This would be the correct answer if asking about asplenia." },
      { "text": "Administer prophylactic acyclovir.", "explanation": "Incorrect. Acyclovir is not the recommended prophylaxis for eculizumab. This would be the correct answer if asking about HSV/VZV suppression in transplant patients." },
      { "text": "Vaccinate against Neisseria meningitidis", "explanation": "Correct. The lecturer specifically named eculizumab as a monoclonal antibody directed at the terminal complement component C5, blocking the formation of the membrane attack complex (MAC). The MAC is essential for killing encapsulated Neisseria species; without it, patients on eculizumab are at dramatically increased risk of meningococcal disease (Neisseria meningitidis, which can cause overwhelming sepsis and meningitis) and rarely Neisseria gonorrhoeae. Standard practice before initiating eculizumab: (1) Vaccinate against Neisseria meningitidis with both MenACWY (covers serogroups A, C, W, Y) and MenB (covers serogroup B) conjugate vaccines; ideally given at least 2 weeks before eculizumab to allow immune response; boosters per schedule. (2) Some experts also prescribe prophylactic penicillin (or alternative if allergic) for additional coverage. (3) Counsel patients about prompt evaluation for any febrile illness — meningococcal disease can be rapidly fatal. A REMS (Risk Evaluation and Mitigation Strategy) program is in place for eculizumab requiring meningococcal vaccination documentation before dispensing. Other complement deficiency contexts: SLE patients (also at increased Neisseria risk) and inherited terminal complement deficiencies (especially recurrent meningococcal infections)." },
      { "text": "Provide vitamin K prophylaxis for hemorrhage prevention.", "explanation": "Incorrect. Vitamin K is for coagulation, not infection prevention. This would be the correct answer if asking about hemorrhagic disease of newborn." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Eculizumab (anti-C5) blocks terminal complement → MAC deficiency → high Neisseria infection risk. Vaccinate with MenACWY + MenB ≥2 weeks before eculizumab; prophylactic penicillin per some guidelines; REMS program. SLE and inherited terminal complement deficiency similar risk.",
    "pdfPage": 9,
    "pdfQuote": "Eculizumab"
  },
  {
    "id": 25,
    "category": "Microbiology: Stem Cell Transplant Phases",
    "questionText": "A patient who underwent allogeneic hematopoietic stem cell transplantation 4 weeks ago presents with new fever, dyspnea, and bilateral pulmonary infiltrates. Which infectious agents are MOST likely in this 'post-engraftment' phase (3 weeks-3 months post-transplant)?",
    "options": [
      { "text": "Cytomegalovirus (CMV), adenovirus, Aspergillus, Candida, and Pneumocystis", "explanation": "Correct. The lecturer specified the time-stratified infectious risks after allogeneic stem cell transplantation: (1) Pre-engraftment phase (1-21 days): severe neutropenia → staphylococci, gram-negative bacteria, HSV, RSV, Candida, Aspergillus; (2) POST-ENGRAFTMENT phase (3 weeks-3 months): CMV (most concerning, with reactivation risk), adenovirus, Aspergillus, Candida, Pneumocystis — these are exactly the agents listed in this option, classic for the post-engraftment period; (3) Late phase (>3 months): VZV, Aspergillus, CMV. CMV reactivation is particularly important in the post-engraftment phase, with CMV-positive donor + CMV-negative recipient at highest risk. Surveillance with CMV PCR is routine; pre-emptive therapy (treating when PCR rises) or prophylaxis are options. Pneumocystis prophylaxis is given throughout the post-transplant period (TMP/SMX or alternatives). Aspergillus is a major invasive fungal threat; prophylaxis with azoles (e.g., posaconazole, voriconazole) is sometimes given. Bronchoscopy with BAL would be appropriate for this patient to identify the specific etiology, alongside empiric broad-spectrum antibacterial and antifungal coverage." },
      { "text": "Streptococcus pneumoniae and Hib (encapsulated bacteria).", "explanation": "Incorrect. Encapsulated bacterial infections (S. pneumoniae, Hib, Neisseria) are typically the late-phase concern after stem cell transplant (>3 months) due to humoral immune deficiency, not the post-engraftment phase. This would be the correct answer if asking about late-phase risks (>3 months) after asplenia or HSCT." },
      { "text": "Lassa virus and other VHFs.", "explanation": "Incorrect. VHFs are not typical post-transplant opportunistic infections in the absence of specific exposure history. This would be the correct answer if the patient had recent travel to West Africa with exposure to multimammate rats." },
      { "text": "Mycobacterium tuberculosis only.", "explanation": "Incorrect. While TB can occur in transplant recipients, the post-engraftment phase typically features the broader infectious pattern listed in the correct answer, not TB exclusively. This would be the correct answer if asking about TB-specific risk in immunocompromised patients." },
      { "text": "Trypanosoma brucei (African sleeping sickness).", "explanation": "Incorrect. African sleeping sickness is not a typical post-transplant opportunistic infection in the absence of specific exposure. This would be the correct answer if the patient had recent travel to sub-Saharan Africa with tsetse fly exposure." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: Post-engraftment phase HSCT (3 weeks-3 months) = CMV (highest concern, surveillance with PCR), adenovirus, Aspergillus, Candida, Pneumocystis. CMV D+/R- highest risk. Aspergillus prophylaxis with azoles. Pneumocystis prophylaxis with TMP/SMX.",
    "pdfPage": 13,
    "pdfQuote": "post-engraftment"
  },
  {
    "id": 26,
    "category": "Microbiology: Asplenia",
    "questionText": "A patient with sickle cell disease and functional asplenia (autosplenectomy by age 5) is at increased risk for which infection?",
    "options": [
      { "text": "Toxoplasma gondii cerebral disease.", "explanation": "Incorrect. Toxoplasma is associated with cell-mediated immune deficiency, not asplenia. This would be the correct answer if asking about cerebral toxoplasmosis in AIDS." },
      { "text": "Cytomegalovirus retinitis.", "explanation": "Incorrect. CMV retinitis is associated with cell-mediated immune deficiency (AIDS, transplant), not asplenia. This would be the correct answer if asking about CMV retinitis." },
      { "text": "Encapsulated bacterial infections", "explanation": "Correct. The lecturer specified that asplenic patients (whether anatomic asplenia from splenectomy or functional asplenia from sickle cell disease autosplenectomy) are at high risk for encapsulated bacterial infections — Streptococcus pneumoniae, Haemophilus influenzae type b, Neisseria meningitidis, Salmonella, Capnocytophaga (especially after dog bites), and severe babesiosis (parasitic, included due to asplenic risk). The spleen normally serves two roles: (1) phagocytic clearance of encapsulated organisms (via splenic macrophages and antibody-coated organisms), and (2) antibody production against capsular polysaccharides (via splenic plasma cells). Functional or anatomic asplenia removes both functions. Prevention strategy: (1) pneumococcal vaccinations (PCV13 + PPSV23), Hib vaccine, and meningococcal vaccines (MenACWY + MenB); (2) prophylactic penicillin (especially in children with sickle cell disease until age 5; some experts continue beyond); (3) prompt empiric broad-spectrum antibiotics for any febrile illness — overwhelming postsplenectomy infection (OPSI) is rapidly fatal. Patients are counseled to seek immediate care for fever and to carry an emergency course of antibiotics." },
      { "text": "Aspergillus fumigatus invasive aspergillosis.", "explanation": "Incorrect. Aspergillosis is associated with prolonged neutropenia (chemotherapy, transplant), not asplenia. This would be the correct answer if asking about post-chemotherapy or post-transplant infections." },
      { "text": "Pneumocystis jirovecii pneumonia.", "explanation": "Incorrect. PCP is associated with cell-mediated immune deficiency (AIDS, prolonged steroids), not asplenia. This would be the correct answer if asking about PCP." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Asplenia (anatomic or functional, e.g., sickle cell) → high risk for encapsulated bacteria: S. pneumoniae, Hib, Neisseria, Salmonella, Capnocytophaga + severe Babesia. Vaccinate (pneumo + Hib + meningococcal) + prophylactic penicillin + immediate empiric broad-spectrum antibiotics for fever.",
    "pdfPage": 11,
    "pdfQuote": "Splenectomy"
  },
  {
    "id": 27,
    "category": "Microbiology: PCP Prophylaxis",
    "questionText": "A 36-year-old man has just been diagnosed with HIV. CD4 count is 165 cells/uL. He is started on antiretroviral therapy. Which prophylactic medication should also be initiated for opportunistic infection prevention?",
    "options": [
      { "text": "Isoniazid 9 months for TB without testing.", "explanation": "Incorrect. INH prophylaxis (or alternative shorter regimens) is given when TB testing is positive, not empirically. This would be the correct answer in a patient with positive PPD or IGRA." },
      { "text": "Trimethoprim-sulfamethoxazole (TMP/SMX) for Pneumocystis jirovecii prophylaxis", "explanation": "Correct. The lecturer specified that PCP prophylaxis is indicated at CD4 <200 cells/uL. This patient at CD4 165 needs PCP prophylaxis. Standard regimen is TMP/SMX (Bactrim) double-strength tablet three times weekly (Monday/Wednesday/Friday) or once daily. Alternatives for sulfa-allergic patients: dapsone (test G6PD first to avoid hemolysis), atovaquone (suspension, expensive but well-tolerated), or aerosolized pentamidine (less effective; reserved for severely sulfa-intolerant). Continue prophylaxis until CD4 is sustained >200 cells/uL for at least 6 months on effective ART. TMP/SMX prophylaxis at CD4 <200 also provides cross-coverage for cerebral toxoplasmosis (a risk at CD4 <100), so most patients do not need additional toxoplasmosis-specific prophylaxis. MAC prophylaxis (azithromycin weekly at CD4 <50) is no longer routinely given because MAC has become rare in the modern ART era." },
      { "text": "Empiric clarithromycin + ethambutol for MAC.", "explanation": "Incorrect. MAC prophylaxis is not indicated at CD4 165; it would be considered at CD4 <50 in older protocols (now generally not given). This would be the correct answer at CD4 <50 in a patient with prior MAC exposure or known risk." },
      { "text": "Daily fluconazole for esophageal candidiasis.", "explanation": "Incorrect. Routine fluconazole prophylaxis is not given in HIV; treatment is initiated when esophageal candidiasis develops. This would be the correct answer if the patient already had esophageal candidiasis." },
      { "text": "Empiric pyrimethamine + sulfadiazine for cerebral toxoplasmosis.", "explanation": "Incorrect. Empiric anti-toxoplasmosis is not indicated at CD4 165 (toxoplasmosis becomes a risk at CD4 <100), and TMP/SMX provides adequate cross-coverage. This would be the correct answer if the patient had positive Toxoplasma IgG and CD4 <100." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HIV + CD4 <200 = TMP/SMX PCP prophylaxis (DS three times weekly or daily); cross-covers cerebral toxoplasmosis. Discontinue when CD4 sustained >200 for 6 months on ART. MAC prophylaxis (azithromycin) not routinely given anymore.",
    "pdfPage": 28,
    "pdfQuote": "TMP/SMZ"
  },
  {
    "id": 28,
    "category": "Microbiology: Cryptococcal Antigen",
    "questionText": "A patient with AIDS (CD4 22) has a positive serum cryptococcal antigen titer of 1:64. Which is the most appropriate next step?",
    "options": [
      { "text": "Reassure the patient that this represents past asymptomatic infection and no action is needed.", "explanation": "Incorrect. A positive serum cryptococcal antigen in a patient with AIDS at CD4 <100 indicates active or impending cryptococcal disease and demands further evaluation, not reassurance. This would be the correct answer in a misframed monitoring approach." },
      { "text": "Check serum cryptococcal antigen monthly without further imaging or LP.", "explanation": "Incorrect. Once a positive serum cryptococcal antigen is detected at CD4 <100, lumbar puncture is indicated to evaluate for CNS involvement. This would be the correct answer in a misframed monitoring approach." },
      { "text": "Initiate ART immediately to recover the immune system.", "explanation": "Incorrect. ART initiation is essential but should not be the immediate first step before evaluating for CNS cryptococcal involvement. ART started before treating cryptococcal meningitis can precipitate IRIS with potentially fatal increased intracranial pressure. This would be the correct answer if cryptococcal disease has already been excluded or fully treated." },
      { "text": "Perform lumbar puncture to evaluate for cryptococcal meningitis", "explanation": "Correct. A positive serum cryptococcal antigen in a patient with AIDS and CD4 <100 indicates active cryptococcal disease (or impending) and demands further evaluation. The next step is lumbar puncture to evaluate for CNS involvement (cryptococcal meningitis is the most serious manifestation and the most common cause of meningitis in advanced AIDS). CSF analysis: opening pressure (often markedly elevated), India ink (encapsulated yeast cells), cryptococcal antigen titer (positive in CSF if there is meningeal involvement), glucose/protein/cell count, and culture. Fluconazole can be started pre-emptively while awaiting LP results. If CSF is POSITIVE for cryptococcal disease: induction with liposomal amphotericin B + flucytosine for 2 weeks, then consolidation with high-dose fluconazole for 8 weeks, then chronic suppression with fluconazole until CD4 sustained >100 for 6 months on ART. Therapeutic LPs (or ventriculostomy in extreme cases) for elevated opening pressure. ART start should be delayed by 2-4 weeks (some experts wait longer) to reduce IRIS risk in cryptococcal meningitis. If CSF is NEGATIVE: this is 'isolated cryptococcal antigenemia' — treat with fluconazole alone (high-dose initially, then maintenance) to prevent progression to CNS disease. Routine cryptococcal antigen screening at CD4 <100 is now recommended in some guidelines as a way to detect early disease and prevent meningitis." },
      { "text": "Initiate empiric pyrimethamine + sulfadiazine for cerebral toxoplasmosis.", "explanation": "Incorrect. Cerebral toxoplasmosis is a different entity (gray matter ring-enhancing lesions, positive Toxoplasma IgG); positive cryptococcal antigen specifically indicates cryptococcal disease. This would be the correct answer in a patient with ring-enhancing brain lesions and positive Toxoplasma serology, not positive cryptococcal antigen." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Positive serum cryptococcal antigen in AIDS CD4 <100 = perform LP to evaluate for cryptococcal meningitis (India ink, CSF cryptococcal antigen, opening pressure). If CNS disease: lipo-amphotericin B + flucytosine x 2 wk → fluconazole 8 wk → chronic suppression + therapeutic LPs. Delay ART 2-4 wk to reduce IRIS. If CSF negative: fluconazole for cryptococcal antigenemia.",
    "pdfPage": 28,
    "pdfQuote": "cryptococcal antigen"
  },
  {
    "id": 29,
    "category": "Microbiology: Lady Windermere",
    "questionText": "A 65-year-old thin, elderly woman with no major medical illnesses presents with chronic cough and sputum production. CT chest shows tree-in-bud opacities, bronchiectasis, and small nodular infiltrates predominantly in the right middle lobe and lingula. Sputum AFB cultures grow Mycobacterium avium complex. Which clinical entity does this represent?",
    "options": [
      { "text": "Lady Windermere syndrome", "explanation": "Correct. The lecturer specifically named Lady Windermere syndrome — pulmonary MAC disease occurring in thin, elderly women without obvious immune deficiency. The condition was named after the Oscar Wilde character (Lady Windermere refused to clear her throat in polite society — speculatively linked to inadequate cough leading to bronchiectasis and infection). The classic radiographic findings include tree-in-bud opacities, bronchiectasis, and nodular infiltrates predominantly in the right middle lobe and lingula (RML/LL distribution). Recently, the entity has been linked to a genetic susceptibility, with cystic fibrosis transmembrane conductance regulator (CFTR) mutations and other genetic factors implicated. Treatment is similar to disseminated MAC but for the pulmonary form: clarithromycin or azithromycin + ethambutol, often with rifampin or rifabutin (the 'three-drug regimen'), for prolonged courses (often >12 months and continued until sputum cultures are negative for ≥12 months). Macrolide resistance testing is essential. Some patients require lobectomy for severely affected segments." },
      { "text": "Mycobacterium tuberculosis with drug-resistant pattern.", "explanation": "Incorrect. The cultures grew MAC, not M. tuberculosis. The radiographic distribution (RML/lingula) and demographic (elderly thin woman without TB risk factors) also favor MAC. This would be the correct answer if the cultures grew M. tuberculosis." },
      { "text": "Allergic bronchopulmonary aspergillosis (ABPA).", "explanation": "Incorrect. ABPA presents in patients with asthma or cystic fibrosis with elevated IgE and central bronchiectasis, with positive Aspergillus IgE/IgG. This would be the correct answer if the patient had asthma or CF with positive Aspergillus serology." },
      { "text": "Cystic fibrosis with chronic Pseudomonas infection.", "explanation": "Incorrect. CF typically presents earlier in life and the cultures grew MAC, not Pseudomonas. Genetic testing for CF mutations could be considered (links to Lady Windermere). This would be the correct answer with positive sweat chloride test or CFTR mutations and cultures positive for Pseudomonas." },
      { "text": "Sarcoidosis.", "explanation": "Incorrect. Sarcoidosis typically shows bilateral hilar lymphadenopathy and parenchymal infiltrates, not the RML/lingula nodular pattern with positive AFB cultures for MAC. This would be the correct answer if biopsy showed non-caseating granulomas without organisms." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: Lady Windermere syndrome = thin elderly women + chronic cough + RML/lingula bronchiectasis + tree-in-bud + nodular infiltrates + MAC on culture. CFTR/genetic susceptibility. Treat with clarithromycin/azithromycin + ethambutol ± rifampin/rifabutin for 12+ months until sputum cultures clear.",
    "pdfPage": 33,
    "pdfQuote": "Lady Windermere syndrome"
  },
  {
    "id": 30,
    "category": "Microbiology: IRIS Vignette",
    "questionText": "A 38-year-old man with newly diagnosed AIDS (CD4 35) is started on antiretroviral therapy. Three weeks later, he develops acute decreased visual acuity in his left eye with new floaters and flashing lights. Funduscopy shows new cotton wool spots and flame hemorrhages — findings consistent with CMV retinitis that was not present on baseline ophthalmologic exam at HIV diagnosis. Which clinical entity does this represent?",
    "options": [
      { "text": "Drug-induced retinopathy from antiretroviral therapy.", "explanation": "Incorrect. ART medications do not classically produce CMV retinitis findings (cotton wool spots + flame hemorrhages). This would be the correct answer in a misframed adverse effect pattern." },
      { "text": "Acute retinal detachment from a subclinical retinal tear.", "explanation": "Incorrect. Retinal detachment produces different findings (visual field defect with shadow/curtain progression) and is not associated with cotton wool spots and flame hemorrhages on initial presentation. This would be the correct answer if the patient had visual field defects with retinal tear on exam." },
      { "text": "New primary CMV infection acquired since HIV diagnosis.", "explanation": "Incorrect. New primary CMV infection in an adult is rare and would not produce the classic retinitis pattern in this short timeframe. This is more likely IRIS-mediated unmasking of subclinical reactivation. This would be the correct answer in a misframed pathophysiology." },
      { "text": "Bacterial endophthalmitis.", "explanation": "Incorrect. Endophthalmitis features pain, vitreous opacification, and hypopyon, not the cotton wool spots + flame hemorrhages pattern of CMV retinitis. This would be the correct answer if the patient had pain and hypopyon." },
      { "text": "Unmasking IRIS", "explanation": "Correct. The clinical picture is classic 'unmasking' IRIS: CMV retinitis was likely subclinical at the time of HIV diagnosis (the immune system was too suppressed to mount an inflammatory response, so symptoms and findings were absent), and the immune recovery from ART has now allowed the inflammatory response to develop and unmask the disease. The lecturer specifically described this exact scenario — 'unmasking' IRIS occurs from undiagnosed occult infection like CMV retinitis. Classic timing: 1 week to 3-4 months after ART initiation, especially in patients starting ART with CD4 <100 (or <200 for TB). Management: continue ART (DO NOT stop — the immune recovery is therapeutic), initiate IV ganciclovir or oral valganciclovir for CMV, consider intravitreal ganciclovir injections for sight-threatening lesions, ophthalmology consultation. Corticosteroids may be added in some cases of severe IRIS-related inflammation. This scenario specifically illustrates why some experts recommend baseline ophthalmologic exam and routine fundoscopic surveillance in patients with low CD4 starting ART, and why treating known opportunistic infections for 2-4 weeks before ART initiation can reduce IRIS risk. The lecturer specified this prevention strategy explicitly: 'check for these infections and treat for at least 2-4 weeks before beginning antiretroviral therapy.'" }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: Unmasking IRIS = previously occult OI (CMV retinitis, TB, MAC, etc.) becomes apparent as immune recovers on ART; 1 wk-3-4 mo after ART start, especially CD4 <100. Continue ART + treat OI + consider steroids. Prevention: baseline ophthalmologic/imaging surveillance + treat known OIs 2-4 weeks before ART.",
    "pdfPage": 35,
    "pdfQuote": "Unmasking IRIS"
  }
];