// Thinking Process:
// 1. High-Yield Concept: Cold-related injuries (trench foot, chilblains/pernio, panniculitis, cold urticaria, frostbite) and accidental hypothermia (Swiss staging 1-4, cold diuresis, Osborn J wave, coagulopathy, paradoxical undressing, rewarming-method selection, "no one is dead until warm and dead," K+ >12 futility, DNR override).
// 2. The "Trap": Confusing non-freezing injuries (no cyanosis, no ice crystals) with frostbite; over-aggressive intervention in mild hypothermia (hot bath causing afterdrop / vasodilation); reflexively pacing bradycardia or starting CPR in cold but perfusing patients; declaring death before rewarming.
// 3. Key Distractor: "Right intervention, wrong stage" — active external rewarming in Stage 1, CPR in Stage 3, full-dose antiarrhythmics in cold patient, debriding a clear (non-hemorrhagic) blister.
// 4. Vignette Strategy: Mechanism-first stems describe the exposure, vitals, ECG findings, and exam without naming the injury; force reasoning from physiology -> intervention. Include exposure history (alcohol, hiker, submersion, elderly cachectic sepsis) to make distractors plausible.
//
// PDF Mapping Check: (assumed) Found
// PDF Filename: Lecture # 191. M. Gindi, M.D. (PPT).pdf
// Mapping Key: 22-Environmental Medicine: Cold Injuries & Hypothermia (L191)
// Status: Verified

window.Test_L191 = [
  {
    "id": 1,
    "category": "Environmental Medicine: Non-Freezing Cold Injury",
    "questionText": "A 22-year-old infantry soldier returns from a 36-hour patrol in which he stood for prolonged periods in cold puddles inside his combat boots. On removal of his wet socks in the aid station, both feet are mottled with patches of blue, red, and waxy white skin. The skin is anesthetic to monofilament testing and no posterior tibial pulse can be palpated. The ambient temperature during the exposure remained around 8 C (46 F) and never fell below freezing. After warming the feet in a tent for 30 minutes, the soldier develops intense, burning pain, brisk erythema, and pronounced edema of both feet. Which mechanism best explains the new findings that appeared with rewarming?",
    "options": [
      { "text": "Intracellular ice-crystal formation rupturing endothelial cells with leakage of plasma into the interstitium.", "explanation": "Incorrect. Ice crystals require tissue temperatures below 0 C, but this exposure stayed at 8 C, so the lesion is a non-freezing injury rather than a true frostbite. This would be the correct answer if the soldier had been exposed below freezing and now had cyanosis and tissue blanching characteristic of true frostbite." },
      { "text": "Reperfusion of cold-damaged, abnormally porous capillaries with leakage of intravascular fluid into the extravascular space.", "explanation": "Correct. In trench (immersion) foot, prolonged cold-and-wet exposure damages the small vessels and nerves; on rewarming, blood flow returns through endothelium that has become abnormally porous, so plasma fluid moves from the intravascular into the extravascular space, producing the marked edema. The brisk inflow of blood also activates the previously anesthetic nerves, causing the characteristic intense burning pain and erythema described in the vignette." },
      { "text": "Sympathetically driven skin buckling that is the same physiology as pruning of the fingers in a long shower.", "explanation": "Incorrect. Sympathetically mediated skin buckling (pruning) is a transient cosmetic phenomenon that does not produce mottling, anesthesia, or rewarming edema; in fact, patients with a sympathectomy fail to prune. This would be the correct answer if asking why fingertips wrinkle after a long shower or bath." },
      { "text": "Arachidonic-acid-driven release of thromboxane and prostaglandins with platelet plugging of small vessels.", "explanation": "Incorrect. Thromboxane/prostaglandin-mediated microvascular thrombosis is the rewarming cascade of frostbite, where tissue temperature fell below 0 C and produced ice; this patient never froze. This would be the correct answer if the soldier had been exposed below freezing and now showed cyanosis and hemorrhagic blisters during rewarming." },
      { "text": "Cold-induced histamine release from cutaneous mast cells producing wheals and intense pruritus.", "explanation": "Incorrect. Mast-cell histamine release is the mechanism of cold urticaria, which produces hives and itching rather than mottling, anesthesia, and pulseless feet from prolonged immersion. This would be the correct answer if the soldier had developed wheals on areas of skin exposed to cold and improved with antihistamines." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Trench (immersion) foot is a non-freezing injury from prolonged cold-wet exposure; rewarming reperfuses damaged porous capillaries, producing pain, erythema, and edema rather than the cyanosis seen in true frostbite.",
    "pdfPage": 3,
    "pdfQuote": "Trench foot non-freezing cold"
  },
  {
    "id": 2,
    "category": "Environmental Medicine: Non-Freezing Cold Injury - Chilblains",
    "questionText": "A 28-year-old woman who recently moved from Arizona to a rainy region of the United Kingdom presents in late autumn with painful, itchy, swollen, bluish nodules on her toes and the dorsa of her fingers. Lesions appear within hours after walking outdoors in damp 5 C (41 F) weather and persist for several days. She has a long history of one or two fingers turning blanched-white in the cold, then becoming red and painful when she comes indoors. The ambient temperature has never been below 0 C (32 F) during these episodes. The lesions never become anesthetic or cyanotic, and no blisters form. Which of the following best explains why this patient is predisposed to this disorder?",
    "options": [
      { "text": "Underlying tendency to exaggerated digital vasospasm with characteristic blanching of fingers in the cold.", "explanation": "Correct. The patient's history of one or two fingers turning blanched-white on cold exposure is classic Raynaud's phenomenon, and chilblains (pernio) are more common in patients who experience Raynaud's. Repeated intermittent damp, non-freezing exposure in a Raynaud-predisposed person produces the tender, pruritic, edematous blue nodules described, which is why the disorder is endemic in damp climates such as the UK." },
      { "text": "Prior exposure of skin to temperatures below 0 C with ice-crystal formation in superficial vessels.", "explanation": "Incorrect. The vignette specifies the temperature never went below freezing, so ice-crystal-mediated injury cannot occur. This would be the correct answer if the lesions appeared only after sub-zero exposure and produced waxy, cyanotic, anesthetic skin characteristic of true frostbite." },
      { "text": "Cold-induced IgE-mediated mast-cell degranulation producing wheals on exposed skin.", "explanation": "Incorrect. IgE/mast-cell mediated histamine release causes cold urticaria, which produces transient wheals and pruritus rather than persistent tender blue nodules lasting several days. This would be the correct answer if the patient developed hives within minutes of cold exposure that resolved with antihistamines." },
      { "text": "Necrosis of subcutaneous fat caused by adjacent vasoconstriction during prolonged cold exposure.", "explanation": "Incorrect. Cold panniculitis produces unsightly depressed cosmetic lesions over fatty areas (such as the thighs of wet horseback riders) rather than tender pruritic nodules of digits. This would be the correct answer if the patient developed cosmetic indentations over the inner thighs after prolonged horseback riding in wet, cold conditions." },
      { "text": "Standing for prolonged periods in shoes filled with cold water leading to macerated, anesthetic skin.", "explanation": "Incorrect. Prolonged immersion in cold water produces trench foot, characterized by macerated, mottled, anesthetic skin without pulses, not the brief intermittent damp exposures and pruritic blue nodules of this patient. This would be the correct answer if the patient had stood for many hours in waterlogged boots and developed mottled, pulseless, anesthetic feet." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: Chilblains (pernio) follow intermittent damp non-freezing exposure and are more common in patients with Raynaud's phenomenon; nifedipine can help by dilating cutaneous vessels.",
    "pdfPage": 4,
    "pdfQuote": "Chilblains also called perneo"
  },
  {
    "id": 3,
    "category": "Environmental Medicine: Cold Panniculitis",
    "questionText": "A 35-year-old equestrian competes in a multi-day endurance ride during which her thighs are pressed against a wet horse for hours in 4 C (39 F) weather. Two weeks later she notices firm, mildly tender, depressed lesions along the medial aspects of both thighs that produce a poor cosmetic appearance but no functional impairment. There were no blisters, no ulcerations, and the skin overlying the lesions was never anesthetic or cyanotic during exposure. Which pathophysiologic mechanism is most directly responsible for these subcutaneous lesions?",
    "options": [
      { "text": "Microvascular thrombosis from rewarming-induced thromboxane and prostaglandin release.", "explanation": "Incorrect. The rewarming thromboxane/prostaglandin cascade is the mechanism of frostbite and requires sub-zero exposure with ice-crystal formation, neither of which occurred at 4 C. This would be the correct answer if the patient's feet had been exposed below freezing and developed cyanotic, blistered digits requiring debridement." },
      { "text": "IgE-mediated mast cell degranulation producing histamine-driven wheal formation.", "explanation": "Incorrect. Mast-cell histamine release produces cold urticaria, a wheal-and-itch reaction rather than persistent depressed cosmetic lesions in subcutaneous fat. This would be the correct answer if the patient had developed pruritic wheals immediately on cold exposure that resolved with antihistamines." },
      { "text": "Cold-induced vasoconstriction depriving subcutaneous adipocytes of adjacent blood supply, leading to fat death.", "explanation": "Correct. The subcutaneous fat depends on perfusion from adjacent skin vessels; prolonged cold-induced vasoconstriction starves the adipocytes of that adjacent blood supply, and the fat dies. The classic scenario is exactly what is described - prolonged pressure of a fatty body region (medial thighs) against a wet, cold horse - and the lesions are unsightly but have no specific treatment." },
      { "text": "Permanent peripheral nerve damage from prolonged immersion of skin in cold water inside footwear.", "explanation": "Incorrect. Immersion (trench) foot from waterlogged footwear produces mottled, anesthetic, edematous feet rather than depressed subcutaneous lesions on the thighs. This would be the correct answer if the patient had stood for many hours in cold puddles in her boots and developed numb, pulseless, macerated feet." },
      { "text": "Exaggerated digital sympathetic vasospasm causing white-to-red color changes in the cold.", "explanation": "Incorrect. Sympathetic digital vasospasm describes Raynaud's phenomenon, which affects fingers in the cold and predisposes to chilblains, not necrosis of thigh fat. This would be the correct answer if the patient had episodic blanching of her fingers when reaching into the freezer." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Cold panniculitis is necrosis (not true inflammation) of subcutaneous fat from cold-induced vasoconstriction depriving adipocytes of adjacent blood supply; treatment is supportive and the cosmetic defect may be permanent.",
    "pdfPage": 6,
    "pdfQuote": "Panniculitis necrosis of the fat"
  },
  {
    "id": 4,
    "category": "Environmental Medicine: Frostbite - Environmental Requirements",
    "questionText": "An emergency physician is reviewing case files from a winter season. The first patient developed cyanotic, hemorrhagic blisters on the fingertips after a long climb in still air at -10 C (14 F). The second patient hiked in 4 C (39 F) weather with sustained 40-mph winds and reported severe cold sensation but his fingertips remained warm to touch and developed no blisters or color changes. The third was a soldier whose feet had been in cold puddles inside boots for 36 hours at 8 C (46 F). The physician wants to identify which of these patients actually sustained the freezing injury characterized by ice-crystal formation in tissue. Which environmental condition is required for that specific freezing injury to occur?",
    "options": [
      { "text": "Any prolonged exposure to wind, regardless of the ambient temperature.", "explanation": "Incorrect. Wind alone increases the rate of heat loss and lowers the perceived temperature but cannot, by itself, freeze tissue if the ambient temperature is above 0 C. This would be the correct answer if asking what worsens cold sensation without changing the true air temperature." },
      { "text": "Prolonged standing in cold water above the freezing point.", "explanation": "Incorrect. Prolonged immersion at temperatures above 0 C produces trench foot (a non-freezing injury), not the freezing injury with ice crystals. This would be the correct answer if asking what environment produces macerated, mottled, anesthetic feet without tissue freezing." },
      { "text": "Intermittent damp non-freezing exposure in a person predisposed to Raynaud's phenomenon.", "explanation": "Incorrect. Intermittent damp non-freezing exposure produces chilblains (pernio), not the freezing injury; ice crystals cannot form when the temperature stays above 0 C. This would be the correct answer if asking what produces tender blue nodules on the toes after walking outdoors in damp UK weather." },
      { "text": "Ambient temperature below 0 C with sufficient time for the skin temperature to fall below the freezing point.", "explanation": "Correct. By definition, the freezing injury requires the tissue temperature itself to fall below 0 C, which is impossible when the ambient air temperature remains above freezing. Wind, lack of insulation, alcohol use, and dehydration accelerate heat loss and shorten the time required, but they only matter when the air is already below 0 C, as in the first patient." },
      { "text": "Exposure to subcutaneous pressure against a wet surface in a fatty region of the body.", "explanation": "Incorrect. Pressure of a fatty region against a wet cold surface produces cold panniculitis from vasoconstriction-driven fat necrosis, not the freezing injury. This would be the correct answer if asking the mechanism of medial-thigh subcutaneous lesions in equestrians riding wet horses." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Frostbite requires ambient temperature below 0 C; wind does not lower the actual temperature but increases the rate of heat loss, shortening the time to tissue freezing.",
    "pdfPage": 8,
    "pdfQuote": "Frostbite ambient temperature below freezing"
  },
  {
    "id": 5,
    "category": "Environmental Medicine: Frostbite - Rewarming Cascade",
    "questionText": "A 30-year-old climber is rescued after his hands were exposed for several hours to -15 C (5 F) air. On arrival at a warm shelter with no possibility of refreezing, his fingers are rewarmed in 38 C water. Over the following 12-24 hours the fingertips become cyanotic with hemorrhagic blisters, and Doppler reveals absent flow at the distal digital arteries despite the proximal vessels being intact. The medical team plans treatment aimed at the dominant pathophysiologic process that produces the worsening tissue ischemia during rewarming. Which mechanism best explains the deterioration in perfusion seen after thawing?",
    "options": [
      { "text": "Direct cytotoxicity from intracellular ice crystals causing membrane rupture during freezing.", "explanation": "Incorrect. Intracellular ice formation does cause direct damage during freezing, but it does not by itself explain the progressive ischemia and microvascular thrombosis that appear specifically during rewarming. This would be the correct answer if asking what initially damages cells during the frozen phase rather than what worsens perfusion during thawing." },
      { "text": "Massive intravascular hemolysis with potassium release and obstruction of distal arterioles by red-cell stroma.", "explanation": "Incorrect. Cold can lyse blood cells and elevate measured potassium, but distal-arteriole obstruction from red-cell stroma is not the primary mechanism of frostbite rewarming injury. This would be the correct answer if asking why measured serum potassium can rise spuriously in cold-stored blood samples." },
      { "text": "Reperfusion of cold-damaged porous capillaries with leakage of plasma into the interstitium.", "explanation": "Incorrect. Capillary leak from reperfusion of porous vessels is the dominant rewarming process in trench foot (a non-freezing injury), where the result is edema rather than cyanosis and microvascular clots. This would be the correct answer if the climber had only stood in cold puddles above freezing and developed mottled, edematous feet on rewarming." },
      { "text": "IgE-mediated mast cell degranulation producing histamine and a cold-induced anaphylactoid reaction.", "explanation": "Incorrect. Histamine release from mast cells underlies cold urticaria, not the microvascular thrombosis of frostbite rewarming, and anaphylaxis from cold is rare. This would be the correct answer if the patient had developed wheals and hypotension within minutes of cold exposure." },
      { "text": "Activation of arachidonic-acid metabolites causing vasoconstriction, platelet aggregation, and microvascular thrombosis.", "explanation": "Correct. On thawing, the arachidonic-acid cascade is triggered, releasing thromboxanes and prostaglandins that constrict vessels and promote platelet aggregation on the endothelium. Platelet plugs and sludging of red and white cells produce microvascular thrombosis distal to the larger patent vessels, leading to the ischemia, cyanosis, and hemorrhagic blisters described, and this is the rationale for thrombolytic therapy in severe cases." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: Frostbite rewarming activates the arachidonic-acid cascade (thromboxane and prostaglandins), causing vasoconstriction, platelet aggregation, and microvascular thrombosis - the rationale for thrombolytic therapy in severe cases.",
    "pdfPage": 10,
    "pdfQuote": "Arachidonic acid cascade upon rewarming"
  },
  {
    "id": 6,
    "category": "Environmental Medicine: Frostbite - Distinguishing Features",
    "questionText": "A 40-year-old man is brought to a mountain clinic after several hours of exposure at -18 C (0 F) air temperature. On examination, both feet show waxy white pallor with patches of deep blue-purple cyanosis, and the skin is hard. A second patient seen the same day has macerated, mottled, anesthetic, pulseless feet from prolonged exposure to puddles inside boots at 6 C (43 F); the second patient's feet are not cyanotic. Which of the following physical findings is most useful for distinguishing the freezing injury of the first patient from the non-freezing injury of the second?",
    "options": [
      { "text": "Patchy bluish discoloration reflecting deoxygenated blood trapped distal to microvascular clots.", "explanation": "Correct. Cyanosis appears in frostbite because the rewarming microvascular thrombosis traps deoxygenated blood distal to the clots so it cannot return to be reoxygenated; the lecturer specifically emphasized that the non-freezing injuries (trench foot, pernio) do not cause cyanosis. This makes cyanosis the most useful single feature for separating freezing from non-freezing cold injuries at the bedside." },
      { "text": "Anesthesia of the affected skin to light touch and temperature.", "explanation": "Incorrect. Anesthesia of affected skin occurs in trench foot, chilblains, and frostbite alike, so it cannot reliably distinguish freezing from non-freezing injuries. This would be the correct answer if asking which finding all cold injuries share." },
      { "text": "Absence of palpable peripheral pulses on initial presentation.", "explanation": "Incorrect. Pulses can be absent in both freezing and non-freezing cold injuries due to vasoconstriction or edema. This would be the correct answer if asking a finding that is shared by both conditions rather than one that distinguishes them." },
      { "text": "Edema of the affected extremity appearing after rewarming.", "explanation": "Incorrect. Edema after rewarming is prominent in trench foot from leaky capillaries and also occurs in chilblains and frostbite, so it is not specific to either category. This would be the correct answer if asking which finding is most prominent in immersion foot." },
      { "text": "Severe pain on rewarming as blood flow returns to previously cold tissue.", "explanation": "Incorrect. Both trench foot and frostbite produce severe pain on rewarming when blood returns to formerly insensate tissue. This would be the correct answer if asking which symptom requires generous opioid analgesia during rewarming of any cold injury." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: Cyanosis specifically distinguishes frostbite (microvascular thrombosis from rewarming cascade) from non-freezing injuries such as trench foot and pernio, which do not produce cyanosis.",
    "pdfPage": 11,
    "pdfQuote": "Cyanosis distinguishes from non-freezing injuries"
  },
  {
    "id": 7,
    "category": "Environmental Medicine: Frostbite - Field Rewarming Decisions",
    "questionText": "A search-and-rescue team reaches an injured climber on a remote mountain peak. His fingers and toes are hard, waxy, and white from prolonged exposure to -25 C (-13 F) air. He must still be evacuated for several hours through terrain where temperatures will remain below freezing and where there is no realistic way to keep the rewarmed extremities reliably warm. The lead clinician must decide whether to rewarm the affected digits in 38 C water now or to defer rewarming until the patient reaches the base camp shelter. Which of the following is the most appropriate action in this scenario?",
    "options": [
      { "text": "Begin immediate rewarming in 38 C water in the field to limit duration of ice-crystal damage.", "explanation": "Incorrect. Rapid rewarming in 37-39 C water is the standard initial therapy, but only when refreezing is impossible; refreezing of thawed tissue produces dramatically worse injury than continued freezing. This would be the correct answer if the team were already in a warm shelter with no risk of refreezing." },
      { "text": "Briskly rub the extremities with snow to gently warm and exfoliate the frozen skin.", "explanation": "Incorrect. Rubbing frozen tissue with snow causes additional mechanical damage to already injured cells and does not warm the tissue; it has no role in modern frostbite care. This would be the correct answer in no real clinical scenario." },
      { "text": "Defer rewarming until the patient reaches an environment where refreezing is not possible.", "explanation": "Correct. Rewarming should be deferred whenever there is any risk that the tissue will refreeze, because refreezing thawed tissue causes far worse injury than leaving it frozen for additional hours. Only once the patient is in a safe, warm environment with no risk of refreezing should the digits be immersed in 37-39 C water until they become mushy, pliable, and red." },
      { "text": "Use slow ambient rewarming with the digits inside the rescuer's clothing.", "explanation": "Incorrect. Slow ambient rewarming is inadequate to limit ice damage, and the partial thawing produced by body heat could still leave tissue vulnerable to refreezing on the mountain. This would be the correct answer if asking the only available option in an extremely austere setting with no water or heat source, but it is not the recommended approach." },
      { "text": "Apply dry chemical heating packs directly against the frozen skin during evacuation.", "explanation": "Incorrect. Chemical heat packs against frostbitten skin risk thermal burns of cold, anesthetic tissue and cause exactly the kind of partial thawing that is dangerous when refreezing is possible. This would be the correct answer if the question asked about active external rewarming in a sheltered Stage 2 hypothermia patient with intact sensation." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Frostbite rewarming is in 37-39 C water until the tissue is mushy, pliable, and red, but NEVER rewarm in the field if there is any risk of refreezing - refreezing thawed tissue causes far worse injury.",
    "pdfPage": 13,
    "pdfQuote": "Do not rewarm if refreezing possible"
  },
  {
    "id": 8,
    "category": "Environmental Medicine: Frostbite - Tetanus Prophylaxis",
    "questionText": "A 45-year-old day-laborer is brought to the ED after several hours of exposure of his hands to -20 C (-4 F) air. The fingertips are cyanotic with several hemorrhagic blisters. He is given parenteral morphine and his hands are rewarmed in 38 C water until they become red and pliable. He grew up in a rural area abroad and reports no childhood immunizations and no tetanus boosters. The wounds appear to be evolving toward devitalized necrotic skin around the blisters. Which additional intervention should be added to his initial treatment regimen?",
    "options": [
      { "text": "Active tetanus toxoid booster only, with no further immunization needed.", "explanation": "Incorrect. A booster alone provides no immediate protection in a patient who has never been primed; in an unimmunized patient with a tetanus-prone wound, passive protection is required as well. This would be the correct answer in a fully immunized adult whose last booster was more than five years ago." },
      { "text": "Empiric broad-spectrum IV antibiotics directed against Clostridium tetani.", "explanation": "Incorrect. Antibiotics are not the primary prophylaxis against tetanus; the disease is mediated by an exotoxin, so neutralization (TIG) and active immunization are needed. This would be the correct answer if the patient had established clostridial wound infection requiring directed antimicrobial therapy." },
      { "text": "No tetanus prophylaxis is indicated because frostbite is a 'clean' injury without soil contamination.", "explanation": "Incorrect. The lecturer explicitly emphasized that frostbite is a tetanus-prone wound, regardless of soil contamination, because it produces devitalized tissue. This would be the correct answer if the patient had only a small superficial clean laceration in an up-to-date adult." },
      { "text": "Tetanus toxoid plus tetanus immune globulin because this is a tetanus-prone wound in an unimmunized patient.", "explanation": "Correct. Frostbite is explicitly a tetanus-prone wound (along with infected, puncture, devitalized, and contaminated wounds). A patient who has never been immunized requires both the active immunization (tetanus toxoid) and the passive immunization (tetanus immune globulin) to be protected, because the toxoid alone provides no immediate antibody coverage." },
      { "text": "Tetanus immune globulin only, deferring active immunization until the wounds have healed.", "explanation": "Incorrect. Passive immunization alone leaves the patient without long-term protection; the active vaccine should be initiated at the same time so that durable immunity develops. This would be the correct answer in a patient with confirmed clinical tetanus who cannot receive simultaneous active vaccination for some reason." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Frostbite is a tetanus-prone wound (like infected, puncture, devitalized, and contaminated wounds); an unimmunized patient needs both tetanus toxoid AND tetanus immune globulin.",
    "pdfPage": 15,
    "pdfQuote": "Frostbite is a tetanus-prone wound"
  },
  {
    "id": 9,
    "category": "Environmental Medicine: Frostbite - Blister Management",
    "questionText": "A 52-year-old hiker arrives at the ED two days after his fingers were frostbitten at -20 C (-4 F). Examination reveals two intact, fluid-filled blisters on the dorsum of the second digit; the fluid inside one of them is clear, while the other contains frank blood. A third blister on the third digit has already ruptured and a flap of devitalized skin is overlying it. The patient has good pain control and reliable follow-up planned with a burn surgeon. Which approach to the blisters is most consistent with current frostbite management?",
    "options": [
      { "text": "Debride dead skin over the ruptured blister, leave the intact clear blister alone, and do not break the intact hemorrhagic blister.", "explanation": "Correct. Skin overlying a ruptured blister is dead and serves as a bacterial substrate, so it should be debrided; an intact clear blister is sterile and the standard practice is to leave it intact (often with a doughnut dressing for protection); and an intact hemorrhagic blister should not be broken because a study showed worse outcomes when these are opened, with the only exceptions being blisters so large they limit joint motion. This option matches Dr. Gindi's three-rule summary exactly." },
      { "text": "Break only the intact hemorrhagic blister to release thromboxane and prostaglandins.", "explanation": "Incorrect. Although thromboxane and prostaglandins are present inside blister fluid, breaking an intact hemorrhagic blister has been shown to worsen outcomes in one study; only the clear, ruptured, or joint-limiting blisters are addressed in this way. This would be the correct answer if the hemorrhagic blister were so large that it limited motion of an adjacent joint and required decompression." },
      { "text": "Leave all blisters intact regardless of whether they are ruptured, clear, or hemorrhagic.", "explanation": "Incorrect. Leaving a ruptured blister alone permits the overlying dead skin to harbor bacteria as a culture medium and worsens infection risk; that flap should be removed. This would be the correct answer if there were a way to keep the ruptured blister truly sterile, which clinically is not feasible." },
      { "text": "Inject all intact blisters with a topical antimicrobial before deciding on debridement.", "explanation": "Incorrect. Routine intra-blister injection of antimicrobials is not standard; the evidence supports topical gooey ointments after blister rupture to promote epithelialization. This would be the correct answer in no recognized scenario from this lecture." },
      { "text": "Aggressively debride all blisters (ruptured and intact) to allow topical antimicrobial penetration.", "explanation": "Incorrect. Routinely debriding intact blisters removes sterile cover and, for hemorrhagic blisters, has been shown to worsen outcomes. This would be the correct answer if the blisters were so massive that they limited joint motion and required immediate decompression." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: In frostbite, debride dead skin over RUPTURED blisters, LEAVE intact clear blisters alone, and DO NOT break intact hemorrhagic blisters (one study showed worse outcomes when broken).",
    "pdfPage": 17,
    "pdfQuote": "Hemorrhagic blisters do not break"
  },
  {
    "id": 10,
    "category": "Environmental Medicine: Frostbite - Thrombolysis",
    "questionText": "A 38-year-old climber presents within 4 hours of severe deep-tissue frostbite involving the distal fingers of both hands after exposure to -30 C (-22 F). After rapid rewarming in 38 C water, the fingertips are profoundly cyanotic with no Doppler signal in the distal digital arteries, and angiography shows extensive small-vessel thrombosis. There is no recent surgery, no intracranial bleeding, and no other thrombolytic contraindication. The team plans an intervention to disrupt the established clots and restore distal perfusion before irreversible tissue loss occurs. Which intervention has now received a 1C recommendation (weak evidence but recommended) for severe frostbite by the people who specialize in this disease?",
    "options": [
      { "text": "Hyperbaric oxygen therapy aimed at delivering more dissolved oxygen to ischemic tissue.", "explanation": "Incorrect. Hyperbaric oxygen has been tried in severe frostbite but the literature remains controversial and it has not received a definitive recommendation. This would be the correct answer if the question asked about an adjunctive, unproven oxygen-delivery intervention for ischemic limbs." },
      { "text": "Systemic heparin anticoagulation to prevent further clot propagation.", "explanation": "Incorrect. Heparin has been tried in frostbite but, as the lecturer noted, the patient has already coagulated and the evidence does not support heparin's routine use. This would be the correct answer if the patient had documented active distal thrombosis with low bleeding risk in a non-frostbite context such as DVT." },
      { "text": "Pharmacologic sympathetic blockade with bupivacaine to relieve vasoconstriction.", "explanation": "Incorrect. Sympathetic blockade is an aggressive and controversial maneuver to relieve vasoconstriction; long-acting anesthetics like bupivacaine and ropivacaine are primarily used for pain control rather than as proven therapy to restore perfusion. This would be the correct answer if asking about a long-acting anesthetic for severe rewarming pain." },
      { "text": "Intravenous dextran to expand intravascular volume and theoretically wash clots distally.", "explanation": "Incorrect. Dextran has been used to expand intravascular volume in hopes of washing clots further downstream, but this remains unproven and is not a 1C recommendation. This would be the correct answer if asking which colloid was historically tried for its theoretical clot-displacement effect." },
      { "text": "Thrombolytic therapy with an agent such as alteplase or streptokinase to break apart existing clots.", "explanation": "Correct. Since the prior version of this lecture, the literature has become less controversial about using thrombolysis for severe frostbite, and thrombolytic agents such as alteplase and streptokinase have received a 1C recommendation by specialists. The rationale is that the dominant rewarming injury is microvascular thrombosis, so breaking apart established clots can restore distal perfusion and reduce eventual tissue loss." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: Thrombolysis (alteplase, streptokinase) for severe frostbite carries a 1C recommendation - based on weak but accumulating evidence - because it can lyse the rewarming-induced microvascular thrombi.",
    "pdfPage": 18,
    "pdfQuote": "Thrombolysis recommendation severe frostbite"
  },
  {
    "id": 11,
    "category": "Environmental Medicine: Hypothermia - Swiss Staging",
    "questionText": "A 65-year-old man is found outdoors on a winter morning after spending the night intoxicated on a park bench. In the ED his esophageal thermistor reads 30 C (86 F). He is somnolent and his consciousness is clearly impaired. He has stopped shivering. His blood pressure is 92/60, heart rate 48/min and irregular, respirations 12/min. There is no evidence of cardiac arrest and he has palpable pulses. According to the Swiss staging system used in this lecture, which stage best describes this patient?",
    "options": [
      { "text": "Stage II (moderate hypothermia, 28-32 C): impaired consciousness, may or may not be shivering, requires active external rewarming.", "explanation": "Correct. The patient's core temperature of 30 C falls within the 28-32 C Stage II window, and his impaired consciousness with absent shivering and preserved pulses fits this stage. Stage II management involves active external rewarming (warm blankets, forced-air bear hugger), minimally invasive techniques (warmed humidified oxygen, warmed IV fluids, bladder/NG lavage), horizontal positioning, and gentle handling to avoid arrhythmias." },
      { "text": "Stage I (mild hypothermia, 32-35 C): conscious, shivering, treated with passive external rewarming.", "explanation": "Incorrect. Stage I patients are alert and shivering with core temperature 32-35 C and are not somnolent; this patient is below 32 C with impaired consciousness and absent shivering. This would be the correct answer if the patient had returned from a day of skiing alert, shivering, and with a core of 34 C." },
      { "text": "Stage III (severe hypothermia, <28 C): unconscious but with vital signs present, requires invasive rewarming and ECMO consideration.", "explanation": "Incorrect. Stage III requires core temperature below 28 C with vital signs present, but this patient's core is 30 C. This would be the correct answer if his esophageal temperature were 26 C with preserved pulses and unconsciousness, mandating ECMO-center transfer." },
      { "text": "Stage IV (cardiac arrest from hypothermia): no detectable circulation despite warming, requires CPR and ECMO/CPB.", "explanation": "Incorrect. Stage IV is hypothermic cardiac arrest with no perfusion, and this patient has palpable pulses with measurable blood pressure. This would be the correct answer if he had no pulse, no blood pressure, and ultrasound confirmed no forward flow." },
      { "text": "Secondary hypothermia from underlying sepsis, requiring antibiotics rather than rewarming.", "explanation": "Incorrect. Although sepsis can lower body temperature (especially in elderly and cachectic patients), this man's exposure history of a cold night outdoors with alcohol points to primary environmental hypothermia. This would be the correct answer if a cachectic elderly nursing-home resident had a temperature of 35 C with hypotension, leukocytosis, and a pneumonia infiltrate." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: Swiss hypothermia staging: I (mild) 32-35 C / alert / shivering; II (moderate) 28-32 C / impaired consciousness; III (severe) <28 C / unconscious; IV cardiac arrest.",
    "pdfPage": 27,
    "pdfQuote": "Swiss staging moderate hypothermia 28-32"
  },
  {
    "id": 12,
    "category": "Environmental Medicine: Hypothermia - Cold Diuresis",
    "questionText": "A 28-year-old woman participates in an outdoor winter hike for several hours in 2 C (36 F) air with minimal fluid intake. She reports a markedly increased urge to urinate during the activity and produces several liters of dilute urine. On arrival at the lodge her core temperature is 34 C, she is shivering and alert, and her exam reveals dry mucous membranes and orthostatic dizziness. Her serum sodium is normal. Which mechanism best explains the increased urine production in this patient?",
    "options": [
      { "text": "Inappropriate suppression of ADH from cold-induced hypothalamic injury.", "explanation": "Incorrect. Cold-induced hypothalamic dysfunction with central diabetes insipidus is not the mechanism of cold diuresis; cold diuresis reflects redistribution of intravascular volume to the core. This would be the correct answer if the patient had a brainstem lesion with low urine osmolality and serum hypernatremia." },
      { "text": "Peripheral vasoconstriction shifting blood to the core, increasing renal perfusion, with kidney response that volume is excessive.", "explanation": "Correct. Cold causes peripheral vasoconstriction to preserve core heat; the shift in blood toward central organs increases renal perfusion, and the kidneys interpret this as volume overload and increase urine output (cold diuresis). The bladder also becomes more sensitive to small volumes, contracting earlier and producing the frequent urge to void described, which together cause significant intravascular volume depletion." },
      { "text": "Renal vasoconstriction with reduced glomerular filtration and concentrated urine output.", "explanation": "Incorrect. Renal vasoconstriction would reduce, not increase, urine output, and the urine is dilute rather than concentrated. This would be the correct answer in shock states such as severe hemorrhage where renal perfusion drops and oliguria ensues." },
      { "text": "Direct cold-induced damage to renal tubules producing osmotic diuresis from solute spillage.", "explanation": "Incorrect. Cold-induced tubular damage with osmotic diuresis is not the standard mechanism of cold diuresis and would typically produce abnormal urinalysis or rhabdomyolysis-associated changes. This would be the correct answer if the patient had elevated CPK with myoglobinuria from prolonged immobility." },
      { "text": "Hyperglycemia-induced osmotic diuresis from cold-mediated insulin resistance.", "explanation": "Incorrect. While cold can transiently alter glucose handling, hyperglycemia is not the dominant cause of cold diuresis and the patient does not have features of an osmotic glucose load. This would be the correct answer if the patient had a blood glucose of 600 mg/dL in DKA with polyuria and polydipsia." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Cold diuresis = peripheral vasoconstriction shunts blood to the core, the kidneys see this as volume overload and excrete fluid; the bladder also becomes more sensitive, producing the urge to void with smaller volumes.",
    "pdfPage": 21,
    "pdfQuote": "Cold diuresis vasoconstriction kidneys"
  },
  {
    "id": 13,
    "category": "Environmental Medicine: Hypothermia - ECG Findings",
    "questionText": "A 60-year-old man is found in a snowbank after several hours of cold exposure. His esophageal temperature is 29 C. He is somnolent but has palpable pulses. His ECG shows an irregularly irregular rhythm at 42/min with absent P waves, a notched 'hump' at the J point at the end of the QRS complex, a wavy baseline artifact, and a prolonged QT interval. Blood pressure is 96/58 and he is perfusing his organs. A junior team member proposes immediate transvenous pacing for the bradycardia. Which of the following best reflects the appropriate next step in management?",
    "options": [
      { "text": "Place a transvenous pacemaker immediately because the heart rate is 42/min.", "explanation": "Incorrect. Pacing this cold heart risks triggering a malignant ventricular arrhythmia because cold myocardium is extremely irritable, and the bradycardia is physiologically appropriate to a markedly reduced metabolic rate. This would be the correct answer if the patient were normothermic with symptomatic third-degree heart block." },
      { "text": "Give a full normothermic dose of intravenous amiodarone to suppress the underlying atrial fibrillation.", "explanation": "Incorrect. Standard antiarrhythmic doses are dangerous in cold patients because drug metabolism is markedly slowed; on rewarming, the accumulated drug can produce overdose toxicity. This would be the correct answer if the patient were normothermic with new symptomatic atrial fibrillation requiring rhythm control." },
      { "text": "Continue gentle rewarming and handling, recognizing that slow atrial fibrillation with Osborn (J) waves is expected in this stage.", "explanation": "Correct. Slow atrial fibrillation is the 'classic' rhythm in hypothermia, the notched J-point wave is the Osborn (J) wave, and a prolonged QT and shivering artifact complete the picture; bradycardia is appropriate because the cold heart has a low metabolic demand. The cold myocardium is highly irritable, so handling should be gentle and rewarming should proceed without provocative interventions, since tachycardia in this setting would actually suggest concurrent bleeding, sepsis, or intoxication." },
      { "text": "Initiate immediate chest compressions because Osborn waves indicate impending cardiac arrest.", "explanation": "Incorrect. Osborn waves do not indicate arrest, and CPR in a hypothermic patient who is still perfusing can itself precipitate ventricular fibrillation in an irritable cold myocardium. This would be the correct answer only when the patient is in confirmed cardiac arrest with no detectable forward flow." },
      { "text": "Cardiovert urgently because slow atrial fibrillation in cold patients carries a high risk of stroke.", "explanation": "Incorrect. Urgent cardioversion is not indicated; the rhythm is the expected hypothermic pattern and the heart is too irritable to manipulate aggressively. This would be the correct answer if the patient were normothermic with new-onset atrial fibrillation and hemodynamic instability from the rhythm itself." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Slow atrial fibrillation with Osborn (J) waves is the 'classic' hypothermic ECG; bradycardia is physiologic - do NOT pace, handle gently, and avoid full-dose antiarrhythmics that will overdose on rewarming.",
    "pdfPage": 24,
    "pdfQuote": "Osborn wave J wave hypothermia"
  },
  {
    "id": 14,
    "category": "Environmental Medicine: Hypothermia - Paradoxical Undressing",
    "questionText": "A search team finds a hiker dead in a snowfield. He is partially undressed: his jacket, hat, and gloves are scattered nearby, even though the ambient temperature is -15 C (5 F). Two prior victims found in similar circumstances had also removed clothing immediately before dying. Investigators are puzzled because the behavior appears irrational given the cold. Which mechanism best explains why severely hypothermic patients sometimes shed their clothing shortly before death?",
    "options": [
      { "text": "Cold-induced acute psychosis driven by catecholamine surge in the early shivering phase.", "explanation": "Incorrect. Early cold stress activates the sympathetic nervous system and shivering, but acute psychosis is not the recognized mechanism of paradoxical undressing in severe late hypothermia. This would be the correct answer if asking about agitation in early Stage I when the patient is still shivering and alert." },
      { "text": "Cerebral cortical disinhibition from anesthetic effect of cold producing euphoria similar to ethanol intoxication.", "explanation": "Incorrect. Although cold does depress cortical function progressively, paradoxical undressing is specifically explained by loss of peripheral vasoconstriction and the resulting sensation of warmth, not by euphoric disinhibition. This would be the correct answer if asking what produces giddiness in early acute cold exposure." },
      { "text": "Hypothalamic set-point reset by cold injury producing a febrile sensation requiring heat shedding.", "explanation": "Incorrect. The hypothalamic set point is not reset upward in primary environmental hypothermia, and the warm sensation reflects peripheral perfusion shifts rather than a febrile drive. This would be the correct answer if the patient had a destructive hypothalamic lesion producing dysautonomic temperature dysregulation." },
      { "text": "Exhaustion of vasoconstriction with sudden return of warm blood to the periphery, producing a sensation of being hot.", "explanation": "Correct. After prolonged cold stress, catecholamine stores are depleted; the previously maintained peripheral vasoconstriction abruptly fails, and a rush of warm core blood flows to the skin, making the patient feel warm or even hot. This sudden sensation drives the patient to remove clothing despite freezing ambient conditions - a recognized terminal event called paradoxical undressing." },
      { "text": "Severe hyperkalemia from cold-induced hemolysis triggering compulsive motor behavior.", "explanation": "Incorrect. Hypothermia-related hyperkalemia is a marker of cell lysis and futility (K+ >12) but does not cause stereotyped clothes-removal behavior. This would be the correct answer if asking which lab value above 12 mmol/L indicates the patient is not salvageable." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Paradoxical undressing in severe hypothermia results from catecholamine exhaustion, failure of peripheral vasoconstriction, and a sudden rush of warm blood to the skin that produces a sensation of being hot.",
    "pdfPage": 23,
    "pdfQuote": "Paradoxical undressing feels warm"
  },
  {
    "id": 15,
    "category": "Environmental Medicine: Hypothermia - Stage I Management",
    "questionText": "A 30-year-old skier returns to the lodge after a long cold day on the slopes. He is shivering vigorously, alert, and reports cold extremities; his esophageal temperature is 34 C (93 F). His clothing is damp from snow. Vitals: BP 124/78, HR 92/min and regular, RR 16/min, O2 sat 99% on room air. He has no other injuries. Which of the following is the most appropriate management plan for this patient?",
    "options": [
      { "text": "Immerse the patient in a 40 C hot tub for rapid external rewarming.", "explanation": "Incorrect. A hot bath causes peripheral vasodilation that can shunt blood away from the core and the convective currents of the water actually accelerate heat loss in this setting. This would be the correct answer in no recognized hypothermia scenario, although warm-water bath is the chosen method for frostbitten extremities (not whole-body Stage I patients)." },
      { "text": "Place an esophageal thermistor and begin warmed IV fluids and humidified warm oxygen.", "explanation": "Incorrect. Esophageal thermistors and minimally invasive active rewarming (warmed IV fluids, warmed humidified oxygen) are reserved for Stage II patients with impaired consciousness, not Stage I patients who are alert and shivering. This would be the correct answer if the patient were 30 C with impaired consciousness." },
      { "text": "Sedate the patient and intubate to facilitate gentle handling and prevent shivering-induced arrhythmias.", "explanation": "Incorrect. Sedation suppresses shivering - the most important endogenous heat-generation mechanism - and is harmful in a Stage I patient; intubation is reserved for Stage III patients who cannot protect their airway. This would be the correct answer if the patient were Stage III with unconsciousness and unable to protect his airway." },
      { "text": "Transfer urgently to an ECMO center for cardiopulmonary bypass rewarming.", "explanation": "Incorrect. ECMO/CPB is reserved for Stage III patients with malignant arrhythmias or Stage IV cardiac arrest, far beyond the needs of an alert, shivering Stage I patient. This would be the correct answer if the patient had severe hypothermia with refractory ventricular fibrillation and hemodynamic collapse." },
      { "text": "Strip wet clothing, dry the skin, place dry warm clothes, give warm sweet drinks, and encourage gentle movement in a warm environment.", "explanation": "Correct. Stage I hypothermia (core 32-35 C, alert and shivering) responds to passive external rewarming: remove wet clothing, replace with dry insulating layers, provide a warm environment, give warm sweet drinks to fuel the calorie-intensive shivering response, and encourage movement. A hot bath is specifically avoided because it can cause vasodilation and convective heat loss, paradoxically worsening cold exposure." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: Stage I hypothermia management = passive external rewarming (remove wet clothes, dry layers, warm environment, warm sweet drinks, encourage movement); AVOID hot baths because vasodilation and convection lose more heat.",
    "pdfPage": 28,
    "pdfQuote": "Stage 1 passive external rewarming"
  },
  {
    "id": 16,
    "category": "Environmental Medicine: Hypothermia - Stage II Management",
    "questionText": "A 55-year-old woman is brought to the ED after several hours of exposure. Esophageal temperature is 30 C. She is somnolent and confused but breathing spontaneously and protecting her airway; she is no longer shivering. Vitals: BP 100/64, HR 50/min, RR 12/min. ECG shows slow atrial fibrillation with Osborn waves, no malignant rhythms. The team has decided on active external rewarming plus minimally invasive techniques. Which of the following best describes the appropriate combination of minimally invasive interventions for this patient?",
    "options": [
      { "text": "Open thoracotomy with direct cardiac massage and warm mediastinal lavage.", "explanation": "Incorrect. Open thoracotomy is far beyond minimally invasive rewarming and is not part of standard hypothermia care; it would be reserved for traumatic arrest scenarios. This would be the correct answer if the patient were in penetrating chest trauma arrest, which is unrelated to environmental hypothermia care." },
      { "text": "Warmed IV fluids, warmed humidified oxygen, and warm bladder or nasogastric lavage with insulating blankets and horizontal positioning.", "explanation": "Correct. Stage II minimally invasive active rewarming includes warmed IV fluids and warmed humidified oxygen (both well tolerated) plus warm bladder or nasogastric lavage (slightly more invasive) with active external rewarming such as a bear-hugger forced-air blanket. The patient should be kept horizontal with full insulation and gentle handling to avoid triggering arrhythmias in the irritable cold myocardium." },
      { "text": "Place chest tubes for warm pleural lavage and begin venovenous ECMO.", "explanation": "Incorrect. Pleural lavage via chest tubes and ECMO are invasive rewarming techniques reserved for Stage III hypothermia with malignant rhythms or for Stage IV arrest, not for stable Stage II patients. This would be the correct answer if the patient were unconscious with refractory ventricular fibrillation requiring extracorporeal support." },
      { "text": "Begin therapeutic hypothermia at 33 C and avoid warming to prevent reperfusion arrhythmias.", "explanation": "Incorrect. Targeted temperature management at 33 C is a controversial post-arrest neuroprotection strategy and is the opposite of what is needed for accidental hypothermia, where the goal is to raise the core temperature. This would be the correct answer in no recognized accidental hypothermia scenario." },
      { "text": "Sedation, paralysis, and full-dose intravenous amiodarone to convert the rhythm.", "explanation": "Incorrect. Sedation and paralysis abolish shivering (a key endogenous heat source), and standard-dose antiarrhythmics accumulate dangerously in cold patients with slowed metabolism. This would be the correct answer if the patient were normothermic with persistent symptomatic ventricular arrhythmias unresponsive to lower interventions." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Stage II hypothermia: active external rewarming (bear hugger) + minimally invasive techniques (warmed IV fluids, warmed humidified oxygen, warm bladder/NG lavage), insulating blankets, horizontal position, gentle handling.",
    "pdfPage": 29,
    "pdfQuote": "Stage 2 minimally invasive rewarming"
  },
  {
    "id": 17,
    "category": "Environmental Medicine: Hypothermia - Stage III Management",
    "questionText": "A 50-year-old man is found unconscious outdoors after a winter night. He has a faint femoral pulse, a blood pressure of 70/40, and an esophageal temperature of 25 C. His ECG shows recurrent runs of ventricular tachycardia that have not responded to two doses of an antiarrhythmic. The receiving hospital has no ECMO capability. The team is preparing for transport and considering which interventions to provide simultaneously. Which of the following best reflects appropriate Stage III management for this patient?",
    "options": [
      { "text": "Apply intense external heating to the head to protect the brain during transport.", "explanation": "Incorrect. Applying heat to the head is specifically not recommended; the goal is to warm blood circulating through the whole body, not focally apply heat to the cranium. This would be the correct answer in no recognized hypothermia scenario." },
      { "text": "Initiate full-dose intravenous amiodarone every 5 minutes until rhythm conversion.", "explanation": "Incorrect. Antiarrhythmic drugs work poorly in the cold heart and are metabolized very slowly; accumulating doses risk overdose toxicity once the patient is rewarmed. This would be the correct answer if the patient were normothermic with refractory ventricular tachycardia in a hemodynamically unstable state." },
      { "text": "Withhold rewarming until the patient can be transported because peripheral rewarming will cause cardiac arrest.", "explanation": "Incorrect. Withholding rewarming altogether is not appropriate; the concern is unbalanced external rewarming, which is mitigated by combining external with internal rewarming during transport. This would be the correct answer if external rewarming alone were the only option, which is not the case." },
      { "text": "Transfer immediately to an ECMO/CPB center while continuing more invasive rewarming techniques such as warm pleural lavage en route.", "explanation": "Correct. Stage III patients with malignant arrhythmias unresponsive to medication preferentially go to an ECMO/CPB center, because cardiopulmonary bypass simultaneously oxygenates and warms the patient's blood. While transferring, the team continues more invasive rewarming (warm pleural lavage via chest tubes, peritoneal lavage), and external rewarming alone is avoided because peripheral vasodilation would shift blood away from the core unless internal rewarming proceeds simultaneously." },
      { "text": "Begin immediate chest compressions because of the blood pressure of 70/40 and the abnormal rhythm.", "explanation": "Incorrect. The patient still has a pulse and detectable forward flow, and chest compressions on an irritable cold myocardium can themselves precipitate ventricular fibrillation. This would be the correct answer if the patient had no pulse and confirmed absent forward flow on ultrasound." }
    ],
    "correctAnswerIndex": 3,
    "clinicalPearl": "Key takeaway: Stage III hypothermia with malignant arrhythmias preferentially goes to ECMO/CPB; if transferring, combine external rewarming with invasive internal rewarming (pleural/peritoneal lavage) to avoid afterdrop and peripheral blood shunting.",
    "pdfPage": 30,
    "pdfQuote": "ECMO center severe hypothermia"
  },
  {
    "id": 18,
    "category": "Environmental Medicine: Hypothermia - Drug Dosing",
    "questionText": "A team is caring for a 60-year-old man with severe hypothermia (core 26 C) who has refractory ventricular tachycardia. The senior clinician is considering whether to administer antiarrhythmic medication. The junior member asks whether standard normothermic dosing is appropriate. Which principle best guides drug administration in this severely hypothermic patient?",
    "options": [
      { "text": "Give standard doses every 5 minutes as usual; cold does not change drug pharmacokinetics meaningfully.", "explanation": "Incorrect. Cold dramatically slows drug metabolism, so standard repeat dosing leads to drug accumulation that is unmasked as overdose toxicity on rewarming. This would be the correct answer if the patient were normothermic with stable hepatic and renal function." },
      { "text": "Give increased doses to compensate for the cold-induced reduction in drug efficacy.", "explanation": "Incorrect. Dose escalation is explicitly contraindicated; doses should never be increased in cold patients because the slowed metabolism causes drug accumulation. This would be the correct answer in no recognized hypothermia scenario." },
      { "text": "Consider giving medications at lower doses, never higher; many antiarrhythmics work poorly in the cold and accumulate to be unmasked on rewarming.", "explanation": "Correct. Drugs work less effectively at lower core temperatures and are metabolized much more slowly, so repeated standard dosing risks accumulation that produces overdose toxicity once rewarming restores normal metabolism. The lecturer specifically said never increase the dose; consider giving at lower doses if drug therapy is necessary, although the precise dose reduction is uncertain - which is part of why ECMO/CPB transfer is preferred over pharmacologic management." },
      { "text": "Defibrillation and antiarrhythmics are equally effective at all core temperatures and should be used liberally.", "explanation": "Incorrect. Both defibrillation and antiarrhythmics are markedly less effective in severely hypothermic hearts; the lecture noted limited defibrillation attempts and at most three doses of epinephrine in Stage IV. This would be the correct answer in no recognized hypothermia scenario." },
      { "text": "Give a single test dose and observe for 24 hours before deciding on subsequent dosing.", "explanation": "Incorrect. While caution is warranted, the recommendation is not to wait 24 hours between doses; the principle is to use reduced doses and rely preferentially on ECMO/CPB. This would be the correct answer in no recognized hypothermia scenario." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: In severe hypothermia, drugs work poorly and are metabolized slowly - give LOWER doses if at all, NEVER increase, because accumulated drug will overdose the patient on rewarming.",
    "pdfPage": 31,
    "pdfQuote": "Drugs metabolized slowly when cold"
  },
  {
    "id": 19,
    "category": "Environmental Medicine: Hypothermia - Cardiac Arrest Management",
    "questionText": "A 45-year-old woman is brought to the ED after being found in a snowbank. She has no detectable pulse and no measurable blood pressure, confirmed by absent forward flow on bedside cardiac ultrasound. Her esophageal temperature is 22 C. The team initiates CPR and prepares for transfer to an ECMO center. The team leader is asked when CPR is and is not indicated in hypothermic patients and how many doses of epinephrine should be considered during initial resuscitation. Which of the following statements best reflects appropriate Stage IV management?",
    "options": [
      { "text": "CPR should begin in any hypothermic patient with heart rate below 40, regardless of pulse or blood pressure.", "explanation": "Incorrect. Bradycardia is physiologic in hypothermia and CPR on a perfusing patient risks inducing fibrillation; CPR is only for arrest. This would be the correct answer if the patient were normothermic and symptomatic from a heart rate of 30." },
      { "text": "Give unlimited doses of epinephrine until ROSC is achieved, because drug accumulation in the cold is irrelevant during arrest.", "explanation": "Incorrect. Drug accumulation in cold patients remains a concern even during arrest; the lecture specifies considering three doses of epinephrine initially, more only if the patient is responding. This would be the correct answer if the patient were normothermic with witnessed cardiac arrest under standard ACLS." },
      { "text": "Do not perform CPR at all because the cold heart cannot tolerate compressions.", "explanation": "Incorrect. CPR is in fact the only indication when there is no detectable forward flow; not doing CPR would deny the patient any chance of perfusion. This would be the correct answer if the patient still had a pulse and was perfusing organs, in which case compressions could induce fibrillation." },
      { "text": "Use aggressive external rewarming alone without invasive rewarming during transport to the ECMO center.", "explanation": "Incorrect. External rewarming alone causes peripheral vasodilation and afterdrop; if rewarming the outside, the inside must be rewarmed simultaneously with more invasive techniques during transport. This would be the correct answer if no internal rewarming options existed, which is rarely the case at facilities preparing patients for transfer." },
      { "text": "CPR is indicated only when the patient is in full cardiac arrest; consider up to three doses of epinephrine and defibrillation for ventricular fibrillation, then transfer for ECMO.", "explanation": "Correct. CPR is reserved for confirmed cardiac arrest in hypothermic patients because compressions on an irritable cold myocardium can themselves induce ventricular fibrillation. Once arrest is confirmed (no pulse, no blood pressure, ultrasound showing no forward flow), the lecture recommends considering three doses of epinephrine and defibrillation for VF, airway management, and urgent transfer to an ECMO/CPB center, with invasive peritoneal or pleural rewarming if ECMO is not available." }
    ],
    "correctAnswerIndex": 4,
    "clinicalPearl": "Key takeaway: Stage IV (hypothermic cardiac arrest): CPR only when truly arrested; consider three doses of epinephrine and defibrillation for VF; secure airway; urgent ECMO/CPB; pleural/peritoneal lavage if ECMO not available.",
    "pdfPage": 32,
    "pdfQuote": "CPR only when in cardiac arrest"
  },
  {
    "id": 20,
    "category": "Environmental Medicine: Hypothermia - Termination of Resuscitation",
    "questionText": "Four separate hypothermic patients arrive at an ED on the same winter night. Patient A has a serum potassium of 14 mmol/L. Patient B was witnessed to clutch his chest and collapse in the snow before becoming cold. Patient C has all four extremities frozen solid AND no movement of the heart on bedside ultrasound. Patient D has fixed and dilated pupils, no measurable blood pressure, no detectable pulse, and a flat ECG, but a core temperature of 24 C with the whole body NOT frozen, no preceding witnessed arrest, and a serum K+ of 6 mmol/L; a family member arrives reporting a DNR order. Which of these patients should the team continue to actively resuscitate and rewarm rather than declare dead?",
    "options": [
      { "text": "Patient A, because a potassium of 14 mmol/L reflects acidemia that can be corrected with bicarbonate.", "explanation": "Incorrect. A potassium above 12 mmol/L reflects so much cellular lysis and prolonged downtime that it is incompatible with successful resuscitation and is a recognized futility marker in hypothermic arrest. This would be the correct answer if the K+ were elevated only modestly from a different cause such as renal failure in a normothermic patient." },
      { "text": "Patient D, because the apparent signs of death (fixed pupils, no pulse, flat ECG) may be reversible at this core temperature, and the standard DNR should be overridden.", "explanation": "Correct. The principle 'no one is dead until warm and dead' applies because fixed and dilated pupils, asystole, and absent reflexes can all be reversible findings in severe hypothermia; the patient must be rewarmed before death can be declared. In addition, the lecturer specifically argued that a DNR order should be reconsidered in this scenario because hypothermic patients have a much better chance of meaningful neurologic recovery than patients in normothermic arrest, since cold reduces brain oxygen demand and is neuroprotective." },
      { "text": "Patient B, because a witnessed normothermic arrest before cooling represents a salvageable cardiac event.", "explanation": "Incorrect. A witnessed normothermic arrest (e.g., clutching the chest and collapsing) before becoming cold means a primary event such as MI caused the arrest before cooling could provide neuroprotection; the prognosis is poor and this is a recognized futility marker. This would be the correct answer if a patient had become cold first and then later developed arrest, where the cold may have been neuroprotective." },
      { "text": "Patient C, because frozen extremities can be revived with rapid warm-water immersion.", "explanation": "Incorrect. A whole body frozen solid with no cardiac motion on ultrasound represents irreversibility; only isolated frozen extremities with an unfrozen torso may still be salvageable. This would be the correct answer if only the limbs were frozen and ultrasound showed cardiac motion." },
      { "text": "Patient A, because thrombolysis can correct the underlying microvascular thrombosis driving the hyperkalemia.", "explanation": "Incorrect. Thrombolysis is used for severe frostbite microvascular thrombosis, not hypothermic hyperkalemia, which reflects extensive cellular lysis. This would be the correct answer if the question concerned severe frostbite with established distal microvascular thrombosis on angiography." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: 'No one is dead until warm and dead' - fixed pupils, asystole, and flatline EEG can be reversible in hypothermia; markers of futility include K+ >12 mmol/L, preceding witnessed normothermic arrest, drowning, whole-body frozen solid, and decapitation/decomposition. A DNR may be appropriately overridden in salvageable hypothermic arrest.",
    "pdfPage": 34,
    "pdfQuote": "No one is dead until warm and dead"
  }
];
