window.Test_L20 = [
  {
    "id": 1,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "A 30-year-old female with Myasthenia Gravis is being treated with an oral acetylcholinesterase inhibitor. Which drug is the standard maintenance therapy for this condition?",
    "options": [
      {
        "text": "Edrophonium",
        "explanation": "Incorrect. Edrophonium is ultra-short acting and was historically used for diagnosis (Tensilon test), not maintenance."
      },
      {
        "text": "Pyridostigmine",
        "explanation": "Correct. Pyridostigmine has a longer duration of action (3-6 hours) than neostigmine and is available orally, making it the first-line maintenance therapy for Myasthenia Gravis."
      },
      {
        "text": "Physostigmine",
        "explanation": "Incorrect. Physostigmine crosses the BBB and causes unnecessary CNS side effects. It is not used for MG."
      },
      {
        "text": "Donepezil",
        "explanation": "Incorrect. Used for Alzheimer's disease."
      },
      {
        "text": "Echothiophate",
        "explanation": "Incorrect. This is an irreversible organophosphate used rarely for glaucoma."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Pyridostigmine is the long-acting oral treatment of choice for Myasthenia Gravis.",
    "pdfPage": 23
  },
  {
    "id": 2,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "A child is brought to the ER after ingesting berries from a Jimson weed plant (Attrhopa belladonna). He presents with dry skin, hyperthermia, mydriasis, delirium, and tachycardia (Anticholinergic syndrome). Which drug can reverse both the peripheral and CENTRAL effects of this poisoning?",
    "options": [
      {
        "text": "Neostigmine",
        "explanation": "Incorrect. Neostigmine is a quaternary amine and cannot cross the Blood-Brain Barrier to fix the delirium."
      },
      {
        "text": "Pyridostigmine",
        "explanation": "Incorrect. Also quaternary; does not cross BBB."
      },
      {
        "text": "Physostigmine",
        "explanation": "Correct. Physostigmine is a Tertiary amine (uncharged) that can cross the Blood-Brain Barrier. It effectively reverses both central (delirium) and peripheral antimuscarinic toxicity."
      },
      {
        "text": "Pralidoxime",
        "explanation": "Incorrect. This is used for organophosphate poisoning."
      },
      {
        "text": "Atropine",
        "explanation": "Incorrect. This would worsen the condition."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Physostigmine crosses the BBB and treats Anticholinergic toxicity (Atropine overdose). 'Physostigmine fixes Atropine'.",
    "pdfPage": 20
  },
  {
    "id": 3,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Organophosphates (like Sarin gas or Parathion) are dangerous because they bind to acetylcholinesterase and undergo a process called 'aging', which renders the enzyme inhibition:",
    "options": [
      {
        "text": "Reversible",
        "explanation": "Incorrect."
      },
      {
        "text": "Competitive",
        "explanation": "Incorrect."
      },
      {
        "text": "Irreversible",
        "explanation": "Correct. Aging involves the loss of an alkyl group from the phosphorylated enzyme, stabilizing the bond so that it cannot be hydrolyzed or regenerated by oximes like Pralidoxime. This makes the inhibition irreversible."
      },
      {
        "text": "Short-acting",
        "explanation": "Incorrect."
      },
      {
        "text": "Allosteric",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: 'Aging' of the organophosphate-enzyme complex makes the inhibition irreversible.",
    "pdfPage": 35
  },
  {
    "id": 4,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Donepezil (Aricept) is used in the management of Alzheimer's disease. Its mechanism of action is:",
    "options": [
      {
        "text": "Direct muscarinic agonist",
        "explanation": "Incorrect."
      },
      {
        "text": "NMDA receptor antagonist",
        "explanation": "Incorrect. This is Memantine."
      },
      {
        "text": "Reversible inhibition of central acetylcholinesterase",
        "explanation": "Correct. Donepezil is a lipid-soluble, reversible inhibitor of AChE that crosses the BBB to increase cholinergic transmission in the CNS, improving cognitive function."
      },
      {
        "text": "Irreversible inhibition of acetylcholinesterase",
        "explanation": "Incorrect."
      },
      {
        "text": "Inhibition of butyrylcholinesterase only",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Donepezil is a centrally acting AChE inhibitor for Alzheimer's.",
    "pdfPage": 19
  },
  {
    "id": 5,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "A patient undergoing surgery receives Rocuronium (a non-depolarizing neuromuscular blocker). At the end of the case, the anesthesiologist administers Neostigmine. What is the purpose of the Neostigmine?",
    "options": [
      {
        "text": "To sedate the patient",
        "explanation": "Incorrect."
      },
      {
        "text": "To increase Acetylcholine at the NMJ and compete away the blocker",
        "explanation": "Correct. Neostigmine inhibits AChE, increasing the concentration of ACh at the neuromuscular junction. This accumulated ACh competes with the non-depolarizing blocker (Rocuronium) for the Nicotinic (Nm) receptors, reversing the paralysis."
      },
      {
        "text": "To directly degrade the Rocuronium",
        "explanation": "Incorrect. Sugammadex encapsulates rocuronium, but Neostigmine does not degrade it."
      },
      {
        "text": "To block muscarinic receptors",
        "explanation": "Incorrect. Neostigmine INCREASES muscarinic activity (causing bradycardia), which is why it is often co-administered with Glycopyrrolate or Atropine to prevent side effects."
      },
      {
        "text": "To induce amnesia",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Neostigmine reverses neuromuscular blockade by increasing ACh at the NMJ.",
    "pdfPage": 23
  },
  {
    "id": 6,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Which drug is a short-acting AChE inhibitor historically used in the 'Tensilon test' to diagnose Myasthenia Gravis?",
    "options": [
      {
        "text": "Edrophonium",
        "explanation": "Correct. Edrophonium is a simple quaternary structur with a very short duration of action (5-10 mins). Improvement in muscle strength upon injection supports a diagnosis of MG (though this test is rarely used now due to cardiac risks and better alternatives)."
      },
      {
        "text": "Echothiophate",
        "explanation": "Incorrect."
      },
      {
        "text": "Donepezil",
        "explanation": "Incorrect."
      },
      {
        "text": "Pralidoxime",
        "explanation": "Incorrect."
      },
      {
        "text": "Succinylcholine",
        "explanation": "Incorrect. This is a depolarizing blocker."
      }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: Edrophonium is short-acting and was used for the Tensilon test.",
    "pdfPage": 20
  },
  {
    "id": 7,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Pralidoxime (2-PAM) works as an antidote for organophosphate poisoning by:",
    "options": [
      {
        "text": "Blocking muscarinic receptors",
        "explanation": "Incorrect. That is Atropine's job."
      },
      {
        "text": "Regenerating the acetylcholinesterase enzyme",
        "explanation": "Correct. Pralidoxime binds to the organophosphate-inhibited enzyme and displaces the phosphate group, regenerating the active enzyme. It is effective only BEFORE 'aging' occurs."
      },
      {
        "text": "Inhibiting acetylcholine release",
        "explanation": "Incorrect."
      },
      {
        "text": "Rapidly degrading acetylcholine",
        "explanation": "Incorrect."
      },
      {
        "text": "Binding to the organophosphate in the plasma",
        "explanation": "Incorrect. It acts at the enzyme active site."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Pralidoxime regenerates AChE if given before aging occurs.",
    "pdfPage": 35
  },
  {
    "id": 8,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "A farmer is brought to the ER with pinpoint pupils (miosis), sweating, drooling, wheezing, and bradycardia. He was spraying crops. The most likely toxic agent is:",
    "options": [
      {
        "text": "Atropine",
        "explanation": "Incorrect. Causes dry skin, mydriasis, tachycardia."
      },
      {
        "text": "Parathion (Organophosphate)",
        "explanation": "Correct. Parathion is an organophosphate insecticide. Poisoning causes a Cholinergic Crisis (DUMBBELSS: Diarrhea, Urination, Miosis, Bradycardia, Bronchospasm, Emesis, Lacrimation, Salivation, Sweating)."
      },
      {
        "text": "Botulinum toxin",
        "explanation": "Incorrect. Causes flaccid paralysis and dry mouth."
      },
      {
        "text": "Cocaine",
        "explanation": "Incorrect. Sympathomimetic."
      },
      {
        "text": "Carbon monoxide",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Organophosphate poisoning causes massive cholinergic excess (Muscarinic + Nicotinic).",
    "pdfPage": 11
  },
  {
    "id": 9,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Why is Neostigmine NOT useful for treating central anticholinergic toxicity (e.g., delirium from atropine)?",
    "options": [
      {
        "text": "It is an unrelated drug class",
        "explanation": "Incorrect."
      },
      {
        "text": "It is a quaternary amine and cannot cross the BBB",
        "explanation": "Correct. Being charged, Neostigmine stays in the periphery. It cannot treat the central nervous system effects of toxicity."
      },
      {
        "text": "It has no effect on muscarinic receptors",
        "explanation": "Incorrect."
      },
      {
        "text": "It is rapidly degraded by plasma esterases",
        "explanation": "Incorrect."
      },
      {
        "text": "It causes seizures",
        "explanation": "Incorrect. Physostigmine can cause seizures if given too rapidly, but Neostigmine simply doesn't get there."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Quaternary amines (Neostigmine, Pyridostigmine) do not cross the BBB.",
    "pdfPage": 20
  },
  {
    "id": 10,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Rivastigmine is unique among the Alzheimer's drugs because:",
    "options": [
      {
        "text": "It is an organophosphate",
        "explanation": "Incorrect."
      },
      {
        "text": "It is a 'pseudo-irreversible' carbamate inhibitor",
        "explanation": "Correct. Rivastigmine has a carbamyl group (like Neostigmine) leading to a slower dissociation/longer inhibition compared to the non-competitive inhibition of Donepezil."
      },
      {
        "text": "It does not cross the BBB",
        "explanation": "Incorrect. It must cross to work for Alzheimer's."
      },
      {
        "text": "It is injected only",
        "explanation": "Incorrect. It is oral or patch."
      },
      {
        "text": "It blocks nicotinic receptors",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Rivastigmine is a carbamate (long-acting 'pseudo-irreversible') AChE inhibitor.",
    "pdfPage": 19
  },
  {
    "id": 11,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "In the treatment of Myasthenia Gravis, excessive dosing of pyridostigmine can lead to a 'Cholinergic Crisis', characterized by muscle weakness. This weakness is due to:",
    "options": [
      {
        "text": "Blockade of nicotinic receptors by the drug",
        "explanation": "Incorrect."
      },
      {
        "text": "Depolarizing blockade (Desensitization) of Nicotinic receptors",
        "explanation": "Correct. Excessive ACh at the NMJ causes persistent depolarization, leading to Na+ channel inactivation and receptor desensitization. This results in flaccid paralysis (weakness), similar to Succinylcholine."
      },
      {
        "text": "Downregulation of Muscarinic receptors",
        "explanation": "Incorrect."
      },
      {
        "text": "Fatigue of the muscle fibers",
        "explanation": "Incorrect."
      },
      {
        "text": "Autoantibody production",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Cholinergic Crisis causes weakness via Depolarizing Blockade (Desensitization) of Nicotinic receptors.",
    "pdfPage": 22
  },
  {
    "id": 12,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Echothiophate is an organophosphate that is used therapeutically for:",
    "options": [
      {
        "text": "Myasthenia Gravis",
        "explanation": "Incorrect."
      },
      {
        "text": "Glaucoma",
        "explanation": "Correct. Echothiophate is a long-acting irreversible inhibitor used as a last resort for chronic open-angle glaucoma (drops). It causes miosis and increases outflow."
      },
      {
        "text": "Alzheimer's",
        "explanation": "Incorrect."
      },
      {
        "text": "Urinary Retention",
        "explanation": "Incorrect."
      },
      {
        "text": "Asthma",
        "explanation": "Incorrect. Contraindicated."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Echothiophate is a therapeutic organophosphate for Glaucoma.",
    "pdfPage": 16
  },
  {
    "id": 13,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "The carbamyl group on Neostigmine binds to which site on the Acetylcholinesterase enzyme?",
    "options": [
      {
        "text": "The Anionic site",
        "explanation": "Incorrect. The quaternary ammonium binds here."
      },
      {
        "text": "The Esteratic site (Serine hydroxyl)",
        "explanation": "Correct. The carbamyl group binds covalently to the serine hydroxyl at the esteratic site, preventing acetylcholine from binding and being hydrolyzed. This bond hydrolyzes slowly (hours)."
      },
      {
        "text": "The Allosteric site",
        "explanation": "Incorrect."
      },
      {
        "text": "The Lipid bilayer",
        "explanation": "Incorrect."
      },
      {
        "text": "The Calcium channel",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Carbamates bind to the Esteratic site of AChE.",
    "pdfPage": 18
  },
  {
    "id": 14,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "Galantamine, used for Alzheimer's, has a dual mechanism. In addition to inhibiting AChE, it also:",
    "options": [
      {
        "text": "Blocks NMDA receptors",
        "explanation": "Incorrect."
      },
      {
        "text": "Allosterically modulates Nicotinic receptors",
        "explanation": "Correct. Galantamine acts as a Positive Allosteric Modulator (PAM) at presynaptic nicotinic receptors, enhancing Acetylcholine release."
      },
      {
        "text": "Stimulates release of Dopamine",
        "explanation": "Incorrect."
      },
      {
        "text": "Inhibits serotonin reuptake",
        "explanation": "Incorrect."
      },
      {
        "text": "Blocks Beta receptors",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Galantamine modulates nicotinic receptors + inhibits AChE.",
    "pdfPage": 9
  },
  {
    "id": 15,
    "category": "Pharmacology: Indirect Acting Cholinomimetics",
    "questionText": "A patient with glaucoma is being treated with an AChE inhibitor. They report difficulty seeing constantly at night. This is likely due to:",
    "options": [
      {
        "text": "Cataract formation",
        "explanation": "Incorrect (though Echothiophate can cause cataracts long term, the immediate complaint is usually vision related)."
      },
      {
        "text": "Fixed Miosis",
        "explanation": "Correct. The drug causes persistent constriction of the pupil (pinpoint). This prevents the pupil from dilating in low light, significantly reducing the amount of light entering the eye (Night blindness)."
      },
      {
        "text": "Retinal detachment",
        "explanation": "Incorrect."
      },
      {
        "text": "Corneal abrasion",
        "explanation": "Incorrect."
      },
      {
        "text": "Dry eye",
        "explanation": "Incorrect."
      }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Miotics cause poor night vision because the pupil cannot dilate.",
    "pdfPage": 11
  }
];
