// Thinking Process (Part 2 — strictly 2nd/3rd-order vignettes per v5 prompt):
// 1. High-Yield Concept: Application/diagnosis/management of HL subtypes, NHL by translocation/marker, plasma cell neoplasms (MM, Waldenstrom, MGUS), and treatment-emergent issues (TLS, CRS, R-CHOP cardiotoxicity).
// 2. The "Trap": Mistaking PMLBCL for HL or DLBCL; missing transformation of indolent to aggressive; using R-CHOP for HL or ABVD for NHL; missing tumor lysis in Burkitt; confusing MGUS with smoldering myeloma vs symptomatic MM.
// 3. Key Distractor: Many lymphomas overlap clinically — use translocations + immunophenotype + clinical context (age, geography, autoimmune disease, organ) to pick the right answer.
// 4. Vignette Strategy: Full demographics + clinical features + biopsy/flow/cytogenetics + force selection of correct chemo regimen, next diagnostic step, or recognition of treatment complication.
//
// PDF Mapping Check: Found
// PDF Filename: Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf
// Mapping Key: 17-Hematology: Lymphomas - Vignettes (L155 Part 2)
// Status: Verified

const Test_L155_Part2 = [
  {
    "id": 1,
    "category": "Hematology: HL Advanced Stage Treatment",
    "questionText": "A 32-year-old woman with newly diagnosed classical Hodgkin lymphoma (nodular sclerosing subtype) is staged. She has cervical, mediastinal (with bulky mass >10 cm), and para-aortic lymphadenopathy plus drenching night sweats and 9 kg weight loss in 4 months. PET/CT: FDG-avid disease in cervical, mediastinal, abdominal, and bone marrow regions (stage IVB). Echocardiogram EF 65%, PFTs normal. Which is the most appropriate first-line treatment regimen?",
    "options": [
      { "text": "Single-agent rituximab for 4 cycles", "explanation": "Incorrect. Classical Hodgkin lymphoma Reed-Sternberg cells are typically CD20-NEGATIVE (or only weakly positive), so rituximab is not standard for classical HL. Rituximab IS used in NLPHL (CD20+). For classical HL, ABVD or A-AVD is standard. This would be the correct answer in NLPHL." },
      { "text": "BV-AVD (brentuximab vedotin + doxorubicin + vinblastine + dacarbazine) for advanced-stage disease (preferred over ABVD per ECHELON-1)", "explanation": "Correct. Modern first-line therapy for ADVANCED-STAGE (stage III-IV) classical Hodgkin lymphoma has evolved beyond the historic ABVD: (1) BV-AVD (or 'A-AVD') REPLACES bleomycin with BRENTUXIMAB VEDOTIN (anti-CD30 antibody-drug conjugate) in the front-line setting for stage III-IV classical HL, based on the ECHELON-1 trial showing improved progression-free survival vs ABVD. Eliminates bleomycin (avoids bleomycin lung toxicity, especially with concurrent G-CSF, an issue with ABVD). (2) ABVD (doxorubicin, bleomycin, vinblastine, dacarbazine) remains a standard alternative, particularly in early-stage disease and when BV cost/access is limited. Beware bleomycin pulmonary toxicity (PFTs before and during). (3) ESCALATED BEACOPP can be used in selected advanced-stage cases (higher toxicity but historically better PFS); response-adapted therapy based on interim PET. (4) INVOLVED-SITE RADIATION THERAPY (ISRT) for bulky disease (mediastinal mass >10 cm, this patient's case) after chemotherapy. (5) For RELAPSED/REFRACTORY classical HL: BRENTUXIMAB VEDOTIN, NIVOLUMAB or PEMBROLIZUMAB (anti-PD-1 mAbs — classical HL is highly responsive to checkpoint inhibitors because the RS cells have copy gains of 9p24.1 encoding PD-L1/PD-L2), autologous SCT in fit patients. PRE-TREATMENT: echocardiogram (anthracycline EF), PFTs (bleomycin if used), fertility preservation (chemotherapy can cause infertility, especially with BEACOPP). LATE EFFECTS to discuss: secondary malignancies (especially breast cancer after thoracic radiation in young women — annual screening starts 8-10 years post-radiation), cardiac disease (anthracycline + radiation), thyroid dysfunction (neck radiation), infertility." },
      { "text": "R-CHOP (rituximab + cyclophosphamide + doxorubicin + vincristine + prednisone) for 6 cycles", "explanation": "Incorrect. R-CHOP is first-line for DIFFUSE LARGE B-CELL LYMPHOMA (DLBCL), not classical Hodgkin lymphoma. Rituximab targets CD20, which is not strongly expressed on classical HL RS cells. This would be the correct answer in DLBCL." },
      { "text": "DA-EPOCH-R (dose-adjusted etoposide + prednisone + vincristine + cyclophosphamide + doxorubicin + rituximab) for 6 cycles", "explanation": "Incorrect. DA-EPOCH-R is used for DOUBLE-HIT/TRIPLE-HIT high-grade B-cell lymphomas, primary mediastinal large B-cell lymphoma, Burkitt lymphoma — not classical HL. This would be the correct answer in those aggressive B-cell NHLs." },
      { "text": "Watchful waiting with PET monitoring every 6 months", "explanation": "Incorrect. Symptomatic advanced-stage HL with B symptoms is rapidly progressive without treatment. Watchful waiting is appropriate ONLY for indolent lymphomas without active disease. This would be the correct answer in early indolent NHL like follicular without GELF criteria." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Advanced classical HL = BV-AVD (brentuximab + AVD, ECHELON-1 trial) replacing ABVD in many centers. ISRT for bulky disease. Relapsed: BV, nivolumab/pembrolizumab (PD-L1 gain on RS cells), auto-SCT.",
    "pdfPage": 4,
    "pdfQuote": "nodular sclerosis"
  },
  {
    "id": 2,
    "category": "Hematology: Follicular Lymphoma Watch and Wait",
    "questionText": "A 58-year-old man is found to have asymptomatic cervical, axillary, and inguinal lymphadenopathy on routine physical exam. Excisional cervical node biopsy shows FOLLICULAR LYMPHOMA grade 1-2 (low grade), with t(14;18) BCL-2 confirmed by FISH. He is asymptomatic, no B symptoms, no organomegaly, normal CBC and metabolic panel. LDH normal, beta-2-microglobulin normal. PET/CT shows multiple FDG-avid nodes (highest SUV 5.5, not bulky, no single mass >7 cm, no compressive symptoms). Which is the most appropriate management?",
    "options": [
      { "text": "R-CHOP chemotherapy for 6 cycles immediately as standard for all NHL", "explanation": "Incorrect. R-CHOP is for DLBCL and other AGGRESSIVE NHL — for ASYMPTOMATIC LOW-TUMOR-BURDEN follicular lymphoma, immediate treatment does NOT improve survival vs watchful waiting. Treating asymptomatic indolent FL exposes the patient to chemotherapy toxicity without benefit. This would be the correct answer in DLBCL or symptomatic bulky follicular lymphoma with GELF criteria." },
      { "text": "Watchful waiting until GELF/symptomatic indications met", "explanation": "Correct. Defer treatment until GELF/symptomatic indications: (1) bulky disease (single mass >7 cm or 3+ nodes >3 cm), (2) compressive symptoms or organ dysfunction, (3) B symptoms, (4) significant cytopenias from marrow involvement, (5) rapidly progressive disease, (6) elevated LDH or beta-2-microglobulin. FOLLICULAR LYMPHOMA is the prototypical INDOLENT B-cell NHL — generally INCURABLE but SLOWLY PROGRESSIVE, often with patients living 15-20+ years. Multiple randomized trials have demonstrated that early treatment of ASYMPTOMATIC LOW-BURDEN FL does NOT improve survival compared with WATCHFUL WAITING ('active surveillance'). The GELF (Groupe d'Etude des Lymphomes Folliculaires) criteria help identify patients who need treatment: (1) BULKY DISEASE (single nodal mass >7 cm, or 3+ nodes each >3 cm); (2) symptomatic SPLENOMEGALY; (3) COMPRESSIVE SYMPTOMS or organ dysfunction; (4) PLEURAL/PERITONEAL EFFUSION; (5) B SYMPTOMS; (6) SIGNIFICANT CYTOPENIAS from marrow involvement; (7) leukemic phase with circulating cells >5K; (8) elevated LDH or beta-2-microglobulin. This patient has LOW-BURDEN ASYMPTOMATIC disease (no bulk, no B symptoms, normal labs) → watchful waiting is the best initial approach. WHEN TREATMENT IS INDICATED: (1) R-CHOP for advanced or high-grade FL; (2) BR (bendamustine + rituximab) — common alternative; (3) RITUXIMAB monotherapy for low-tumor-burden symptomatic disease; (4) R-CVP for some patients; (5) OBINUTUZUMAB-based regimens; (6) MAINTENANCE rituximab for 2 years after induction (improves PFS); (7) RADIATION for localized stage I-II FL (potentially curative in early-stage). RELAPSED/REFRACTORY options: lenalidomide + rituximab (R-squared), idelalisib (PI3K inhibitor), CD19 CAR-T (axicabtagene, lisocabtagene), epcoritamab (CD20xCD3 bispecific), tazemetostat (EZH2 inhibitor in EZH2-mutant), allogeneic SCT in selected cases. TRANSFORMATION to DLBCL occurs in ~3% per year (Richter-like) — suspect with rapidly enlarging nodes, B symptoms, rising LDH." },
      { "text": "Allogeneic stem cell transplant in first remission", "explanation": "Incorrect. Allogeneic SCT is too aggressive for asymptomatic indolent FL with very long natural history. It is considered for transformed FL or multiply relapsed disease in young fit patients with matched donors. This would be the correct answer in young patient with multiply relapsed transformed FL." },
      { "text": "CD19 CAR-T therapy immediately as standard first-line", "explanation": "Incorrect. CAR-T (axicabtagene, lisocabtagene) is FDA-approved for relapsed/refractory FL after 2+ prior lines of therapy, not first-line. Toxicity (CRS, ICANS) makes it inappropriate for asymptomatic indolent disease. This would be the correct answer for multiply relapsed FL." },
      { "text": "Single-agent ibrutinib for life", "explanation": "Incorrect. Ibrutinib has activity in some B-cell malignancies (CLL, MCL, Waldenstrom, MZL) but is not standard for FL. Even in MCL/CLL, ibrutinib is not used in asymptomatic disease. This would be the correct answer in symptomatic CLL or MCL requiring treatment." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Asymptomatic low-burden follicular lymphoma = WATCHFUL WAITING (no survival benefit from early tx). Treat when GELF criteria met: bulky (>7cm), symptomatic, B symptoms, cytopenias, rapid progression, elevated LDH/B2M. R-CHOP or BR when needed.",
    "pdfPage": 5,
    "pdfQuote": "follicular"
  },
  {
    "id": 3,
    "category": "Hematology: Burkitt DA-EPOCH-R",
    "questionText": "A 28-year-old HIV-positive man (CD4 380, on ART, viral load undetectable) presents with abdominal pain and a rapidly enlarging right lower quadrant mass over 4 weeks. Vitals: T 38.0°C, HR 98, BP 120/78. Exam: 8 cm RLQ mass, no hepatosplenomegaly. CT: mesenteric mass + multiple involved nodes. Biopsy: sheets of medium-sized monomorphic B cells with 'starry sky', Ki-67 nearly 100%, c-MYC translocation [t(8;14)] by FISH. Labs: LDH 8,500 (markedly elevated), uric acid 12, K 4.8, phosphorus 5.5, creatinine 1.0, calcium 9.0. Which is the most appropriate INITIAL management?",
    "options": [
      { "text": "R-CHOP for 6 cycles with intrathecal MTX prophylaxis", "explanation": "Incorrect. R-CHOP is INADEQUATE for Burkitt lymphoma — Burkitt's extremely high proliferation rate requires more intensive dose-dense regimens. R-CHOP is first-line for DLBCL but inferior for Burkitt. This would be the correct answer in DLBCL." },
      { "text": "TLS prophylaxis + DA-EPOCH-R + intrathecal MTX", "explanation": "Correct. Aggressive TLS prophylaxis (IV hydration + RASBURICASE) followed by intensive chemotherapy: DA-EPOCH-R (dose-adjusted etoposide + prednisone + vincristine + cyclophosphamide + doxorubicin + rituximab) OR CODOX-M/IVAC (combination regimens) with intrathecal MTX for CNS prophylaxis; continue ART in HIV-positive patients. BURKITT LYMPHOMA is the most aggressive lymphoma, with the highest proliferation rate (Ki-67 ~100%), highest tumor lysis risk, and short doubling time. Three variants: ENDEMIC (African jaw, EBV+), SPORADIC (abdominal/ileocecal mass, sometimes EBV+), IMMUNODEFICIENCY (HIV-associated, this patient). MANAGEMENT PRIORITIES: (1) URGENT TLS PROPHYLAXIS — IV hydration + RASBURICASE BEFORE chemotherapy (LDH 8,500 + uric acid 12 + bulky disease = VERY HIGH TLS risk); rasburicase if uric acid elevated and no G6PD deficiency; close monitoring of K+, phos, Ca, creat every 4-6 hours during cytoreduction. (2) INTENSIVE CHEMOTHERAPY (Burkitt requires dose-intensive treatment): DA-EPOCH-R (dose-adjusted etoposide, prednisone, vincristine, cyclophosphamide, doxorubicin, rituximab) — generally well-tolerated, increasingly preferred; alternative high-intensity regimens include CODOX-M/IVAC (cyclophosphamide, vincristine, doxorubicin, methotrexate / ifosfamide, etoposide, cytarabine) — Magrath regimen, hyperCVAD. (3) CNS PROPHYLAXIS is critical (Burkitt has high CNS relapse risk): intrathecal methotrexate ± cytarabine; some regimens include high-dose systemic methotrexate. (4) HIV PATIENTS: continue/optimize ART concurrently with chemotherapy (HAART-era outcomes for HIV-related Burkitt approach those of non-HIV patients). (5) AUTOLOGOUS SCT in first CR not typically needed for Burkitt (it is highly chemo-sensitive, with cure rates >80% in standard-risk adult/pediatric Burkitt). (6) Workup includes lumbar puncture for CNS staging, bone marrow biopsy, echocardiogram (anthracycline), HIV viral load + CD4 in HIV+ patients. Cure rates: pediatric Burkitt >90%, adult Burkitt with intensive therapy 60-80%, HIV-associated with concurrent ART approaching non-HIV outcomes." },
      { "text": "Watchful waiting since the patient is asymptomatic", "explanation": "Incorrect. Burkitt is the fastest-growing human tumor and is symptomatic and rapidly progressive — observation would be rapidly fatal. This would be the correct answer NEVER in Burkitt." },
      { "text": "Allogeneic stem cell transplant immediately without induction chemotherapy", "explanation": "Incorrect. SCT requires complete remission first; cytoreduction with chemotherapy is needed before SCT consideration. Also, Burkitt is highly chemo-curable with intensive regimens without SCT in most patients. This would be the correct answer in refractory/relapsed Burkitt after multiple lines, in a young fit patient." },
      { "text": "ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is for APL (M3 AML with t(15;17) PML-RARA) — NOT Burkitt lymphoma. This would be the correct answer in APL." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Burkitt = aggressive intensive chemo (DA-EPOCH-R or CODOX-M/IVAC) + intrathecal CNS prophylaxis + AGGRESSIVE TLS PROPHYLAXIS (hydration + rasburicase). Continue ART in HIV+. Cure rates 60-90% with intensive therapy.",
    "pdfPage": 5,
    "pdfQuote": "Burkitt"
  },
  {
    "id": 4,
    "category": "Hematology: Mantle Cell Lymphoma Aggressive",
    "questionText": "A 64-year-old man presents with widespread painless lymphadenopathy over 6 months and recent night sweats. Vitals: BP 132/76, HR 80. Exam: diffuse cervical, axillary, and inguinal adenopathy; spleen palpable 4 cm below costal margin. Labs: WBC 22,000 (60% lymphocytes, leukemic phase), Hgb 11.0, platelets 130K, LDH elevated. Flow cytometry of peripheral blood: CD5+ CD19+ CD20+ CD23-NEGATIVE, surface Ig kappa-restricted, FMC7+. Bone marrow biopsy shows interstitial and nodular infiltrate; cyclin D1 IHC POSITIVE, SOX11+. FISH: t(11;14) confirmed. Endoscopy: lymphomatous polyposis of the GI tract. Which is the most appropriate first-line therapy for a fit patient?",
    "options": [
      { "text": "Watchful waiting since mantle cell lymphoma is generally indolent", "explanation": "Incorrect. Mantle cell lymphoma is GENERALLY AGGRESSIVE, NOT indolent. There IS a small subset with indolent biology (leukemic non-nodal MCL with SOX11- negative status), but MCL traditionally has poor prognosis and requires treatment. The patient is symptomatic. This would be the correct answer ONLY in the rare indolent SOX11-negative non-nodal leukemic MCL variant with no symptoms." },
      { "text": "Cytarabine-based induction + autologous SCT + rituximab", "explanation": "Correct. Intensive induction with cytarabine-containing chemoimmunotherapy (e.g., R-DHAP alternating with R-CHOP, or Nordic MCL regimen with R-maxi-CHOP + high-dose cytarabine) → consolidation with HIGH-DOSE CHEMOTHERAPY + AUTOLOGOUS STEM CELL TRANSPLANT in first complete remission → rituximab maintenance; alternatively for less fit: BR (bendamustine + rituximab) ± maintenance; emerging: covalent BTK inhibitors (acalabrutinib, zanubrutinib) or BTK + venetoclax + rituximab as chemo-free options. MANTLE CELL LYMPHOMA (MCL) is an aggressive B-cell NHL with historically poor prognosis (median survival 3-5 years before modern therapy). Defined by t(11;14) cyclin D1 + CD5+CD19+CD20+CD23-NEGATIVE. Common presentations: widespread nodal disease with extra-nodal involvement (GI tract — 'lymphomatous polyposis,' bone marrow, leukemic phase, splenomegaly). FIRST-LINE THERAPY in FIT PATIENTS: (1) INTENSIVE INDUCTION with cytarabine-containing chemoimmunotherapy — Nordic MCL2 regimen (alternating R-maxi-CHOP and R-high-dose cytarabine) OR Hyper-CVAD/MA OR alternating R-CHOP/R-DHAP — produces high response rates including MRD negativity. (2) CONSOLIDATION with HIGH-DOSE CHEMOTHERAPY + AUTOLOGOUS STEM CELL TRANSPLANT in first complete remission — improves PFS and OS (LyMa trial). Now being challenged by newer BTK-based regimens. (3) RITUXIMAB MAINTENANCE for 3 years post-ASCT — improves OS. FIRST-LINE in LESS-FIT/OLDER patients: (1) BR (bendamustine + rituximab) ± rituximab maintenance; (2) VR-CAP (bortezomib + R-CAP); (3) Chemo-free option: ACALABRUTINIB + VENETOCLAX + RITUXIMAB or IBRUTINIB-based regimens. RELAPSED/REFRACTORY MCL: (1) BTK INHIBITORS (acalabrutinib, zanubrutinib, ibrutinib) — first-line in relapse historically; (2) VENETOCLAX (BCL-2 inhibitor); (3) BREXUCABTAGENE AUTOLEUCEL (CD19 CAR-T, ZUMA-2 trial) — FDA-approved for relapsed MCL after BTK failure; (4) Allogeneic SCT in young fit patients with chemo-sensitive disease. POOR PROGNOSTIC FEATURES: blastoid morphology, TP53 mutation, high Ki-67, MIPI score. The lymphomatous polyposis pattern of GI involvement is classic for MCL." },
      { "text": "R-CHOP for 6 cycles as the same regimen used for DLBCL", "explanation": "Incorrect. R-CHOP alone is INADEQUATE for fit MCL patients — historical R-CHOP gives only 2-3 year median PFS in MCL. Intensified cytarabine-containing regimens with autologous SCT consolidation significantly improve outcomes in fit patients. R-CHOP alone is acceptable only in older/unfit patients who cannot tolerate intensive therapy. This would be the correct answer in older unfit patients without other options, or in DLBCL." },
      { "text": "Single-agent rituximab maintenance for 5 years", "explanation": "Incorrect. Single-agent rituximab is inadequate as initial therapy for aggressive MCL — combination chemoimmunotherapy with intensive consolidation is needed. Rituximab maintenance is given AFTER induction/consolidation to maintain remission. This would be the correct answer for low-grade indolent disease maintenance." },
      { "text": "Hydroxyurea single-agent for chronic disease control", "explanation": "Incorrect. Hydroxyurea is not used in MCL. It is used in CML, polycythemia vera, essential thrombocythemia, and sickle cell disease. This would be the correct answer in those diseases." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Aggressive MCL (fit patient) = intensive cytarabine-based induction + autologous SCT in CR1 + rituximab maintenance. Less fit: BR ± maintenance. Relapse: BTK inhibitors (acalabrutinib > ibrutinib due to safety), venetoclax, CD19 CAR-T (brexucabtagene). Lymphomatous polyposis of GI = classic MCL.",
    "pdfPage": 5,
    "pdfQuote": "mantle cell"
  },
  {
    "id": 5,
    "category": "Hematology: Gastric MALT t(11;18)",
    "questionText": "A 60-year-old man with chronic dyspepsia is found to have gastric MALT lymphoma on biopsy. H. pylori is POSITIVE. He completes 14 days of triple therapy (PPI + clarithromycin + amoxicillin) with documented eradication on repeat urea breath test. However, 6 months later, repeat endoscopy shows persistent gastric MALT lymphoma. FISH on the biopsy now reveals t(11;18) (API2-MALT1) translocation. Which is the most appropriate NEXT step?",
    "options": [
      { "text": "Repeat the same H. pylori eradication therapy", "explanation": "Incorrect. The patient has already been documented to have eradicated H. pylori (negative urea breath test). The persistent MALT lymphoma despite eradication is consistent with t(11;18) status — these patients are LESS LIKELY to respond to H. pylori eradication alone and need additional disease-directed therapy. Repeating eradication will not help. This would be the correct answer if H. pylori had not been confirmed eradicated." },
      { "text": "Involved-site radiation therapy (ISRT) to the stomach, or single-agent rituximab", "explanation": "Correct. Most gastric MALT lymphomas are H. PYLORI-DRIVEN and regress with eradication therapy in 60-80% of localized stage IE/IIE cases WITHOUT the t(11;18) translocation. However, MALT lymphomas with the t(11;18) (API2-MALT1) translocation are: (1) LESS LIKELY to respond to H. pylori eradication alone (~20% response); (2) ASSOCIATED with H. pylori-NEGATIVE disease in some cases; (3) MORE LIKELY to disseminate beyond the stomach. For MALT lymphoma that does NOT respond to H. pylori eradication (regardless of t(11;18) status), or for H. pylori-NEGATIVE MALT, or for t(11;18)-POSITIVE disease: (a) LOCALIZED disease (stage IE/IIE) → involved-site radiation therapy (ISRT) is the standard, with high cure rates (>90%); (b) ADVANCED/DISSEMINATED disease (stage III-IV) → systemic therapy with single-agent rituximab, or combination chemoimmunotherapy (R-CHOP, R-CVP, R-bendamustine), or rituximab + chlorambucil (R-CL, IELSG-19 trial); (c) EXTENSIVE SURGERY is generally AVOIDED in gastric MALT (preserves gastric function); selected for emergency complications. KEY DECISION TREE for early gastric MALT: H. PYLORI POSITIVE + NO t(11;18) → eradicate H. pylori first → if regression, observe; if no regression → radiation; H. PYLORI POSITIVE + t(11;18) POSITIVE → eradicate H. pylori (still beneficial for gastritis even if lymphoma doesn't respond) → radiation as primary lymphoma therapy; H. PYLORI NEGATIVE → consider other infections (Achromobacter, Pseudomonas) → radiation or systemic therapy. Other MALT lymphoma associations to recall: SJÖGREN → parotid; HASHIMOTO → thyroid; CHLAMYDIA PSITTACI → ocular adnexa; BORRELIA → skin; HEPATITIS C → splenic marginal zone (treat HCV with DAA can lead to regression)." },
      { "text": "Total gastrectomy with regional lymph node dissection", "explanation": "Incorrect. Gastric MALT lymphoma is highly responsive to local radiation or systemic therapy; total gastrectomy is unnecessarily morbid and reserved for emergency complications (perforation, refractory bleeding). This would be the correct answer in gastric adenocarcinoma." },
      { "text": "Initiate ibrutinib for life", "explanation": "Incorrect. Ibrutinib has activity in some MALT lymphomas but is not first-line — radiation or rituximab-based therapy is preferred initially. Ibrutinib may be considered in relapsed/refractory cases. This would be the correct answer in CLL, MCL, or Waldenstrom." },
      { "text": "Allogeneic stem cell transplant", "explanation": "Incorrect. MALT lymphoma is indolent and generally well-managed with local or modest systemic therapy. SCT is far too aggressive. This would be the correct answer in transformation to DLBCL with poor response to therapy in a young fit patient." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Gastric MALT + t(11;18) is LESS RESPONSIVE to H. pylori eradication alone. Treat localized failure with ISRT (radiation); advanced disease with rituximab ± chemo. Avoid extensive surgery.",
    "pdfPage": 5,
    "pdfQuote": "MALT"
  },
  {
    "id": 6,
    "category": "Hematology: Primary CNS Lymphoma HIV",
    "questionText": "A 45-year-old man with advanced AIDS (CD4 25, ART intermittently) presents with progressive headache, confusion, right-sided weakness, and visual field deficits over 6 weeks. Vitals: BP 130/80, HR 88, T 37.4°C. Exam: right hemiparesis, right homonymous hemianopsia. MRI: SINGLE 4-cm periventricular ring-enhancing lesion in left parietal lobe with surrounding edema. CSF: EBV DNA POSITIVE by PCR; toxoplasma IgG NEGATIVE. SPECT shows increased thallium uptake in the lesion (favoring lymphoma over toxoplasmosis). Which is the most appropriate management approach?",
    "options": [
      { "text": "Empiric sulfadiazine + pyrimethamine + leucovorin for presumed toxoplasmosis without further workup", "explanation": "Incorrect. While empiric anti-toxoplasmosis therapy is reasonable in HIV patients with multifocal ring-enhancing lesions and positive Toxoplasma IgG, this patient has NEGATIVE Toxoplasma IgG AND POSITIVE CSF EBV PCR — both pointing to PRIMARY CNS LYMPHOMA, not toxoplasmosis. Empirically treating toxoplasmosis would delay correct lymphoma therapy. This would be the correct answer with positive Toxo IgG + multiple lesions + EBV PCR negative." },
      { "text": "Stereotactic brain biopsy, then high-dose methotrexate-based chemotherapy with ART optimization", "explanation": "Correct. PRIMARY CNS LYMPHOMA (PCNSL) in HIV is essentially always EBV-DRIVEN DIFFUSE LARGE B-CELL LYMPHOMA confined to the brain. Pathogenesis: severely immunocompromised CD4+ T-cell control of EBV-infected B cells fails → EBV-driven B-cell proliferation in the CNS → DLBCL. Classic features distinguishing from other HIV CNS lesions: (1) SINGLE periventricular ring-enhancing lesion (vs MULTIPLE in toxoplasmosis); (2) NEGATIVE Toxoplasma IgG; (3) POSITIVE CSF EBV PCR (sensitive and highly specific in HIV PCNSL); (4) increased uptake on SPECT/PET (lymphoma cells metabolically active vs toxoplasmosis which is decreased uptake); (5) generally rapid course over weeks-months. DIAGNOSIS: stereotactic brain biopsy is gold standard (avoid STARTING STEROIDS BEFORE biopsy because steroids cause rapid tumor shrinkage and obscure the pathologic diagnosis — only give steroids after biopsy unless mass effect is life-threatening). MANAGEMENT: (1) HIGH-DOSE METHOTREXATE (3.5 g/m2 or higher) is the BACKBONE of PCNSL treatment — only drug class that crosses BBB at therapeutic concentrations; combined with leucovorin rescue, hydration, urinary alkalinization (carefully); RITUXIMAB is added (despite the question of CNS penetration, R-MPV or R-MVP regimens are standard); (2) Combination regimens: MPV (methotrexate + procarbazine + vincristine), MTR (MTX + temozolomide + rituximab), or HD-MTX + cytarabine + thiotepa + rituximab (MATRix trial) → consolidation with autologous SCT or whole-brain RT; (3) WHOLE-BRAIN RADIATION historically used but has significant neurocognitive toxicity in older patients; (4) For HIV PCNSL: AGGRESSIVE ART optimization (immune reconstitution helps long-term control); HIV-PCNSL outcomes have improved dramatically with combined HD-MTX + ART. PROGNOSIS without therapy: <2 months; with HD-MTX-based therapy: median 30-60 months." },
      { "text": "Whole-brain radiation alone as the only therapy", "explanation": "Incorrect. WBRT alone produces only short responses with significant neurocognitive toxicity. HD-MTX-based chemoimmunotherapy is now the backbone. WBRT may be used for consolidation in select patients. This would be the correct answer in palliative care for very frail patients who cannot tolerate chemotherapy." },
      { "text": "Surgical resection of the lesion for cure", "explanation": "Incorrect. PCNSL is typically multifocal microscopically even when imaging shows a single lesion; surgical resection does not improve outcomes and is reserved for diagnostic biopsy or for managing herniation from mass effect. The treatment is systemic chemo. This would be the correct answer in localized solid brain tumors like meningioma where surgery is curative." },
      { "text": "Single-agent ibrutinib monotherapy as primary treatment", "explanation": "Incorrect. Ibrutinib has some CNS penetration and activity in CD79b/MYD88-mutant ABC-type DLBCL (and PCNSL often has these mutations), but is not standard first-line for newly diagnosed PCNSL. HD-MTX-based regimens are first-line. Ibrutinib has been used in relapsed PCNSL. This would be the correct answer in relapsed PCNSL." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HIV PCNSL = EBV-driven DLBCL of brain. Clues: CD4 <50, single periventricular ring-enhancing lesion, CSF EBV+, Toxo IgG-. Treat with HD-METHOTREXATE-based chemoimmunotherapy (R-MPV or MATRix) + ART optimization. AVOID steroids before biopsy.",
    "pdfPage": 5,
    "pdfQuote": "EBV"
  },
  {
    "id": 7,
    "category": "Hematology: Sezary Brentuximab CD30+",
    "questionText": "A 64-year-old man with stage IVB mycosis fungoides progressing to Sezary syndrome has been treated with multiple lines of therapy (PUVA, extracorporeal photopheresis, bexarotene, romidepsin, mogamulizumab) over the past 5 years. He now presents with worsening erythroderma, intense pruritus, lymphadenopathy, and circulating Sezary cells. A skin biopsy is re-examined and is now STRONGLY POSITIVE for CD30 (>30% of malignant cells). Which targeted therapy specifically exploits CD30 expression?",
    "options": [
      { "text": "Mogamulizumab (anti-CCR4)", "explanation": "Incorrect. Mogamulizumab targets CCR4 and is approved for relapsed cutaneous T-cell lymphoma — the patient has already received it. This would be the correct answer when CCR4 is the target." },
      { "text": "Brentuximab vedotin — an anti-CD30 antibody-drug conjugate", "explanation": "Correct. BRENTUXIMAB VEDOTIN is an anti-CD30 monoclonal antibody conjugated to monomethyl auristatin E (MMAE, microtubule-disrupting payload). Mechanism: binds CD30 → internalized → MMAE released → cell death via microtubule disruption → apoptosis. APPROVED USES: (1) Classical Hodgkin lymphoma (front-line in advanced stage as A-AVD per ECHELON-1; relapsed disease; post-transplant maintenance); (2) Anaplastic large cell lymphoma (ALCL) — front-line in CD30+ peripheral T-cell lymphomas in BV-CHP per ECHELON-2 trial; (3) RELAPSED CD30+ CUTANEOUS T-CELL LYMPHOMAS (mycosis fungoides, Sezary syndrome with CD30+ disease, primary cutaneous ALCL, lymphomatoid papulosis) — ALCANZA trial demonstrated superiority of brentuximab over methotrexate/bexarotene in CD30+ CTCL with response rates ~67%; (4) Some other CD30+ peripheral T-cell lymphomas. KEY TOXICITY: PERIPHERAL NEUROPATHY (dose-limiting), neutropenia, infusion reactions. NOT FOR primary cutaneous T-cell lymphomas with CD30-NEGATIVE disease. Note: CD30 expression in mycosis fungoides/Sezary varies; testing is important before considering brentuximab. Other emerging therapies in CTCL: vorinostat (HDAC inhibitor), denileukin diftitox (anti-CD25 IL-2 fusion toxin), lenalidomide, allogeneic SCT for refractory cases in young fit patients." },
      { "text": "Rituximab (anti-CD20)", "explanation": "Incorrect. Rituximab targets CD20, which is a B-CELL marker. Mycosis fungoides and Sezary are T-CELL lymphomas — they do NOT express CD20 (they express CD3, CD4, often CD7-negative). Rituximab would have no effect. This would be the correct answer in B-cell lymphomas (DLBCL, FL, MCL, MZL, CLL)." },
      { "text": "Bortezomib (proteasome inhibitor)", "explanation": "Incorrect. Bortezomib is used in multiple myeloma and mantle cell lymphoma (and some other contexts). It does not specifically target CD30. This would be the correct answer in multiple myeloma." },
      { "text": "Daratumumab (anti-CD38)", "explanation": "Incorrect. Daratumumab targets CD38, primarily expressed on plasma cells — used in multiple myeloma. Not relevant to Sezary syndrome. This would be the correct answer in multiple myeloma." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Brentuximab vedotin = anti-CD30 + MMAE microtubule disruptor. Uses: classical HL, ALCL, CD30+ CTCL (mycosis fungoides/Sezary). ALCANZA trial showed efficacy in CD30+ CTCL. Watch for peripheral neuropathy.",
    "pdfPage": 4,
    "pdfQuote": "CD30"
  },
  {
    "id": 8,
    "category": "Hematology: Waldenstrom Ibrutinib First-Line",
    "questionText": "A 70-year-old man is found to have Waldenstrom macroglobulinemia. His IgM is 4,500 (markedly elevated) and he has mild fatigue and slight peripheral neuropathy but no symptomatic hyperviscosity, no transfusion-dependent anemia, no organomegaly. After 6 months of observation, he develops symptomatic anemia (Hgb 9), worsening fatigue, and B symptoms. Bone marrow shows lymphoplasmacytic infiltrate; MYD88 L265P mutation POSITIVE, CXCR4 WHIM-like mutation NEGATIVE. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Continue watchful waiting indefinitely", "explanation": "Incorrect. The patient now has SYMPTOMATIC disease (symptomatic anemia, B symptoms) — clear indication for treatment per consensus criteria. Watchful waiting is no longer appropriate. This would be the correct answer in asymptomatic Waldenstrom without indications for treatment." },
      { "text": "BTK inhibitor (ibrutinib or zanubrutinib)", "explanation": "Correct. Covalent BTK inhibitors (ibrutinib, zanubrutinib, acalabrutinib) or non-covalent pirtobrutinib as monotherapy or with rituximab — MYD88 L265P-mutant disease is highly responsive; CXCR4 WHIM mutations decrease BTK inhibitor responsiveness. Alternative first-line: rituximab + bendamustine (BR) or rituximab + cyclophosphamide/dexamethasone (RCD). WALDENSTROM MACROGLOBULINEMIA (WM) / LYMPHOPLASMACYTIC LYMPHOMA — chronic indolent B-cell NHL secreting monoclonal IgM, characterized by MYD88 L265P mutation in >90% of cases. INDICATIONS FOR TREATMENT (NOT all patients with WM need immediate therapy — many are asymptomatic and observed): (1) symptomatic hyperviscosity, (2) symptomatic anemia (Hgb <10 with related symptoms), (3) B symptoms, (4) bulky lymphadenopathy/organomegaly, (5) peripheral neuropathy from IgM antibody, (6) cryoglobulinemia, cold agglutinin disease, amyloidosis. THIS patient now has clear indications (anemia + B symptoms). FIRST-LINE OPTIONS: (1) BTK INHIBITORS — IBRUTINIB (first BTK approved for WM), ZANUBRUTINIB or ACALABRUTINIB (newer, better cardiovascular safety than ibrutinib); covalent BTKi. Monotherapy or with rituximab. (2) PIRTOBRUTINIB — non-covalent BTKi for relapsed disease and BTKi-resistant disease. (3) RITUXIMAB-BASED CHEMOTHERAPY: BR (bendamustine + rituximab) is highly effective; alternative RCD (rituximab + cyclophosphamide + dexamethasone). (4) PROTEASOME INHIBITORS: bortezomib-based regimens (e.g., BDR — bortezomib + dexamethasone + rituximab). MUTATIONAL CONSIDERATIONS: MYD88 L265P-MUTANT patients respond well to BTK inhibitors. MYD88-WILD-TYPE patients (rare in WM) respond less well to BTKi; better with chemoimmunotherapy. CXCR4 WHIM-like mutations (~30% of WM) confer relative BTKi resistance. ACUTE HYPERVISCOSITY: PLASMAPHERESIS rapidly removes IgM (intravascular distribution). Rituximab can cause an IgM 'FLARE' (transient rise) in 30-50% of patients during first 1-2 months → potentially worsening hyperviscosity → consider holding rituximab until plasmapheresis stabilizes acute hyperviscosity. RELAPSED/REFRACTORY: switching BTKi class, venetoclax, autologous SCT in select cases." },
      { "text": "ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is for APL (M3 AML with t(15;17)) — not Waldenstrom. This would be the correct answer in APL." },
      { "text": "Allogeneic SCT immediately as first-line", "explanation": "Incorrect. Allogeneic SCT is reserved for multiply relapsed Waldenstrom in young fit patients with matched donors — not first-line in an older patient. This would be the correct answer in refractory disease in a young patient." },
      { "text": "Hydroxyurea single-agent for cytoreduction", "explanation": "Incorrect. Hydroxyurea is not used in Waldenstrom. It is used in CML, PV, ET, sickle cell. This would be the correct answer in those diseases." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Waldenstrom symptomatic (anemia, B symptoms, hyperviscosity) = BTK inhibitor (acalabrutinib/zanubrutinib preferred over ibrutinib for safety; pirtobrutinib for resistance) OR BR (bendamustine + rituximab). MYD88 L265P-mutant respond well to BTKi; CXCR4 WHIM mutations resist BTKi.",
    "pdfPage": 5,
    "pdfQuote": "Waldenstrom"
  },
  {
    "id": 9,
    "category": "Hematology: Multiple Myeloma CRAB Diagnosis",
    "questionText": "A 68-year-old man presents with progressive lower back pain over 4 months that is not relieved by NSAIDs. He has had recurrent pneumonia in the past year. Vitals: BP 138/82, HR 80. Exam: tender thoracolumbar spine, no organomegaly. Labs: Hgb 9.5 (normocytic), creatinine 2.4 (baseline 0.8), calcium 11.8 (elevated), albumin 3.0, total protein 11 (markedly elevated). SPEP: monoclonal M-spike of 4.5 g/dL in gamma region (IgG kappa). Skeletal survey: multiple lytic lesions in vertebrae and ribs ('punched-out' appearance, no sclerotic rim). Bone marrow biopsy: 45% plasma cells. Which is the most appropriate diagnosis?",
    "options": [
      { "text": "Monoclonal gammopathy of undetermined significance (MGUS)", "explanation": "Incorrect. MGUS is defined by: M-spike <3 g/dL, bone marrow plasma cells <10%, AND ABSENCE of CRAB symptoms (no end-organ damage). This patient has M-spike >3 g/dL, plasma cells 45%, AND multiple CRAB criteria — far beyond MGUS. This would be the correct answer with M-spike <3, plasma cells <10%, and no symptoms." },
      { "text": "Symptomatic (active) multiple myeloma — meets CRAB criteria, requiring treatment", "explanation": "Correct. SYMPTOMATIC MULTIPLE MYELOMA (MM) is diagnosed by the IMWG criteria: clonal plasma cells in bone marrow ≥10% (or biopsy-proven plasmacytoma) PLUS at least one MYELOMA-DEFINING EVENT: (1) CRAB criteria — Hypercalcemia (Ca >11), Renal failure (creatinine >2 or CrCl <40, AL amyloidosis); Anemia (Hgb <10 or ≥2 below normal); Bone lesions (≥1 lytic lesion on imaging — skeletal survey, low-dose whole-body CT, or PET/CT); OR (2) BIOMARKERS OF MALIGNANCY (SLiM criteria): >60% clonal plasma cells in marrow, involved:uninvolved free light chain ratio ≥100, >1 focal lesion on MRI. This patient meets full criteria (45% plasma cells + hypercalcemia + renal failure + anemia + bone lesions + 4.5 g/dL M-spike). STAGING (R-ISS uses albumin, beta-2-microglobulin, LDH, cytogenetics — high-risk include del(17p), t(4;14), t(14;16), gain(1q)). INITIAL TREATMENT: (1) INDUCTION with quadruplet therapy typically including PROTEASOME INHIBITOR + IMID + ANTI-CD38 + STEROID, e.g., D-VRd (daratumumab + bortezomib + lenalidomide + dexamethasone) — increasingly the preferred first-line in transplant-eligible patients per MAIA/GRIFFIN trials; (2) HIGH-DOSE MELPHALAN + AUTOLOGOUS SCT consolidation in TRANSPLANT-ELIGIBLE PATIENTS (age <70-75, fit); (3) MAINTENANCE with lenalidomide (± daratumumab) for years. NON-TRANSPLANT-ELIGIBLE: Dara-Rd or D-VRd. SUPPORTIVE CARE: BISPHOSPHONATES (zoledronic acid) or DENOSUMAB for bone disease + skeletal-related events; vertebroplasty/kyphoplasty for compression fractures; pain control; hydration and supportive care for AKI; vaccination updates. RELAPSED/REFRACTORY: BCMA-DIRECTED therapies (idecabtagene CAR-T, ciltacabtagene CAR-T, belantamab mafodotin ADC), bispecific antibodies (teclistamab BCMA×CD3, talquetamab GPRC5D×CD3), newer proteasome inhibitors (carfilzomib, ixazomib), pomalidomide, venetoclax for t(11;14)." },
      { "text": "Smoldering multiple myeloma (asymptomatic, no CRAB)", "explanation": "Incorrect. Smoldering myeloma is intermediate between MGUS and symptomatic MM: M-spike ≥3 g/dL OR bone marrow plasma cells 10-60%, WITHOUT CRAB or other myeloma-defining events. This patient HAS CRAB → symptomatic disease, not smoldering. High-risk smoldering MM (20-50-20: 2 of 3 criteria of M-spike >2, free light chain ratio >20, marrow plasma cells >20%) may be considered for early treatment in some trials. This would be the correct answer with no CRAB or biomarkers of malignancy." },
      { "text": "Waldenstrom macroglobulinemia (lymphoplasmacytic lymphoma)", "explanation": "Incorrect. Waldenstrom has monoclonal IgM (not IgG), lymphoplasmacytoid cells (not plasma cells), MYD88 L265P mutation, and characteristically lacks lytic bone lesions and hypercalcemia. This patient has IgG kappa and lytic lesions — diagnostic of MM, not Waldenstrom. This would be the correct answer with IgM monoclonal protein and hyperviscosity features." },
      { "text": "Solitary plasmacytoma of bone", "explanation": "Incorrect. Solitary plasmacytoma is a single localized lesion with NO other bone marrow involvement, NO CRAB criteria from systemic disease. The bone marrow plasma cells must be <10%. This patient has multiple lytic lesions and 45% marrow plasma cells → multiple myeloma, not solitary plasmacytoma. This would be the correct answer with a single bone lesion and normal marrow elsewhere." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Multiple myeloma = ≥10% clonal plasma cells + at least one CRAB (hyperCalcemia, Renal failure, Anemia, lytic Bone lesions) OR SLiM biomarker. Treat with quadruplet induction (D-VRd) → ASCT if eligible → maintenance lenalidomide. Bisphosphonates/denosumab for bone disease.",
    "pdfPage": 4,
    "pdfQuote": "M spike"
  },
  {
    "id": 10,
    "category": "Hematology: Splenic MZL HCV",
    "questionText": "A 60-year-old man with chronic hepatitis C infection (genotype 1) presents with fatigue and abdominal fullness. Vitals: BP 130/78, HR 80. Exam: massive splenomegaly (spleen tip 8 cm below costal margin), no significant peripheral lymphadenopathy. Labs: Hgb 10.5, WBC 8.0 (mild lymphocytosis with 'villous lymphocytes' on smear), platelets 110K, mild transaminitis (AST 65, ALT 78), HCV RNA detectable. Bone marrow biopsy: intrasinusoidal lymphoid infiltrate of small B cells with villous projections. Flow cytometry: CD19+ CD20+ CD5-NEGATIVE CD10-NEGATIVE CD23-NEGATIVE. Cytogenetics: deletion 7q. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Splenectomy as the only effective therapy", "explanation": "Incorrect. While splenectomy IS a recognized therapy for SMZL (often produces durable responses), it is no longer the obligatory first-line. In HCV-positive SMZL, antiviral therapy of HCV alone can produce lymphoma regression. This would be the correct answer in HCV-negative SMZL with massive symptomatic splenomegaly and no other treatment options." },
      { "text": "Direct-acting antiviral therapy for HCV", "explanation": "Correct. DAA therapy for HCV (e.g., sofosbuvir + velpatasvir, glecaprevir + pibrentasvir) — HCV-driven splenic marginal zone lymphoma can REGRESS with HCV eradication; reassess lymphoma response after sustained virologic response (SVR); add rituximab-based therapy for non-responders or progressive disease. SPLENIC MARGINAL ZONE LYMPHOMA (SMZL) is an indolent B-cell NHL of the splenic marginal zone — characterized by: (1) massive splenomegaly OFTEN WITHOUT significant peripheral lymphadenopathy (key distinction from other NHL); (2) 'VILLOUS LYMPHOCYTES' on peripheral smear (small lymphocytes with short hairy/villous cytoplasmic projections); (3) intrasinusoidal pattern in bone marrow; (4) immunophenotype CD19+ CD20+ CD5-NEGATIVE CD10-NEGATIVE CD23-NEGATIVE (distinguishing from CLL/MCL which are CD5+, and follicular which is CD10+); (5) common 7q deletion; (6) strong association with HEPATITIS C VIRUS infection. KEY UNIQUE FEATURE: HCV-ASSOCIATED SMZL can REGRESS with HCV eradication using direct-acting antivirals (DAAs) — clonal B-cells driven by chronic HCV antigen stimulation can involute when the antigen drive is removed. This is similar to gastric MALT responding to H. pylori eradication. Management approach: (1) HCV-POSITIVE: DAA therapy first; lymphoma often regresses with SVR; reassess at 6-12 months; (2) HCV-NEGATIVE OR persistent lymphoma despite SVR: depends on symptoms — watchful waiting if asymptomatic; symptomatic disease → RITUXIMAB monotherapy (highly effective in SMZL), or rituximab + chemo (BR), or SPLENECTOMY (especially for symptomatic massive splenomegaly without disseminated disease — historically standard, now competing with rituximab); (3) For relapsed/refractory: BTK inhibitors, lenalidomide + rituximab, allogeneic SCT in select cases. HEPATITIS C ASSOCIATIONS to recall: cryoglobulinemia (mixed type II), HCC, splenic marginal zone lymphoma, glomerulonephritis (membranoproliferative)." },
      { "text": "R-CHOP for 6 cycles immediately for all NHL", "explanation": "Incorrect. R-CHOP is appropriate for AGGRESSIVE NHL like DLBCL; for indolent SMZL, less aggressive approaches (HCV treatment, watchful waiting, rituximab monotherapy) are preferred. This would be the correct answer in DLBCL." },
      { "text": "Allogeneic SCT as first-line", "explanation": "Incorrect. Indolent SMZL has a long natural history; SCT is reserved for transformation to aggressive lymphoma or multiply refractory disease. This would be the correct answer in transformed/aggressive disease in a young patient." },
      { "text": "Hydroxyurea single-agent", "explanation": "Incorrect. Hydroxyurea is not used in SMZL or other lymphomas. It is used in MPNs and sickle cell disease. This would be the correct answer in those diseases." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Splenic MZL = massive splenomegaly + VILLOUS LYMPHOCYTES + CD19+CD20+CD5-CD10-CD23-. STRONG HCV association. HCV-positive SMZL → treat HCV with DAAs first; lymphoma often regresses. Persistent → rituximab ± splenectomy.",
    "pdfPage": 5,
    "pdfQuote": "marginal zone"
  },
  {
    "id": 11,
    "category": "Hematology: Hodgkin Late Effects",
    "questionText": "A 45-year-old woman has been in remission from nodular sclerosing Hodgkin lymphoma for 18 years after ABVD + mediastinal radiation at age 27. She comes for follow-up. Which is the most important LATE EFFECT screening she should receive based on her prior treatment exposure?",
    "options": [
      { "text": "Annual colonoscopy starting now for colorectal cancer (radiation-related)", "explanation": "Incorrect. Mediastinal/upper-body radiation does not significantly increase colorectal cancer risk. Standard age-based colorectal cancer screening at age 45-50 applies. This would be the correct answer after pelvic radiation (which can increase rectal cancer risk)." },
      { "text": "Annual breast MRI + mammography starting 8-10 yrs post-radiation", "explanation": "Correct. Annual breast cancer screening with BREAST MRI (in addition to mammography) starting 8-10 years after thoracic radiation OR at age 30, due to high lifetime risk of secondary breast cancer (~20-30% by age 50 in women irradiated before age 30); also screen for cardiovascular disease, thyroid dysfunction, second malignancies (lung, sarcoma). WOMEN IRRADIATED TO THE CHEST FOR HODGKIN LYMPHOMA BEFORE AGE 30 have a markedly elevated risk of SECONDARY BREAST CANCER (~20-30% lifetime risk by age 50, similar to BRCA mutation carriers). Screening recommendations: ANNUAL BREAST MRI + MAMMOGRAPHY starting 8-10 years after radiation OR at age 30 (whichever comes first), with MRI in alternating intervals with mammography (e.g., breast MRI in one 6-month interval, mammogram in the other for high-risk surveillance). OTHER MAJOR LATE EFFECTS of HL treatment to screen: (1) SECONDARY MALIGNANCIES — breast (women, after thoracic radiation), lung (radiation + smoking synergy), thyroid (after neck radiation), sarcoma (in radiation field), AML/MDS (from alkylators in BEACOPP), Hodgkin/NHL itself can recur; (2) CARDIOVASCULAR DISEASE — premature CAD (from radiation + anthracycline cardiotoxicity), valvular disease (especially after mediastinal radiation), cardiomyopathy (anthracycline cumulative dose-related), pericardial disease, conduction abnormalities. Recommend cardiovascular risk factor management, periodic echocardiogram, stress testing as appropriate. (3) THYROID DYSFUNCTION (hypothyroidism most common, sometimes Graves disease or thyroid cancer) — annual TSH after neck/mediastinal radiation. (4) PULMONARY DISEASE — bleomycin lung toxicity (interstitial fibrosis), radiation pneumonitis. PFTs as indicated. (5) INFERTILITY/EARLY MENOPAUSE (alkylators, pelvic radiation, BEACOPP). (6) SECONDARY MYELODYSPLASIA/AML (from alkylators, especially BEACOPP). Mediastinal radiation is being de-escalated in modern protocols (lower doses, smaller fields, response-adapted to PET) — but historical exposures cause these late effects. Education of HL survivors about late effects is essential." },
      { "text": "Annual whole-body bone scan for skeletal metastases", "explanation": "Incorrect. There is no role for routine whole-body bone scanning in HL survivors without symptoms — HL survivorship surveillance focuses on secondary malignancies (especially breast in young women), cardiovascular disease, and thyroid dysfunction. This would be the correct answer in prostate or breast cancer surveillance with bone-targeting tumors." },
      { "text": "Routine annual brain MRI for primary CNS lymphoma", "explanation": "Incorrect. HL does not typically metastasize to the CNS, and prior HL does not particularly elevate primary CNS lymphoma risk. PCNSL is associated with HIV and immunodeficiency. This would be the correct answer in HIV with low CD4 with concerning neurologic symptoms." },
      { "text": "Annual upper endoscopy for esophageal cancer", "explanation": "Incorrect. Esophageal cancer risk is mildly elevated after mediastinal radiation but is not a primary screening recommendation in HL survivors. Breast cancer surveillance, cardiovascular screening, and thyroid surveillance are higher priority. This would be the correct answer in Barrett's esophagus surveillance." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HL survivors irradiated to chest before age 30 → ANNUAL BREAST MRI + MAMMOGRAPHY starting 8-10 yrs after radiation OR at age 30. Also screen: cardiovascular disease, thyroid dysfunction (TSH), secondary malignancies (lung, sarcoma, leukemia).",
    "pdfPage": 4,
    "pdfQuote": "Hodgkin"
  },
  {
    "id": 12,
    "category": "Hematology: PTLD Reduce Immunosuppression",
    "questionText": "A 24-year-old woman who underwent kidney transplant 18 months ago for IgA nephropathy is on tacrolimus, mycophenolate, and prednisone. She presents with painless cervical and axillary lymphadenopathy, fever, and 5 kg weight loss over 2 months. Vitals: T 38.0°C, BP 130/80, HR 88. Exam: bilateral cervical and axillary nodes, mild hepatosplenomegaly. Labs: WBC 8, Hgb 11, platelets 200K, LDH 750 (elevated), EBV PCR in blood POSITIVE (high viral load). Excisional cervical node biopsy: monomorphic POST-TRANSPLANT LYMPHOPROLIFERATIVE DISORDER (PTLD), CD20+ B-cell type, with EBV-encoded RNA (EBER) by in-situ hybridization POSITIVE. Which is the most appropriate FIRST-LINE management?",
    "options": [
      { "text": "Immediate R-CHOP chemotherapy at full dose", "explanation": "Incorrect. While R-CHOP can be used in PTLD, the FIRST step is usually to REDUCE IMMUNOSUPPRESSION (allowing the patient's immune system to recover and control EBV-driven proliferation) ± rituximab. R-CHOP is added if response is inadequate. Going straight to R-CHOP without reducing immunosuppression and trying rituximab is overly aggressive. This would be the correct answer in advanced PTLD that has failed RIS + rituximab." },
      { "text": "Reduce immunosuppression + single-agent rituximab", "explanation": "Correct. Reduce immunosuppression (carefully, balancing graft rejection risk) and treat with single-agent rituximab; reassess response after 4 cycles; if inadequate response, escalate to R-CHOP; also reduce/eliminate antimetabolite (mycophenolate, azathioprine); maintain calcineurin inhibitor at lower dose; consider antiviral if EBV high; close monitoring for graft rejection. POST-TRANSPLANT LYMPHOPROLIFERATIVE DISORDER (PTLD) is a spectrum from polyclonal lymphoproliferation to monomorphic NHL (most commonly DLBCL or Burkitt-like) arising in immunosuppressed solid organ transplant or HSCT recipients. Most are EBV-DRIVEN (especially early/within 1-2 years post-transplant) — EBV-infected B cells proliferate when T-cell immunosurveillance is suppressed by transplant immunosuppression. RISK FACTORS: EBV-seronegative recipient receiving organ from EBV-seropositive donor (pediatric especially), intensity of immunosuppression, type of organ (intestinal/lung > heart/kidney/liver). CLASSIFICATION (WHO): non-destructive PTLD, polymorphic PTLD, monomorphic PTLD (DLBCL-like, Burkitt-like, plasmacytoma-like, T-cell), classical Hodgkin lymphoma-type PTLD. MANAGEMENT — sequential approach: (1) REDUCE IMMUNOSUPPRESSION (RIS) — first and most important step; often reduce/eliminate antimetabolite (mycophenolate, azathioprine), reduce calcineurin inhibitor to minimal levels. Allows immune reconstitution to control EBV-driven proliferation. Watch for GRAFT REJECTION. RIS alone can produce response in ~40-50% of cases. (2) RITUXIMAB monotherapy weekly × 4 cycles — added if no response to RIS or for initial monomorphic disease. RIS + rituximab response rate ~60-80%. (3) ESCALATION to RITUXIMAB + CHOP-BASED CHEMOTHERAPY (R-CHOP) for monomorphic disease, bulky disease, or non-responders to rituximab alone. (4) EBV-specific cytotoxic T cells (donor or third-party banked) for refractory disease (emerging, available at some centers). (5) Antivirals (ganciclovir, valganciclovir) are not very effective once lytic EBV replication has stopped, but can be used in adjunct in some cases. (6) Reduce immunosuppression for non-EBV-driven PTLD as well, although less responsive. (7) Hodgkin-type PTLD treated with ABVD or BV-AVD. (8) Monitor EBV viral load — predicts response and relapse. Mortality in PTLD remains significant (~30-40% at 5 years) but improving with newer approaches." },
      { "text": "Continue current immunosuppression and add brentuximab vedotin", "explanation": "Incorrect. Brentuximab is for CD30+ malignancies (HL, ALCL, CD30+ T-cell lymphomas). Monomorphic DLBCL-like PTLD is CD20+ CD30-NEGATIVE, so brentuximab is not appropriate. Also, NOT reducing immunosuppression misses the key first step. This would be the correct answer in classical HL-type PTLD." },
      { "text": "Increase tacrolimus to compensate for the lymphoma stress", "explanation": "Incorrect. Increasing immunosuppression would WORSEN PTLD by further suppressing T-cell control of EBV-driven proliferation. The principle is OPPOSITE — REDUCE immunosuppression. This would be the correct answer NEVER in PTLD." },
      { "text": "Allogeneic stem cell transplant immediately for the lymphoma", "explanation": "Incorrect. Allogeneic SCT is not first-line for PTLD; RIS + rituximab is the initial approach. SCT carries enormous toxicity especially in a solid-organ transplant recipient. This would be the correct answer for very refractory PTLD in select patients, though much less common." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: PTLD (EBV-driven post-transplant) management = REDUCE IMMUNOSUPPRESSION + RITUXIMAB → escalate to R-CHOP if inadequate. Watch for graft rejection. Monitor EBV viral load. EBV-specific CTLs for refractory cases.",
    "pdfPage": 5,
    "pdfQuote": "EBV"
  },
  {
    "id": 13,
    "category": "Hematology: Anaplastic Large Cell Lymphoma",
    "questionText": "A 32-year-old man presents with fever, fatigue, and progressively enlarging cervical lymphadenopathy over 2 months. PMH: unremarkable. Vitals: T 38.4°C, BP 130/78, HR 92. Exam: large cervical lymph nodes (some matted), hepatosplenomegaly. Labs: LDH 1,200 (elevated). Excisional node biopsy: sheets of large pleomorphic 'hallmark' cells with horseshoe-shaped or eccentric nuclei and abundant cytoplasm; cells strongly POSITIVE for CD30 and ALK (anaplastic lymphoma kinase), and EMA POSITIVE. CD3 weak positive, CD20 NEGATIVE. FISH: t(2;5) NPM-ALK translocation POSITIVE. Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "R-CHOP for 6 cycles as standard for all aggressive NHL", "explanation": "Incorrect. RITUXIMAB targets CD20, but ALK-positive ALCL is a T-CELL lymphoma with CD20-NEGATIVE phenotype. Rituximab would have no effect. The patient needs T-cell-directed therapy, ideally exploiting CD30 expression. This would be the correct answer in DLBCL or other CD20+ B-cell NHL." },
      { "text": "Brentuximab vedotin + CHP (ECHELON-2)", "explanation": "Correct. BV-CHP (brentuximab vedotin + cyclophosphamide + doxorubicin + prednisone) for 6 cycles per the ECHELON-2 trial — front-line for CD30+ peripheral T-cell lymphomas including ALK+ and ALK- ALCL; for ALK+ ALCL, prognosis is favorable; consider ALK inhibitors (crizotinib, alectinib) in relapsed disease. ANAPLASTIC LARGE CELL LYMPHOMA (ALCL) is a peripheral T-cell lymphoma with two main forms: ALK-POSITIVE (carries t(2;5) NPM-ALK fusion → constitutively active ALK tyrosine kinase; better prognosis, often in younger patients) and ALK-NEGATIVE (worse prognosis, older patients; in this category, DUSP22 rearrangements have intermediate prognosis, TP63 rearrangements have poor prognosis). MORPHOLOGY: large pleomorphic 'HALLMARK' cells with horseshoe-shaped (kidney bean, embryo-like) or eccentric nuclei. IMMUNOPHENOTYPE: strongly CD30+ (Reed-Sternberg-like, but ALCL is not classical HL), often EMA+, often T-cell markers (CD3 variable), CD20-NEGATIVE. ALK protein positive in ALK+ ALCL. FRONT-LINE THERAPY: BV-CHP (BRENTUXIMAB VEDOTIN + CYCLOPHOSPHAMIDE + DOXORUBICIN + PREDNISONE) for 6 cycles, based on the ECHELON-2 trial showing superior PFS and OS vs CHOP in CD30+ peripheral T-cell lymphomas including ALK+ and ALK- ALCL. Brentuximab targets the very strongly expressed CD30. ALK+ ALCL has FAVORABLE prognosis (5-year OS 70-80%) — autologous SCT in first remission is not typically needed. ALK- ALCL has WORSE prognosis (5-year OS 30-50%) — autologous SCT in first remission is often considered, especially in fit younger patients. RELAPSED/REFRACTORY: brentuximab vedotin (if not previously used), ALK INHIBITORS (CRIZOTINIB, ALECTINIB, lorlatinib for ALK+ ALCL specifically — same drugs used in ALK+ non-small cell lung cancer), allogeneic SCT in fit patients. CUTANEOUS ALCL (primary, indolent) is distinct from systemic ALCL and is treated more conservatively. BREAST IMPLANT-ASSOCIATED ALCL (BIA-ALCL) — rare ALK-NEGATIVE ALCL associated with textured silicone implants; usually localized and curable with implant removal + capsulectomy." },
      { "text": "Watchful waiting with serial CT scans every 3 months", "explanation": "Incorrect. ALCL is aggressive and progresses rapidly without treatment. This would be the correct answer in indolent NHL like asymptomatic follicular lymphoma." },
      { "text": "ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is for APL (M3 AML with t(15;17)) — not ALCL. The t(2;5) NPM-ALK is not the same as t(15;17). This would be the correct answer in APL." },
      { "text": "Single-agent imatinib (BCR-ABL inhibitor)", "explanation": "Incorrect. Imatinib targets BCR-ABL fusion (CML, Ph+ ALL), not NPM-ALK. ALK inhibitors (crizotinib, alectinib, lorlatinib) are the correct class for ALK+ ALCL, but these are reserved for relapsed disease — front-line is BV-CHP. This would be the correct answer in CML or Ph+ ALL." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: ALK+ ALCL = T-cell lymphoma with t(2;5) NPM-ALK + 'hallmark cells' + CD30 strongly+. First-line = BV-CHP (brentuximab + CHP, ECHELON-2 trial). ALK+ has favorable prognosis; ALK- worse. Relapsed: brentuximab, ALK inhibitors (crizotinib/alectinib/lorlatinib).",
    "pdfPage": 6,
    "pdfQuote": "anaplastic"
  },
  {
    "id": 14,
    "category": "Hematology: Primary Mediastinal Large B-Cell",
    "questionText": "A 28-year-old woman presents with a 4-week history of progressive dyspnea, dry cough, facial swelling worse in the morning, and dilated neck veins (SVC syndrome features). Vitals: T 37.1°C, HR 96, BP 110/68 (with pulsus paradoxus), RR 22, O2 sat 94%. Exam: facial plethora, dilated neck veins, decreased breath sounds at bases. CT chest: 12 cm bulky anterior mediastinal mass with SVC compression and bilateral pleural effusions. Biopsy of the mass: sheets of large pleomorphic CD19+ CD20+ CD30 variably positive B cells with associated fibrosis. FISH: NO t(15;17), NO t(8;14), NO MYC/BCL-2 rearrangements. Immunophenotype consistent with PRIMARY MEDIASTINAL LARGE B-CELL LYMPHOMA (PMLBCL). Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Standard ABVD + radiation as for classical Hodgkin lymphoma", "explanation": "Incorrect. ABVD is for classical Hodgkin lymphoma. PMLBCL is a distinct DLBCL subtype with biology overlapping HL (both arise from thymic B cells, both have PD-L1 amplification, both can present with mediastinal bulky disease) but is a B-cell NHL requiring B-cell-directed therapy. This would be the correct answer in classical HL." },
      { "text": "DA-EPOCH-R for 6 cycles (preferred over R-CHOP for PMLBCL)", "explanation": "Correct. DA-EPOCH-R (dose-adjusted etoposide, prednisone, vincristine, cyclophosphamide, doxorubicin, rituximab) is generally preferred over R-CHOP for PMLBCL based on intensive 6-cycle dose-adjusted protocol; achieves high cure rates without obligatory radiation; alternatively R-CHOP + radiation; brentuximab and immune checkpoint inhibitors (pembrolizumab, nivolumab) for relapsed disease. PRIMARY MEDIASTINAL LARGE B-CELL LYMPHOMA (PMLBCL) is a distinct subtype of DLBCL with: (1) demographics — predominantly YOUNG WOMEN (median age ~35); (2) presentation — BULKY ANTERIOR MEDIASTINAL MASS (arising from thymic B cells), often with SVC syndrome, dyspnea, cough, pleural/pericardial effusions; (3) histology — DLBCL morphology with diffuse fibrosis; (4) immunophenotype — CD19+ CD20+ CD30 variably positive (intermediate between DLBCL and classical HL); (5) molecular — amplification of 9p24.1 (PD-L1/PD-L2, like classical HL) → highly responsive to PD-1 inhibitors; (6) GENERALLY GOOD PROGNOSIS with appropriate first-line therapy. FIRST-LINE THERAPY: (1) DA-EPOCH-R (dose-adjusted etoposide + prednisone + vincristine + cyclophosphamide + doxorubicin + rituximab) for 6 cycles — preferred by many centers based on excellent outcomes in NCI prospective study (>90% cure rates without radiation in many patients); the 'dose-adjusted' part means escalating doses based on hematologic tolerance; advantage: avoids mediastinal radiation in young women (reduces secondary breast cancer and cardiovascular late effects); (2) Alternative: R-CHOP + mediastinal radiation therapy — also effective but with radiation-related late effects; (3) END-OF-TREATMENT PET-CT to assess response; (4) RESIDUAL FDG-AVIDITY after chemotherapy can be PET-AVID FROM INFLAMMATION/FIBROSIS (PMLBCL has particularly high rate of false-positive PET due to inflammatory background) — biopsy or close follow-up rather than reflexive radiation. RELAPSED/REFRACTORY: (1) Salvage chemotherapy (R-DHAP, R-ICE, R-GDP) → autologous SCT in chemo-sensitive patients; (2) IMMUNE CHECKPOINT INHIBITORS (PEMBROLIZUMAB FDA-approved for relapsed PMLBCL; nivolumab also active) — exploit PD-L1 amplification; (3) BRENTUXIMAB VEDOTIN (CD30 expression in PMLBCL); (4) CD19 CAR-T therapy (axicabtagene, lisocabtagene); (5) Allogeneic SCT in select patients. PROGNOSIS: with DA-EPOCH-R, >80-90% long-term cure. Differential diagnosis of mediastinal masses in young women: PMLBCL, classical HL (nodular sclerosing especially), thymoma, germ cell tumor, T-ALL/lymphoblastic lymphoma." },
      { "text": "Single-agent rituximab for life", "explanation": "Incorrect. Single-agent rituximab is inadequate for an aggressive lymphoma like PMLBCL. Combination chemoimmunotherapy is needed. This would be the correct answer in low-grade indolent disease maintenance." },
      { "text": "Watchful waiting with serial imaging", "explanation": "Incorrect. PMLBCL is aggressive with rapid progression and life-threatening SVC syndrome — urgent treatment is required. Watchful waiting is appropriate ONLY for indolent low-burden disease without active symptoms. This would be the correct answer NEVER in PMLBCL." },
      { "text": "Allogeneic stem cell transplant in first complete remission", "explanation": "Incorrect. PMLBCL has good outcomes with chemoimmunotherapy alone (DA-EPOCH-R) — allogeneic SCT in first CR is not standard. SCT is reserved for relapsed/refractory disease after autologous SCT failure. This would be the correct answer in refractory PMLBCL after multiple lines." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: PMLBCL = young woman + bulky anterior mediastinal mass + SVC syndrome + DLBCL morphology + PD-L1 amplification. First-line = DA-EPOCH-R (NCI protocol, avoids radiation). Relapsed: salvage chemo → auto-SCT; pembrolizumab/nivolumab (PD-L1 amplification); brentuximab; CD19 CAR-T.",
    "pdfPage": 5,
    "pdfQuote": "DLBCL"
  },
  {
    "id": 15,
    "category": "Hematology: Double-Hit Lymphoma",
    "questionText": "A 56-year-old man presents with rapidly enlarging cervical and abdominal lymphadenopathy, B symptoms, and weight loss over 6 weeks. Vitals: BP 130/78, HR 90, T 38.0°C. Exam: bulky cervical and inguinal nodes, mild hepatomegaly. Labs: WBC 18 with circulating large cells, Hgb 11, platelets 200K, LDH 2,800 (markedly elevated). Excisional cervical node biopsy: sheets of large CD19+ CD20+ B cells with high mitotic activity, Ki-67 90%. FISH: BOTH c-MYC translocation AND BCL-2 translocation POSITIVE ('DOUBLE-HIT' lymphoma; some centers also call this 'high-grade B-cell lymphoma with MYC and BCL2 rearrangements'). Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Standard R-CHOP for 6 cycles", "explanation": "Incorrect. DOUBLE-HIT LYMPHOMAS (MYC + BCL-2 rearrangements, sometimes with BCL-6 making it 'triple-hit') have a notably WORSE PROGNOSIS with standard R-CHOP than typical DLBCL. More intensive regimens improve outcomes. This would be the correct answer in standard DLBCL without MYC/BCL-2 rearrangements." },
      { "text": "DA-EPOCH-R with intrathecal CNS prophylaxis", "explanation": "Correct. Dose-intensive regimen: DA-EPOCH-R (dose-adjusted etoposide + prednisone + vincristine + cyclophosphamide + doxorubicin + rituximab) for 6 cycles OR R-HyperCVAD-like regimen, with INTRATHECAL CNS PROPHYLAXIS; consider autologous SCT in first CR for selected patients; CAR-T or bispecific antibodies for relapsed disease. DOUBLE-HIT LYMPHOMA (DHL, now classified as 'high-grade B-cell lymphoma with MYC and BCL2 rearrangements,' HGBCL-DH) has CONCURRENT REARRANGEMENTS of c-MYC (chromosome 8) AND BCL-2 (chromosome 18), with or without BCL-6 rearrangement ('triple-hit'). Pathogenesis: c-MYC drives proliferation; BCL-2 prevents apoptosis — the combination produces a particularly aggressive lymphoma with biological features overlapping Burkitt (high proliferation) and follicular (BCL-2 overexpression). FEATURES: AGGRESSIVE clinical course, frequently with B symptoms, bulky disease, elevated LDH, bone marrow and CNS involvement. PROGNOSIS with standard R-CHOP is POOR (40-50% long-term survival), prompting use of intensified regimens. FIRST-LINE THERAPY: (1) DA-EPOCH-R for 6 cycles — preferred by many based on retrospective data showing improved outcomes vs R-CHOP; the dose-adjusted protocol intensifies treatment based on hematologic tolerance; (2) Alternative intensive regimens: R-HyperCVAD/MA (alternating high-dose chemo with methotrexate and cytarabine), R-CODOX-M/IVAC (Magrath); (3) INTRATHECAL CNS PROPHYLAXIS (intrathecal MTX ± cytarabine) is critical — DHL has high CNS relapse risk (>10%); some regimens include high-dose systemic MTX; (4) AUTOLOGOUS SCT in first CR — controversial in this era; some advocate for fit patients with high-risk features; ongoing study; (5) Pretreatment WORKUP: lumbar puncture (CNS staging), echocardiogram (anthracycline), TLS prophylaxis (hydration + allopurinol or rasburicase given high LDH). RELAPSED/REFRACTORY DHL: very poor prognosis; CD19 CAR-T (axicabtagene, lisocabtagene, tisagenlecleucel) — FDA-approved for relapsed DLBCL/HGBCL after 2 prior lines (or 1 prior line for aggressive disease per ZUMA-7/TRANSFORM/BELINDA); BISPECIFIC ANTIBODIES (glofitamab, epcoritamab — CD20×CD3); polatuzumab vedotin (anti-CD79b ADC); allogeneic SCT in selected cases. Important to differentiate from MYC-rearrangement-only (single-hit MYC+, prognosis similar to DLBCL) and double-EXPRESSOR (immunohistochemistry coexpression of MYC and BCL-2 protein, without translocations — intermediate prognosis, treated as DLBCL)." },
      { "text": "Watchful waiting since the patient has stable disease", "explanation": "Incorrect. DHL is aggressive and rapidly progressive; observation is fatal within weeks. This would be the correct answer in indolent low-grade disease (e.g., asymptomatic follicular)." },
      { "text": "ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is for APL (M3 AML with t(15;17)) — not DHL. This would be the correct answer in APL." },
      { "text": "Single-agent rituximab indefinitely as maintenance", "explanation": "Incorrect. Single-agent rituximab is inadequate for aggressive lymphoma. Combination intensive chemotherapy is required. This would be the correct answer for low-grade indolent maintenance." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Double-hit lymphoma (MYC + BCL-2 ± BCL-6 rearrangements) = AGGRESSIVE, POOR prognosis with R-CHOP. Use DA-EPOCH-R or R-HyperCVAD + INTRATHECAL CNS prophylaxis. Relapse: CD19 CAR-T, bispecifics, polatuzumab.",
    "pdfPage": 5,
    "pdfQuote": "diffuse large B-cell"
  },
  {
    "id": 16,
    "category": "Hematology: Hairy Cell Variant Recognition",
    "questionText": "A 58-year-old man presents with progressive fatigue, fevers, and abdominal fullness. Vitals: BP 130/78, HR 80. Exam: massive splenomegaly. Labs: WBC 32,000 (mostly atypical lymphocytes with cytoplasmic projections), Hgb 9.5, platelets 70K. Bone marrow biopsy: interstitial infiltrate of small lymphoid cells with cytoplasmic projections. Flow cytometry: CD20+ CD11c+ CD103+ but CD25-NEGATIVE (unusual) and CD123-NEGATIVE; BRAF V600E mutation NEGATIVE; MAP2K1 mutation POSITIVE. Which is the most likely diagnosis and best management approach?",
    "options": [
      { "text": "Classic hairy cell leukemia — treat with cladribine alone for durable remission", "explanation": "Incorrect. Classic hairy cell leukemia is characterized by CD25+ CD123+ BRAF V600E POSITIVE phenotype. This patient is CD25-NEGATIVE, CD123-negative, BRAF V600E-NEGATIVE but has MAP2K1 mutation — a different entity. While cladribine is first-line for classic hairy cell, the variant (HCL-v) responds less well. This would be the correct answer in classic HCL with BRAF V600E and CD25+." },
      { "text": "Hairy cell variant (HCL-v); purine analog + rituximab", "explanation": "Correct. HCL-v is a distinct entity from classic HCL, BRAF-WILD-TYPE, CD25-NEGATIVE, often MAP2K1 mutated; LESS RESPONSIVE to purine analogs alone; treat with PURINE ANALOG (cladribine or pentostatin) + RITUXIMAB combination; consider venetoclax, BRAF/MEK inhibitors based on mutation, or moxetumomab for relapsed disease. HAIRY CELL LEUKEMIA VARIANT (HCL-v) is a distinct entity from classic HCL, accounting for ~10% of cases that look like HCL clinically. KEY DIFFERENCES from classic HCL: (1) IMMUNOPHENOTYPE: HCL-v is CD25-NEGATIVE, CD123-NEGATIVE, often FMC7+ (vs classic HCL CD25+ CD123+); (2) MOLECULAR: HCL-v is BRAF V600E-NEGATIVE (vs >90% positive in classic HCL); MAP2K1 (MEK1) mutations and TP53 mutations are common in HCL-v; (3) CLINICAL: HCL-v often presents with HIGHER WBC (leukocytosis vs cytopenia in classic), more aggressive course, often elderly patients; (4) TREATMENT RESPONSE: HCL-v RESPONDS LESS WELL to single-agent purine analogs (cladribine, pentostatin) than classic HCL — only ~50% CR with cladribine alone vs ~80% in classic HCL. MANAGEMENT of HCL-v: (1) Combination CLADRIBINE + RITUXIMAB is preferred over cladribine alone — improves CR rates; (2) PENTOSTATIN + RITUXIMAB is alternative; (3) For relapsed/refractory: BENDAMUSTINE + RITUXIMAB; MOXETUMOMAB PASUDOTOX (anti-CD22 immunotoxin, FDA-approved for relapsed HCL); BTK inhibitors (ibrutinib); VENETOCLAX (BCL-2 inhibitor); MEK inhibitors (TRAMETINIB) in MAP2K1-mutant cases (specific targeted therapy based on genotype); allogeneic SCT in young fit patients. Classic HCL with BRAF V600E can also use VEMURAFENIB (BRAF inhibitor) ± rituximab in relapsed disease — targeted to the mutation. The distinction between classic HCL and HCL-v is important because treatment approach and prognosis differ. SPLENECTOMY is no longer first-line for either entity in the modern era. HCL-v has a worse prognosis than classic HCL." },
      { "text": "Chronic lymphocytic leukemia — observe with watchful waiting", "explanation": "Incorrect. CLL would show smudge cells and CD5+ CD19+ CD23+ B cells with normal splenomegaly (often less massive). Hairy cell variants are distinct with their characteristic morphology (cytoplasmic projections) and immunophenotype. This would be the correct answer in early-stage CLL." },
      { "text": "Marginal zone lymphoma — treat with rituximab alone", "explanation": "Incorrect. While SMZL can show villous lymphocytes and splenomegaly (similar clinical picture), HCL-v has distinct flow cytometry (CD11c+ CD103+) and bone marrow pattern. This would be the correct answer in SMZL." },
      { "text": "Burkitt lymphoma — DA-EPOCH-R with TLS prophylaxis", "explanation": "Incorrect. Burkitt is a high-grade aggressive lymphoma with starry sky histology and Ki-67 ~100% — not the indolent HCL-variant picture. This would be the correct answer in Burkitt." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HCL-VARIANT = BRAF V600E NEGATIVE + CD25 NEGATIVE + often MAP2K1 mutant. Less responsive to cladribine alone. Treat with PURINE ANALOG + RITUXIMAB. Relapsed: moxetumomab, MEK inhibitors for MAP2K1, venetoclax, BTK inhibitors.",
    "pdfPage": 3,
    "pdfQuote": "TRAP"
  },
  {
    "id": 17,
    "category": "Hematology: Nodular Lymphocyte-Predominant HL",
    "questionText": "A 27-year-old man presents with painless, slowly enlarging right cervical lymphadenopathy over 1 year. No B symptoms. Vitals: BP 122/74, HR 78. Exam: 2.5 cm right cervical lymph node, no other adenopathy or organomegaly. Excisional biopsy: nodular pattern, with 'POPCORN CELLS' (L&H cells — large cells with multilobed/popcorn-shaped nuclei) scattered in a background of small B cells and follicular dendritic meshworks. IHC: L&H cells are CD20-POSITIVE, CD45-POSITIVE, CD15-NEGATIVE, CD30-NEGATIVE. PET/CT: localized to single cervical site (stage IA). Which is the most appropriate management?",
    "options": [
      { "text": "Standard ABVD for advanced HL even though disease appears localized", "explanation": "Incorrect. NODULAR LYMPHOCYTE-PREDOMINANT HODGKIN LYMPHOMA (NLPHL) is a distinct entity from classical HL with different biology and treatment approach. The popcorn cells (L&H cells) are CD20+ CD45+ CD15-NEGATIVE CD30-NEGATIVE — opposite of classical HL RS cells. For early-stage NLPHL, INVOLVED-SITE RADIATION ALONE is often curative. ABVD over-treats early-stage NLPHL. This would be the correct answer in advanced-stage classical HL." },
      { "text": "Involved-site radiation therapy (ISRT) alone for stage IA NLPHL", "explanation": "Correct. NODULAR LYMPHOCYTE-PREDOMINANT HODGKIN LYMPHOMA (NLPHL) is a separate entity from CLASSICAL Hodgkin lymphoma in the WHO classification. KEY DIFFERENCES: (1) MALIGNANT CELLS — 'POPCORN CELLS' (L&H cells, lymphocyte-predominant cells, sometimes called LP cells) are large cells with multilobed nuclei — DERIVED FROM germinal center B cells; (2) IMMUNOPHENOTYPE — CD20-POSITIVE (key — B-cell marker preserved), CD45-POSITIVE (CLL antigen preserved), CD15-NEGATIVE, CD30-NEGATIVE, often EMA+, OCT2+ — essentially the OPPOSITE of classical HL RS cells; (3) CLINICAL — usually YOUNG MEN with peripheral (cervical, axillary, inguinal) lymphadenopathy; mediastinal involvement uncommon; B symptoms rare; INDOLENT course (often more like follicular lymphoma than HL); (4) PROGNOSIS — excellent overall; long-term cure rates >90% in early stage; (5) Transformation to DLBCL can occur (5-15% over years). MANAGEMENT: (1) EARLY STAGE (stage IA-IIA, single site) — INVOLVED-SITE RADIATION THERAPY (ISRT) alone is the standard, producing >90% long-term disease control with minimal toxicity. Some advocate for limited-extent surgical excision alone in select cases. (2) Alternative for select patients (avoiding radiation): RITUXIMAB monotherapy (the CD20 expression makes NLPHL highly responsive to rituximab); useful in pediatric patients to avoid radiation late effects. (3) ADVANCED STAGE (III-IV) or relapsed NLPHL — treatment more like B-cell NHL: R-CHOP, R-ABVD (rituximab + ABVD), R-CHVPP, or rituximab + bendamustine. Some use ABVD ± rituximab for stage II-III. (4) Watch for TRANSFORMATION to aggressive B-cell lymphoma (DLBCL or T-cell/histiocyte-rich large B-cell lymphoma — THRLBCL). NLPHL is a SEPARATE LYMPHOMA from classical HL in current classifications and should not be conflated." },
      { "text": "ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is for APL — not NLPHL. This would be the correct answer in APL." },
      { "text": "Single-agent venetoclax indefinitely", "explanation": "Incorrect. Venetoclax (BCL-2 inhibitor) is used in CLL and select BCL-2 rearranged lymphomas — not standard for NLPHL. This would be the correct answer in CLL." },
      { "text": "Allogeneic SCT immediately as primary treatment", "explanation": "Incorrect. NLPHL has excellent prognosis with simple ISRT or rituximab; allogeneic SCT is overkill. SCT may be considered for refractory or transformed disease. This would be the correct answer in refractory transformed NLPHL." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: NLPHL = 'popcorn cells' (CD20+CD45+CD15-CD30-) in young men with peripheral LAD. INDOLENT, B-cell-like. Stage IA = ISRT alone (>90% cure). Advanced = R-based regimens (rituximab + ABVD/CHOP/bendamustine). Watch for transformation to DLBCL.",
    "pdfPage": 4,
    "pdfQuote": "lymphocyte-predominant"
  },
  {
    "id": 18,
    "category": "Hematology: Enteropathy-Associated T-Cell Lymphoma",
    "questionText": "A 58-year-old woman with known celiac disease (diagnosed 20 years ago, intermittently adherent to gluten-free diet) presents with worsening abdominal pain, weight loss, fevers, and new-onset diarrhea over 3 months. Vitals: T 38.0°C, BP 110/68, HR 96. Exam: cachectic, mild diffuse abdominal tenderness. Labs: anemia, mild transaminitis, elevated LDH. CT abdomen: thickening of jejunal wall and several enlarged mesenteric lymph nodes. Capsule endoscopy: multiple ulcerated jejunal lesions. Biopsy: pleomorphic medium-sized T cells with abundant cytoplasm, CD3+ CD8+ CD56+ T-cell receptor gamma-delta or alpha-beta rearrangement; HLA-DQ2 positive. Which is the most likely diagnosis?",
    "options": [
      { "text": "Refractory celiac disease type I (responsive to immunosuppression)", "explanation": "Incorrect. Refractory celiac disease type I has aberrant intraepithelial lymphocytes that retain normal phenotype (CD3+ CD8+ TCR+) and can respond to budesonide/immunosuppression. It does not show mass lesions, ulcerated tumor-forming lymphoma morphology, or LDH elevation. This would be the correct answer in refractory celiac without overt lymphoma." },
      { "text": "Enteropathy-associated T-cell lymphoma (EATL) — a complication of long-standing celiac disease", "explanation": "Correct. ENTEROPATHY-ASSOCIATED T-CELL LYMPHOMA (EATL) is a rare aggressive peripheral T-cell lymphoma of the small intestine, occurring almost exclusively in patients with long-standing CELIAC DISEASE (HLA-DQ2 or HLA-DQ8 positive). Classification: EATL type I (now called 'EATL' in current WHO) — strongly associated with celiac; pleomorphic medium-large T cells; CD3+ CD7+ CD8 variable, CD30 often positive, TCR αβ. Monomorphic epitheliotropic intestinal T-cell lymphoma (MEITL, formerly EATL type II) — less strongly associated with celiac; monomorphic small T cells; CD8+ CD56+ TCR γδ. CLINICAL FEATURES: (1) chronic abdominal pain, weight loss, diarrhea; (2) often presents with COMPLICATIONS — bowel obstruction, perforation, ulcers, bleeding; (3) jejunum > ileum; (4) mesenteric lymphadenopathy; (5) B symptoms common; (6) high LDH. DIAGNOSIS: capsule endoscopy + double-balloon enteroscopy + biopsy; surgical resection sometimes needed for definitive diagnosis. MANAGEMENT: (1) STRICT GLUTEN-FREE DIET (important even in established EATL); (2) CHEMOTHERAPY: CHOP-based regimens (or CHOEP) with intent to consolidate with autologous SCT in first CR — outcomes poor; (3) BRENTUXIMAB VEDOTIN + CHP (BV-CHP) for CD30+ EATL based on extrapolation from ECHELON-2; (4) AUTOLOGOUS SCT in first CR is recommended for fit patients; (5) Allogeneic SCT for relapsed/refractory; (6) PROGNOSIS: POOR overall (5-year survival 20-30%). PREVENTION: strict adherence to gluten-free diet in celiac patients markedly reduces EATL risk over decades — emphasizes importance of adherence. Other celiac-associated complications: small bowel ADENOCARCINOMA, REFRACTORY celiac disease (Type I and Type II — Type II has aberrant clonal IELs and high progression to EATL)." },
      { "text": "Crohn disease with deep mucosal involvement", "explanation": "Incorrect. Crohn disease causes transmural inflammation with skip lesions, granulomas, fistulas — not pleomorphic T-cell lymphocyte infiltrates with monoclonal TCR rearrangement and LDH elevation. The biopsy findings here are diagnostic of EATL, not Crohn. This would be the correct answer in Crohn with appropriate histopathology." },
      { "text": "Whipple disease", "explanation": "Incorrect. Whipple disease shows PAS-positive macrophages in lamina propria (foamy macrophages containing Tropheryma whipplei); not a lymphoma. This would be the correct answer with PAS-positive macrophages and arthralgia/CNS findings." },
      { "text": "Tropical sprue", "explanation": "Incorrect. Tropical sprue presents in patients from tropical regions with chronic diarrhea, malabsorption, and folate/B12 deficiency; not a lymphoma. This would be the correct answer in a patient from a tropical region with mucosal villous flattening responding to tetracycline + folate." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: EATL = aggressive peripheral T-cell lymphoma in long-standing CELIAC patients (HLA-DQ2/DQ8). Jejunal mass + B symptoms + high LDH. Treat: gluten-free diet + CHOP/CHOEP/BV-CHP + auto-SCT in first CR. Poor prognosis. Strict celiac diet adherence reduces risk.",
    "pdfPage": 6,
    "pdfQuote": "T-cell"
  },
  {
    "id": 19,
    "category": "Hematology: Thyroid MALT Hashimoto",
    "questionText": "A 65-year-old woman with long-standing Hashimoto thyroiditis (TPO antibody positive, on levothyroxine for 15 years) develops rapid enlargement of her thyroid over 6 months along with hoarseness and dysphagia. Vitals: BP 130/78, HR 70. Exam: firm enlarged thyroid (5 cm right lobe), no significant cervical lymphadenopathy. Ultrasound + FNA: features suggestive of lymphoma. Open thyroid biopsy: dense lymphoid infiltrate of small marginal zone B cells, with lymphoepithelial lesions and reactive germinal centers; CD20+ CD5-NEGATIVE CD10-NEGATIVE CD23-NEGATIVE BCL2 negative, cyclin D1 negative; FISH negative for t(11;18); kappa light chain restriction confirms clonality. Diagnosis: THYROID MALT LYMPHOMA. Stage IE (localized to thyroid only). Which is the most appropriate first-line therapy?",
    "options": [
      { "text": "Total thyroidectomy + bilateral neck dissection", "explanation": "Incorrect. Thyroid MALT lymphoma is highly responsive to radiation and does not require radical surgery. Total thyroidectomy is unnecessarily morbid. Surgery may be done for biopsy or for management of severe local compression. This would be the correct answer in thyroid carcinoma (papillary, follicular, anaplastic), not lymphoma." },
      { "text": "Involved-site radiation therapy (ISRT)", "explanation": "Correct. ISRT to the thyroid + cervical lymph nodes produces excellent local control and high cure rates in localized thyroid MALT lymphoma; continue levothyroxine for hypothyroidism (will need dose adjustment after thyroid radiation); for advanced/disseminated disease: rituximab ± chemotherapy. THYROID MALT LYMPHOMA (primary thyroid lymphoma) is a rare extranodal marginal zone B-cell lymphoma strongly associated with HASHIMOTO THYROIDITIS — chronic lymphocytic infiltration of the thyroid in autoimmune thyroiditis provides the substrate for clonal B-cell evolution. The risk of thyroid lymphoma is 40-70 fold higher in Hashimoto patients vs general population. CLINICAL FEATURES: (1) rapidly enlarging thyroid mass in a patient with longstanding Hashimoto (often after years of stable thyroid); (2) compressive symptoms — hoarseness (recurrent laryngeal nerve compression), dysphagia (esophageal compression), stridor (tracheal compression); (3) often unilateral lobar enlargement, firm; (4) typically euthyroid or hypothyroid; (5) sometimes cervical lymphadenopathy. DIAGNOSIS: FNA suggestive; OPEN/CORE BIOPSY usually needed for definitive diagnosis (cellular architecture is important — MALT shows lymphoepithelial lesions, monoclonal light chain restriction). HISTOLOGY: most are MALT lymphoma (low grade); some are DLBCL (high grade — transformed or de novo). MANAGEMENT: (1) LOCALIZED MALT (stage IE — limited to thyroid, this patient) — INVOLVED-SITE RADIATION THERAPY (ISRT) to thyroid and cervical lymph nodes is standard, with excellent local control and high cure rates (>90% 10-year disease-free survival); avoids surgical morbidity; (2) ADVANCED-STAGE MALT (disseminated, rare) — single-agent rituximab or rituximab + chemotherapy (BR, R-CHOP); (3) THYROID DLBCL (transformed or de novo high-grade) — R-CHOP for 6 cycles ± ISRT; more aggressive course; (4) Continue LEVOTHYROXINE for underlying Hashimoto hypothyroidism — dose adjustment likely needed after thyroid radiation (further reduction of any residual thyroid function); (5) MONITOR for distant relapse over years (indolent course). KEY POINT: ALWAYS suspect thyroid lymphoma in Hashimoto patients with rapidly enlarging thyroid (vs slowly progressive Hashimoto). Other MALT lymphoma associations to remember: H. PYLORI → gastric MALT; SJÖGREN → parotid MALT; CHLAMYDIA PSITTACI → ocular adnexa MALT; BORRELIA → cutaneous MALT; HCV → splenic marginal zone." },
      { "text": "ATRA + arsenic trioxide as for APL", "explanation": "Incorrect. ATRA + ATO is for APL — not thyroid MALT lymphoma. This would be the correct answer in APL." },
      { "text": "Watchful waiting only since MALT is indolent", "explanation": "Incorrect. The patient has SYMPTOMATIC disease (hoarseness, dysphagia, rapidly enlarging mass) requiring treatment. ISRT is highly effective and well-tolerated. Watchful waiting for asymptomatic indolent disease is reasonable, but not when there is compressive symptoms. This would be the correct answer in asymptomatic low-burden indolent lymphoma without compressive features." },
      { "text": "Single-agent ibrutinib for life", "explanation": "Incorrect. Ibrutinib has limited role in front-line MALT lymphoma; radiation or rituximab-based therapy is preferred. Ibrutinib may be considered in some relapsed MALT (e.g., MZL after multiple lines). This would be the correct answer in CLL, MCL, or Waldenstrom." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Thyroid MALT lymphoma = complication of long-standing HASHIMOTO (40-70x risk). Suspect with rapidly enlarging thyroid + compressive symptoms. Stage IE → ISRT (radiation) is highly curative. Continue levothyroxine. Distinguish from indolent Hashimoto progression and from thyroid CARCINOMA.",
    "pdfPage": 5,
    "pdfQuote": "MALT"
  },
  {
    "id": 20,
    "category": "Hematology: Solitary Plasmacytoma to MM",
    "questionText": "A 55-year-old man underwent vertebroplasty for a T8 compression fracture. Biopsy of the lytic vertebral lesion at the time of vertebroplasty revealed a clonal plasma cell infiltrate (kappa-restricted). MRI: SINGLE T8 lesion with no other bone abnormalities. Skeletal survey: no other lytic lesions. Bone marrow biopsy: 4% plasma cells (below MM threshold), no other clonal abnormalities. SPEP: small monoclonal IgG kappa spike at 1.2 g/dL. No CRAB criteria (calcium normal, creatinine normal, Hgb 13, no other bone lesions). Diagnosis: SOLITARY PLASMACYTOMA OF BONE. Which is the most appropriate management AND counseling?",
    "options": [
      { "text": "Observation only — solitary plasmacytoma is benign", "explanation": "Incorrect. Solitary plasmacytoma is NOT benign — it is a localized malignant clonal plasma cell proliferation that requires treatment to prevent local recurrence and reduces (but does not eliminate) progression to multiple myeloma. Observation alone results in much higher local relapse and progression rates. This would be the correct answer in MGUS without lesions, which is observed." },
      { "text": "Definitive local radiation (45-50 Gy) + surveillance", "explanation": "Correct. Local definitive radiation therapy (45-50 Gy to the involved field) is curative for the local lesion; counsel that there is a significant lifetime risk (~50-70% over 10 years) of progression to multiple myeloma — needs lifelong surveillance with SPEP, CBC, calcium, creatinine every 3-6 months and skeletal imaging as indicated. SOLITARY PLASMACYTOMA OF BONE (SBP) is a localized malignant clonal plasma cell proliferation in a single bony site WITHOUT systemic multiple myeloma criteria. Diagnostic criteria: (1) BIOPSY-PROVEN single lesion of clonal plasma cells; (2) ABSENCE of CRAB criteria (no hypercalcemia, no renal failure attributable to MM, no anemia, no OTHER bone lesions — only the one); (3) BONE MARROW shows <10% clonal plasma cells (some criteria say <10% with no immunophenotypic abnormality on flow); (4) SPEP may show small M-spike (usually <3 g/dL); (5) No other end-organ damage. ALSO recognized: SOLITARY EXTRAMEDULLARY PLASMACYTOMA (head and neck, upper aerodigestive tract, lower progression risk to MM). MANAGEMENT: (1) DEFINITIVE LOCAL RADIATION THERAPY (45-50 Gy) is the standard treatment — produces excellent local control (>90%); (2) SURGICAL stabilization may be needed for pathologic fracture risk (e.g., vertebroplasty already done in this case) but does not replace radiation; (3) CHEMOTHERAPY/IMMUNOTHERAPY NOT routinely given for SBP (unlike MM); (4) MAINTENANCE SURVEILLANCE — SPEP, urine protein electrophoresis (UPEP), free light chains, CBC, calcium, creatinine every 3-6 months for years, plus skeletal imaging (low-dose whole-body CT, MRI, or PET-CT) periodically to detect progression to MM or new lesions; (5) COUNSEL ABOUT PROGRESSION RISK — approximately 50-70% of SBP progress to MM over 10 years (median time to progression 2-5 years). PROGNOSTIC FACTORS for progression to MM: persistent M-protein after radiation (does not resolve = higher risk), abnormal serum free light chain ratio, marrow involvement at borderline level, MRI showing additional occult lesions. SOLITARY EXTRAMEDULLARY PLASMACYTOMA has a much lower progression rate to MM (~30%) and better prognosis. Importance of getting all the staging right BEFORE diagnosis: a missed second lesion would reclassify as MM (multiple lesions) needing systemic therapy." },
      { "text": "Immediate quadruplet myeloma induction therapy (D-VRd) + autologous SCT", "explanation": "Incorrect. The patient does NOT meet criteria for MM (no CRAB, no >10% plasma cells, no biomarkers of malignancy). Treating with full MM induction would be inappropriate over-treatment for solitary plasmacytoma. This would be the correct answer in confirmed symptomatic MM with CRAB criteria." },
      { "text": "Initiate bisphosphonates only without radiation", "explanation": "Incorrect. Bisphosphonates do not provide local disease control; the bone disease is from the malignant plasma cell infiltrate, not osteoporosis. Local radiation is needed for disease control. Bisphosphonates may be added in MM (or eventually if progression occurs), but not in solitary plasmacytoma as monotherapy. This would be the correct answer in osteoporosis or established MM." },
      { "text": "Allogeneic stem cell transplant in first remission", "explanation": "Incorrect. Allogeneic SCT is far too aggressive for solitary plasmacytoma. Even in MM, allogeneic SCT is reserved for highly select cases. This would be the correct answer in refractory young patients with multiply relapsed MM and matched donor in expert centers." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Solitary plasmacytoma of bone = single lesion, NO CRAB, marrow <10% plasma cells. Treat with DEFINITIVE LOCAL RADIATION (45-50 Gy). ~50-70% progress to MM over 10 years — lifelong surveillance (SPEP, FLC, calcium, creatinine, imaging). Distinguish from MM (multiple lesions, CRAB) and from MGUS.",
    "pdfPage": 4,
    "pdfQuote": "plasma cell"
  }
];

window.Test_L155_Part2 = Test_L155_Part2;
