// Thinking Process (Part 2 — strictly 2nd/3rd-order vignettes per v5 prompt):
// 1. High-Yield Concept: Application/diagnosis/management of iron deficiency, anemia of chronic disease, thalassemias, sideroblastic anemia, lead poisoning, hemochromatosis, CKD anemia.
// 2. The "Trap": Students confuse IDA vs ACD vs thalassemia trait when iron studies overlap; mistake hemochromatosis screening criteria; forget GI bleed workup in adult male IDA.
// 3. Key Distractor: For IDA in adult man → "start oral iron and recheck in 4 weeks" without colonoscopy is wrong; for hereditary hemochromatosis → "iron chelation" instead of phlebotomy is wrong.
// 4. Vignette Strategy: Give full demographics + dietary/medication history + iron study panel + smear features + force the student to integrate everything for diagnosis OR next best step.
//
// PDF Mapping Check: Found
// PDF Filename: Lecture # 151. G. Saggio, D.O. (PPT).pdf
// Mapping Key: 17-Hematology: Laboratory Medicine and Anemias Part 1 - Vignettes (L151 Part 2)
// Status: Verified

const Test_L151_Part2 = [
  {
    "id": 1,
    "category": "Hematology: IDA Workup in Adult Male",
    "questionText": "A 58-year-old previously healthy man presents to his PCP with 3 months of progressive fatigue and exertional dyspnea. He denies overt GI bleeding, melena, or hematochezia. PMH: HTN on lisinopril; takes ibuprofen 600 mg TID for chronic knee pain. Vitals: T 37.0°C, HR 92, BP 132/78. Exam: pale conjunctiva, no organomegaly, brown stool guaiac POSITIVE. Labs: Hgb 8.2, MCV 72, RDW 18.5, ferritin 8, TIBC 480, transferrin sat 6%, retic 1.0%. Which is the most appropriate NEXT step?",
    "options": [
      { "text": "Start oral ferrous sulfate 325 mg TID and reassess Hgb in 6 weeks without further workup", "explanation": "Incorrect. While oral iron repletion will treat the iron deficiency anemia, this approach overlooks the critical issue: in an adult male or postmenopausal female, new IDA must be considered occult GI blood loss until proven otherwise. Treating the anemia without investigating the cause risks missing a colorectal malignancy. This would be the correct answer if the patient were a premenopausal woman with documented heavy menstrual losses and no other risk factors." },
      { "text": "Perform bidirectional endoscopy (colonoscopy + upper endoscopy) to evaluate for occult GI blood loss", "explanation": "Correct. This patient has classic IDA (low ferritin, low transferrin sat, high TIBC, elevated RDW, microcytic anemia) and a guaiac-positive stool. In an adult male or postmenopausal female, new IDA is GI blood loss until proven otherwise — colorectal cancer is the most concerning etiology and must be excluded. NSAID use (his chronic ibuprofen) further raises suspicion for upper GI mucosal injury/ulcer. Standard workup includes COLONOSCOPY plus upper endoscopy (bidirectional endoscopy). Oral iron should be started concurrently, but bidirectional endoscopy is the most important next step." },
      { "text": "Obtain hemoglobin electrophoresis to evaluate for beta-thalassemia minor", "explanation": "Incorrect. The iron study pattern (LOW ferritin, HIGH TIBC, LOW transferrin sat, elevated RDW) is diagnostic of iron deficiency, not thalassemia. Beta-thal minor would show NORMAL iron studies and a normal RDW. This would be the correct answer if iron studies were normal in a microcytic anemia with normal RDW, especially in a Mediterranean/Southeast Asian patient." },
      { "text": "Begin recombinant erythropoietin (epoetin alfa) subcutaneous injections", "explanation": "Incorrect. EPO therapy is reserved for hypoproliferative anemias from EPO deficiency, primarily anemia of CKD. This patient has IDA, not EPO deficiency; iron is the problem, not the hormone signal. Giving EPO without adequate iron stores can actually worsen the picture. This would be the correct answer in a CKD patient with GFR <30 and adequately replete iron stores." },
      { "text": "Initiate IV ferric carboxymaltose without further workup since oral iron is contraindicated", "explanation": "Incorrect. Oral iron is not contraindicated in this patient — there is no inflammatory bowel disease, malabsorption, or oral iron intolerance documented. IV iron is reserved for malabsorption, intolerance to oral iron, or need for rapid repletion. More importantly, this option still fails to investigate the underlying GI source. This would be the correct answer if the patient had documented oral iron intolerance after a trial and active inflammatory bowel disease preventing absorption." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: New IDA in adult male or postmenopausal female = GI bleed until proven otherwise. Bidirectional endoscopy (colonoscopy + EGD) is mandatory. NSAID use raises upper GI ulcer risk.",
    "pdfPage": 13,
    "pdfQuote": "iron deficiency"
  },
  {
    "id": 2,
    "category": "Hematology: ACD vs IDA Distinction",
    "questionText": "A 68-year-old woman with a 12-year history of seropositive rheumatoid arthritis on methotrexate and prednisone presents with worsening fatigue. Vitals: T 37.4°C, HR 88, BP 128/76. Exam: bilateral MCP synovitis, no hepatosplenomegaly. Labs: Hgb 9.5, MCV 82, RDW 13.5, ferritin 280, TIBC 220, transferrin sat 14%, serum iron 35, CRP 32 (elevated), retic 0.8%. Bone marrow biopsy shows adequate iron stores in macrophages. Which is the most likely diagnosis AND best initial management approach?",
    "options": [
      { "text": "Iron deficiency anemia — start ferrous sulfate 325 mg TID", "explanation": "Incorrect. The iron study pattern excludes IDA: HIGH ferritin (280), LOW TIBC (220), and adequate iron in bone marrow macrophages all point AWAY from iron deficiency. The single value that overlaps with IDA is the low transferrin saturation, but the high ferritin (an acute phase reactant) and adequate bone marrow iron stores rule out true iron deficiency. This would be the correct answer if ferritin were LOW and TIBC HIGH." },
      { "text": "Anemia of chronic disease — optimize control of underlying rheumatoid arthritis", "explanation": "Correct. The iron study pattern is classic for ANEMIA OF CHRONIC DISEASE/INFLAMMATION: HIGH ferritin (acute phase reactant), LOW TIBC, LOW transferrin sat, LOW serum iron, and importantly, ADEQUATE iron in bone marrow macrophages (iron is present but TRAPPED by hepcidin, which is upregulated by inflammatory cytokines IL-6). The bone marrow biopsy confirming adequate iron stores is the key finding. Treatment is to control the underlying inflammatory disease (optimize RA therapy — consider escalation to a biologic DMARD), not iron supplementation. Adjunctive EPO or IV iron may be considered in select cases. Hepcidin antagonists are an emerging therapy." },
      { "text": "Sideroblastic anemia — start pyridoxine (vitamin B6) supplementation", "explanation": "Incorrect. Sideroblastic anemia would show HIGH ferritin AND HIGH transferrin saturation (because iron accumulates in mitochondria but cannot be incorporated into heme), and bone marrow would show RINGED SIDEROBLASTS on Prussian blue stain. This patient has low transferrin sat and no ringed sideroblasts. This would be the correct answer if the bone marrow biopsy showed ringed sideroblasts and the patient had an INH exposure or B6 deficiency context." },
      { "text": "Mixed IDA and ACD — start IV ferric carboxymaltose plus erythropoietin", "explanation": "Incorrect. While mixed IDA and ACD does occur and can be diagnostically challenging, the adequate iron stores on bone marrow biopsy and high ferritin rule out concurrent iron deficiency in this patient. Adding IV iron in the absence of iron deficiency is unhelpful and exposes the patient to anaphylaxis risk. This would be the correct answer if both conditions coexisted (suggested by elevated soluble transferrin receptor in the setting of inflammation)." },
      { "text": "Thalassemia trait — confirm with hemoglobin electrophoresis", "explanation": "Incorrect. Thalassemia trait shows NORMAL iron studies and a NORMAL RDW. This patient has abnormal iron studies (high ferritin, low TIBC) consistent with inflammation. This would be the correct answer if iron studies were normal in a microcytic anemia of someone with Mediterranean or Southeast Asian ancestry." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: ACD = high ferritin + low TIBC + low transferrin sat + adequate marrow iron. Treat the underlying inflammation; iron supplementation is generally NOT helpful (and may worsen).",
    "pdfPage": 14,
    "pdfQuote": "anemia of chronic disease"
  },
  {
    "id": 3,
    "category": "Hematology: Beta-Thalassemia Trait in Pregnancy",
    "questionText": "A 28-year-old G1P0 Greek-American woman at 12 weeks gestation presents for prenatal labs. She is asymptomatic. Vitals: T 36.9°C, BP 110/68, HR 84. Exam unremarkable. Labs: Hgb 10.5, MCV 64 (markedly low), RDW 13.0 (NORMAL), ferritin 95, TIBC 290, transferrin sat 22%, serum iron 65. Peripheral smear shows numerous TARGET CELLS. The OB is considering empiric oral iron. Which is the most appropriate NEXT diagnostic step before treatment?",
    "options": [
      { "text": "Start ferrous sulfate 325 mg TID and reassess Hgb at 28 weeks", "explanation": "Incorrect. The combination of normal iron studies (normal ferritin, normal transferrin sat), NORMAL RDW (vs elevated in IDA), target cells on smear, and Greek (Mediterranean) ancestry strongly suggests beta-thalassemia minor rather than iron deficiency. Giving iron empirically without confirming diagnosis is incorrect, as iron overload can develop in true thalassemia patients receiving chronic supplementation. This would be the correct answer if iron studies clearly showed deficiency (low ferritin, high TIBC, elevated RDW)." },
      { "text": "Obtain hemoglobin electrophoresis to evaluate for beta-thalassemia and to enable partner screening", "explanation": "Correct. The findings (microcytic anemia with disproportionately low MCV for the degree of anemia, NORMAL iron studies, normal RDW, target cells, Mediterranean ancestry) point to BETA-THALASSEMIA MINOR. Hemoglobin electrophoresis is diagnostic, classically showing ELEVATED HbA2 (>3.5%) ± elevated HbF. Confirming the diagnosis is critical for two reasons: (1) avoids unnecessary iron supplementation (which could cause iron overload over time), and (2) prompts PARTNER SCREENING — if both parents have beta-thal trait, offspring have a 25% chance of beta-thal MAJOR, a transfusion-dependent disease. Genetic counseling can then be offered." },
      { "text": "Start intravenous iron therapy with ferric carboxymaltose", "explanation": "Incorrect. There is no evidence of iron deficiency, so IV iron is unnecessary and potentially harmful (could promote iron overload in true thalassemia). This would be the correct answer in confirmed iron-deficient pregnancy with malabsorption or oral iron intolerance." },
      { "text": "Initiate red blood cell transfusion to target Hgb >12", "explanation": "Incorrect. Mild anemia (Hgb 10.5) in early pregnancy does NOT require transfusion. Beta-thal minor patients typically have mild stable anemia and do not require transfusion support. Transfusion in pregnancy is reserved for severe anemia (Hgb <7) or symptomatic disease. This would be the correct answer if the patient had severe anemia (Hgb <7) with hemodynamic compromise." },
      { "text": "Refer for bone marrow biopsy to rule out myelodysplastic syndrome", "explanation": "Incorrect. MDS in a 28-year-old without prior chemotherapy/radiation is extremely rare; the clinical picture (Mediterranean ancestry, normal iron studies, target cells, normal RDW) far better fits beta-thal trait. Bone marrow biopsy is overly invasive without supporting clinical features. This would be the correct answer in an older patient with unexplained pancytopenia, dysplastic features, or 5-19% marrow blasts." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Microcytic anemia + NORMAL iron studies + normal RDW + target cells + Mediterranean ancestry → check Hb electrophoresis for beta-thal minor (elevated HbA2). Then screen partner for genetic counseling.",
    "pdfPage": 17,
    "pdfQuote": "beta-thalassemia"
  },
  {
    "id": 4,
    "category": "Hematology: Lead Poisoning Management",
    "questionText": "A 3-year-old boy from a pre-1978 housing unit presents to his pediatrician with developmental delay, behavioral changes, and intermittent abdominal pain. His mother reports he chews on the painted windowsills. Vitals: T 37.1°C, HR 110, BP 102/64. Exam: lethargic, mild abdominal tenderness, no organomegaly. Labs: Hgb 9.2, MCV 70, RDW 14.0, ferritin 45, BASOPHILIC STIPPLING on peripheral smear, elevated free erythrocyte protoporphyrin. Venous blood lead level returns at 62 µg/dL. Which is the most appropriate NEXT step?",
    "options": [
      { "text": "Outpatient nutritional counseling and recheck blood lead in 3 months", "explanation": "Incorrect. A blood lead level of 62 µg/dL is a medical emergency requiring immediate chelation (CDC threshold for chelation is generally ≥45 µg/dL). Outpatient counseling alone for a level this high risks irreversible neurodevelopmental damage. This would be the correct answer for a mildly elevated lead level (5-14 µg/dL) without anemia where environmental abatement is sufficient." },
      { "text": "Initiate hospital admission with chelation therapy (oral succimer/DMSA, or for very severe disease IV calcium EDTA + dimercaprol) AND environmental abatement", "explanation": "Correct. This child has SEVERE lead poisoning (level >45 µg/dL, with classic features: microcytic anemia, basophilic stippling, elevated erythrocyte protoporphyrin, behavioral changes, abdominal pain, exposure history). Management requires: (1) HOSPITAL ADMISSION, (2) CHELATION THERAPY — succimer (DMSA, oral) for levels 45-69 µg/dL; for severe disease (>70 µg/dL or encephalopathy), use IV calcium disodium EDTA PLUS dimercaprol/BAL (started first to prevent EDTA from mobilizing lead into the brain), and (3) ENVIRONMENTAL ABATEMENT — child must NOT return to the lead source. Multidisciplinary involvement (pediatrics, toxicology, public health) is essential." },
      { "text": "Start oral iron supplementation alone and recheck CBC in 2 weeks", "explanation": "Incorrect. Iron supplementation can be useful adjunctively (iron deficiency increases lead absorption from the gut), but it does not treat lead toxicity itself. The dominant problem at level 62 is lead's direct multi-organ toxicity, not iron deficiency. This would be the correct answer for isolated mild iron deficiency without lead exposure." },
      { "text": "Order hemoglobin electrophoresis to evaluate for beta-thalassemia minor", "explanation": "Incorrect. While beta-thal minor and lead poisoning are both microcytic anemias, the history of pica/lead exposure, basophilic stippling, abdominal symptoms, behavioral changes, and elevated venous lead level make the diagnosis straightforward. Hb electrophoresis is not the next priority here. This would be the correct answer if lead level were normal and microcytic anemia were unexplained in an at-risk ethnic group." },
      { "text": "Schedule a bone marrow biopsy to rule out sideroblastic anemia", "explanation": "Incorrect. While lead poisoning CAN cause sideroblastic-like changes, bone marrow biopsy is not necessary in a child with a clear lead exposure history and elevated venous lead level. Treatment of the lead intoxication is the priority. This would be the correct answer in an unexplained sideroblastic anemia in an adult with no toxin exposure." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Blood lead ≥45 µg/dL = chelation. Succimer (DMSA) for moderate; IV EDTA + dimercaprol (BAL) for severe/encephalopathy. ALWAYS combine with environmental abatement.",
    "pdfPage": 16,
    "pdfQuote": "lead poisoning"
  },
  {
    "id": 5,
    "category": "Hematology: Isoniazid-Induced Sideroblastic Anemia",
    "questionText": "A 45-year-old man with latent tuberculosis has been on isoniazid (INH) monotherapy for 5 months. He presents with progressive fatigue. Vitals: T 37.0°C, BP 130/82, HR 78. Exam: pale, no organomegaly, mild peripheral neuropathy on sensory testing. Labs: Hgb 8.8, MCV 78, ferritin 580, TIBC 240, transferrin sat 65%, serum iron 155. Bone marrow biopsy with Prussian blue stain shows RINGED SIDEROBLASTS in erythroid precursors. Which is the most appropriate management?",
    "options": [
      { "text": "Discontinue INH and start pyridoxine (vitamin B6) supplementation", "explanation": "Correct. INH causes sideroblastic anemia and peripheral neuropathy through vitamin B6 (pyridoxine) depletion. INH chemically binds pyridoxine and accelerates its excretion, depriving heme synthesis enzymes (particularly ALA synthase) of their essential cofactor. The result: defective heme synthesis → iron accumulates in mitochondria of erythroid precursors → RINGED SIDEROBLASTS. Management: (1) supplement vitamin B6 to reverse the metabolic block (B6 is also standardly given prophylactically when INH is initiated to PREVENT this complication, especially in at-risk patients — alcoholics, malnourished, HIV+, pregnant); (2) review whether continued INH is still needed. The anemia (and neuropathy) typically resolve with B6." },
      { "text": "Start iron chelation therapy with deferasirox", "explanation": "Incorrect. While ferritin is elevated reflecting tissue iron accumulation, the underlying problem is FAILURE TO USE iron (defective heme synthesis), not absolute iron overload. Removing iron will not fix the metabolic block. Restoring B6 reverses the defect. This would be the correct answer in established hereditary hemochromatosis with iron overload and end-organ damage in a patient who cannot tolerate phlebotomy." },
      { "text": "Initiate oral iron supplementation to correct microcytosis", "explanation": "Incorrect. This patient does not have iron deficiency — iron studies show HIGH ferritin and HIGH transferrin saturation. Giving more iron would worsen iron loading without correcting the underlying B6-deficient heme synthesis block. This would be the correct answer for true iron deficiency anemia." },
      { "text": "Initiate red blood cell transfusion every 4-6 weeks", "explanation": "Incorrect. Chronic transfusion exposes the patient to iron overload (especially problematic given his already elevated ferritin) and is reserved for severe, refractory, transfusion-dependent disease. The simpler and definitive treatment here is B6 supplementation, which addresses the cause. This would be the correct answer in severe refractory sideroblastic anemia not responsive to B6 (e.g., congenital X-linked sideroblastic anemia)." },
      { "text": "Begin allogeneic stem cell transplant evaluation", "explanation": "Incorrect. Stem cell transplant is reserved for severe, transfusion-dependent acquired or hereditary sideroblastic anemia (or MDS-associated sideroblastic anemia in younger patients with high-risk features) — not for reversible drug-induced cases. Removing INH and giving B6 will resolve this case. This would be the correct answer in a young patient with severe MDS with ringed sideroblasts and other high-risk MDS features." }
    ],
    "correctAnswerIndex": 0,
    "clinicalPearl": "Key takeaway: INH causes sideroblastic anemia + peripheral neuropathy via B6 depletion. Reverse with PYRIDOXINE (B6). Prophylactic B6 should be coadministered with INH in at-risk patients.",
    "pdfPage": 16,
    "pdfQuote": "sideroblastic anemia"
  },
  {
    "id": 6,
    "category": "Hematology: Hereditary Hemochromatosis Workup",
    "questionText": "A 52-year-old man of Northern European descent presents with fatigue, decreased libido, and joint pain in his 2nd and 3rd MCP joints. He has new-onset diabetes (HbA1c 7.4%) and recently noticed bronze skin. PMH: heavy alcohol use (4 drinks/day). Vitals: T 37.0°C, BP 138/86, HR 76. Exam: hepatomegaly, bronze hyperpigmentation, no scleral icterus. Labs: AST 78, ALT 95, ALP 110, total bilirubin 1.1, ferritin 1,850 (markedly elevated), transferrin saturation 92%, fasting glucose 145. Which is the most appropriate NEXT diagnostic step?",
    "options": [
      { "text": "Liver biopsy with quantitative iron measurement and Perls stain", "explanation": "Incorrect. While liver biopsy was historically the gold standard, it is now reserved for assessing fibrosis stage in patients with ferritin >1000 or to evaluate concomitant liver disease — NOT as the initial diagnostic test. Modern workup begins with non-invasive genetic testing (HFE) given the high pretest probability here. This would be the correct answer if HFE genetic testing were equivocal and assessment for cirrhosis were needed." },
      { "text": "HFE gene mutation analysis (C282Y homozygosity or C282Y/H63D compound heterozygosity)", "explanation": "Correct. This patient has the classic clinical syndrome of hereditary hemochromatosis: middle-aged man of Northern European descent + fatigue + diabetes ('bronze diabetes') + arthropathy of 2nd/3rd MCP joints + bronze skin + hepatomegaly + transaminitis + markedly elevated ferritin and transferrin saturation. Transferrin saturation >45% (here 92%) is the most sensitive screening test. The next step is HFE gene testing for C282Y/H63D mutations — C282Y homozygosity is found in ~85% of clinically affected patients. Confirming the diagnosis allows family screening (first-degree relatives), guides treatment (therapeutic phlebotomy, NOT chelation), and prompts cancer surveillance (HCC risk increased if cirrhosis develops). Alcohol cessation is also critical." },
      { "text": "Begin empiric iron chelation therapy with deferasirox immediately", "explanation": "Incorrect. First-line therapy for hereditary hemochromatosis is THERAPEUTIC PHLEBOTOMY (typically weekly until ferritin <50, then maintenance every 2-4 months), NOT chelation. Chelation (deferasirox, deferoxamine) is reserved for patients who cannot tolerate phlebotomy (e.g., severe anemia, cardiac dysfunction). Also, treatment should not begin until diagnosis is confirmed. This would be the correct answer in transfusion-related iron overload (e.g., chronic transfusion-dependent thalassemia) where phlebotomy is not an option." },
      { "text": "Order serum ceruloplasmin and 24-hour urinary copper to evaluate for Wilson disease", "explanation": "Incorrect. Wilson disease can present with hepatic dysfunction in young adults but classically with Kayser-Fleischer rings, neuropsychiatric symptoms, LOW ceruloplasmin, and high urinary copper — not bronze diabetes with elevated ferritin and transferrin saturation. The clinical picture here is clearly hemochromatosis. This would be the correct answer in a 25-year-old with hepatic dysfunction, neuropsychiatric features, and Kayser-Fleischer rings." },
      { "text": "Send anti-mitochondrial antibody (AMA) to evaluate for primary biliary cholangitis", "explanation": "Incorrect. PBC presents with cholestatic liver enzymes (markedly elevated alkaline phosphatase), pruritus, fatigue, and predominantly affects middle-aged women — not the iron overload syndrome described. The lab pattern here (transaminitis + extreme ferritin elevation + transferrin sat 92%) is diagnostic of iron overload, not cholestatic liver disease. This would be the correct answer in a middle-aged woman with cholestatic pattern and pruritus." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Bronze diabetes + arthropathy + transaminitis + high ferritin + transferrin sat >45% → HFE gene testing (C282Y homozygosity). Treat with phlebotomy (NOT chelation). Screen first-degree relatives.",
    "pdfPage": 14,
    "pdfQuote": "transferrin saturation"
  },
  {
    "id": 7,
    "category": "Hematology: IDA in Pregnancy",
    "questionText": "A 26-year-old G2P1 woman at 30 weeks gestation presents for routine prenatal labs. She follows a vegan diet and reports increasing fatigue. Vitals: BP 110/68, HR 88. Exam: pale conjunctiva, gravid uterus consistent with dates, no organomegaly. Labs: Hgb 8.5 (down from 11.2 at 12 weeks), MCV 71, RDW 17, ferritin 8, TIBC 510, transferrin sat 7%, serum iron 22. She has tolerated oral ferrous sulfate 325 mg daily but is non-compliant due to constipation and nausea, with minimal Hgb response over 4 weeks. Which is the most appropriate NEXT step?",
    "options": [
      { "text": "Continue oral ferrous sulfate at the same dose and reassess at 38 weeks", "explanation": "Incorrect. The patient has demonstrated intolerance to oral iron AND inadequate response — the Hgb has not risen significantly in 4 weeks. Time is short in the third trimester before delivery, when blood loss is expected. Switching strategy is needed. This would be the correct answer if the patient were tolerating oral iron and showing a reticulocytosis with rising Hgb." },
      { "text": "Initiate IV iron therapy with ferric carboxymaltose or iron sucrose", "explanation": "Correct. This patient has severe iron-deficiency anemia in the third trimester (Hgb 8.5) with intolerance to oral iron AND inadequate response after a trial. IV iron is indicated when: (1) oral iron is not tolerated, (2) absorption is inadequate, (3) rapid repletion is needed, or (4) there is insufficient time before delivery. IV iron (ferric carboxymaltose, iron sucrose, or ferric gluconate) is safe in the 2nd and 3rd trimesters and produces rapid iron repletion. Goal is to optimize Hgb before delivery to reduce transfusion risk and improve maternal/neonatal outcomes." },
      { "text": "Switch to alternative oral iron formulation (e.g., ferrous gluconate or carbonyl iron)", "explanation": "Incorrect. While alternative oral formulations may be better tolerated, the response time is too slow given proximity to delivery and the severe anemia. IV iron is more appropriate at 30 weeks with intolerance to oral. This would be the correct answer in the 1st or 2nd trimester with mild anemia and time for a slower oral trial." },
      { "text": "Initiate red blood cell transfusion to target Hgb >10", "explanation": "Incorrect. RBC transfusion in pregnancy is reserved for severe anemia (Hgb <7) with symptoms or hemodynamic compromise, or for active blood loss. At Hgb 8.5 in an otherwise stable patient, IV iron is preferred to address the underlying iron deficiency. This would be the correct answer in a patient with Hgb <7 with severe symptoms or acute hemorrhage." },
      { "text": "Begin recombinant erythropoietin (epoetin alfa) injections", "explanation": "Incorrect. EPO is not standard therapy for iron deficiency in pregnancy unless there is concurrent CKD with EPO deficiency. The patient has plenty of EPO drive (her anemia stimulates endogenous EPO); the problem is lack of substrate (iron). Giving EPO without correcting iron deficiency is ineffective. This would be the correct answer in a pregnant CKD patient with EPO deficiency after iron repletion." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: 3rd trimester IDA + oral iron intolerance/failure → IV iron (ferric carboxymaltose, iron sucrose). Safe in 2nd/3rd trimesters; rapid repletion before delivery reduces transfusion risk.",
    "pdfPage": 13,
    "pdfQuote": "iron deficiency"
  },
  {
    "id": 8,
    "category": "Hematology: CKD Anemia Management",
    "questionText": "A 64-year-old man with diabetic nephropathy (eGFR 22) is followed in nephrology clinic. He reports fatigue and exertional dyspnea. Vitals: BP 138/80, HR 82. Exam: pale conjunctiva, bilateral lower extremity edema, no organomegaly. Labs: Hgb 9.2, MCV 88, RDW 13.2, ferritin 320, TIBC 230, transferrin sat 28%, serum iron 64, retic 0.9%. Erythropoietin level low. B12 and folate normal. Which is the most appropriate management?",
    "options": [
      { "text": "Start oral ferrous sulfate 325 mg TID", "explanation": "Incorrect. Iron studies do not show iron deficiency (ferritin 320, transferrin sat 28% are adequate). The dominant problem is EPO deficiency from CKD. Treating with iron alone will not correct the anemia. This would be the correct answer in CKD patients with concurrent absolute iron deficiency (ferritin <100, transferrin sat <20%)." },
      { "text": "Initiate erythropoiesis-stimulating agent (epoetin alfa or darbepoetin) targeting Hgb 10-11.5", "explanation": "Correct. This patient has the classic anemia of CKD: NORMOCYTIC, NORMOCHROMIC anemia with LOW reticulocyte count, LOW erythropoietin, and adequate iron stores. Mechanism: failing kidneys do not produce sufficient EPO. Treatment: recombinant EPO (epoetin alfa, darbepoetin) targeting Hgb 10-11.5 g/dL. Higher Hgb targets (>13) have been associated with increased cardiovascular events (TREAT trial in DM-CKD; CHOIR/CREATE/Normal Hematocrit trials) — so the target is intentionally modest. Adequate iron stores (ferritin 100-500, transferrin sat >20%) must be maintained for EPO to work; if iron drops, give IV iron in CKD patients (oral iron absorption is impaired in CKD). Newer agents include HIF-PH inhibitors (roxadustat, daprodustat) which stimulate endogenous EPO production." },
      { "text": "Schedule immediate RBC transfusion to target Hgb >12", "explanation": "Incorrect. RBC transfusion in CKD anemia is reserved for symptomatic severe anemia (Hgb <7) or acute blood loss — not for chronic asymptomatic-to-mild anemia. Chronic transfusions also expose the patient to iron overload, alloimmunization (problematic for future transplant), and infection risk. This would be the correct answer if the patient had severe symptomatic anemia or active hemorrhage." },
      { "text": "Begin IV iron sucrose alone (no EPO)", "explanation": "Incorrect. While CKD patients often need IV iron to maintain stores, this patient already has adequate ferritin and transferrin saturation. IV iron alone without EPO will not stimulate erythropoiesis. EPO is the primary deficient hormone. This would be the correct answer if iron stores were depleted (ferritin <100, transferrin sat <20%) and EPO was not yet indicated." },
      { "text": "Bone marrow biopsy to rule out myelodysplastic syndrome", "explanation": "Incorrect. The clinical picture (CKD with low EPO, normocytic anemia, adequate iron) is straightforward for anemia of CKD. Bone marrow biopsy is invasive and unnecessary. This would be the correct answer with unexplained cytopenias, dysplastic features on smear, or 5-19% blasts." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: CKD anemia = EPO deficiency. Target Hgb 10-11.5 with ESA (epoetin/darbepoetin). Maintain iron stores (ferritin >100, transferrin sat >20%). Higher Hgb targets increase CV risk.",
    "pdfPage": 15,
    "pdfQuote": "erythropoietin"
  },
  {
    "id": 9,
    "category": "Hematology: Aplastic Anemia from Chloramphenicol",
    "questionText": "A 25-year-old returned Peace Corps volunteer was treated with chloramphenicol for typhoid fever during her deployment 2 months ago. She presents with petechiae on her shins, fatigue, and a 3-day history of fever (38.5°C). Vitals: T 38.5°C, HR 105, BP 110/64, RR 18. Exam: petechial rash on lower extremities, oral mucosal pallor, no hepatosplenomegaly or lymphadenopathy. Labs: WBC 1.8 (ANC 400), Hgb 6.5, platelets 18, reticulocyte count 0.2%, MCV 92. Bone marrow biopsy shows MARKEDLY HYPOCELLULAR marrow with fatty replacement and no infiltrate. Which is the most likely diagnosis?",
    "options": [
      { "text": "Acute myeloid leukemia", "explanation": "Incorrect. AML would show HYPERCELLULAR marrow with ≥20% blasts; this patient has a HYPOCELLULAR marrow with fatty replacement, the opposite picture. This would be the correct answer if the marrow biopsy showed sheets of myeloblasts ≥20% with Auer rods." },
      { "text": "Aplastic anemia, likely chloramphenicol-induced", "explanation": "Correct. The clinical picture is classic for APLASTIC ANEMIA: PANCYTOPENIA (low WBC, low Hgb, low platelets), severe reticulocytopenia (0.2%), and HYPOCELLULAR bone marrow with FATTY REPLACEMENT and no infiltrate. The drug exposure clue (CHLORAMPHENICOL) is a well-known cause of both DOSE-DEPENDENT reversible marrow suppression AND IDIOSYNCRATIC aplastic anemia (rare, ~1 in 25,000, occurring weeks to months after exposure and often fatal). Other drug culprits: carbamazepine, sulfa drugs, gold, methimazole. Other causes: idiopathic (most common), benzene, radiation, viral hepatitis (non-A, non-B, non-C), parvovirus B19 (causes pure red cell aplasia specifically). Treatment: immunosuppression (ATG + cyclosporine) for older or non-transplant candidates; allogeneic stem cell transplant for younger patients with HLA-matched donors." },
      { "text": "Myelodysplastic syndrome with excess blasts", "explanation": "Incorrect. MDS typically shows HYPERCELLULAR marrow with dysplastic morphology and 5-19% blasts (≥20% would be AML). This patient has hypocellular marrow without dysplasia or excess blasts. Hypocellular MDS exists but is rare; the patient's recent chloramphenicol exposure makes aplastic anemia more likely. This would be the correct answer if marrow were hypercellular with dysplastic precursors and blasts in 5-19% range." },
      { "text": "Megaloblastic anemia from severe B12 deficiency", "explanation": "Incorrect. B12 deficiency causes MEGALOBLASTIC anemia with MCV >100, hypersegmented neutrophils, and HYPERCELLULAR marrow (paradoxical — ineffective hematopoiesis). This patient has normocytic anemia and hypocellular marrow. This would be the correct answer with MCV >100, hypersegmented neutrophils on smear, and a vegan diet or pernicious anemia history." },
      { "text": "Iron deficiency anemia from chronic GI loss", "explanation": "Incorrect. IDA does not cause pancytopenia — it causes isolated MICROCYTIC anemia (MCV <80), not normocytic pancytopenia with hypocellular marrow. This would be the correct answer with isolated microcytic anemia and low ferritin." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Pancytopenia + HYPOCELLULAR marrow with fatty replacement = aplastic anemia. Drug causes: chloramphenicol, carbamazepine, sulfa, gold, methimazole. Tx: immunosuppression (ATG+CSA) or allogeneic SCT.",
    "pdfPage": 23,
    "pdfQuote": "aplastic anemia"
  },
  {
    "id": 10,
    "category": "Hematology: Mixed IDA + ACD",
    "questionText": "A 72-year-old man with chronic heart failure, rheumatoid arthritis, and chronic GI blood loss from NSAID-induced gastritis presents with worsening fatigue. Vitals: BP 124/76, HR 92. Exam: pale conjunctiva, RA changes in hands, no acute distress. Labs: Hgb 8.4, MCV 75, RDW 19.5, ferritin 140 (within normal range), TIBC 250, transferrin sat 12%, serum iron 30, CRP 28 (elevated), soluble transferrin receptor (sTfR) markedly elevated. Which is the most likely diagnosis?",
    "options": [
      { "text": "Pure anemia of chronic disease only — no need for iron supplementation", "explanation": "Incorrect. In a pure ACD picture, the elevated sTfR would NOT be present — sTfR is a marker of iron-deficient erythropoiesis that is NOT affected by inflammation (unlike ferritin). The markedly elevated sTfR here indicates that despite the normal-range ferritin (falsely elevated by inflammation), the marrow is iron-starved. This would be the correct answer if sTfR were normal and ferritin were appropriately elevated without need for iron." },
      { "text": "Pure iron deficiency anemia only — ignore the inflammatory markers", "explanation": "Incorrect. The elevated CRP and chronic inflammatory conditions clearly indicate concurrent inflammation/ACD. Ferritin in pure IDA would be markedly LOW (<30); a 'normal range' ferritin in this setting is artificially elevated by the inflammation, masking the iron deficiency. The combination is MIXED IDA + ACD. This would be the correct answer if there were no inflammatory disease and ferritin were clearly low." },
      { "text": "Mixed iron deficiency anemia AND anemia of chronic disease — IV iron supplementation indicated alongside disease control", "explanation": "Correct. This is a classic MIXED IDA + ACD presentation. Clues: (1) elevated SOLUBLE TRANSFERRIN RECEPTOR (sTfR) — unaffected by inflammation, so it stays elevated in iron deficiency even when ferritin is masked; (2) ferritin is 'normal' but disproportionately low for the degree of inflammation (cutoff for IDA in setting of inflammation is often raised to ferritin <100); (3) low transferrin saturation and low serum iron; (4) chronic GI losses providing a mechanism for iron deficiency. Management: IV IRON (oral absorption is impaired by hepcidin in ACD) PLUS optimization of underlying inflammatory disease. Soluble transferrin receptor (or sTfR/log ferritin ratio) is the workhorse test for detecting concurrent iron deficiency in patients with ACD." },
      { "text": "Beta-thalassemia minor with concurrent inflammation", "explanation": "Incorrect. Beta-thal minor has normal iron studies (normal ferritin, normal TIBC, normal transferrin sat) and a normal RDW. This patient has an elevated RDW and the iron studies are abnormal with elevated sTfR — beta-thal does not fit. This would be the correct answer in a Mediterranean patient with normal iron studies, normal RDW, and target cells." },
      { "text": "Sideroblastic anemia from lead exposure", "explanation": "Incorrect. Sideroblastic anemia shows HIGH ferritin and HIGH transferrin saturation, with ringed sideroblasts on bone marrow. Lead poisoning shows basophilic stippling and is suggested by lead exposure history. Neither fits this patient. This would be the correct answer with elevated lead level and basophilic stippling." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: When IDA and ACD coexist, ferritin is unreliable (inflammation falsely elevates it). SOLUBLE TRANSFERRIN RECEPTOR (sTfR) is the key test — unaffected by inflammation. Use IV iron (hepcidin blocks oral absorption in ACD).",
    "pdfPage": 14,
    "pdfQuote": "transferrin receptor"
  },
  {
    "id": 11,
    "category": "Hematology: B12 Deficiency from Long-Term PPI",
    "questionText": "A 78-year-old woman on omeprazole for the past 12 years for GERD presents to her PCP with progressive fatigue, gait imbalance, and tingling in both feet. She has no GI symptoms. Vitals: T 36.8°C, BP 128/74, HR 76. Exam: glossitis, decreased vibratory sense and proprioception in both feet, positive Romberg, brisk Achilles reflexes. Labs: Hgb 10.2, MCV 110, RDW 16, hypersegmented neutrophils on smear, serum B12 145 (low), methylmalonic acid 850 (markedly elevated), homocysteine 32 (elevated). Which is the most likely mechanism of her B12 deficiency?",
    "options": [
      { "text": "Inadequate dietary intake from progressive anorexia of aging", "explanation": "Incorrect. While dietary deficiency is possible, it is uncommon in non-vegan elderly with otherwise normal nutrition. The 12-year PPI exposure is a more likely culprit. This would be the correct answer in a strict vegan without animal product intake for years." },
      { "text": "Chronic PPI use causing reduced gastric acid → impaired release of B12 from food protein-binding", "explanation": "Correct. Long-term PPI use (and H2 blockers) reduces gastric acid secretion. Gastric acid is required to cleave dietary B12 from food protein, allowing it to bind R-binder (haptocorrin) in saliva, then be transferred to intrinsic factor in the duodenum. Without acid, B12 cannot be released from food, and chronic deficiency develops over years. Risk factors for PPI-associated B12 deficiency: long duration (>2 years), elderly, concurrent atrophic gastritis. Other consequences of PPIs to know: hypomagnesemia, increased fracture risk, C. difficile risk, possible CKD progression, dementia association. Management here: PARENTERAL B12 (IM cyanocobalamin) — oral B12 in high dose can also work since absorption uses both an IF-dependent and a passive paracellular route at high concentrations." },
      { "text": "Pernicious anemia from autoimmune destruction of parietal cells", "explanation": "Incorrect. While pernicious anemia is the most common cause of B12 deficiency overall, the patient's long-term PPI use provides a more proximate explanation. Pernicious anemia could be confirmed/excluded with anti-intrinsic factor antibody (more specific) or anti-parietal cell antibody (more sensitive). The PPI exposure shifts the most likely mechanism. This would be the correct answer if positive anti-IF antibodies were present without significant PPI use." },
      { "text": "Diphyllobothrium latum infestation acquired from undercooked freshwater fish", "explanation": "Incorrect. Fish tapeworm B12 deficiency is rare and occurs in people who eat raw freshwater fish (sushi, sashimi from infected sources). No exposure history is mentioned. This would be the correct answer if the patient consumed raw freshwater fish from endemic areas." },
      { "text": "Terminal ileal Crohn disease causing malabsorption", "explanation": "Incorrect. Crohn disease affecting the terminal ileum (where B12-IF complex is absorbed) is a recognized cause of B12 deficiency but is not suggested by this patient's history (no GI symptoms, no inflammatory bowel disease). This would be the correct answer in a patient with known Crohn ileitis or ileal resection." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Chronic PPI use → reduced gastric acid → impaired B12 release from food protein → B12 deficiency over years. Especially in the elderly. Other PPI consequences: hypomagnesemia, fractures, C. diff.",
    "pdfPage": 10,
    "pdfQuote": "B12"
  },
  {
    "id": 12,
    "category": "Hematology: Reticulocyte Response after Iron Repletion",
    "questionText": "A 35-year-old woman with heavy menstrual bleeding and confirmed IDA was started on oral ferrous sulfate 325 mg TID 8 days ago. She returns for follow-up. Vitals: BP 110/68, HR 78. Exam: improved energy. Labs: Hgb 10.5 (baseline 8.5), MCV 76 (baseline 72), reticulocyte count 8% (baseline 1.5%). She tolerates oral iron well. Which best describes the next expected lab finding 4-6 weeks from now if she continues therapy?",
    "options": [
      { "text": "Reticulocytosis will persist indefinitely throughout therapy at 8%", "explanation": "Incorrect. Reticulocytosis peaks 7-10 days after iron repletion begins and then DECLINES as the anemia corrects and EPO drive falls. Persistent high reticulocyte count at 6 weeks would suggest ongoing iron loss exceeding repletion. This would be the correct answer if the patient had ongoing blood loss not yet controlled." },
      { "text": "Hemoglobin and MCV will both rise, with ferritin gradually normalizing as the iron deficit closes", "explanation": "Correct. The expected response to iron therapy is well-defined: (1) RETICULOCYTOSIS within 5-10 days (already seen — 8% at day 8), peaking ~day 10; (2) HEMOGLOBIN rises ~1 g/dL per week for 6-8 weeks until normalized; (3) MCV normalizes more slowly as new normocytic RBCs replace microcytic ones over ~8-12 weeks; (4) FERRITIN/iron stores require 3-6 months of continued therapy after Hgb normalizes to fully repolish stores. The general rule: continue iron therapy for at least 3-6 months AFTER Hgb normalizes to replete iron stores. Failure to mount this response after 4 weeks of compliance with adequate-dose oral iron warrants reevaluation (compliance? absorption? ongoing loss? wrong diagnosis?)." },
      { "text": "Hgb will plateau at 10.5 and not rise further without IV iron", "explanation": "Incorrect. Oral iron at the dose given is generally sufficient for repletion in uncomplicated IDA — the patient is already responding well (Hgb up 2 g/dL in 8 days, brisk reticulocytosis). IV iron is reserved for malabsorption, intolerance, or rapid repletion needs. This would be the correct answer in a patient with celiac disease or persistent inability to absorb oral iron." },
      { "text": "Hgb will rise but reticulocyte count will paradoxically fall to ZERO due to suppression", "explanation": "Incorrect. Reticulocyte count will fall as the anemia corrects (lowering EPO drive) but will not drop to zero — it returns to normal baseline (~1-2%). This would be the correct answer in pure red cell aplasia (parvovirus B19 in sickle cell), where reticulocytes are completely absent." },
      { "text": "Pernicious anemia features will emerge requiring B12 replacement", "explanation": "Incorrect. There is no indication that this patient has B12 deficiency; her response to iron is appropriate for pure IDA. Adding B12 without indication is unnecessary. This would be the correct answer if the patient had concurrent B12 deficiency revealed by macrocytosis emerging during treatment." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: IDA response to iron — reticulocytosis at 5-10 days, Hgb ~1 g/dL/week, MCV normalizes slowly over 8-12 weeks. Continue iron 3-6 months AFTER Hgb normalization to replete stores.",
    "pdfPage": 12,
    "pdfQuote": "reticulocyte"
  },
  {
    "id": 13,
    "category": "Hematology: Pure Red Cell Aplasia in Sickle Cell",
    "questionText": "An 8-year-old girl with known sickle cell disease (HbSS) presents to the ED with profound fatigue, pallor, and shortness of breath. Her mother reports she had a 'slapped cheek' rash 10 days ago. Vitals: T 37.2°C, HR 140, BP 92/56, RR 24, O2 sat 94%. Exam: marked pallor, tachycardia, no jaundice or new pain crisis. Labs: Hgb 3.2 (baseline 9), reticulocyte count 0.1% (baseline 8-10%), platelets 240, WBC 6.0. Smear shows essentially NO RBCs being produced (no polychromasia, no reticulocytes). Which is the most likely cause?",
    "options": [
      { "text": "Acute splenic sequestration crisis with trapped RBCs in spleen", "explanation": "Incorrect. Splenic sequestration occurs in YOUNG children with sickle cell before autosplenectomy (typically before age 5), and presents with rapidly enlarging spleen. Reticulocyte count would be PRESERVED or elevated (marrow is responsive). At age 8 with HbSS, the spleen is usually already infarcted/autosplenectomized. This would be the correct answer in a 2-year-old with rapidly enlarging spleen and preserved reticulocytosis." },
      { "text": "Aplastic crisis from parvovirus B19 infection causing pure red cell aplasia", "explanation": "Correct. PARVOVIRUS B19 specifically infects erythroid precursors (binds to the P antigen receptor on erythroblasts), shutting down RBC production for 7-10 days. In a healthy person, this transient marrow shutdown is invisible because RBCs live ~120 days. But in sickle cell disease, the RBC lifespan is dramatically shortened (~17 days), so a 10-day pause in production = catastrophic Hgb crash (APLASTIC CRISIS). Clues: SLAPPED CHEEK rash (erythema infectiosum/Fifth disease) is the pathognomonic prodromal sign of parvovirus B19; profound RETICULOCYTOPENIA (0.1%) is the key lab finding distinguishing aplastic crisis from other acute anemia events in sickle cell (hyperhemolytic crisis would show retic UP); isolated red cell line affected (WBC and platelets preserved). Treatment: TRANSFUSION (urgently, target Hgb 8-10) to bridge until the marrow recovers in ~1 week; IVIG in immunocompromised. Pure red cell aplasia from parvovirus B19 is also seen in HIV (chronic anemia), transplant recipients, and fetuses (hydrops fetalis)." },
      { "text": "Vaso-occlusive pain crisis affecting vertebral bone marrow", "explanation": "Incorrect. Vaso-occlusive pain crisis presents with bone/joint/abdominal/chest pain (often acute chest syndrome if pulmonary), not isolated profound anemia with reticulocytopenia. This patient has no pain crisis described. This would be the correct answer in a sickle cell patient with severe musculoskeletal or chest pain." },
      { "text": "Acute hyperhemolytic crisis from new alloantibody", "explanation": "Incorrect. Hyperhemolytic crisis shows MARKED HEMOLYSIS (elevated bilirubin, LDH, low haptoglobin) with COMPENSATORY RETICULOCYTOSIS (retic UP, not down). This patient's retic is DOWN, indicating marrow failure rather than excess destruction. This would be the correct answer with rising bilirubin/LDH and brisk reticulocytosis after recent transfusion." },
      { "text": "Folate deficiency from chronic hemolysis exhausting folate stores", "explanation": "Incorrect. Folate deficiency in sickle cell can occur from chronic high RBC turnover, but it causes a MEGALOBLASTIC pattern with macrocytosis and pancytopenia, not isolated red cell aplasia with normal WBC and platelets. The slapped cheek rash and isolated red cell shutdown point to parvovirus. This would be the correct answer in a malnourished patient with macrocytic anemia and hypersegmented neutrophils." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Sickle cell + slapped cheek rash + profound anemia with retic ~0% = APLASTIC CRISIS from parvovirus B19. Treat with urgent transfusion; marrow recovers in ~1 week.",
    "pdfPage": 23,
    "pdfQuote": "aplastic"
  },
  {
    "id": 14,
    "category": "Hematology: Anemia of CKD Non-Responder",
    "questionText": "A 70-year-old dialysis-dependent patient on darbepoetin weekly for the past 4 months has not achieved a Hgb response (current Hgb 9.0, target 10-11.5). The dose of darbepoetin has been escalated twice without effect. Vitals: BP 144/82, HR 78. Exam: pale conjunctiva, dialysis fistula intact. Labs: ferritin 65, transferrin sat 14%, CRP 22 (elevated), B12 and folate normal, no overt blood loss. Which is the most likely cause of ESA hyporesponsiveness?",
    "options": [
      { "text": "Aluminum toxicity from old dialysate", "explanation": "Incorrect. Aluminum toxicity is rare with modern dialysis water purification and would more characteristically cause microcytic anemia with neurological symptoms (dialysis encephalopathy). The iron studies here clearly suggest iron deficiency. This would be the correct answer in a dialysis patient with neurologic symptoms and exposure to non-purified dialysate." },
      { "text": "Absolute iron deficiency (low ferritin <100, low transferrin sat <20%) AND functional iron deficiency from inflammation — supplement with IV iron", "explanation": "Correct. The most common causes of ESA hyporesponsiveness in CKD are: (1) ABSOLUTE iron deficiency (ferritin <100, transferrin sat <20%) — here the patient has both, and (2) FUNCTIONAL iron deficiency from inflammation (ferritin can appear adequate but iron is sequestered by hepcidin, marker = transferrin sat <20% with normal/high ferritin). Both forms are present in this patient (ferritin 65 + low TSAT + elevated CRP). Management: IV iron (oral iron poorly absorbed in CKD due to hepcidin); continue/optimize ESA; address underlying inflammation if possible. Other ESA hyporesponsiveness causes to consider: occult blood loss, hyperparathyroidism, malignancy, infection, B12/folate deficiency (already excluded here), aluminum toxicity (rare), pure red cell aplasia from anti-EPO antibodies (rare). Goal: replete iron, then reassess Hgb response." },
      { "text": "Hyperthyroidism causing rapid metabolism of darbepoetin", "explanation": "Incorrect. Thyroid dysfunction is not a typical cause of ESA hyporesponsiveness. This would be the correct answer if the patient had clear hyperthyroid features (weight loss, palpitations, heat intolerance, suppressed TSH)." },
      { "text": "Anti-EPO antibody-mediated pure red cell aplasia (rare ESA complication)", "explanation": "Incorrect. While this is a recognized rare complication of subcutaneous ESA (especially with certain epoetin formulations historically), it would present with profound reticulocytopenia (essentially zero) and rapidly worsening anemia despite escalating ESA doses — the picture would be more dramatic. Iron-related causes are far more common and should be excluded first. This would be the correct answer with retic count near zero and confirmed anti-EPO antibodies." },
      { "text": "Switch to oral ferrous sulfate to improve iron stores", "explanation": "Incorrect. Oral iron is poorly absorbed in CKD because chronic inflammation upregulates hepcidin, which blocks ferroportin and prevents enterocyte iron release into circulation. Standard of care in CKD with iron deficiency is IV iron (sucrose, ferric carboxymaltose, ferric gluconate, ferumoxytol). This would be the correct answer in non-CKD iron deficiency without inflammation." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: ESA hyporesponsiveness in CKD — first check iron (ferritin <100 or transferrin sat <20% = need IV iron). Hepcidin from inflammation blocks oral iron absorption. Other causes: bleeding, hyperPTH, infection.",
    "pdfPage": 15,
    "pdfQuote": "erythropoietin"
  },
  {
    "id": 15,
    "category": "Hematology: G6PD-Triggered Hemolysis in IDA Workup",
    "questionText": "A 32-year-old African American man presents with sudden onset dark urine, jaundice, and fatigue 3 days after starting trimethoprim-sulfamethoxazole for a urinary tract infection. Vitals: T 37.5°C, BP 122/72, HR 102. Exam: scleral icterus, no hepatosplenomegaly, dark cola-colored urine. Labs: Hgb 8.0 (baseline 14), MCV 92, RDW 17, reticulocyte count 9%, total bilirubin 4.5 (indirect 4.0), LDH 850 (elevated), haptoglobin <10 (very low). Peripheral smear shows BITE CELLS and HEINZ BODIES on supravital staining. Which is the most appropriate immediate management?",
    "options": [
      { "text": "Continue TMP-SMX (the infection must be treated) and start oral iron for the anemia", "explanation": "Incorrect. TMP-SMX is the TRIGGER of acute hemolysis in this G6PD-deficient patient and must be DISCONTINUED. Continuing it would worsen the hemolysis. The anemia is not from iron deficiency — it is acute hemolytic anemia. This would be the correct answer if the patient had iron deficiency anemia without hemolysis." },
      { "text": "Discontinue TMP-SMX immediately, provide supportive care (hydration, monitor for renal injury), consider transfusion if Hgb continues to fall, and obtain quantitative G6PD assay AFTER acute episode resolves", "explanation": "Correct. This is classic G6PD-DEFICIENCY HEMOLYTIC CRISIS triggered by an oxidant drug (sulfa). G6PD deficiency is X-linked recessive, most common variant in African Americans (mild, A- type) and severe Mediterranean type. Without G6PD, RBCs cannot generate NADPH to reduce glutathione, leaving them vulnerable to oxidative stress → oxidized hemoglobin precipitates as HEINZ BODIES → splenic macrophages 'bite out' the precipitates leaving BITE CELLS. Management: (1) STOP the offending agent immediately; (2) supportive care — IV hydration to prevent pigment nephropathy from free hemoglobin/hemoglobinuria, monitor renal function and potassium; (3) transfusion if symptomatic or severe anemia; (4) G6PD testing should be done AFTER the acute crisis because during active hemolysis, the most deficient RBCs have already been destroyed, leaving relatively normal G6PD-replete younger reticulocytes and producing a falsely normal G6PD level. (5) Patient counseling: avoid sulfa, dapsone, primaquine, nitrofurantoin, fava beans. Provide a 'list of drugs to avoid' card." },
      { "text": "Start corticosteroids (prednisone 1 mg/kg) for autoimmune hemolytic anemia", "explanation": "Incorrect. The patient has G6PD deficiency-related oxidative hemolysis, not autoimmune hemolysis. The Coombs test would be NEGATIVE in G6PD (intrinsic defect, not antibody-mediated). The smear findings (bite cells, Heinz bodies) and clear drug trigger point to G6PD. Steroids would not help and could mask important features. This would be the correct answer in WAIHA with spherocytes and positive direct Coombs." },
      { "text": "Initiate emergent plasmapheresis (plasma exchange)", "explanation": "Incorrect. Plasmapheresis is the urgent therapy for TTP (ADAMTS13 deficiency with pentad of thrombocytopenia/MAHA/fever/neuro/renal) or Waldenstrom hyperviscosity. This patient has neither — he has G6PD-triggered oxidative hemolysis from a sulfa drug. This would be the correct answer in TTP with schistocytes and thrombocytopenia." },
      { "text": "Start IV iron sucrose to replete iron stores depleted by hemolysis", "explanation": "Incorrect. Hemolysis typically does NOT cause iron deficiency because the iron from destroyed RBCs is recycled by macrophages. The patient has acute hemolysis, not iron deficiency. Giving IV iron is unnecessary and could be harmful if the patient has not been evaluated for true iron deficiency. This would be the correct answer in confirmed iron deficiency, especially with chronic intravascular hemolysis from prosthetic valves causing hemoglobinuria and iron loss." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: G6PD hemolytic crisis = stop oxidant trigger (sulfa, primaquine, dapsone, nitrofurantoin, fava bean) + supportive care. Test G6PD AFTER the crisis (falsely normal during active hemolysis).",
    "pdfPage": 30,
    "pdfQuote": "G6PD"
  },
  {
    "id": 16,
    "category": "Hematology: Cobalamin vs Folate in Megaloblastic Anemia",
    "questionText": "A 68-year-old woman has progressive fatigue and unsteady gait. She avoids meat but eats dairy and eggs. Vitals: BP 132/78, HR 86. Exam: glossitis, decreased proprioception and vibratory sense in both lower extremities, brisk reflexes. Labs: Hgb 9.5, MCV 113, RDW 17, hypersegmented neutrophils on smear, total bilirubin 2.1, LDH 380 (elevated), serum B12 105 (low), folate normal, MMA 950 (markedly elevated), homocysteine 28 (elevated). She is started on oral folate 1 mg daily by an outside provider. What is the most concerning consequence of this approach?",
    "options": [
      { "text": "Hyperhomocysteinemia will worsen because folate cannot reduce homocysteine in B12 deficiency", "explanation": "Incorrect. Actually, folate DOES participate in homocysteine recycling (via methylenetetrahydrofolate to methionine synthase pathway), so giving folate can partially lower homocysteine. The more dangerous concern is that folate replacement HIDES the hematologic problem while neurologic damage progresses unchecked. This would be the correct answer if the principal concern were biochemical homocysteine elevation alone." },
      { "text": "Hematologic anemia may improve transiently while NEUROLOGIC damage from B12 deficiency progresses unchecked, possibly becoming irreversible", "explanation": "Correct. This is the classic pitfall: in B12 deficiency, giving FOLATE ALONE can transiently correct the megaloblastic anemia (because both vitamins are required for thymidine synthesis and folate can bypass some of the methylenetetrahydrofolate trap) — BUT the neurologic damage from B12 deficiency (subacute combined degeneration of dorsal columns and lateral corticospinal tracts) continues to worsen because folate does NOT participate in the B12-dependent methylmalonyl-CoA mutase reaction critical for myelin synthesis. Untreated, the neurologic deficits become PERMANENT. This is why: (1) ALWAYS measure B12 in any patient with megaloblastic anemia BEFORE giving folate; (2) if both are deficient, treat B12 FIRST (or simultaneously); (3) routine high-dose folate supplementation in elderly without checking B12 can mask underlying B12 deficiency. Management here: STOP folate alone, start parenteral B12 (cyanocobalamin IM 1000 µg daily for 1 week → weekly for 1 month → monthly lifelong), and continue oral folate." },
      { "text": "Iatrogenic iron overload from folate's iron content", "explanation": "Incorrect. Folate supplements do not contain significant iron. This is not a recognized complication of folate therapy. This would be the correct answer if iron supplementation were the topic, not folate." },
      { "text": "Acute hemolytic crisis from folate-induced oxidative stress", "explanation": "Incorrect. Folate does not trigger oxidative hemolysis. This would be the correct answer for G6PD-deficient patients exposed to oxidant drugs (sulfa, primaquine, dapsone)." },
      { "text": "Megaloblastic anemia will paradoxically worsen as folate competes with B12", "explanation": "Incorrect. Folate does not compete with B12 receptor; the anemia would actually improve transiently with folate alone (which is the problem — it masks the diagnosis). This would be the correct answer if folate inhibited B12 absorption, which it does not." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: NEVER give folate alone without checking B12 in megaloblastic anemia. Folate can correct the hematologic picture but neurologic damage from B12 deficiency progresses irreversibly. Always check both; replace B12 first or concurrently.",
    "pdfPage": 12,
    "pdfQuote": "subacute combined degeneration"
  },
  {
    "id": 17,
    "category": "Hematology: Hereditary vs Acquired Sideroblastic Anemia",
    "questionText": "A 72-year-old man with no prior medical issues presents with progressive fatigue over 6 months. He does not drink alcohol, takes no medications, and has no toxin exposure. Vitals: BP 130/78, HR 80. Exam: pale conjunctiva, no organomegaly. Labs: Hgb 8.7, MCV 78, RDW 19.5, ferritin 480, transferrin sat 62%, serum iron 165. CBC also shows MCV-dimorphic RBCs (some microcytic, some normocytic), platelets 90K (mildly low), WBC 3.6 with neutrophil HYPOSEGMENTATION (pseudo-Pelger-Huet cells). Bone marrow biopsy shows HYPERCELLULAR marrow with dysplastic erythroid, granulocytic, and megakaryocytic precursors, 8% blasts, and >15% RINGED SIDEROBLASTS in erythroid precursors. Cytogenetics: del(5q). Which is the most likely diagnosis?",
    "options": [
      { "text": "Hereditary X-linked sideroblastic anemia (ALAS2 mutation)", "explanation": "Incorrect. Hereditary sideroblastic anemia typically presents in childhood/young adulthood (X-linked → males), with isolated red cell line involvement, no pancytopenia, no dysplastic features in other lineages, and no chromosomal abnormalities like del(5q). This patient is elderly with pancytopenia, dysplasia in multiple lineages, and a defining cytogenetic abnormality. This would be the correct answer in a young man with isolated microcytic anemia and ringed sideroblasts responsive to B6 supplementation." },
      { "text": "Acquired sideroblastic anemia in the context of MYELODYSPLASTIC SYNDROME with ring sideroblasts (MDS-RS) and del(5q)", "explanation": "Correct. This is a classic MDS-RS (MDS with ring sideroblasts) presentation, a subtype of myelodysplastic syndrome. Diagnostic features: (1) older adult with progressive cytopenia(s), (2) HYPERCELLULAR marrow (paradoxical given peripheral cytopenia — ineffective hematopoiesis), (3) DYSPLASTIC features across lineages (pseudo-Pelger-Huet hyposegmented neutrophils, dysplastic erythroid and megakaryocytes), (4) ≥15% RINGED SIDEROBLASTS, (5) <20% blasts (≥20% would be AML), (6) defining cytogenetic abnormalities (del(5q), monosomy 7, trisomy 8, complex karyotype). Del(5q) syndrome ('5q minus syndrome') is a distinct MDS subtype with predominant macrocytic anemia, normal or elevated platelets, and excellent response to LENALIDOMIDE. Management: lenalidomide for del(5q) MDS; ESAs for non-del(5q) with low EPO; luspatercept for MDS-RS; hypomethylating agents (azacitidine, decitabine) for higher-risk MDS; allogeneic SCT for younger high-risk patients. Risk of transformation to AML." },
      { "text": "Isoniazid-induced sideroblastic anemia", "explanation": "Incorrect. The patient takes no medications, so INH is not the trigger. INH-induced sideroblastic anemia is also typically isolated to the red cell line without pancytopenia, dysplasia in other lineages, or cytogenetic abnormalities. This would be the correct answer with INH exposure and isolated reversible sideroblastic anemia." },
      { "text": "Lead poisoning causing sideroblastic-like changes", "explanation": "Incorrect. Lead poisoning causes BASOPHILIC STIPPLING (not described here), is associated with environmental exposure (not present), and does not produce pancytopenia with dysplasia or del(5q). This would be the correct answer with lead exposure and basophilic stippling." },
      { "text": "Alcohol-induced reversible sideroblastic anemia", "explanation": "Incorrect. The patient does not drink alcohol. Alcohol-related sideroblastic anemia is also reversible with abstinence and typically does not show widespread dysplasia or del(5q). This would be the correct answer in a chronic heavy drinker with reversible sideroblastic changes." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Elderly + pancytopenia + HYPERCELLULAR dysplastic marrow + ringed sideroblasts + del(5q) = MDS-RS (del 5q syndrome). Treat with LENALIDOMIDE. Distinguish from reversible drug-induced sideroblastic anemia.",
    "pdfPage": 16,
    "pdfQuote": "sideroblastic anemia"
  },
  {
    "id": 18,
    "category": "Hematology: Alpha-Thalassemia Spectrum",
    "questionText": "A pediatrician is counseling a Southeast Asian couple about alpha-thalassemia genetics. The father is found to have alpha-thalassemia trait (--/αα: 2 gene deletion in cis on one chromosome). The mother has alpha-thalassemia silent carrier (-α/αα: 1 gene deletion). Which is the WORST possible alpha-thalassemia genotype in their offspring, AND what is its clinical consequence?",
    "options": [
      { "text": "Alpha-thalassemia silent carrier (-α/αα) — asymptomatic with normal CBC", "explanation": "Incorrect. Silent carrier (1 gene deletion) is asymptomatic with normal CBC and is NOT the worst possible outcome given this parental combination. This would be the correct answer if the question were about the mildest phenotype." },
      { "text": "Alpha-thalassemia trait (-α/-α or --/αα) — mild microcytic anemia, normal life expectancy", "explanation": "Incorrect. Alpha-thal trait (2 gene deletions) causes mild microcytic anemia but is not life-limiting and is not the WORST possible outcome with these parents. This would be the correct answer for the typical asymptomatic-to-mild phenotype." },
      { "text": "Hemoglobin Bart's hydrops fetalis (all 4 alpha genes deleted, --/--) — incompatible with extrauterine life, severe in utero anemia, fetal hydrops, often stillbirth", "explanation": "Correct. With one parent being -α/αα (silent carrier) and the other being --/αα (trait in cis), there is a 25% chance of conceiving a fetus with --/-α (HbH disease, 3 deletions, surviving with chronic moderate-severe hemolytic anemia) — NOT the 4-deletion --/-- combination from these specific parents because the silent carrier parent can only contribute -α or αα, not --. WAIT — re-examining: father is --/αα (can pass -- or αα), mother is -α/αα (can pass -α or αα). Combinations: --/-α (HbH), --/αα (trait), αα/-α (silent), αα/αα (normal). So the WORST outcome here is HbH disease (--/-α, 3 deletions): chronic moderate-severe microcytic hemolytic anemia, splenomegaly, gallstones, bone changes, requires monitoring and sometimes transfusion. HbH electrophoresis shows β4 tetramers. Hb Bart's hydrops (--/--) would only occur if BOTH parents had the cis (--/αα) deletion (common in Southeast Asians, not in those with trans deletions or single gene loss). Bart's hydrops is fatal in utero from severe anemia, hydrops fetalis, and γ4 tetramers (Bart's hemoglobin) that cannot release oxygen." },
      { "text": "Alpha-thalassemia major requiring chronic transfusions starting at age 2", "explanation": "Incorrect. There is no clinical entity called 'alpha-thalassemia major' analogous to beta-thal major. Severe alpha-thalassemia phenotypes are HbH disease (3 deletions) and Bart's hydrops (4 deletions). This would be the correct answer if alpha-thalassemia followed beta-thal nomenclature." },
      { "text": "Beta-thalassemia major from compound heterozygous mutations", "explanation": "Incorrect. Beta-thalassemia is unrelated to alpha-thalassemia genetics; the parents both have alpha-thalassemia and would not produce beta-thalassemia offspring solely from these mutations. This would be the correct answer if both parents had beta-thal trait." }
    ],
    "correctAnswerIndex": 2,
    "clinicalPearl": "Key takeaway: Alpha-thalassemia spectrum: 1 deletion = silent carrier (normal CBC); 2 = trait (mild microcytic); 3 = HbH disease (chronic hemolysis, β4 tetramers); 4 = Bart's hydrops (fatal in utero, γ4 tetramers). Cis vs trans deletions matter for predicting offspring phenotypes.",
    "pdfPage": 18,
    "pdfQuote": "alpha thalassemia"
  },
  {
    "id": 19,
    "category": "Hematology: ACD vs Mixed in Active Disease",
    "questionText": "A 60-year-old woman with active ulcerative colitis (current flare with bloody diarrhea 8x/day) presents with worsening fatigue. Vitals: T 38.0°C, BP 110/68, HR 102. Exam: pale conjunctiva, abdominal tenderness, no organomegaly. Labs: Hgb 7.8, MCV 75, RDW 21, ferritin 35, TIBC 380, transferrin sat 11%, CRP 95 (markedly elevated), serum iron 28. She is started on infliximab for the UC flare. Which is the most appropriate management of the anemia?",
    "options": [
      { "text": "Wait for the colitis to be controlled by infliximab and reassess the anemia in 6-8 weeks before treating", "explanation": "Incorrect. The patient has SEVERE iron deficiency anemia (Hgb 7.8) requiring active management. Waiting weeks for inflammation to control while the patient remains symptomatic is inappropriate. Iron repletion can and should be done concurrently with disease control. This would be the correct answer if anemia were mild and asymptomatic." },
      { "text": "Initiate IV iron (ferric carboxymaltose) AND continue infliximab/control underlying UC", "explanation": "Correct. This patient has MIXED iron deficiency anemia (low ferritin, high TIBC, low transferrin sat, elevated RDW — even with concurrent inflammation that would tend to elevate ferritin) AND inflammation from active UC. Key points: (1) IV IRON is strongly preferred over oral iron in IBD because: (a) oral iron is poorly absorbed in active inflammation (hepcidin blocks ferroportin), (b) oral iron can WORSEN GI mucosal inflammation and is poorly tolerated in IBD (nausea, constipation, abdominal pain), (c) IV iron achieves rapid repletion without GI exposure. Preferred IV iron in IBD: ferric carboxymaltose (large doses single infusion) or iron sucrose. (2) Concurrent control of the underlying inflammation (anti-TNF, steroids, etc.) addresses the ACD component and reduces hepcidin. (3) Transfusion is reserved for severe symptoms or hemodynamic compromise. (4) Avoid oral iron in IBD — strongly discouraged in current guidelines." },
      { "text": "Start oral ferrous sulfate 325 mg TID", "explanation": "Incorrect. Oral iron is poorly tolerated and poorly absorbed in active IBD (gut inflammation increases hepcidin and impairs absorption; oral iron can worsen GI mucosal injury). IV iron is preferred. This would be the correct answer in non-IBD iron deficiency without GI inflammation." },
      { "text": "Initiate erythropoietin alone without iron supplementation", "explanation": "Incorrect. The patient is iron-deficient — giving EPO without iron is futile because the marrow lacks substrate. Iron must be replaced. This would be the correct answer in CKD anemia with adequate iron stores and low EPO without iron deficiency." },
      { "text": "Transfuse 4 units of packed RBCs immediately", "explanation": "Incorrect. While transfusion may be needed if the patient is severely symptomatic or hemodynamically unstable, the standard threshold (Hgb <7 with symptoms, or <8 in cardiac patients) is borderline here, and IV iron achieves a more durable correction without transfusion risks (alloimmunization, infection, iron overload, transfusion reactions). Restrictive transfusion practice favors IV iron in stable IBD anemia. This would be the correct answer with hemodynamic instability or active uncontrolled bleeding." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: IBD-related anemia (mixed IDA + ACD) = IV iron (ferric carboxymaltose preferred). AVOID oral iron in active IBD (worsens GI inflammation, poorly absorbed due to hepcidin). Treat underlying disease concurrently.",
    "pdfPage": 14,
    "pdfQuote": "anemia of chronic disease"
  },
  {
    "id": 20,
    "category": "Hematology: Iron Studies in Pregnancy",
    "questionText": "A 30-year-old G3P2 woman at 36 weeks gestation has serial CBCs showing: 12 weeks gestation Hgb 12.5/MCV 90; 24 weeks Hgb 10.8/MCV 88; 36 weeks Hgb 11.0/MCV 87. She is asymptomatic, follows a balanced omnivorous diet, takes prenatal vitamins (containing 27 mg elemental iron), and reports no GI losses. Vitals: BP 116/72, HR 84. Exam: gravid uterus, no organomegaly, no pallor. Repeat labs: ferritin 25, TIBC 410, transferrin sat 18%, serum iron 75. Which best describes this clinical picture?",
    "options": [
      { "text": "Pathologic iron deficiency anemia requiring IV iron and bidirectional endoscopy to rule out GI source", "explanation": "Incorrect. In pregnancy, mild dilutional and iron-related anemia is physiologic — plasma volume expands by ~50% while red cell mass expands by only ~25%, producing a 'physiologic anemia of pregnancy' with mildly decreased Hgb that does not require aggressive workup. Pregnant women do have increased iron demand (~1000 mg total), but the workup for occult GI bleeding is not standard in pregnancy unless symptoms suggest it. This would be the correct answer in a non-pregnant adult man or postmenopausal woman with new IDA." },
      { "text": "Physiologic anemia of pregnancy WITH borderline iron deficiency — increase elemental iron supplementation orally", "explanation": "Correct. Pregnancy normally produces a 'physiologic anemia' from disproportionate plasma volume expansion (~50%) over red cell mass expansion (~25%), and is most pronounced in the second/third trimester (nadir around 28-32 weeks). Hgb at 11.0 in the third trimester is acceptable (>10.5-11 g/dL is typical). HOWEVER, the borderline-low ferritin (25), low transferrin saturation (18%), and elevated TIBC suggest concurrent iron deficiency — common given that pregnancy requires ~1000 mg iron (fetus, placenta, expanded RBC mass, delivery losses) and the typical prenatal contains only 27 mg/day. Management: increase oral iron intake (e.g., add 60-100 mg elemental iron daily — many providers use ferrous sulfate 325 mg = 65 mg elemental once or twice daily), encourage iron-rich diet (heme iron sources, vitamin C to enhance absorption), and reassess Hgb and ferritin postpartum. IV iron is reserved for intolerance, malabsorption, severe deficiency, or proximity to delivery." },
      { "text": "Beta-thalassemia minor newly unmasked by pregnancy", "explanation": "Incorrect. Beta-thal trait would show normal iron studies, normal RDW, and a disproportionately low MCV relative to the degree of anemia. The iron studies here show borderline iron deficiency, not normal iron studies. This would be the correct answer if iron studies were normal in a Mediterranean patient with mild microcytic anemia." },
      { "text": "Hemoglobinopathy crisis from previously unknown sickle cell disease", "explanation": "Incorrect. Sickle cell crisis presents with severe pain and would show very characteristic findings (sickled cells, elevated reticulocytes, evidence of hemolysis) — none are described. This would be the correct answer with severe pain crisis, hemolysis labs, and sickled cells on smear." },
      { "text": "Acquired aplastic anemia of pregnancy", "explanation": "Incorrect. Aplastic anemia of pregnancy is rare and would show pancytopenia with hypocellular marrow, not isolated borderline anemia with iron studies suggesting iron deficiency. This would be the correct answer with pancytopenia and a hypocellular marrow biopsy." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Pregnancy = physiologic anemia (plasma volume expands more than RBC mass) PLUS increased iron demand (~1000 mg total). Hgb ~11 in T3 is normal. Borderline ferritin → optimize oral iron; reassess postpartum.",
    "pdfPage": 13,
    "pdfQuote": "iron deficiency"
  }
];

window.Test_L151_Part2 = Test_L151_Part2;
