// Thinking Process (Part 2 — strictly 2nd/3rd-order vignettes per v5 prompt):
// 1. High-Yield Concept: Application/diagnosis/management of megaloblastic anemias (B12, folate) and hemolytic anemias (intrinsic vs extrinsic; HS, G6PD, PNH, sickle cell, AIHA, MAHA/TTP/HUS).
// 2. The "Trap": Confusing TTP vs HUS vs DIC; missing that folate alone can mask B12 neuro damage; forgetting Coombs to distinguish HS from WAIHA.
// 3. Key Distractor: Plasmapheresis is the answer for TTP and Waldenstrom hyperviscosity, not for HUS or DIC; cold AIHA (IgM) vs warm AIHA (IgG) treatment differs.
// 4. Vignette Strategy: Vignettes with full demographics, dietary/medication history, exposure, lab panel, smear, Coombs, ADAMTS13, MMA/homocysteine to force differential narrowing.
//
// PDF Mapping Check: Found
// PDF Filename: Lecture # 152. G. Saggio, D.O. (PPT).pdf
// Mapping Key: 17-Hematology: Laboratory Medicine and Anemias Part 2 - Vignettes (L152 Part 2)
// Status: Verified

const Test_L152_Part2 = [
  {
    "id": 1,
    "category": "Hematology: Pernicious Anemia Workup and Treatment",
    "questionText": "A 68-year-old woman with hypothyroidism and vitiligo presents with progressive fatigue, gait imbalance, and tingling in her toes over 6 months. Vitals: T 36.9°C, BP 130/76, HR 78. Exam: glossitis, decreased vibratory sense in toes, positive Romberg. Labs: Hgb 9.4, MCV 116, RDW 17, hypersegmented neutrophils on smear, B12 110 (low), folate normal, MMA 1100 (markedly elevated), homocysteine 36 (elevated). Anti-intrinsic factor antibody is POSITIVE. Which is the most appropriate management?",
    "options": [
      { "text": "Oral folate 1 mg daily indefinitely", "explanation": "Incorrect. The patient has B12 deficiency (not folate), and giving folate alone in B12 deficiency is potentially dangerous — it can correct the hematologic anemia transiently while the neurologic damage from B12 deficiency progresses, possibly becoming irreversible. This would be the correct answer in pure folate deficiency without B12 issues." },
      { "text": "Intramuscular cyanocobalamin (B12) 1000 µg daily for 1 week, then weekly for 1 month, then monthly LIFELONG", "explanation": "Correct. The patient has PERNICIOUS ANEMIA — autoimmune destruction of parietal cells (and/or intrinsic factor itself) impairing B12 absorption. Confirmatory features: B12 deficiency with elevated MMA and homocysteine, anti-IF antibody POSITIVE (highly specific), associated other autoimmune diseases (Hashimoto thyroiditis, vitiligo) — pattern of polyautoimmunity. Management: B12 must be replaced PARENTERALLY (IM cyanocobalamin) because the patient cannot absorb oral B12 due to intrinsic factor deficiency. Loading dose schedule: 1000 µg IM daily x 1 week → weekly x 1 month → monthly LIFELONG. (High-dose oral B12 ~1000-2000 µg/day can sometimes work via the passive paracellular route at high concentrations, but IM is the standard and most reliable.) Surveillance: PA is associated with increased gastric cancer risk → periodic upper endoscopy in selected high-risk patients. Neurologic damage may not fully reverse, especially if treatment is delayed." },
      { "text": "Oral cyanocobalamin 100 µg daily and standard prenatal vitamin", "explanation": "Incorrect. Low-dose oral B12 (100 µg/day) is insufficient to overcome the absorption deficit in pernicious anemia. While high-dose oral (1000+ µg/day) can work in some PA patients via passive absorption, IM is the standard. This would be the correct answer for mild dietary B12 insufficiency without absorption defect." },
      { "text": "Initiate cyanocobalamin 1000 µg IM monthly only after oral folate has failed", "explanation": "Incorrect. There is no reason to try folate first — the patient has documented B12 deficiency with neurologic features and positive anti-IF antibody. Giving folate first would mask the picture and risk worsening neuro damage. Start B12 now. This would be the correct answer if it were established that folate deficiency was the cause and B12 was normal." },
      { "text": "Recommend dietary B12 increase with red meat and fortified cereals only", "explanation": "Incorrect. Dietary modification cannot fix the absorption defect in PA — the patient lacks intrinsic factor, so dietary B12 still cannot be absorbed in the terminal ileum. Parenteral replacement is required. This would be the correct answer in pure dietary deficiency (e.g., strict vegan without absorption issues)." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Pernicious anemia = autoimmune parietal cell/IF destruction. Treatment = LIFELONG parenteral B12 (IM cyanocobalamin). Loading: daily x 1 wk → weekly x 1 mo → monthly. Watch for gastric cancer risk.",
    "pdfPage": 10,
    "pdfQuote": "pernicious anemia"
  },
  {
    "id": 2,
    "category": "Hematology: TTP Plasmapheresis",
    "questionText": "A 38-year-old woman presents to the ED with a 3-day history of fever, headache, confusion, fatigue, and dark urine. She also noted petechiae on her shins. Vitals: T 38.4°C, HR 110, BP 142/86, RR 18. Exam: confused (not oriented to date), petechiae on lower extremities, mild RUQ tenderness. Labs: Hgb 7.5, platelets 15K, WBC 8.2, creatinine 1.4, total bilirubin 4.2 (indirect 3.5), LDH 1,850 (markedly elevated), haptoglobin <10, PT/PTT NORMAL, fibrinogen normal, SCHISTOCYTES on smear. ADAMTS13 activity returns at <5% with positive inhibitor. Which is the most appropriate IMMEDIATE management?",
    "options": [
      { "text": "Immediate platelet transfusion to raise platelets above 50K before any further intervention", "explanation": "Incorrect. PLATELET TRANSFUSION IN TTP IS RELATIVELY CONTRAINDICATED — it can paradoxically WORSEN microthrombosis by adding fuel to the platelet aggregation in small vessels (the so-called 'fueling the fire' phenomenon). Platelets should only be given for life-threatening bleeding or before high-risk procedures. This would be the correct answer in ITP with bleeding or other thrombocytopenia without microthrombi." },
      { "text": "URGENT PLASMA EXCHANGE (plasmapheresis) plus high-dose corticosteroids; consider caplacizumab and rituximab", "explanation": "Correct. This patient has CLASSIC TTP: the pentad (incomplete in most patients) of (1) microangiopathic hemolytic anemia (schistocytes, elevated LDH, low haptoglobin, indirect hyperbilirubinemia), (2) thrombocytopenia, (3) fever, (4) neurologic dysfunction, (5) renal dysfunction. ADAMTS13 activity <10% with an inhibitor confirms acquired TTP (immune-mediated). Untreated mortality >90%. Treatment: URGENT PLASMA EXCHANGE (replaces the deficient ADAMTS13 enzyme and removes the inhibitor and ultra-large vWF multimers) — should be initiated within hours of suspicion, do NOT wait for ADAMTS13 results. CORTICOSTEROIDS (prednisone 1 mg/kg or methylprednisolone) address the autoimmune component. CAPLACIZUMAB (anti-vWF nanobody) reduces time to platelet recovery. RITUXIMAB is added for refractory or relapsing TTP. Continue plasma exchange daily until platelets normalize. AVOID platelet transfusion (worsens microthrombosis) — only give for life-threatening bleeding." },
      { "text": "Begin broad-spectrum antibiotics for presumed sepsis and supportive care", "explanation": "Incorrect. While fever and confusion suggest infection in the differential, the lab pattern (MAHA + thrombocytopenia + normal PT/PTT + ADAMTS13 <10%) is diagnostic of TTP. Antibiotics may be added if infection is suspected, but the dominant immediate intervention is plasma exchange. This would be the correct answer in septic patient without TTP features." },
      { "text": "Initiate broad-spectrum antibiotics and emergent hemodialysis", "explanation": "Incorrect. The patient has mildly elevated creatinine but does not have an indication for emergent dialysis (no severe hyperkalemia, severe acidosis, uremic symptoms, volume overload, or toxic ingestion). Hemodialysis is also not the treatment for TTP — plasma exchange is. This would be the correct answer with severe AKI requiring emergent dialysis." },
      { "text": "Hold all interventions and observe for spontaneous resolution since TTP is self-limited", "explanation": "Incorrect. TTP is NOT self-limited — it has >90% mortality without treatment. This is a hematologic emergency requiring immediate plasma exchange. This would be the correct answer in mild self-limited illnesses (which TTP is not)." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: TTP = ADAMTS13 <10% → URGENT PLASMA EXCHANGE + steroids + caplacizumab (± rituximab). AVOID platelet transfusion (worsens microthrombi). Untreated mortality >90%.",
    "pdfPage": 36,
    "pdfQuote": "ADAMTS13"
  },
  {
    "id": 3,
    "category": "Hematology: HUS Antibiotic Avoidance",
    "questionText": "A 4-year-old boy presents 7 days after attending a county fair where he ate a hamburger. He has had 5 days of bloody diarrhea and abdominal cramps, and his parents now note pallor, decreased urine output, and bruising. Vitals: T 37.1°C, HR 130, BP 95/55, RR 24. Exam: pale, lethargic, periorbital edema, abdominal tenderness, petechiae. Labs: Hgb 7.8, platelets 35K, WBC 16, creatinine 2.8 (baseline ~0.4), BUN 65, LDH 1,300, total bilirubin 3.2 (indirect), schistocytes on smear, stool culture growing E. coli O157:H7 (Shiga toxin-producing E. coli, STEC). Which is the most appropriate management?",
    "options": [
      { "text": "Initiate IV ciprofloxacin to eradicate the E. coli O157:H7 infection", "explanation": "Incorrect. Antibiotics — especially fluoroquinolones, TMP-SMX, and beta-lactams — are RELATIVELY CONTRAINDICATED in STEC-associated bloody diarrhea (and especially in evolving/established HUS). Antibiotics can INCREASE Shiga toxin release from bacterial lysis (SOS response), potentially worsening HUS. Antimotility agents (loperamide) are also contraindicated. This would be the correct answer in non-Shiga-toxin-producing bacterial dysentery (e.g., shigella in some contexts, although guidelines have evolved)." },
      { "text": "Supportive care: IV fluids, AVOID antibiotics, monitor for dialysis", "explanation": "Correct. Provide aggressive supportive care: IV fluids, blood transfusion as needed, AVOID antibiotics, monitor for need for renal replacement therapy (dialysis), and AVOID platelet transfusion unless bleeding. This is typical post-diarrheal SHIGA TOXIN-MEDIATED HUS (D+ HUS), the most common cause of acute kidney injury in young children. Management is SUPPORTIVE: (1) IV FLUIDS (volume support is critical and may reduce severity of AKI if given early in the diarrheal phase), (2) RBC transfusion for symptomatic anemia, (3) AVOID ANTIBIOTICS (increase Shiga toxin release; meta-analyses show worse outcomes), (4) AVOID ANTIMOTILITY AGENTS (loperamide — increase toxin exposure time), (5) MONITOR FOR RENAL REPLACEMENT THERAPY — many children need temporary dialysis (peritoneal or hemodialysis); 5-15% have long-term renal sequelae, 1-5% mortality, (6) AVOID platelet transfusion unless actively bleeding. ECULIZUMAB (anti-complement C5) is now used for ATYPICAL HUS (complement-mediated, no diarrhea) but NOT for typical Shiga toxin HUS — recent data on STEC-HUS with eculizumab is mixed and not yet standard. Plasma exchange is NOT helpful in typical HUS (unlike TTP)." },
      { "text": "Initiate emergent plasma exchange similar to TTP management", "explanation": "Incorrect. Plasma exchange is the treatment for TTP (ADAMTS13 deficiency) but is NOT effective in typical Shiga toxin-mediated HUS. The two diseases share MAHA + thrombocytopenia but have different pathophysiology and treatment. This would be the correct answer in TTP." },
      { "text": "Transfuse platelets to raise the count above 50K to prevent bleeding", "explanation": "Incorrect. Platelets in HUS (like TTP) are consumed in microthrombi, and prophylactic transfusion can worsen microvascular thrombosis. Reserve platelet transfusion for active bleeding or pre-procedure. This would be the correct answer with active life-threatening hemorrhage." },
      { "text": "Begin high-dose IV corticosteroids", "explanation": "Incorrect. Corticosteroids are not standard therapy for typical HUS and have no proven benefit. They may be considered in atypical HUS or as adjunctive therapy in some autoimmune contexts, but not routinely in Shiga toxin HUS. This would be the correct answer in some autoimmune AIHAs with thrombocytopenia." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Typical (Shiga toxin) HUS in kids = supportive care + AVOID antibiotics (increase toxin release) + AVOID antimotility agents. Many need dialysis. Eculizumab is for ATYPICAL HUS, not typical.",
    "pdfPage": 37,
    "pdfQuote": "HUS"
  },
  {
    "id": 4,
    "category": "Hematology: Cold Agglutinin AIHA from Mycoplasma",
    "questionText": "A 24-year-old college student presents with a 2-week history of nonproductive cough, low-grade fever, malaise. Today he developed acrocyanosis of his fingertips and dark urine. Vitals: T 38.0°C, HR 96, BP 122/74, RR 18. Exam: scattered crackles bilaterally, acrocyanosis (especially in cold environment), no scleral icterus. Labs: Hgb 9.5 (down from 14 baseline), MCV 95, reticulocyte count 7%, total bilirubin 2.8 (indirect), LDH 480, haptoglobin <10, direct Coombs POSITIVE for COMPLEMENT (C3) only, NEGATIVE for IgG. Chest X-ray shows patchy bilateral lower lobe infiltrates. Cold agglutinin titer 1:1024 (markedly elevated). Which is the most appropriate management?",
    "options": [
      { "text": "High-dose prednisone (1 mg/kg) plus splenectomy if no response", "explanation": "Incorrect. Steroids and splenectomy are first-line therapy for WARM AIHA (IgG-mediated, Coombs positive for IgG), not COLD AIHA. Cold AIHA responds poorly to steroids because complement-coated RBCs are destroyed extravascularly in the LIVER (Kupffer cells via C3 receptors) — splenectomy is unhelpful. This would be the correct answer in WAIHA with IgG-positive Coombs." },
      { "text": "Keep warm; treat Mycoplasma with azithromycin; supportive care", "explanation": "Correct. KEEP THE PATIENT WARM (avoid cold exposure), treat underlying Mycoplasma infection with azithromycin or doxycycline, and supportive transfusion as needed (warmed blood). This patient has POST-INFECTIOUS COLD AGGLUTININ DISEASE (cold AIHA) triggered by atypical pneumonia from MYCOPLASMA PNEUMONIAE. The clue: walking pneumonia (low-grade fever, dry cough, bilateral infiltrates) + new hemolytic anemia with COLD-induced symptoms (acrocyanosis) + direct Coombs positive for C3/complement ONLY (NOT IgG) + high cold agglutinin titer. Mechanism: Mycoplasma triggers IgM autoantibodies (often against I antigen on RBCs) that bind in cooler peripheral circulation, fix complement, then either: (a) cause complement-mediated intravascular hemolysis, or (b) coat RBCs with C3 which are then cleared extravascularly by Kupffer cells in the liver. Management: (1) KEEP WARM — avoid cold exposure (insulate IV lines, warm any blood products before transfusion); (2) TREAT THE UNDERLYING INFECTION (azithromycin or doxycycline for Mycoplasma); (3) SUPPORTIVE — most post-infectious cold AIHA is self-limited within 2-12 weeks as the IgM autoantibody titer falls. For chronic cold agglutinin disease (idiopathic or associated with lymphoproliferative disorder), RITUXIMAB ± bendamustine is preferred. Steroids and splenectomy do NOT work well in cold AIHA. EBV mononucleosis is another classic cold AIHA trigger." },
      { "text": "Start eculizumab to inhibit complement-mediated hemolysis", "explanation": "Incorrect. Eculizumab (anti-C5) is the standard therapy for PNH and atypical HUS, but is not standard for post-infectious cold AIHA, which is usually self-limited. Sutimlimab (anti-C1s) is approved specifically for COLD agglutinin disease (chronic form), not the post-infectious form. This would be the correct answer in PNH or atypical HUS, or chronic cold agglutinin disease with sutimlimab." },
      { "text": "Splenectomy as definitive therapy", "explanation": "Incorrect. Splenectomy does not help cold AIHA because the destruction is extravascular in the LIVER (Kupffer cells via C3), not the spleen. Splenectomy is effective in warm AIHA (where IgG-coated cells are destroyed by splenic macrophages). This would be the correct answer in refractory warm AIHA." },
      { "text": "Plasmapheresis weekly until cold agglutinin titer normalizes", "explanation": "Incorrect. While plasmapheresis can transiently reduce circulating IgM, post-infectious cold AIHA is usually self-limited with supportive care (warm, treat infection). Plasmapheresis is occasionally used in severe acute disease. This would be the correct answer in severe acute IgM-driven hemolysis with hemodynamic compromise." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Cold AIHA (IgM, post-Mycoplasma or EBV) = KEEP WARM + treat infection + supportive. Steroids/splenectomy don't work (extravascular destruction in LIVER, not spleen). Rituximab for chronic disease.",
    "pdfPage": 32,
    "pdfQuote": "cold"
  },
  {
    "id": 5,
    "category": "Hematology: Warm AIHA from Methyldopa",
    "questionText": "A 55-year-old woman with hypertension was started on methyldopa 3 months ago after another antihypertensive caused side effects. She now presents with fatigue, jaundice, and dark urine. Vitals: T 37.2°C, BP 138/80, HR 96. Exam: scleral icterus, mild splenomegaly. Labs: Hgb 7.6 (baseline 13), MCV 100 (slightly elevated), reticulocyte count 10%, total bilirubin 4.5 (indirect 4.0), LDH 720, haptoglobin <10, direct Coombs POSITIVE for IgG, peripheral smear shows SPHEROCYTES. Which is the most appropriate INITIAL management?",
    "options": [
      { "text": "Continue methyldopa for blood pressure control and start oral folate supplementation only", "explanation": "Incorrect. METHYLDOPA IS THE TRIGGER of this warm AIHA and must be DISCONTINUED. Continuing it would perpetuate the hemolysis. This would be the correct answer if hypertension control were paramount and AIHA were unrelated to the drug." },
      { "text": "Discontinue methyldopa, start prednisone 1 mg/kg/day, and consider IVIG if symptomatic; supportive transfusion if severe", "explanation": "Correct. This is DRUG-INDUCED WARM AUTOIMMUNE HEMOLYTIC ANEMIA. Clues: (1) onset after a known culprit drug (methyldopa is the classic example — also penicillin, cephalosporins, NSAIDs, fludarabine, oxaliplatin), (2) warm AIHA features (IgG-positive Coombs, spherocytes on smear, extravascular splenic destruction), (3) typical hemolytic labs (indirect hyperbilirubinemia, elevated LDH, low haptoglobin, reticulocytosis). Management: (1) DISCONTINUE THE OFFENDING DRUG — this alone may resolve mild cases. (2) PREDNISONE (1 mg/kg/day) is first-line for moderate-to-severe AIHA. (3) IVIG is adjunctive in severe disease. (4) RITUXIMAB is second-line for steroid-refractory or chronic cases. (5) SPLENECTOMY is reserved for refractory cases (spleen is the site of IgG-coated RBC destruction). (6) Supportive blood transfusion if symptomatic anemia — use the LEAST INCOMPATIBLE unit (any unit will be 'incompatible' due to autoantibody, but the goal is to avoid additional alloimmunization). (7) Folate supplementation in chronic hemolysis to prevent megaloblastic crisis." },
      { "text": "Initiate plasmapheresis to remove autoantibodies", "explanation": "Incorrect. Plasmapheresis is the urgent therapy for TTP and Waldenstrom hyperviscosity, but is NOT first-line for warm AIHA — IgG autoantibodies are largely extravascular (tissue-bound), and plasma exchange is therefore less effective than for IgM-mediated diseases. Steroids are first-line. This would be the correct answer in TTP." },
      { "text": "Initiate eculizumab to block complement-mediated hemolysis", "explanation": "Incorrect. Warm AIHA (IgG) is typically NOT complement-mediated (some C3 can be present, but the dominant mechanism is splenic macrophage clearance of IgG-coated cells). Eculizumab targets complement-mediated diseases (PNH, atypical HUS, cold agglutinin disease in some cases). This would be the correct answer in PNH or atypical HUS." },
      { "text": "Immediate splenectomy as definitive therapy", "explanation": "Incorrect. Splenectomy IS effective in warm AIHA (the spleen is the site of IgG-coated RBC destruction), but is reserved for steroid-refractory or relapsed disease, not first-line. Also, removing the offending drug may resolve drug-induced AIHA without splenectomy. This would be the correct answer in chronic refractory warm AIHA after steroids and rituximab failed." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Warm AIHA (IgG, Coombs+, spherocytes) = (1) stop offending drug, (2) prednisone 1 mg/kg, (3) IVIG/rituximab/splenectomy for refractory. Methyldopa, penicillin, NSAIDs are classic drug triggers.",
    "pdfPage": 32,
    "pdfQuote": "warm"
  },
  {
    "id": 6,
    "category": "Hematology: PNH Thrombosis and Eculizumab",
    "questionText": "A 32-year-old previously healthy man presents to the ED with severe RUQ pain, nausea, and abdominal distension. He has a 1-year history of recurrent dark morning urine, fatigue, and one prior episode of unexplained pancytopenia. Vitals: T 37.4°C, BP 110/68, HR 110, RR 18. Exam: tender hepatomegaly, ascites. Labs: Hgb 8.5, WBC 3.2, platelets 95K, total bilirubin 4.0 (indirect 3.5), LDH 1,500 (markedly elevated), haptoglobin <10, direct Coombs NEGATIVE. Doppler ultrasound shows acute thrombosis of the hepatic veins (Budd-Chiari syndrome). Flow cytometry on peripheral blood shows ABSENCE of CD55 and CD59 on RBCs and granulocytes. Which is the most appropriate definitive management for the underlying disease?",
    "options": [
      { "text": "Lifelong warfarin only, with INR target 2-3 to prevent further thrombotic events", "explanation": "Incorrect. While anticoagulation is appropriate for acute thrombosis, it does not address the underlying disease (PNH) which is the driver of ongoing hemolysis and thrombosis risk. Without disease-modifying therapy, recurrent thrombosis remains likely. This would be the correct answer in a thrombosis from a transient provoked event without underlying thrombophilia." },
      { "text": "Initiate ECULIZUMAB (or ravulizumab); vaccinate against encapsulated organisms", "explanation": "Correct. Eculizumab (or ravulizumab) is an anti-C5 monoclonal antibody that inhibits terminal complement activation; provide vaccinations and antibiotic prophylaxis against encapsulated organisms (especially Neisseria meningitidis). This patient has PAROXYSMAL NOCTURNAL HEMOGLOBINURIA (PNH). Classic triad: (1) intravascular hemolytic anemia (often worse at night/early morning when respiratory acidosis activates complement → 'paroxysmal nocturnal hemoglobinuria'), (2) cytopenias (some patients have aplastic anemia/MDS-like marrow), (3) THROMBOSIS — especially in unusual sites (hepatic veins → BUDD-CHIARI SYNDROME, cerebral veins, mesenteric, portal). Pathogenesis: acquired PIGA mutation in hematopoietic stem cells → loss of GPI anchor → loss of complement inhibitors CD55 (DAF) and CD59 (MIRL) → uncontrolled complement-mediated lysis. Diagnosis: flow cytometry for CD55/CD59 deficiency. Treatment: ECULIZUMAB (anti-C5 monoclonal Ab) blocks terminal complement activation → markedly reduces hemolysis and thrombosis risk. NEWER agent ravulizumab is longer-acting. PEGCETACOPLAN (anti-C3) is approved for patients with residual extravascular hemolysis on eculizumab. MUST vaccinate against encapsulated organisms (meningococcus, pneumococcus, H. influenzae) and provide penicillin prophylaxis — eculizumab blocks the terminal complement pathway, leaving patients vulnerable to Neisseria meningitidis sepsis. Anticoagulation for acute thrombosis. Allogeneic SCT is curative but reserved for select high-risk patients." },
      { "text": "Start oral iron supplementation and B12 injections", "explanation": "Incorrect. Iron and B12 are not the underlying treatment for PNH. While iron deficiency CAN coexist (from chronic urinary iron loss in hemoglobinuria), treating the underlying complement-mediated destruction with eculizumab is the priority. This would be the correct answer for nutritional deficiency anemias." },
      { "text": "Begin chronic immunosuppression with cyclosporine and ATG for presumed aplastic anemia", "explanation": "Incorrect. While PNH can coexist with or evolve from aplastic anemia, this patient's presentation (Budd-Chiari thrombosis, intravascular hemolysis, CD55/CD59 deficiency) is dominated by classic complement-mediated PNH features. Eculizumab is the targeted therapy. Immunosuppression is reserved for patients with concurrent aplastic anemia or as a bridge to transplant. This would be the correct answer in primary aplastic anemia without PNH features." },
      { "text": "Emergent splenectomy to reduce extravascular hemolysis", "explanation": "Incorrect. PNH hemolysis is INTRAVASCULAR (complement-mediated lysis in the bloodstream), not extravascular (splenic destruction). Splenectomy is not indicated. This would be the correct answer in refractory warm AIHA or hereditary spherocytosis." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: PNH = PIGA mutation → loss of CD55/CD59 → complement-mediated INTRAVASCULAR hemolysis + cytopenias + THROMBOSIS (Budd-Chiari!). Treat with ECULIZUMAB + meningococcal vaccination. SCT is curative.",
    "pdfPage": 31,
    "pdfQuote": "paroxysmal nocturnal hemoglobinuria"
  },
  {
    "id": 7,
    "category": "Hematology: Sickle Cell Vaso-Occlusive Crisis",
    "questionText": "A 22-year-old African-American man with known HbSS presents to the ED with severe pain in his back, hips, and chest that began 12 hours ago after dehydration during outdoor work in hot weather. He rates his pain 10/10. Vitals: T 38.1°C, HR 118, BP 130/82, RR 22, O2 sat 92% on room air. Exam: tenderness over thoracic spine and bilateral hips, no neurologic deficits, chest exam shows decreased breath sounds and crackles at the right base. Labs: Hgb 7.5 (baseline 8.0), WBC 18, reticulocyte 12%, LDH 480. Chest X-ray shows a new right lower lobe infiltrate. Which is the most appropriate IMMEDIATE management?",
    "options": [
      { "text": "Oral NSAIDs for pain and discharge home with hydroxyurea adjustment", "explanation": "Incorrect. This patient has not only a vaso-occlusive pain crisis but also features of ACUTE CHEST SYNDROME (new pulmonary infiltrate, hypoxia, fever, chest findings) — a life-threatening complication requiring hospital admission and aggressive management. NSAIDs alone are inadequate for 10/10 pain. This would be the correct answer for mild vaso-occlusive crisis without acute chest features." },
      { "text": "Admit; IV opioids, O2, ceftriaxone + azithromycin, transfuse as needed", "explanation": "Correct. Hospital admission with: IV opioids (e.g., morphine via PCA) for severe pain, IV fluids (cautious), supplemental oxygen to keep sat ≥95%, empiric antibiotics (ceftriaxone + azithromycin) for acute chest syndrome, incentive spirometry, simple or exchange transfusion as needed. This patient has CONCURRENT vaso-occlusive crisis AND ACUTE CHEST SYNDROME (ACS) — a life-threatening pulmonary complication defined by new pulmonary infiltrate + ≥1 of: chest pain, fever, hypoxia, cough, tachypnea, wheezing. ACS is the leading cause of mortality in sickle cell disease. Triggers include infection (pneumonia), fat embolism from bone marrow infarction, atelectasis, and vaso-occlusion in the pulmonary microvasculature. Management of ACS: (1) HOSPITAL ADMISSION; (2) AGGRESSIVE PAIN CONTROL (IV opioids via PCA — pain control reduces splinting and atelectasis); (3) JUDICIOUS IV FLUIDS (overhydration can worsen pulmonary edema); (4) SUPPLEMENTAL OXYGEN to maintain sat ≥95% (prevents further sickling); (5) EMPIRIC ANTIBIOTICS (ceftriaxone + azithromycin to cover typical and atypical pneumonia organisms — sickle cell patients are functionally asplenic and at risk for encapsulated organisms); (6) INCENTIVE SPIROMETRY (prevents atelectasis); (7) TRANSFUSION — simple transfusion if Hgb has dropped substantially; EXCHANGE TRANSFUSION for severe ACS with worsening hypoxia or multi-organ involvement (rapidly reduces HbS%); (8) Bronchodilators if reactive airway component. Chronic management with hydroxyurea reduces ACS risk." },
      { "text": "Initiate emergent allogeneic stem cell transplant evaluation", "explanation": "Incorrect. While allogeneic SCT is potentially curative for sickle cell disease (especially in children with matched sibling donors), it is not emergent therapy for an acute crisis. The patient needs acute management first; SCT evaluation is appropriate in stable outpatients with high-risk disease and matched donors. This would be the correct answer for elective outpatient SCT counseling." },
      { "text": "Provide aggressive IV hydration (3-4 L over 4 hours) and observation only", "explanation": "Incorrect. Over-aggressive hydration can WORSEN acute chest syndrome by causing pulmonary edema. Fluid resuscitation should be cautious, particularly in patients with ACS. Pain control and oxygen are more important. This would be the correct answer in pure dehydration-triggered crisis without pulmonary complications." },
      { "text": "Withhold opioids due to concern for addiction; use only acetaminophen and gentle massage", "explanation": "Incorrect. Inadequate analgesia is a major failure in sickle cell care. These patients have severe documented pain physiology and require adequate opioid analgesia. Untreated pain prolongs the crisis, worsens splinting/atelectasis, and is unethical. Concerns about addiction are outweighed by the need for humane and effective pain control. This would be the correct answer NEVER in acute sickle cell crisis." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Sickle cell + new pulmonary infiltrate + chest symptoms = ACUTE CHEST SYNDROME (leading cause of mortality). Treat: pain control + O2 + cautious fluids + ABX (ceftriaxone+azithro) + incentive spirometry + exchange transfusion if severe.",
    "pdfPage": 40,
    "pdfQuote": "sickle cell"
  },
  {
    "id": 8,
    "category": "Hematology: Hereditary Spherocytosis Management",
    "questionText": "A 12-year-old girl with a family history of 'jaundice and gallstones' presents with chronic fatigue, intermittent scleral icterus, and now a 2-week history of right upper quadrant pain. Vitals: BP 110/70, HR 88. Exam: scleral icterus, palpable spleen 6 cm below costal margin, RUQ tenderness with Murphy sign. Labs: Hgb 9.0, MCV 80, MCHC 38 (elevated), RDW 15, reticulocyte count 12%, total bilirubin 3.5 (indirect 3.0), LDH 320, haptoglobin <10, direct Coombs NEGATIVE, smear shows SPHEROCYTES with no central pallor, osmotic fragility test POSITIVE, EMA-binding test reduced. Abdominal ultrasound shows multiple gallstones. Which is the most appropriate definitive management?",
    "options": [
      { "text": "Begin lifelong oral folate supplementation; no other intervention", "explanation": "Incorrect. While daily folate supplementation IS recommended in chronic hemolytic anemias to prevent megaloblastic crisis, it does not address the symptomatic splenomegaly, ongoing hemolysis, or pigment gallstones requiring cholecystectomy. This would be the correct answer in mild HS without complications." },
      { "text": "Splenectomy + cholecystectomy; vaccinate first", "explanation": "Correct. Splenectomy is preferably partial in children, or total in severe cases, performed with cholecystectomy at the same operation; continue folate supplementation lifelong; vaccinate against encapsulated organisms BEFORE splenectomy. This patient has moderate-to-severe HEREDITARY SPHEROCYTOSIS (HS) confirmed by smear (spherocytes, no central pallor, elevated MCHC), positive osmotic fragility, reduced EMA-binding, and negative Coombs (distinguishing from WAIHA). She also has SYMPTOMATIC PIGMENT GALLSTONES (chronic hemolysis → unconjugated bilirubin → calcium bilirubinate stones). Indications for SPLENECTOMY in HS: (1) severe anemia (Hgb <8) or transfusion dependence, (2) symptomatic anemia with limitations, (3) growth retardation in children, (4) symptomatic splenomegaly, (5) symptomatic gallstones (combined with cholecystectomy). Splenectomy resolves anemia because the malformed spherocytes are no longer destroyed in the spleen. PARTIAL splenectomy may be preferred in young children to preserve immune function. Pre-splenectomy: VACCINATE against encapsulated organisms (S. pneumoniae, H. influenzae type B, N. meningitidis) at least 2 weeks before surgery, ideally complete prior to age 5 if planned earlier. Post-splenectomy: daily penicillin prophylaxis in children up to age 5+ years (some recommend lifelong in children). CHOLECYSTECTOMY at same operation if symptomatic gallstones. Continue folate supplementation lifelong to prevent megaloblastic crisis from chronic high RBC turnover." },
      { "text": "Long-term oral corticosteroids", "explanation": "Incorrect. HS is NOT autoimmune — it is an intrinsic membrane cytoskeleton defect (spectrin, ankyrin, band 3, protein 4.2). Steroids do not help. They would help warm AIHA (which is Coombs positive, unlike HS). This would be the correct answer in WAIHA." },
      { "text": "Plasmapheresis to remove autoantibodies", "explanation": "Incorrect. HS is not antibody-mediated. Plasmapheresis is not appropriate. This would be the correct answer in TTP or Waldenstrom hyperviscosity." },
      { "text": "Allogeneic stem cell transplant", "explanation": "Incorrect. SCT is far too aggressive for HS, which is well-managed with splenectomy. The treatment toxicities of SCT outweigh the benefit. This would be the correct answer in severe transfusion-dependent thalassemia major or sickle cell with matched donors." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Symptomatic HS = splenectomy (often with cholecystectomy for pigment stones). Vaccinate against encapsulated organisms BEFORE surgery. Lifelong folate supplementation in all chronic hemolysis.",
    "pdfPage": 28,
    "pdfQuote": "spherocytosis"
  },
  {
    "id": 9,
    "category": "Hematology: HELLP Syndrome Management",
    "questionText": "A 28-year-old G1P0 woman at 33 weeks gestation presents with right upper quadrant pain, headache, and visual changes. Vitals: T 37.2°C, BP 168/108, HR 90, RR 18. Exam: RUQ tenderness, 2+ pitting edema, brisk reflexes with sustained clonus. Urine dipstick shows 3+ protein. Labs: Hgb 9.0, platelets 65K, AST 380, ALT 320, total bilirubin 2.1 (indirect 1.5), LDH 850, schistocytes on smear, fibrinogen 280 (normal), PT/PTT normal. Fetal monitoring shows reassuring tracing. Which is the most appropriate management?",
    "options": [
      { "text": "Discharge home with bed rest and follow-up in 1 week", "explanation": "Incorrect. HELLP syndrome is a life-threatening obstetric emergency for both mother and fetus, requiring immediate hospitalization and definitive management (delivery). Discharge would risk maternal mortality from stroke, hepatic hematoma rupture, DIC, or eclampsia. This would be the correct answer NEVER in HELLP." },
      { "text": "Admit; IV magnesium, antihypertensives, and DEFINITIVE DELIVERY of the fetus", "explanation": "Correct. Hospital admission with IV magnesium sulfate (seizure prophylaxis), antihypertensive therapy (IV labetalol or hydralazine), and DEFINITIVE DELIVERY of the fetus (after corticosteroid course for fetal lung maturity if time permits). This patient has HELLP SYNDROME — a severe variant of preeclampsia with: (1) HEMOLYSIS (schistocytes, indirect hyperbili, elevated LDH), (2) ELEVATED LIVER ENZYMES (AST/ALT elevated), (3) LOW PLATELETS (thrombocytopenia). Plus signs of preeclampsia with severe features (BP >160/110, proteinuria, RUQ pain, headache, visual changes, hyperreflexia/clonus). HELLP is a MAHA-like condition where microangiopathy in the placental/hepatic vasculature drives hemolysis. PT/PTT/fibrinogen are usually NORMAL (distinguishing from DIC where they would be deranged). Management: (1) HOSPITAL ADMISSION at a facility with high-risk obstetric and neonatal care; (2) MAGNESIUM SULFATE for seizure prophylaxis (prevents eclampsia); (3) ANTIHYPERTENSIVES — IV labetalol, IV hydralazine, or oral nifedipine (target BP <160/110 but not too low to avoid placental hypoperfusion); (4) DEFINITIVE TREATMENT IS DELIVERY — at 34+ weeks, deliver promptly; at <34 weeks, may give corticosteroids (betamethasone) for fetal lung maturation over 24-48 hours IF maternal/fetal status allows, then deliver; (5) PLATELET TRANSFUSION before delivery only if platelets <20K or active bleeding (or higher if cesarean); (6) Monitor for postpartum eclampsia (can occur up to 6 weeks postpartum); (7) Avoid plasma exchange (HELLP is not TTP). MAHA + thrombocytopenia + pregnancy is HELLP until proven otherwise (vs TTP, atypical HUS, acute fatty liver of pregnancy — sometimes overlapping)." },
      { "text": "Initiate plasma exchange daily until platelets normalize, then continue pregnancy to term", "explanation": "Incorrect. HELLP is not TTP — plasma exchange is not first-line. The definitive treatment is delivery. Plasma exchange may be considered in HELLP that does not resolve postpartum (suggesting overlap with TTP or atypical HUS). This would be the correct answer in TTP, not HELLP." },
      { "text": "Allow vaginal delivery only after platelets recover to >100K with steroids and tocolytics for 1-2 weeks", "explanation": "Incorrect. Tocolytics (which delay delivery) are NOT appropriate in HELLP — delivery is the definitive treatment and delay can be catastrophic for mother. Corticosteroids (betamethasone) for fetal lung maturity may be given briefly (24-48 hours) at <34 weeks but only if maternal status allows. This would be the correct answer in preterm labor without HELLP." },
      { "text": "Initiate emergent hemodialysis for AKI", "explanation": "Incorrect. The patient does not have acute renal failure requiring dialysis in this vignette. HELLP does not typically require dialysis. This would be the correct answer in severe AKI with metabolic indications for dialysis." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HELLP = Hemolysis (MAHA, schistocytes) + Elevated Liver enzymes + Low Platelets in preeclamptic pregnancy. Definitive treatment = DELIVERY. Magnesium for seizure prophylaxis; antihypertensives. Distinguish from TTP (which needs plasma exchange).",
    "pdfPage": 36,
    "pdfQuote": "schistocytes"
  },
  {
    "id": 10,
    "category": "Hematology: Folate Deficiency in Pregnancy",
    "questionText": "A 25-year-old G2P1 woman at 16 weeks gestation presents with progressive fatigue and pallor. She had no prenatal care until now. Diet is poor in leafy greens. Vitals: BP 108/68, HR 90. Exam: pale conjunctiva, glossitis, no organomegaly, fundal height appropriate for dates. Labs: Hgb 8.8, MCV 112, RDW 18, hypersegmented neutrophils, serum folate 1.2 (low), B12 320 (normal), MMA NORMAL, homocysteine elevated. She is unsure if she took prenatal vitamins. Her first child was born with spina bifida. Which is the most appropriate management?",
    "options": [
      { "text": "Iron supplementation alone and a follow-up CBC in 4 weeks", "explanation": "Incorrect. The patient has folate deficiency (low folate, macrocytic anemia, hypersegmented neutrophils, elevated homocysteine with normal MMA — pattern of pure folate deficiency). Iron alone would not treat folate deficiency and would not correct the macrocytosis. This would be the correct answer in pure iron deficiency anemia." },
      { "text": "Folic acid 4 mg daily PLUS prenatal vitamins", "explanation": "Correct. Folic acid 1-5 mg daily orally (high-dose for those with prior NTD-affected pregnancy, typically 4 mg/day from at least 1 month before conception and continued through first trimester) PLUS standard prenatal vitamins. This patient has FOLATE DEFICIENCY in pregnancy — confirmed by low serum folate, macrocytic megaloblastic anemia, NORMAL B12 and NORMAL MMA (distinguishing folate-only from B12 deficiency where MMA would be elevated). Pregnancy dramatically increases folate demand (rapidly dividing fetal and placental cells) and folate body stores are small (~3-month supply). Risks: (1) maternal megaloblastic anemia, (2) NEURAL TUBE DEFECTS (spina bifida, anencephaly) — folate prevents these by supporting normal neural tube closure in the first 28 days post-conception. Her prior child with spina bifida marks her as HIGH-RISK; she should receive HIGH-DOSE FOLIC ACID (4 mg/day, ideally started ≥1 month BEFORE conception and continued through the first trimester — standard recommendation is 4 mg/day for women with prior NTD-affected pregnancy or who are on antiepileptics). At 16 weeks the neural tube has already formed, so for this pregnancy NTD prevention is past — but standard folate replacement is still needed to treat her anemia and prevent recurrence in future pregnancies. Standard prenatal vitamins contain 400-800 mcg folate, which is insufficient for high-risk patients. Pre-conception counseling is critical." },
      { "text": "IM cyanocobalamin (B12) 1000 µg weekly", "explanation": "Incorrect. The patient does not have B12 deficiency — her B12 is normal and MMA is normal (B12 deficiency would elevate MMA). Giving B12 alone would not treat her folate deficiency. This would be the correct answer in confirmed B12 deficiency." },
      { "text": "Initiate emergency RBC transfusion to target Hgb >12", "explanation": "Incorrect. The patient is stable at Hgb 8.8 with chronic anemia and is not symptomatic enough to warrant transfusion. Folate replacement will correct the anemia in weeks. Transfusion is reserved for severe symptomatic anemia or hemodynamic instability. This would be the correct answer with Hgb <7 with severe symptoms or hemodynamic compromise." },
      { "text": "Refer for bone marrow biopsy to rule out myelodysplastic syndrome", "explanation": "Incorrect. The straightforward folate-deficient picture (low folate, normal B12, dietary risk factor, pregnancy) does not warrant invasive bone marrow biopsy. Treat folate deficiency first; if the anemia does not resolve, then reconsider. This would be the correct answer in unexplained pancytopenia with dysplastic features or excess blasts." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Folate deficiency in pregnancy → megaloblastic anemia + NTD risk. Standard prenatal = 400-800 mcg folic acid; HIGH-RISK (prior NTD baby, antiepileptics) = 4 mg/day starting ≥1 month preconception through T1.",
    "pdfPage": 9,
    "pdfQuote": "folate"
  },
  {
    "id": 11,
    "category": "Hematology: MAHA from Malignant Hypertension",
    "questionText": "A 48-year-old man with a history of untreated essential hypertension presents to the ED with severe headache, blurred vision, and chest pain. Vitals: T 37.0°C, BP 230/140, HR 100, RR 22. Exam: confused, papilledema with retinal hemorrhages and exudates on funduscopy, S4 gallop, no focal neurologic deficits. Labs: Hgb 8.5, platelets 80K, creatinine 3.5 (baseline normal), LDH 950, total bilirubin 2.4 (indirect), haptoglobin <10, schistocytes on smear, PT/PTT normal, fibrinogen normal, ADAMTS13 activity normal (75%). Urinalysis: hematuria, proteinuria, RBC casts. Which is the most likely diagnosis?",
    "options": [
      { "text": "Thrombotic thrombocytopenic purpura (TTP)", "explanation": "Incorrect. TTP would show very low ADAMTS13 (<10%), classically with the pentad including fever and neurologic symptoms but typically without hypertensive emergency features. This patient's ADAMTS13 is normal at 75%, ruling out TTP. This would be the correct answer with ADAMTS13 <10% and inhibitor present." },
      { "text": "Malignant hypertension causing MAHA", "explanation": "Correct. There is mechanical RBC fragmentation in damaged small vessels. MALIGNANT (HYPERTENSIVE EMERGENCY) HYPERTENSION = severely elevated BP (typically >180/120) WITH END-ORGAN DAMAGE (encephalopathy/papilledema, acute renal failure, MAHA, acute cardiac decompensation, pulmonary edema, retinal hemorrhages). The mechanism of MAHA in malignant hypertension: the severe hypertension damages small vessel endothelium → fibrin deposition in damaged vessels → mechanical SHEARING of RBCs as they pass → SCHISTOCYTES (helmet cells, fragmented RBCs), causing microangiopathic hemolysis. This is distinct from TTP (where ADAMTS13 deficiency drives the microthrombi) and HUS (where Shiga toxin or complement drives endothelial injury). Key features distinguishing this MAHA from TTP: severely elevated BP, normal ADAMTS13, response to BP control. Management: (1) URGENT BLOOD PRESSURE REDUCTION — IV labetalol, nicardipine, or nitroprusside; reduce MAP by ~25% in first hour, then more gradually over 24-48 hours (avoid rapid lowering which can cause cerebral or coronary hypoperfusion); (2) Treat underlying hypertension chronically; (3) Supportive care for AKI, including dialysis if needed; (4) MAHA resolves once BP is controlled. (5) AVOID plasma exchange (this is NOT TTP)." },
      { "text": "Atypical hemolytic uremic syndrome (aHUS)", "explanation": "Incorrect. Atypical HUS is caused by complement system dysregulation (mutations in regulators or anti-factor H antibodies) and produces MAHA + thrombocytopenia + AKI WITHOUT preceding diarrhea. While the lab picture could be similar, the dominant feature here is the malignant hypertension with end-organ damage. The right call is malignant HTN-induced MAHA first; aHUS would be considered if MAHA persisted after BP control. This would be the correct answer with MAHA + AKI without hypertensive emergency or diarrhea." },
      { "text": "Disseminated intravascular coagulation (DIC)", "explanation": "Incorrect. DIC would show abnormal coagulation — prolonged PT/PTT, LOW FIBRINOGEN, elevated D-dimer. This patient has NORMAL PT/PTT and NORMAL fibrinogen, ruling out DIC. This would be the correct answer with low fibrinogen, prolonged PT/PTT, and elevated D-dimer in a sepsis/trauma context." },
      { "text": "HELLP syndrome", "explanation": "Incorrect. HELLP occurs in pregnancy — this patient is male. This would be the correct answer in a pregnant patient with similar lab findings." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Malignant HTN causes MAHA via endothelial damage and fibrin-mediated RBC shearing. ADAMTS13 NORMAL (vs TTP <10%). Treat with controlled BP reduction; MAHA resolves with BP control.",
    "pdfPage": 35,
    "pdfQuote": "schistocytes"
  },
  {
    "id": 12,
    "category": "Hematology: Acute Hemolytic Transfusion Reaction",
    "questionText": "A 45-year-old woman with active GI bleeding receives a blood transfusion. Within 15 minutes of starting the unit, she develops fever (39.0°C), severe back/flank pain, hypotension (BP 78/40), tachycardia, dyspnea, and dark red urine. The transfusion is immediately stopped. Vitals after stopping: BP 82/45, HR 130, RR 28, T 39.2°C. Labs: hemoglobinuria, indirect hyperbilirubinemia, undetectable haptoglobin, positive direct Coombs (now after transfusion). DIC labs pending. Which is the most likely cause of her transfusion reaction?",
    "options": [
      { "text": "Allergic transfusion reaction (Type I hypersensitivity)", "explanation": "Incorrect. Allergic reactions typically present with urticaria, pruritus, mild bronchospasm — without fever, hemoglobinuria, or hemodynamic collapse. This patient has severe acute intravascular hemolysis, not an allergic reaction. This would be the correct answer with urticaria and mild bronchospasm only." },
      { "text": "Acute hemolytic transfusion reaction (AHTR)", "explanation": "Correct. This is most often from ABO incompatibility due to clerical error/mismatch. The presentation is classic ACUTE HEMOLYTIC TRANSFUSION REACTION: within minutes to hours of transfusion, fever, flank/back pain, hypotension, hemoglobinuria (intravascular hemolysis = free hemoglobin in plasma → urine), and DIC. The dominant cause is ABO INCOMPATIBILITY — preformed recipient anti-A or anti-B IgM antibodies bind donor RBC ABO antigens, fix complement, and cause massive intravascular hemolysis. Most cases are due to CLERICAL ERROR (mislabeled tube, wrong patient ID, blood sent to wrong patient). Management: (1) STOP THE TRANSFUSION IMMEDIATELY (already done); (2) keep the IV open with saline; (3) SEND the residual unit + a fresh patient sample BACK TO THE BLOOD BANK for compatibility re-testing and direct Coombs; (4) AGGRESSIVE IV FLUIDS to maintain renal perfusion and prevent pigment nephropathy from free hemoglobin; (5) Monitor for DIC (PT/PTT, fibrinogen, D-dimer, platelets); supportive care; (6) Vasopressors for hypotension; (7) Possible diuretics to maintain urine output. Other transfusion reactions: febrile non-hemolytic (cytokines from donor WBCs, treat with antipyretics, prevented by leukoreduction); TRALI (transfusion-related acute lung injury — donor anti-HLA antibodies → ARDS within 6 hours, supportive care); TACO (volume overload — diuretics)." },
      { "text": "Febrile non-hemolytic transfusion reaction (FNHTR)", "explanation": "Incorrect. FNHTR presents with fever, chills, and mild discomfort but NOT hemoglobinuria, severe hypotension, or hemolysis. It is caused by recipient antibodies against donor leukocyte HLA antigens or cytokines released by donor WBCs during storage. Prevented by leukoreduction. This would be the correct answer with isolated fever/chills without other features." },
      { "text": "Transfusion-related acute lung injury (TRALI)", "explanation": "Incorrect. TRALI presents with non-cardiogenic pulmonary edema (ARDS-like) within 6 hours of transfusion — fever, hypoxia, bilateral pulmonary infiltrates. While dyspnea is present in this patient, the dominant features (hemoglobinuria, flank pain, hypotension) point to AHTR. This would be the correct answer with predominant respiratory failure and bilateral infiltrates." },
      { "text": "Bacterial contamination of the unit (septic transfusion reaction)", "explanation": "Incorrect. Bacterial contamination (often platelets, less often RBCs) presents with high fever, rigors, hypotension within hours of transfusion. While clinically can mimic AHTR, the hemoglobinuria and intravascular hemolysis pattern point specifically to AHTR (ABO mismatch). Workup with Gram stain and culture of the unit is part of the standard reaction workup. This would be the correct answer with positive blood culture on the unit." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: AHTR = fever + flank pain + hypotension + hemoglobinuria within minutes of transfusion. ABO mismatch from clerical error is the typical cause. Stop transfusion, send unit back to blood bank, support BP, prevent renal injury.",
    "pdfPage": 33,
    "pdfQuote": "Coombs"
  },
  {
    "id": 13,
    "category": "Hematology: Nitrous Oxide Megaloblastic Anemia",
    "questionText": "A 22-year-old man presents to the neurology clinic with progressive lower extremity weakness, gait imbalance, and burning paresthesias in both feet that began 2 months ago. He works at a dental office and admits to recreational use of nitrous oxide (whippets) for the past 6 months, escalating to daily use. Vitals: BP 122/70, HR 80. Exam: ataxic gait, positive Romberg, decreased vibratory sense and proprioception in both feet, brisk lower extremity reflexes with extensor plantar response. Labs: Hgb 11.5, MCV 108, RDW 16, mild hypersegmented neutrophils, serum B12 320 (within normal range), MMA 580 (markedly elevated), homocysteine 28 (elevated). Which best explains his presentation?",
    "options": [
      { "text": "Primary autoimmune neuropathy unrelated to drug use", "explanation": "Incorrect. The combination of elevated MMA + elevated homocysteine + macrocytosis + dorsal column/lateral corticospinal signs (subacute combined degeneration pattern) + nitrous oxide use is a well-described drug-induced functional B12 deficiency syndrome, not autoimmune. This would be the correct answer with GBS-like or MS-like presentation and appropriate confirmatory testing." },
      { "text": "Nitrous oxide-induced functional B12 deficiency", "explanation": "Correct. N2O irreversibly OXIDIZES the cobalt center of B12 (cobalamin) from the active Co+ form to the inactive Co3+ form, inactivating methionine synthase and methylmalonyl-CoA mutase even when serum B12 levels appear normal. NITROUS OXIDE (N2O) inactivates vitamin B12 by oxidizing the cobalt center of methylcobalamin from the +1 to the +3 oxidation state, rendering it unable to serve as a cofactor for methionine synthase. With chronic exposure, this functional B12 deficiency develops despite NORMAL serum B12 levels (the standard assay doesn't distinguish active vs inactive cobalamin). Diagnostic clue: elevated MMA and elevated HOMOCYSTEINE confirm functional B12 deficiency. Clinical syndrome: SUBACUTE COMBINED DEGENERATION of the spinal cord (dorsal columns → loss of vibration/proprioception, positive Romberg; lateral corticospinal tracts → spastic weakness, hyperreflexia, extensor plantars) — plus megaloblastic anemia (often mild). N2O abuse is increasingly recognized as a cause; healthcare workers, dental staff, and recreational users are at risk. Management: (1) STOP N2O exposure; (2) PARENTERAL B12 REPLACEMENT (high-dose IM cyanocobalamin or hydroxocobalamin) — typically 1000 µg daily initially, then weekly, sometimes longer; (3) Neurologic recovery may be incomplete if exposure has been prolonged; (4) Counseling and addiction support if recreational use. Note: methionine and folate co-supplementation has also been suggested." },
      { "text": "Multiple sclerosis with new myelin demyelination", "explanation": "Incorrect. MS would not cause elevated MMA and macrocytic anemia. The lab pattern points to functional B12 deficiency. This would be the correct answer with MRI showing demyelinating white matter lesions and CSF oligoclonal bands." },
      { "text": "Vitamin E deficiency causing sensory ataxia", "explanation": "Incorrect. Vitamin E deficiency can cause spinocerebellar degeneration but does not cause megaloblastic anemia or elevated MMA. The lab pattern points to functional B12 deficiency. This would be the correct answer with confirmed low vitamin E in malabsorption (e.g., cystic fibrosis, abetalipoproteinemia)." },
      { "text": "Lead poisoning with neurotoxicity", "explanation": "Incorrect. Lead poisoning causes peripheral neuropathy (often motor wrist drop) and microcytic anemia with basophilic stippling — not macrocytic anemia with subacute combined degeneration. This would be the correct answer with lead exposure, basophilic stippling, microcytic anemia, and elevated blood lead." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Nitrous oxide oxidizes B12 (Co+ → Co3+) → FUNCTIONAL B12 deficiency despite normal serum B12. Elevated MMA + homocysteine. Subacute combined degeneration. Stop N2O + parenteral B12.",
    "pdfPage": 12,
    "pdfQuote": "B12"
  },
  {
    "id": 14,
    "category": "Hematology: Sickle Cell Splenic Sequestration",
    "questionText": "A 2-year-old child with known sickle cell disease (HbSS) is brought to the ED by her parents with sudden onset pallor, lethargy, and a markedly enlarged abdomen over the past 6 hours. Vitals: T 37.6°C, HR 160, BP 70/35, RR 32, O2 sat 96%. Exam: pale, lethargic but rousable, abdomen distended with a massively enlarged spleen palpable to the umbilicus, tender. Labs: Hgb 3.5 (down from baseline 8.5), platelets 90K (down from baseline 350K), WBC 18, reticulocyte count 14% (PRESERVED). Which is the most likely diagnosis AND best immediate management?",
    "options": [
      { "text": "Vaso-occlusive abdominal crisis — manage with IV opioids and hydration only", "explanation": "Incorrect. While vaso-occlusive crisis can cause abdominal pain in sickle cell patients, the dominant features here (massive splenomegaly, profound Hgb drop, hypovolemic shock) point to acute splenic sequestration, NOT VOC. Pain management alone would not address the rapidly fatal hemorrhagic shock. This would be the correct answer in vaso-occlusive crisis with severe pain but stable Hgb and no splenic enlargement." },
      { "text": "Acute splenic sequestration crisis — IV fluid resuscitation and urgent RBC transfusion", "explanation": "Correct. Emergent IV fluid resuscitation, urgent RBC transfusion (typically simple, 5-10 mL/kg), supportive care; consider splenectomy after recovery for recurrence prevention. This is ACUTE SPLENIC SEQUESTRATION CRISIS — a life-threatening complication seen in young children with sickle cell disease (typically <5 years) BEFORE the spleen autoinfarcts. RBCs are trapped in the spleen, causing rapid Hgb drop, splenomegaly, and HYPOVOLEMIC SHOCK from sequestration of blood volume. Distinguishing features from aplastic crisis: reticulocyte count is PRESERVED (marrow is working — the problem is sequestration, not production), splenomegaly is dramatic. Management: (1) URGENT IV FLUID RESUSCITATION (treat hypovolemic shock); (2) URGENT RBC TRANSFUSION — typically simple transfusion at 5-10 mL/kg (avoid over-transfusion because as the crisis resolves, sequestered RBCs may release from the spleen back into the circulation, causing hyperviscosity or hypertension if total RBC load is too high); (3) Monitor in PICU; (4) AFTER recovery, consider chronic management with: chronic transfusion, hydroxyurea, or SPLENECTOMY (for recurrent episodes — typically after 2+ episodes). Family education on splenic palpation for early detection of recurrence is critical. By adolescence, most HbSS patients have autoinfarcted their spleen, so splenic sequestration is essentially absent thereafter — but HbSC patients retain splenic function longer and can have sequestration at older ages." },
      { "text": "Acute parvovirus B19-induced aplastic crisis — supportive care and transfusion if Hgb continues to fall", "explanation": "Incorrect. Aplastic crisis would show RETICULOCYTOPENIA (essentially absent reticulocytes), not the preserved 14% reticulocytes seen here. Splenomegaly would not be the dominant feature in aplastic crisis. This would be the correct answer with retic count near zero." },
      { "text": "Acute hemolytic crisis from new alloantibody — initiate plasma exchange", "explanation": "Incorrect. Acute hemolytic crisis from alloimmunization would show severe hemolysis labs (very elevated LDH, indirect bilirubin, low haptoglobin) and would not cause acute massive splenomegaly with sequestration. Plasma exchange is not standard therapy for this scenario. This would be the correct answer in a severe delayed hemolytic transfusion reaction with elevated bilirubin/LDH after recent transfusion." },
      { "text": "Acute chest syndrome with peripheral signs — start ceftriaxone and azithromycin", "explanation": "Incorrect. Acute chest syndrome presents with pulmonary symptoms (cough, chest pain, hypoxia, new infiltrate on CXR), not splenomegaly and hemorrhagic shock from sequestration. This would be the correct answer in pulmonary distress with new infiltrate." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: Sickle cell + young child + acute splenomegaly + Hgb crash + PRESERVED retic = SPLENIC SEQUESTRATION CRISIS. Urgent IV fluids + RBC transfusion (avoid over-transfusion). Splenectomy if recurrent.",
    "pdfPage": 40,
    "pdfQuote": "splenic"
  },
  {
    "id": 15,
    "category": "Hematology: Methotrexate Macrocytic Anemia and Leucovorin Rescue",
    "questionText": "A 64-year-old woman with rheumatoid arthritis on methotrexate 20 mg weekly for 8 months presents with worsening fatigue, mouth ulcers, and a 5-day history of diarrhea. Vitals: T 37.8°C, BP 122/74, HR 88. Exam: oral mucositis, mild abdominal tenderness, no acute distress. Labs: Hgb 9.0, MCV 110, RDW 16, platelets 90K, WBC 2.8 (ANC 1,400), hypersegmented neutrophils, AST 65, ALT 88. Methotrexate level not detectable (last dose 4 days ago). Which is the most appropriate management?",
    "options": [
      { "text": "Continue methotrexate at the same dose and add prednisone for RA flare", "explanation": "Incorrect. The patient has methotrexate toxicity (pancytopenia, oral mucositis, transaminitis) — continuing MTX would worsen toxicity. Holding the drug is essential. This would be the correct answer in an RA flare without MTX toxicity." },
      { "text": "Hold methotrexate, give LEUCOVORIN (folinic acid) rescue, supplement folic acid", "explanation": "Correct. For severe toxicity, consider glucarpidase (carboxypeptidase G2) to rapidly clear MTX. The patient has METHOTREXATE TOXICITY — characterized by pancytopenia (anemia, leukopenia, thrombocytopenia), oral and GI mucositis, hepatotoxicity (transaminitis), and renal injury. Mechanism: MTX is a DIHYDROFOLATE REDUCTASE INHIBITOR that blocks conversion of dihydrofolate to tetrahydrofolate, depriving cells of reduced folates needed for thymidine and purine synthesis — affecting rapidly dividing cells (marrow, mucosa). Management: (1) HOLD METHOTREXATE; (2) LEUCOVORIN (folinic acid = formyl-THF) RESCUE — leucovorin is a REDUCED folate that bypasses the DHFR block, restoring folate availability to normal cells (cancer cells generally express lower DHFR and accumulate less leucovorin; in non-cancer contexts, leucovorin rescue is purely protective); dose depends on severity, often 10-25 mg PO every 6 hours; (3) GLUCARPIDASE (carboxypeptidase G2) — for severe toxicity or AKI with persistent high MTX levels, this enzyme rapidly inactivates MTX in plasma; (4) AGGRESSIVE HYDRATION + URINARY ALKALINIZATION (with NaHCO3 to keep urine pH >7) to maintain MTX solubility and renal clearance; (5) Daily oral folic acid 1 mg (standard supplement with MTX for RA) was likely already in place but should continue; (6) Monitor renal function, LFTs, CBC; (7) Avoid drugs that increase MTX toxicity (NSAIDs, TMP-SMX, PPIs). Note that leucovorin (folinic acid) is distinct from folic acid — only leucovorin bypasses the DHFR block." },
      { "text": "Administer high-dose oral folic acid 5 mg daily and reduce methotrexate dose by half", "explanation": "Incorrect. In acute MTX toxicity, FOLIC ACID alone does not bypass the DHFR block (folic acid must be reduced by DHFR to active forms — but DHFR is blocked by MTX). LEUCOVORIN (folinic acid, already reduced) is the appropriate rescue. Standard folic acid supplementation (1 mg daily) is given prophylactically with MTX for RA. This would be the correct answer for routine maintenance with MTX, but inadequate for acute toxicity." },
      { "text": "Start IV penicillin G to treat presumed mucositis from group A strep", "explanation": "Incorrect. The oral mucositis is a direct effect of MTX-induced disruption of rapidly dividing mucosal cells, not bacterial infection. Antibiotics are not indicated unless there is documented secondary infection. This would be the correct answer in confirmed bacterial pharyngitis." },
      { "text": "Begin GCS-F (filgrastim) to recover neutrophil count and continue methotrexate", "explanation": "Incorrect. While G-CSF can be used in severe neutropenia, continuing MTX without rescue would worsen toxicity. The first step is to hold MTX and provide leucovorin rescue. This would be the correct answer in chemotherapy-induced neutropenia with planned recovery for next cycle." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: MTX toxicity = pancytopenia + mucositis + transaminitis. Treat: HOLD MTX + LEUCOVORIN (folinic acid bypasses DHFR block) + hydration/urinary alkalinization. Glucarpidase for severe AKI with persistent MTX levels. FOLIC ACID alone does not rescue acute toxicity.",
    "pdfPage": 9,
    "pdfQuote": "folate"
  },
  {
    "id": 16,
    "category": "Hematology: G6PD Episode After Anti-malarial",
    "questionText": "A 28-year-old man of Mediterranean descent travels to sub-Saharan Africa and is given PRIMAQUINE for radical cure of P. vivax malaria (treating presumed hypnozoites). Twenty-four hours after his first dose, he develops dark urine, jaundice, abdominal pain, and weakness. Vitals: T 38.0°C, BP 100/60, HR 110, RR 22. Exam: pale, scleral icterus, mild abdominal tenderness, no hepatosplenomegaly. Labs: Hgb 7.5 (baseline 14), MCV 95, retic 12%, total bilirubin 5.0 (indirect 4.5), LDH 1,400, haptoglobin <10, peripheral smear shows BITE CELLS and HEMIGHOSTS, Heinz bodies on supravital staining. Which is the most appropriate management?",
    "options": [
      { "text": "Continue primaquine to complete the antimalarial course; supportive care", "explanation": "Incorrect. Primaquine is the TRIGGER of acute hemolysis in this G6PD-deficient patient and must be DISCONTINUED. The MEDITERRANEAN variant of G6PD is much more severe than the African (A-) variant — hemolysis can be life-threatening. This would be the correct answer if the patient had no G6PD issues and tolerated the drug." },
      { "text": "Discontinue primaquine; hydrate; confirm G6PD ≥3 months later", "explanation": "Correct. Supportive care with hydration to prevent pigment nephropathy, monitor for renal function and potassium, transfuse if symptomatic anemia worsens; confirm G6PD status with quantitative assay AFTER acute hemolysis has subsided (≥3 months). This is G6PD DEFICIENCY HEMOLYTIC CRISIS triggered by PRIMAQUINE (a well-known oxidative drug). G6PD is a key enzyme in the pentose phosphate pathway generating NADPH — required to maintain reduced glutathione that detoxifies oxidative stress. Without G6PD, oxidant exposure causes hemoglobin oxidation (Heinz bodies = oxidized denatured hemoglobin), splenic macrophages 'bite out' the precipitates (bite cells), and severe hemolysis ensues. The Mediterranean variant has very low residual enzyme activity (<10% of normal) and causes severe, prolonged hemolysis. Management: (1) DISCONTINUE the offending drug; (2) Supportive care: IV hydration to prevent pigment nephropathy (free hemoglobin can damage renal tubules); (3) Monitor renal function and potassium (hemolysis releases K+); (4) Transfuse if Hgb continues to fall and patient is symptomatic; (5) G6PD ASSAY: do NOT do during the acute crisis — the most deficient RBCs have already been destroyed, leaving only younger reticulocytes that are relatively G6PD-replete, producing a FALSELY NORMAL or NEAR-NORMAL G6PD level. Wait at least 3 months (until reticulocytes have aged into mature RBCs) for accurate measurement. (6) PROVIDE PATIENT EDUCATION on drugs/foods to avoid: SULFA drugs (TMP-SMX, sulfasalazine, dapsone), antimalarials (primaquine, tafenoquine — should screen G6PD BEFORE these), nitrofurantoin, methylene blue, fava beans, and certain henna products. Always screen G6PD BEFORE prescribing primaquine or tafenoquine." },
      { "text": "Initiate eculizumab to prevent further complement-mediated hemolysis", "explanation": "Incorrect. G6PD hemolysis is OXIDATIVE, not complement-mediated. Eculizumab targets complement (PNH, atypical HUS, cold agglutinin disease), not oxidative hemolysis. This would be the correct answer in PNH with thrombosis." },
      { "text": "Start prednisone 1 mg/kg for presumed autoimmune hemolytic anemia", "explanation": "Incorrect. G6PD hemolysis is NOT autoimmune — Coombs test would be NEGATIVE (intrinsic enzyme defect, not antibody-mediated). The bite cells, Heinz bodies, and drug trigger point clearly to G6PD. Steroids would not help. This would be the correct answer in warm AIHA with positive direct Coombs." },
      { "text": "Plasmapheresis to remove oxidized hemoglobin and offending drug", "explanation": "Incorrect. Plasmapheresis is not standard for G6PD hemolysis — supportive care after stopping the drug is the management. The drug is largely metabolized within hours and oxidized hemoglobin clearance is by macrophages. This would be the correct answer in TTP." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: G6PD crisis from primaquine (Mediterranean variant most severe) → discontinue drug + supportive care. Test G6PD AFTER acute hemolysis (≥3 months) — falsely normal during acute episode. SCREEN G6PD BEFORE prescribing primaquine/tafenoquine/dapsone.",
    "pdfPage": 30,
    "pdfQuote": "G6PD"
  },
  {
    "id": 17,
    "category": "Hematology: DIC vs TTP Differentiation",
    "questionText": "A 56-year-old man with metastatic prostate cancer presents with diffuse oozing from IV sites, hematuria, and bruising. Vitals: T 37.8°C, BP 110/70, HR 100, RR 22. Exam: petechiae, ecchymoses across the trunk, hematomas around IV sites, no neurologic deficits, mild splenomegaly. Labs: Hgb 8.5, platelets 35K, PT 22 (PROLONGED, INR 2.5), PTT 55 (PROLONGED), FIBRINOGEN 90 (LOW), D-dimer markedly elevated, schistocytes on smear, LDH 600, indirect hyperbili, ADAMTS13 activity normal (65%). Which is the most likely diagnosis?",
    "options": [
      { "text": "Thrombotic thrombocytopenic purpura (TTP)", "explanation": "Incorrect. TTP would show MAHA + thrombocytopenia with NORMAL PT/PTT and NORMAL fibrinogen (because the coagulation cascade itself is not activated) — and ADAMTS13 <10%. This patient has prolonged PT/PTT, low fibrinogen, and normal ADAMTS13 — pattern of consumptive coagulopathy (DIC), not TTP. This would be the correct answer with normal PT/PTT, low ADAMTS13, and the TTP pentad." },
      { "text": "Disseminated intravascular coagulation (DIC) from malignancy", "explanation": "Correct. DIC is most likely triggered by his metastatic malignancy. DIC is characterized by simultaneous WIDESPREAD ACTIVATION OF COAGULATION (with thrombosis) AND BLEEDING (from consumption of clotting factors and platelets). Lab pattern: (1) PROLONGED PT and PTT (consumption of clotting factors), (2) LOW FIBRINOGEN (consumption of fibrinogen → fibrin), (3) ELEVATED D-DIMER (fibrin breakdown), (4) THROMBOCYTOPENIA (consumption), (5) MAHA with schistocytes (mechanical fragmentation in fibrin-clotted small vessels). Triggers: SEPSIS (gram-negative bacteria, especially); OBSTETRIC catastrophes (amniotic fluid embolism, abruption); MALIGNANCY (especially adenocarcinomas — prostate, pancreatic, gastric); MASSIVE TRAUMA, BURNS, snake envenomation; APL (with release of procoagulant granules from promyelocytes). Treatment: (1) IDENTIFY AND TREAT THE UNDERLYING CAUSE (most important — DIC will not resolve until the trigger is addressed); (2) SUPPORTIVE TRANSFUSIONS: FFP for prolonged PT/PTT and to replace factors; cryoprecipitate for fibrinogen <100; platelets for thrombocytopenia with bleeding (target >50K with bleeding); (3) Treat with anticoagulation (e.g., low-dose heparin) ONLY in select cases with predominant thrombosis (rare). (4) Most patients have BOTH bleeding and clotting tendencies. CRITICAL distinction from TTP: in DIC, PT/PTT are deranged and fibrinogen low; in TTP, coag is normal." },
      { "text": "Atypical hemolytic uremic syndrome (aHUS)", "explanation": "Incorrect. Atypical HUS shows MAHA + thrombocytopenia + AKI with NORMAL coagulation (PT/PTT/fibrinogen normal) and is mediated by complement dysregulation. This patient has deranged coagulation, ruling out aHUS. This would be the correct answer with MAHA + AKI without preceding diarrhea and with normal coagulation." },
      { "text": "Heparin-induced thrombocytopenia (HIT)", "explanation": "Incorrect. HIT presents 5-14 days after heparin exposure with isolated thrombocytopenia and thrombosis (paradoxically). The lab pattern (prolonged PT/PTT, low fibrinogen, elevated D-dimer) is consumptive coagulopathy, not HIT. This would be the correct answer with heparin exposure + thrombocytopenia + new thrombosis + positive HIT antibody/SRA." },
      { "text": "Immune thrombocytopenic purpura (ITP)", "explanation": "Incorrect. ITP shows ISOLATED thrombocytopenia with normal PT/PTT, normal fibrinogen, and no MAHA. The deranged coagulation in this patient excludes ITP. This would be the correct answer with isolated low platelets and normal coags." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: DIC = prolonged PT/PTT + LOW FIBRINOGEN + elevated D-dimer + MAHA + thrombocytopenia. Triggers: sepsis, obstetric, malignancy, trauma, APL. Treat the cause + supportive (FFP, cryo, plt). Distinguish from TTP (normal PT/PTT, low ADAMTS13).",
    "pdfPage": 35,
    "pdfQuote": "DIC"
  },
  {
    "id": 18,
    "category": "Hematology: Folate vs B12 in Macrocytic Anemia Workup",
    "questionText": "A 72-year-old man presents with progressive fatigue, gait imbalance, and a recent fall. He lives alone, eats poorly (mostly canned soup and crackers), drinks 4 alcoholic beverages daily, and has been on a PPI for 10 years. Vitals: BP 130/76, HR 78. Exam: glossitis, decreased vibratory sense and proprioception bilateral feet, positive Romberg, normal deep tendon reflexes. Labs: Hgb 9.5, MCV 115, RDW 18, hypersegmented neutrophils, serum B12 180 (LOW-normal range), folate 2.0 (LOW), MMA 900 (markedly elevated), homocysteine 38 (elevated). Which is the most appropriate management?",
    "options": [
      { "text": "Treat folate deficiency with oral folate 1 mg daily alone (the B12 is within normal range)", "explanation": "Incorrect. While serum B12 (180) falls in the 'low-normal' range (200-350 is the gray zone), the markedly ELEVATED MMA (specific for B12 deficiency) confirms FUNCTIONAL B12 deficiency despite a 'normal-range' B12 level. Treating folate alone would mask the megaloblastic anemia while neurologic damage from B12 deficiency progresses. This would be the correct answer in pure folate deficiency with normal MMA and normal B12." },
      { "text": "Treat BOTH: parenteral B12 first or with oral folate 1 mg daily; address underlying causes", "explanation": "Correct. Start parenteral B12 (IM cyanocobalamin) FIRST or simultaneously with oral folate 1 mg daily; address underlying causes (alcohol cessation counseling, dietary support, evaluate need for PPI cessation). This patient has CONCURRENT FOLATE AND FUNCTIONAL B12 DEFICIENCY — common in elderly with poor diet, alcohol use, and chronic PPI exposure. Lab clues: low folate (clearly folate deficiency); B12 in 'low-normal gray zone' BUT elevated MMA (specific marker for true B12 deficiency unmasked by gray-zone serum values); elevated homocysteine (elevated in both deficiencies). NEUROLOGIC FINDINGS (vibration/proprioception loss, positive Romberg) confirm the B12 component — folate alone does NOT cause neurologic damage. Management principles: (1) ALWAYS check both B12 and folate in megaloblastic anemia; (2) When in doubt, treat B12 first or concurrently (folate alone risks neurologic deterioration); (3) MMA is the best test to confirm B12 deficiency when serum B12 is in the gray zone (200-350); (4) Replace B12 PARENTERALLY (IM cyanocobalamin) given alcohol/PPI/dietary risks for poor absorption; (5) Folate 1 mg PO daily; (6) Address underlying causes: alcohol cessation, nutritional support, evaluate PPI necessity, screen for pernicious anemia, evaluate for malabsorption. Note: in any megaloblastic anemia with low-normal B12, ALWAYS check MMA — it is the most sensitive test for true B12 deficiency." },
      { "text": "Refer for bone marrow biopsy before treatment", "explanation": "Incorrect. The straightforward megaloblastic anemia with documented nutritional deficiencies does not warrant invasive bone marrow biopsy. Treat the deficiencies first; if anemia does not respond, then reconsider. This would be the correct answer in unexplained pancytopenia with dysplastic features." },
      { "text": "Administer RBC transfusion to target Hgb >12", "explanation": "Incorrect. The patient is stable at Hgb 9.5 — transfusion is reserved for severe symptomatic anemia. Folate and B12 replacement will correct the anemia. This would be the correct answer with hemodynamic instability or Hgb <7 with symptoms." },
      { "text": "Empiric treatment with iron supplementation alone", "explanation": "Incorrect. The patient has MACROCYTIC anemia (MCV 115), not microcytic — iron deficiency would cause microcytic anemia. Iron alone would not correct the underlying vitamin deficiencies. This would be the correct answer in pure iron deficiency anemia with microcytic indices." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: When B12 is in gray zone (200-350), check MMA (specific for B12 deficiency). Elevated MMA = true B12 deficiency regardless of serum level. Always replace B12 BEFORE or with folate to avoid masking neurologic damage.",
    "pdfPage": 11,
    "pdfQuote": "methylmalonic acid"
  },
  {
    "id": 19,
    "category": "Hematology: Anemia of Chronic Inflammation in HIV",
    "questionText": "A 34-year-old man with HIV (CD4 220, viral load suppressed on ART for 2 years) presents with progressive fatigue and pallor over 4 months. He has no acute infections, no GI symptoms. Vitals: BP 122/72, HR 88. Exam: pale conjunctiva, no organomegaly, no lymphadenopathy. Labs: Hgb 9.0, MCV 96, RDW 14, ferritin 250, TIBC 240, transferrin sat 25%, serum iron 65, CRP 12 (mildly elevated), B12 and folate normal, retic 1.2%, EPO level low. He has no overt blood loss or nutritional deficiency. Which is the most likely cause of his anemia?",
    "options": [
      { "text": "Iron deficiency anemia from chronic GI blood loss", "explanation": "Incorrect. Iron studies do not show iron deficiency — ferritin is elevated and transferrin saturation is within range. No symptoms of GI blood loss. This would be the correct answer with low ferritin and high TIBC." },
      { "text": "Anemia of chronic inflammation from HIV", "explanation": "Correct. There is suppressed EPO production and iron sequestration; consider erythropoietin therapy if symptomatic. HIV (even when virologically suppressed) is associated with chronic inflammation and ANEMIA OF CHRONIC INFLAMMATION/DISEASE features. Mechanisms: (1) chronic inflammatory cytokines (IL-6, TNF-alpha) → hepcidin upregulation → iron sequestration in macrophages; (2) suppressed EPO production; (3) direct marrow effects of HIV; (4) drug effects (some antiretrovirals — historically zidovudine — caused macrocytic anemia). Lab pattern fits ACD: NORMOCYTIC anemia, ferritin normal-high, TIBC normal-low, low EPO. Management: (1) Optimize HIV control (already done — viral load suppressed); (2) Address contributing factors (drug review, infection screening, nutritional deficiencies); (3) For symptomatic anemia not responding to optimization, consider ERYTHROPOIESIS-STIMULATING AGENTS (epoetin, darbepoetin) targeting Hgb 10-11.5 g/dL; (4) Iron supplementation only if iron stores are inadequate (ferritin <100); (5) HIV-associated parvovirus B19-induced pure red cell aplasia is also possible in advanced HIV — consider checking parvovirus B19 IgG/IgM/PCR if reticulocytopenia is profound. Other HIV-related anemia causes to keep in mind: opportunistic infection of marrow (TB, MAC, fungal), HIV-associated malignancy (lymphoma), drug toxicity, hemophagocytic syndrome." },
      { "text": "Aplastic anemia from idiopathic immune-mediated marrow failure", "explanation": "Incorrect. Aplastic anemia would show PANCYTOPENIA with HYPOCELLULAR bone marrow on biopsy, not isolated normocytic anemia with adequate iron. This would be the correct answer with pancytopenia and hypocellular marrow." },
      { "text": "Beta-thalassemia minor newly emerging", "explanation": "Incorrect. Beta-thal trait is congenital, not newly emerging; would show microcytic anemia and not be linked to HIV-related ACD pattern. This would be the correct answer with microcytic anemia, normal iron studies, normal RDW, and elevated HbA2 on electrophoresis." },
      { "text": "Sickle cell disease unmasked by chronic illness", "explanation": "Incorrect. Sickle cell disease is congenital and presents in childhood with characteristic findings (sickled cells, hemolysis, vaso-occlusive crises); not unmasked by HIV in adulthood. This would be the correct answer in a known sickle cell patient." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HIV-related anemia = often ACD pattern (chronic inflammation, hepcidin, suppressed EPO). Optimize ART, address contributing factors. ESA for symptomatic anemia. Watch for parvovirus B19-induced PRCA in advanced HIV.",
    "pdfPage": 14,
    "pdfQuote": "anemia of chronic disease"
  },
  {
    "id": 20,
    "category": "Hematology: HbSC vs HbSS",
    "questionText": "A 24-year-old African-American woman presents to clinic with vision loss in her right eye and proliferative retinopathy on funduscopic exam. PMH: occasional bone pain episodes, no hospitalization for crises, no transfusions. She has never had splenic sequestration or acute chest syndrome. Vitals: BP 122/74, HR 80. Exam: spleen palpable 4 cm below costal margin (preserved into adulthood — unusual for HbSS), proliferative retinopathy in right eye, normal cardiovascular exam. Labs: Hgb 11.5 (HIGHER than typical HbSS), MCV 72, retic 5%, smear shows TARGET CELLS and a few sickled cells. Hb electrophoresis: HbS 50%, HbC 50%, HbA absent. Which best describes her condition?",
    "options": [
      { "text": "Sickle cell disease (HbSS) with unusually mild course", "explanation": "Incorrect. HbSS patients have NO HbC; electrophoresis would show HbS predominant (~90%), HbF variable (5-15%), and NO HbA. Also, HbSS patients typically have autosplenectomized by adulthood and have lower baseline Hgb (~6-9). This patient's electrophoresis (50% HbS + 50% HbC) and preserved spleen point clearly to HbSC. This would be the correct answer with HbS predominant and absent HbC." },
      { "text": "HbSC disease (compound heterozygous sickle and HbC)", "explanation": "Correct. HbSC is milder than HbSS overall but has higher rates of proliferative retinopathy, splenic complications, and avascular necrosis. HbSC disease is the compound heterozygous combination of one HbS allele and one HbC allele. Clinical features distinguishing it from HbSS: (1) MILDER OVERALL — less severe anemia (Hgb often 9-12, vs HbSS ~6-9), fewer pain crises, fewer hospitalizations; (2) PRESERVED SPLEEN longer (often into adulthood — unlike HbSS where autosplenectomy occurs in childhood) → at risk for splenic sequestration even into adolescence/adulthood; (3) PROLIFERATIVE SICKLE RETINOPATHY is significantly more common in HbSC than HbSS (related to higher Hb levels and increased blood viscosity in retinal vessels); (4) AVASCULAR NECROSIS of the femoral head is more common; (5) Hematuria from medullary infarction; (6) Pregnancy can be more complicated. Hb electrophoresis is diagnostic: 50% HbS + 50% HbC + absent HbA. Management: similar principles to HbSS — annual eye exams (especially looking for proliferative retinopathy → may need laser photocoagulation), hydroxyurea consideration, pain crisis management, vaccinations against encapsulated organisms (functional asplenia still develops eventually). HbC alone (homozygous) produces only mild hemolytic anemia." },
      { "text": "Sickle cell trait (HbAS)", "explanation": "Incorrect. Sickle cell trait shows HbA predominant (~60%) + HbS (~40%), with NO HbC. Sickle trait is generally asymptomatic. This would be the correct answer with HbA-predominant electrophoresis and minimal symptoms." },
      { "text": "Beta-thalassemia major", "explanation": "Incorrect. Beta-thal major shows ABSENT HbA + markedly elevated HbF + elevated HbA2, with severe transfusion-dependent anemia from childhood. No HbS or HbC. This would be the correct answer with absent HbA, elevated HbF and HbA2, and chronic transfusion dependence." },
      { "text": "HbCC disease (homozygous HbC)", "explanation": "Incorrect. HbCC homozygous would show 100% HbC + no HbS + no HbA on electrophoresis. The patient has 50% HbS, ruling out HbCC. HbC alone causes only mild hemolytic anemia with target cells; the SC compound has its distinct features. This would be the correct answer with 100% HbC and mild hemolytic anemia." }
    ],
    "correctAnswerIndex": 1,
    "clinicalPearl": "Key takeaway: HbSC = compound heterozygous (50% HbS + 50% HbC + no HbA). MILDER than HbSS but HIGHER rates of proliferative retinopathy, AVN, and splenic complications (preserved spleen longer). Annual eye exams essential.",
    "pdfPage": 41,
    "pdfQuote": "HbC"
  }
];

window.Test_L152_Part2 = Test_L152_Part2;
