const PDF_MAPPING = {
    "L1a": "pdfs/Lecture # 1a. T. Li, D.O. (PPT).pdf",
    "L1b": "pdfs/Lecture # 1b. M. Terzella, D.O. (PPT).pdf",
    "L2": "pdfs/Lecture # 2. K. Poole, Ph.D. (PPT)-1.pdf",
    "L3": "pdfs/Lecture # 3. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "L4": "pdfs/Lecture # 4. J. Xie, Ph.D. (PPT).pdf",
    "L5": "pdfs/Lecture # 5. S. Zakhary, D.O. (PPT).pdf",
    "L6": "pdfs/Lecture # 6. J. Xie, Ph.D. (PPT).pdf",
    "L7": "pdfs/Lecture # 7. I. Kurtzer, Ph.D. (PPT).pdf",
    "L8": "pdfs/Lecture # 8. I. Kurtzer, Ph.D. (PPT).pdf",
    "L9": "pdfs/Lecture # 9. J. Xie, Ph.D. (PPT)-1.pdf",
    "L10": "pdfs/Lecture # 10. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "L11": "pdfs/Lecture # 11. V. Grubisic, M.D., Ph.D. (PPT).pdf",
    "L12": "pdfs/Lecture # 12. J. Xie, Ph.D. (PPT).pdf",
    "L13": "pdfs/Lecture # 13. R. Morgan, D.O. (PPT).pdf",
    "L15": "pdfs/Lecture # 15. J. Xie, Ph.D. (PPT)-1.pdf",
    "L16": "pdfs/Lecture # 16. G. Otazu, Ph.D. (PPT)-1.pdf",
    "L17": "pdfs/Lecture # 17. G. Otazu, Ph.D. (PPT)-1.pdf",
    "L18": "pdfs/Lecture # 18. R. Ramos, Ph.D. (PPT)-1.pdf",
    "L19": "pdfs/Lecture # 19. L. Goldstein, Pharm.D. (PPT).pdf",
    "L20": "pdfs/Lecture # 20. L. Goldstein, Pharm.D. (PPT).pdf",
    "L21": "pdfs/Lecture # 21. L. Goldstein, Pharm.D. (PPT).pdf",
    "L22": "pdfs/Lecture # 22. L. Goldstein, Pharm.D. (PPT).pdf",
    "L23": "pdfs/Lecture # 23. A. Reno, D.O. (PPT).pdf",
    "L24": "pdfs/Lecture # 24. G. Otazu, Ph.D. (PPT)-1.pdf",
    "L25": "pdfs/Lecture # 25. J. Xie, Ph.D. (PPT).pdf",
    "L26": "pdfs/Lecture # 26. R. Morgan, D.O. (PPT).pdf",
    "L27": "pdfs/Lecture # 27. T. Li, D.O. (PPT).pdf",
    "L28": "pdfs/Lecture # 28. R. Ramos, Ph.D. (PPT).pdf",
    "L29": "pdfs/Lecture # 29. R. Ramos, Ph.D. (PPT).pdf",
    "L30": "pdfs/Lecture # 30. I. Kurtzer, Ph.D. (PPT).pdf",
    "L31": "pdfs/Lecture # 31. I. Kurtzer, Ph.D. (PPT).pdf",
    "L32": "pdfs/Lecture # 32. I. Kurtzer, Ph.D. (PPT).pdf",
    "L33": "pdfs/Lecture # 33. L. Goldstein, Pharm.D. (PPT).pdf",
    "L34": "pdfs/Lecture # 34. L. Goldstein, Pharm.D. (PPT).pdf",
    "L35": "pdfs/Lecture # 35. I. Kurtzer, Ph.D. (PPT).pdf",
    "L36": "pdfs/Lecture # 36. I. Kurtzer, Ph.D. (PPT).pdf",
    "L37": "pdfs/Lecture # 37. R. Morgan, D.O. (PPT).pdf",
    "L38": "pdfs/Lecture # 38a. M. Terzella, D.O. (PPT).pdf",
    "L39": "pdfs/Lecture # 39. L. Goldstein, Pharm.D. (PPT)-1.pdf",
    "L40": "pdfs/Lecture # 40. A. Leder, D.O. (PPT)-1.pdf",
    "L41": "pdfs/Lecture # 41. A. Leder, D.O. (PPT)-1.pdf",
    "L42": "pdfs/Lecture # 42. M. Plummer, M.D. (PPT)-1.pdf",
    "L43": "pdfs/Lecture # 43. M. Pino, Ph.D. (PPT)-1.pdf",
    "L44": "pdfs/Lecture # 44. A. Nattis, D.O. (PPT).pdf",
    "L45": "pdfs/Lecture # 45. J. Xie, Ph.D. (PPT).pdf",
    "L46": "pdfs/Lecture # 46. R. Morgan, D.O. (PPT).pdf",
    "L48": "pdfs/Lecture # 48. M. Pino, Ph.D. (PPT).pdf",
    "L49": "pdfs/Lecture # 49. C. Abraham, M.D. (PPT)-1.pdf",
    "L50": "pdfs/Lecture # 50. R. Ramos, Ph.D. (PPT).pdf",
    "L51": "pdfs/Lecture # 51. A. Leder, D.O. (PPT)-1.pdf",
    "L52": "pdfs/Lecture # 52. L. Goldstein, Pharm.D. (PPT).pdf",
    "L53": "pdfs/Lecture # 53. L. Goldstein, Pharm.D. (PPT).pdf",
    "L54": "pdfs/Lecture # 54. A. Leder, D.O. (PPT).pdf",
    "L55": "pdfs/Lecture # 55. W. Zaloga, D.O. (PPT).pdf",
    "L56": "pdfs/Lecture # 56. M. Plummer, M.D. (PPT).pdf",
    "L57": "pdfs/Lecture # 57. A. Leder, D.O. (PPT).pdf",
    "L58": "pdfs/Lecture # 58. M. Pino, Ph.D. (PPT).pdf",
    "L59": "pdfs/Lecture # 59. P. Ryo, D.O. (PPT - with notes).pdf",
    "L60": "pdfs/Lecture # 60. D. Whitson, D.O. (PPT).pdf",
    "L61": "pdfs/Lecture # 61. A. Leder, D.O. (PPT - updated 1.29.26).pdf",
    "L62": "pdfs/Lecture # 62. M. Mihlbachler, Ph.D. (PPT).pdf",
    "L64": "pdfs/Lecture #64. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "L66": "pdfs/Lecture # 66. L. Goldstein, Pharm.D. (PPT).pdf",
    "L67": "pdfs/Lecture # 67. M. Pino, Ph.D. (PPT).pdf",
    "L68": "pdfs/Lecture # 68. G. Otazu, Ph.D. (PPT).pdf",
    "L63": "pdfs/Lecture #63. A. Reno, DO, MPH (PPT).pdf",
    "L69": "pdfs/Lecture #69. A. Coladner, D.O. (PPT).pdf",
    "L70": "pdfs/Lecture # 70. A. Patel, D.O. (PPT).pdf",
    "L71": "pdfs/Lecture # 71. T. Li, D.O. (PPT).pdf",
    "L72": "pdfs/Lecture # 72. M. Plummer, M.D..pdf",
    "L73": "pdfs/Lecture # 73. M. Plummer, M.D..pdf",
    "L74": "pdfs/Lecture # 74. W. Zaloga, D.O. (PPT).pdf",
    "L75": "pdfs/Lecture # 75. T. Chan, D.O. (PPT).pdf",
    "L76": "pdfs/Lecture # 76. T. Chan, D.O. (PPT)-1.pdf",
    "L77": "pdfs/Lecture # 77. A. Hurst, M.D. (PPT).pdf",
    "L78": "pdfs/Lecture # 78. A. Hurst, M.D. (PPT)-1.pdf",
    "L79": "pdfs/Lecture # 79. D. Cummins, Pharm.D., BCPS (PPT).pdf",

    "L102": "pdfs/L102.pdf",
    "L103": "pdfs/L103.pdf",
    "L104": "pdfs/L104.pdf",
    "L105": "pdfs/L105.pdf",
    "L106": "pdfs/L106.pdf",
    "L107": "pdfs/L107L108.pdf",
    "L108": "pdfs/L107L108.pdf",
    "L109": "pdfs/L109110.pdf",
    "L110": "pdfs/L109110.pdf",
    "L112": "pdfs/L112.pdf",
    "L113": "pdfs/L113.pdf",
    "L114": "pdfs/L114.pdf",
    "L115": "pdfs/L115L116.pdf",
    "L116": "pdfs/L115L116.pdf",
    "L117": "pdfs/L117L118.pdf",
    "L118": "pdfs/L117L118.pdf",
    "L119": "pdfs/L119.pdf",
    "L120": "pdfs/L120.pdf",
    "L121": "pdfs/L121.pdf",
    "L122": "pdfs/L122.pdf",
    "L123": "pdfs/L123.pdf",
    "L124": "pdfs/L124.pdf",
    "L125": "pdfs/L125.pdf",
    "L126": "pdfs/L126.pdf",
    "L127": "pdfs/L127.pdf",
    "L128": "pdfs/L128.pdf",
    "L129": "pdfs/L129.pdf",
    "L130": "pdfs/L130.pdf",
    "L131": [
        "pdfs/L131_1.pdf",
        "pdfs/L131_2.pdf",
        "pdfs/L131_3.pdf",
        "pdfs/L131_4.pdf"
    ],
    "L132": [
        "pdfs/L132_1.pdf",
        "pdfs/L132_2.pdf",
        "pdfs/L132_3.pdf",
        "pdfs/L132_4.pdf"
    ],
    "L133": "pdfs/L133.pdf",
    "L134": "pdfs/L134.pdf",
    "L135": "pdfs/L135.pdf",
    "L136": "pdfs/L136.pdf",
    "L137": "pdfs/L137.pdf",
    "L138": "pdfs/L138.pdf",
    "L107L108": "pdfs/L107L108.pdf",
    "L109L110": "pdfs/L109110.pdf",
    "L115L116": "pdfs/L115L116.pdf",
    "L117L118": "pdfs/L117L118.pdf",
    "L120L123": [
        "pdfs/L120.pdf",
        "pdfs/L123.pdf"
    ],

    // Practice Quiz Mappings
    "L107L108_Quiz": "pdfs/L107L108_Quiz_Ans.pdf",
    "L109L110_Quiz": "pdfs/L109L110_Quiz_Ans.pdf",
    "L115L116_Quiz": "pdfs/L115L116_Quiz_Ans.pdf",
    "L117L118_Quiz": "pdfs/L117L118_Quiz_Ans.pdf",
    "L120L123_Quiz": "pdfs/L120L123_Quiz_Ans.pdf",

    // Human Readable Mappings (for tests using pdfPage without slideImagePath)
    "Pharmacokinetics": "pdfs/L109110.pdf",
    "Epidemiology I": "pdfs/L134.pdf",
    "Epidemiology II": "pdfs/L135.pdf",
    "Gross Divisions CNS": "pdfs/L136.pdf",
    "Neurons & Synapse": "pdfs/L137.pdf",
    "Neurochemistry": "pdfs/L138.pdf",

    // Week 15 Mappings
    "Beta Lactams Pt2": "pdfs/L123.pdf",
    "Aminoglycosides": "pdfs/L124.pdf",
    "Protein Synthesis Inhibitors": "pdfs/L125.pdf",
    "Folic Acids": "pdfs/L126.pdf",

    // Week 14 Mappings (Fix for Missing PDF Buttons)
    "Special Afferents": "pdfs/L112.pdf",
    "Autonomics of H&N": "pdfs/L113.pdf",
    "DPR - GI": "pdfs/L114.pdf",
    "Clinical Pharmacokinetics": "pdfs/L115L116.pdf",
    "Drug Interactions & Pharmacogenomics": "pdfs/L117L118.pdf",
    "Antimicrobials": "pdfs/L119.pdf",
    "Beta Lactams Pt1": "pdfs/L120.pdf",

    // Full Test Name Mappings (from config.js) - Verified L1a-L13
    "OMM: Basics of Diagnosis (L1a)": "pdfs/Lecture # 1a. T. Li, D.O. (PPT).pdf",
    "OMM: Diagnosis of the Pelvis (L1b)": "pdfs/Lecture # 1b. M. Terzella, D.O. (PPT).pdf",
    "Neuroembryology (L2)": "pdfs/Lecture # 2. K. Poole, Ph.D. (PPT)-1.pdf",
    "Neuroanatomy: Meninges & CSF (L3)": "pdfs/Lecture # 3. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "Blood Supply of the CNS (L4)": "pdfs/Lecture # 4. J. Xie, Ph.D. (PPT).pdf",
    "Clinical Apps of Neuroimaging (L5)": "pdfs/Lecture # 5. S. Zakhary, D.O. (PPT).pdf",
    "Spinal Cord Anatomy (L6)": "pdfs/Lecture # 6. J. Xie, Ph.D. (PPT).pdf",
    "Brain Stem I (L7)": "pdfs/Lecture # 7. I. Kurtzer, Ph.D. (PPT).pdf",
    "Brain Stem II (L8)": "pdfs/Lecture # 8. I. Kurtzer, Ph.D. (PPT).pdf",
    "Reticular Formation (L9)": "pdfs/Lecture # 9. J. Xie, Ph.D. (PPT)-1.pdf",
    "Autonomic Nervous System (L10)": "pdfs/Lecture # 10. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "Hypothalamus (L11)": "pdfs/Lecture # 11. V. Grubisic, M.D., Ph.D. (PPT).pdf",
    "Thalamus Anatomy & Phys (L12)": "pdfs/Lecture # 12. J. Xie, Ph.D. (PPT).pdf",
    "Clinical Decision Making (L13)": "pdfs/Lecture # 13. R. Morgan, D.O. (PPT).pdf",
    "General Sensory System (L15)": "pdfs/Lecture # 15. J. Xie, Ph.D. (PPT)-1.pdf",
    "Visual System (L16)": "pdfs/Lecture # 16. G. Otazu, Ph.D. (PPT)-1.pdf",
    "Auditory System (L17)": "pdfs/Lecture # 17. G. Otazu, Ph.D. (PPT)-1.pdf",
    "Vestibular System (L18)": "pdfs/Lecture # 18. R. Ramos, Ph.D. (PPT)-1.pdf",
    "Pharm: Cholinomimetics (L19)": "pdfs/Lecture # 19. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Indirect Cholinomimetics (L20)": "pdfs/Lecture # 20. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Antimuscarinics (L21)": "pdfs/Lecture # 21. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Ganglionic/NM Blockers (L22)": "pdfs/Lecture # 22. L. Goldstein, Pharm.D. (PPT).pdf",
    "Path: Auditory/Vestibular (L23)": "pdfs/Lecture # 23. A. Reno, D.O. (PPT).pdf",
    "Neuro: Olfaction/Taste (L24)": "pdfs/Lecture # 24. G. Otazu, Ph.D. (PPT)-1.pdf",
    "Neuro: Limbic System (L25)": "pdfs/Lecture # 25. J. Xie, Ph.D. (PPT).pdf",
    "Clin: Neuro Exam I (L26)": "pdfs/Lecture # 26. R. Morgan, D.O. (PPT).pdf",
    "OMM: Lab 17 Prep (L27)": "pdfs/Lecture # 27. T. Li, D.O. (PPT).pdf",
    "Neuro: Neocortex (L28)": "pdfs/Lecture # 28. R. Ramos, Ph.D. (PPT).pdf",
    "Neuro: Neocortical Dev (L29)": "pdfs/Lecture # 29. R. Ramos, Ph.D. (PPT).pdf",
    "Neuro: Motor Systems I (L30)": "pdfs/Lecture # 30. I. Kurtzer, Ph.D. (PPT).pdf",
    "Neuro: Basal Ganglia (L31)": "pdfs/Lecture # 31. I. Kurtzer, Ph.D. (PPT).pdf",
    "Neuro: Cerebellum (L32)": "pdfs/Lecture # 32. I. Kurtzer, Ph.D. (PPT).pdf",
    "Pharm: Sympathomimetics I (L33)": "pdfs/Lecture # 33. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Sympathomimetics II (L34)": "pdfs/Lecture # 34. L. Goldstein, Pharm.D. (PPT).pdf",
    "Neuro: Cranial Nerves I-VI (L35)": "pdfs/Lecture # 35. I. Kurtzer, Ph.D. (PPT).pdf",
    "Neuro: Cranial Nerves VII-XII (L36)": "pdfs/Lecture # 36. I. Kurtzer, Ph.D. (PPT).pdf",
    "DPR: Neuro Exam - Motor/Reflex (L37)": "pdfs/Lecture # 37. R. Morgan, D.O. (PPT).pdf",
    "OMM: Sacral Diagnosis (L38)": "pdfs/Lecture # 38a. M. Terzella, D.O. (PPT).pdf",
    "Pharm: Adrenergic Antagonists (L39)": "pdfs/Lecture # 39. L. Goldstein, Pharm.D. (PPT)-1.pdf",
    "Neuro: Spinal Cord Syndromes (L40)": "pdfs/Lecture # 40. A. Leder, D.O. (PPT)-1.pdf",
    "Neuro: Localization (L41)": "pdfs/Lecture # 41. A. Leder, D.O. (PPT)-1.pdf",
    "Path: Demyelinating Diseases (L42)": "pdfs/Lecture # 42. M. Plummer, M.D. (PPT)-1.pdf",
    "Pharm: Multiple Sclerosis (L43)": "pdfs/Lecture # 43. M. Pino, Ph.D. (PPT)-1.pdf",
    "Ophtho: Introduction (L44)": "pdfs/Lecture # 44. A. Nattis, D.O. (PPT).pdf",
    "Neuro: Structure-Function Integration (L45)": "pdfs/Lecture # 45. J. Xie, Ph.D. (PPT).pdf",
    "Neuro: Sensory Exam/Special Tests (L46)": "pdfs/Lecture # 46. R. Morgan, D.O. (PPT).pdf",
    "Pharm: Sedative Hypnotics (L48)": "pdfs/Lecture # 48. M. Pino, Ph.D. (PPT).pdf",
    "OMM: Sacral MET 2 (L60)": "pdfs/Lecture # 60. D. Whitson, D.O. (PPT).pdf",
    "Neurology: Gait & Movement (L61)": "pdfs/Lecture # 61. A. Leder, D.O. (PPT - updated 1.29.26).pdf",
    "Neurology: Brachial Plexus (L62)": "pdfs/Lecture # 62. M. Mihlbachler, Ph.D. (PPT).pdf",
    "Neurology: Headache (L63)": "pdfs/Lecture #63. A. Reno, DO, MPH (PPT).pdf",
    "Pharmacology: General Anesthetics 1 (L64)": "pdfs/Lecture #64. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "Pharmacology: Antiseizure Drugs, Part 2 (L65)": "pdfs/Lecture # 65. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "L65": "pdfs/Lecture # 65. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "Pharmacology: Local Anesthetics (L66)": "pdfs/Lecture # 66. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharmacology: Opioid Analgesics (L67)": "pdfs/Lecture # 67. M. Pino, Ph.D. (PPT).pdf",
    "Physiology: Drug Addiction (L68)": "pdfs/Lecture # 68. G. Otazu, Ph.D. (PPT).pdf",
    "8-Neurooncology: Gliomas & Ependymomas (L72)": "pdfs/Lecture # 72. M. Plummer, M.D..pdf",
    "8-Neuronal Tumors, Medulloblastoma & Meningioma (L73)": "pdfs/Lecture # 73. M. Plummer, M.D..pdf",
    "8-Neuro Birth Defects (L74)": "pdfs/Lecture # 74. W. Zaloga, D.O. (PPT).pdf",
    "8-Pediatric Neuro 1 (L75)": "pdfs/Lecture # 75. T. Chan, D.O. (PPT).pdf",
    "8-Pediatric Neuro II (L76)": "pdfs/Lecture # 76. T. Chan, D.O. (PPT)-1.pdf",
    "8-Neurodevelopment & Behav Problems (L77)": "pdfs/Lecture # 77. A. Hurst, M.D. (PPT).pdf",
    "8-ADHD & Adolescent Development (L78)": "pdfs/Lecture # 78. A. Hurst, M.D. (PPT)-1.pdf",
    "8-Pharmacologic Management of ADHD (L79)": "pdfs/Lecture # 79. D. Cummins, Pharm.D., BCPS (PPT).pdf",
    "8-Bipolar and Depressive Disorders (L80)": "pdfs/Lecture #80. C. Dyson, M.D. (PPT).pdf",
    "8-Anxiety Disorders (L81)": "pdfs/Lecture # 81. A. Raj, Psy.D. (PPT).pdf",
    "8-Schizophrenia and Psychotic Disorders (L82)": "pdfs/Lecture # 82. C. Dyson, M.D. (PPT).pdf",
    "8-Unusual Neurological Diseases (L83)": "pdfs/Lecture # 83. A. Leder, D.O. (PPT).pdf",
    "L82": "pdfs/Lecture # 82. C. Dyson, M.D. (PPT).pdf",
    "L83": "pdfs/Lecture # 83. A. Leder, D.O. (PPT).pdf",
    "L84": "pdfs/Lecture # 84. A. Patel, D.O. (PPT).pdf",
    "8-Pediatrics Part 2 (L84)": "pdfs/Lecture # 84. A. Patel, D.O. (PPT).pdf"
};

// Expose to global scope
window.PDF_MAPPING = PDF_MAPPING;
