const PDF_MAPPING = {
    "L1a": "pdfs/Lecture # 1a. T. Li, D.O. (PPT).pdf",
    "L1b": "pdfs/Lecture # 1b. M. Terzella, D.O. (PPT).pdf",
    "L2": "pdfs/Lecture # 2. K. Poole, Ph.D. (PPT)-1.pdf",
    "L3": "pdfs/Lecture # 3. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "L4": "pdfs/Lecture # 4. J. Xie, Ph.D. (PPT).pdf",
    "L5": "pdfs/Lecture # 5. S. Zakhary, D.O. (PPT).pdf",
    "L6": "pdfs/Lecture # 6. J. Xie, Ph.D. (PPT).pdf",
    "L7": "pdfs/Lecture # 7. I. Kurtzer, Ph.D. (PPT).pdf",
    "L8": "pdfs/Lecture # 8. I. Kurtzer, Ph.D. (PPT).pdf",
    "L9": "pdfs/Lecture # 9. J. Xie, Ph.D. (PPT)-1.pdf",
    "L10": "pdfs/Lecture # 10. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "L11": "pdfs/Lecture # 11. V. Grubisic, M.D., Ph.D. (PPT).pdf",
    "L12": "pdfs/Lecture # 12. J. Xie, Ph.D. (PPT).pdf",
    "L13": "pdfs/Lecture # 13. R. Morgan, D.O. (PPT).pdf",
    "L15": "pdfs/Lecture # 15. J. Xie, Ph.D. (PPT)-1.pdf",
    "L16": "pdfs/Lecture # 16. G. Otazu, Ph.D. (PPT)-1.pdf",
    "L17": "pdfs/Lecture # 17. G. Otazu, Ph.D. (PPT)-1.pdf",
    "L18": "pdfs/Lecture # 18. R. Ramos, Ph.D. (PPT)-1.pdf",
    "L19": "pdfs/Lecture # 19. L. Goldstein, Pharm.D. (PPT).pdf",
    "L20": "pdfs/Lecture # 20. L. Goldstein, Pharm.D. (PPT).pdf",
    "L21": "pdfs/Lecture # 21. L. Goldstein, Pharm.D. (PPT).pdf",
    "L22": "pdfs/Lecture # 22. L. Goldstein, Pharm.D. (PPT).pdf",
    "L23": "pdfs/Lecture # 23. A. Reno, D.O. (PPT).pdf",
    "L24": "pdfs/Lecture # 24. G. Otazu, Ph.D. (PPT)-1.pdf",
    "L25": "pdfs/Lecture # 25. J. Xie, Ph.D. (PPT).pdf",
    "L26": "pdfs/Lecture # 26. R. Morgan, D.O. (PPT).pdf",
    "L27": "pdfs/Lecture # 27. T. Li, D.O. (PPT).pdf",
    "L28": "pdfs/Lecture # 28. R. Ramos, Ph.D. (PPT).pdf",
    "L29": "pdfs/Lecture # 29. R. Ramos, Ph.D. (PPT).pdf",
    "L30": "pdfs/Lecture # 30. I. Kurtzer, Ph.D. (PPT).pdf",
    "L31": "pdfs/Lecture # 31. I. Kurtzer, Ph.D. (PPT).pdf",
    "L32": "pdfs/Lecture # 32. I. Kurtzer, Ph.D. (PPT).pdf",
    "L33": "pdfs/Lecture # 33. L. Goldstein, Pharm.D. (PPT).pdf",
    "L34": "pdfs/Lecture # 34. L. Goldstein, Pharm.D. (PPT).pdf",
    "L35": "pdfs/Lecture # 35. I. Kurtzer, Ph.D. (PPT).pdf",
    "L36": "pdfs/Lecture # 36. I. Kurtzer, Ph.D. (PPT).pdf",
    "L37": "pdfs/Lecture # 37. R. Morgan, D.O. (PPT).pdf",
    "L38": "pdfs/Lecture # 38a. M. Terzella, D.O. (PPT).pdf",
    "L39": "pdfs/Lecture # 39. L. Goldstein, Pharm.D. (PPT)-1.pdf",
    "L40": "pdfs/Lecture # 40. A. Leder, D.O. (PPT)-1.pdf",
    "L41": "pdfs/Lecture # 41. A. Leder, D.O. (PPT)-1.pdf",
    "L42": "pdfs/Lecture # 42. M. Plummer, M.D. (PPT)-1.pdf",
    "L43": "pdfs/Lecture # 43. M. Pino, Ph.D. (PPT)-1.pdf",
    "L44": "pdfs/Lecture # 44. A. Nattis, D.O. (PPT).pdf",
    "L45": "pdfs/Lecture # 45. J. Xie, Ph.D. (PPT).pdf",
    "L46": "pdfs/Lecture # 46. R. Morgan, D.O. (PPT).pdf",
    "L48": "pdfs/Lecture # 48. M. Pino, Ph.D. (PPT).pdf",
    "L49": "pdfs/Lecture # 49. C. Abraham, M.D. (PPT)-1.pdf",
    "L50": "pdfs/Lecture # 50. R. Ramos, Ph.D. (PPT).pdf",
    "L51": "pdfs/Lecture # 51. A. Leder, D.O. (PPT)-1.pdf",
    "L52": "pdfs/Lecture # 52. L. Goldstein, Pharm.D. (PPT).pdf",
    "L53": "pdfs/Lecture # 53. L. Goldstein, Pharm.D. (PPT).pdf",
    "L54": "pdfs/Lecture # 54. A. Leder, D.O. (PPT).pdf",
    "L55": "pdfs/Lecture # 55. W. Zaloga, D.O. (PPT).pdf",
    "L56": "pdfs/Lecture # 56. M. Plummer, M.D. (PPT).pdf",
    "L57": "pdfs/Lecture # 57. A. Leder, D.O. (PPT).pdf",
    "L58": "pdfs/Lecture # 58. M. Pino, Ph.D. (PPT).pdf",
    "L59": "pdfs/Lecture # 59. P. Ryo, D.O. (PPT - with notes).pdf",
    "L60": "pdfs/Lecture # 60. D. Whitson, D.O. (PPT).pdf",
    "L61": "pdfs/Lecture # 61. A. Leder, D.O. (PPT - updated 1.29.26).pdf",
    "L62": "pdfs/Lecture # 62. M. Mihlbachler, Ph.D. (PPT).pdf",
    "L64": "pdfs/Lecture #64. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "L66": "pdfs/Lecture # 66. L. Goldstein, Pharm.D. (PPT).pdf",
    "L67": "pdfs/Lecture # 67. M. Pino, Ph.D. (PPT).pdf",
    "L68": "pdfs/Lecture # 68. G. Otazu, Ph.D. (PPT).pdf",
    "L63": "pdfs/Lecture #63. A. Reno, DO, MPH (PPT).pdf",
    "L69": "pdfs/Lecture #69. A. Coladner, D.O. (PPT).pdf",
    "L70": "pdfs/Lecture # 70. A. Patel, D.O. (PPT).pdf",
    "L71": "pdfs/Lecture # 71. T. Li, D.O. (PPT).pdf",
    "L72": "pdfs/Lecture # 72. M. Plummer, M.D..pdf",
    "L73": "pdfs/Lecture # 73. M. Plummer, M.D..pdf",
    "L74": "pdfs/Lecture # 74. W. Zaloga, D.O. (PPT).pdf",
    "L75": "pdfs/Lecture # 75. T. Chan, D.O. (PPT).pdf",
    "L76": "pdfs/Lecture # 76. T. Chan, D.O. (PPT)-1.pdf",
    "L77": "pdfs/Lecture # 77. A. Hurst, M.D. (PPT).pdf",
    "L78": "pdfs/Lecture # 78. A. Hurst, M.D. (PPT)-1.pdf",
    "L79": "pdfs/Lecture # 79. D. Cummins, Pharm.D., BCPS (PPT).pdf",

    "L102": "pdfs/Lecture # 102. M. Pino, Ph.D. (PPT).pdf",
    "L103": "pdfs/Lecture # 103. W. Zaloga, D.O. (PPT).pdf",
    "L104": "pdfs/Lecture #104. E. Petcu, M.D. (PPT).pdf",
    "L105": "pdfs/Lecture #105. E. Petcu, M.D. (PPT).pdf",
    "L106": "pdfs/Lecture # 106. W. Zaloga, D.O. (PPT).pdf",
    "L107": "pdfs/Lecture # 107. R. Morgan, D.O. (PPT).pdf",
    "L108": "pdfs/Lecture # 108. A. Coladner, D.O. (PPT).pdf",
    "L109": "pdfs/Lecture 109. K. Cornick, D.O. (PPT) updated 3.13.26.pdf",
    "L110": "pdfs/Lecture # 110. M. Heller, D.O. (PPT).pdf",
    "L111": "pdfs/Lecture # 111. M. Heller, D.O. (PPT).pdf",
    "L112": "pdfs/Lecture # 112. M. Heller, D.O. (PPT).pdf",
    "L113": "pdfs/Lecture # 113. J. Mazzie, D.O. (PPT).pdf",
    "L114": "pdfs/Lecture # 114. J. Mazzie, D.O. (PPT)-1.pdf",
    "L115": "pdfs/Lecture # 115. H. Zwibel, D.O. (PPT).pdf",
    "L116": "pdfs/Lecture # 116. M. Scotten, M.D. (PPT)-1.pdf",
    "L117": "pdfs/Lecture # 117. L. Goldstein, Pharm.D. (PPT).pdf",
    "L118": "pdfs/Lecture #118. L. Goldstein, Pharm.D. (PPT).pdf",
    "L119": "pdfs/Lecture # 119 & #120. T. Slieman, Ph.D. (PPT).pdf",
    "L120": "pdfs/Lecture # 119 & #120. T. Slieman, Ph.D. (PPT).pdf",
    "L121": "pdfs/Lecture # 121. M. Heller, D.O. (PPT).pdf",
    "L122": "pdfs/L122.pdf",
    "L123": "pdfs/Lecture # 123 & #124. T. Slieman, Ph.D. (PPT).pdf",
    "L124": "pdfs/Lecture # 123 & #124. T. Slieman, Ph.D. (PPT).pdf",
    "L125": "pdfs/Lecture # 125. T. Slieman, Ph.D. (PPT).pdf",
    "L126": "pdfs/Lecture # 126. T. Slieman, Ph.D. (PPT).pdf",
    "L127": "pdfs/Lecture # 127. W. Palmer, M.D. (PPT).pdf",
    "L128": "pdfs/Lecture # 128. W. Palmer, M.D. (PPT).pdf",
    "L129": "pdfs/Lecture # 129. W. Palmer, M.D. (PPT).pdf",
    "L130": "pdfs/Lecture # 130. D. Cummins, Pharm.D., BCPS (PPT).pdf",
    "L131": "pdfs/Lecture # 131. A. Patel, D.O. (PPT).pdf",
    "L132": "pdfs/Lecture # 132. L. Goldstein, Pharm.D. (PPT).pdf",
    "L133": "pdfs/Lecture # 133. L. Goldstein, Pharm.D. (PPT).pdf",
    "L134": "pdfs/Lecture # 134. M. Heller, D.O. (PPT).pdf",
    "L135": "pdfs/Lecture # 135. M. Heller, D.O. (PPT).pdf",
    "L136": "pdfs/L136.pdf",
    "L137": "pdfs/Lecture # 137. T. Slieman, Ph.D. (PPT).pdf",
    "L138": "pdfs/Lecture # 138. P. Ryo, D.O. (PPT).pdf",
    "L139": "pdfs/Lecture # 139. M. Pino, Ph.D. (PPT).pdf",
    "L141": "pdfs/Lecture # 141. B. Hickey, M.D. (PPT).pdf",
    "L146": "pdfs/Lecture # 146. A. Patel, D.O. (PPT).pdf",
    "L107L108": "pdfs/Lecture # 107. R. Morgan, D.O. (PPT).pdf",
    "L109L110": "pdfs/Lecture 109. K. Cornick, D.O. (PPT) updated 3.13.26.pdf",
    "L115L116": "pdfs/L115L116.pdf",
    "L117L118": "pdfs/L117L118.pdf",
    "L120L123": [
        "pdfs/L120.pdf",
        "pdfs/L123.pdf"
    ],

    // Practice Quiz Mappings
    "L107L108_Quiz": "pdfs/L107L108_Quiz_Ans.pdf",
    "L109L110_Quiz": "pdfs/L109L110_Quiz_Ans.pdf",
    "L115L116_Quiz": "pdfs/L115L116_Quiz_Ans.pdf",
    "L117L118_Quiz": "pdfs/L117L118_Quiz_Ans.pdf",
    "L120L123_Quiz": "pdfs/L120L123_Quiz_Ans.pdf",

    // Human Readable Mappings (for tests using pdfPage without slideImagePath)
    "Pharmacokinetics": "pdfs/L109110.pdf",
    "OMM: Diagnosis of the Elbow and Wrist (L109)": "pdfs/Lecture 109. K. Cornick, D.O. (PPT) updated 3.13.26.pdf",
    "Epidemiology I": "pdfs/L134.pdf",
    "Epidemiology II": "pdfs/Lecture # 135. M. Heller, D.O. (PPT).pdf",
    "Gross Divisions CNS": "pdfs/L136.pdf",
    "Test of Immune Function": "pdfs/Lecture # 137. T. Slieman, Ph.D. (PPT).pdf",
    "15-Test of Immune Function (L137)": "pdfs/Lecture # 137. T. Slieman, Ph.D. (PPT).pdf",

    // Week 15 Mappings
    "Beta Lactams Pt2": "pdfs/L123.pdf",
    "Aminoglycosides": "pdfs/L124.pdf",
    "Protein Synthesis Inhibitors": "pdfs/L125.pdf",
    "Folic Acids": "pdfs/L126.pdf",

    // Week 14 Mappings (Fix for Missing PDF Buttons)
    "Special Afferents": "pdfs/L112.pdf",
    "Autonomics of H&N": "pdfs/L113.pdf",
    "DPR - GI": "pdfs/L114.pdf",
    "Clinical Pharmacokinetics": "pdfs/L115L116.pdf",
    "Drug Interactions & Pharmacogenomics": "pdfs/L117L118.pdf",
    "Antimicrobials": "pdfs/L119.pdf",
    "Beta Lactams Pt1": "pdfs/L120.pdf",

    // Full Test Name Mappings (from config.js) - Verified L1a-L13
    "OMM: Basics of Diagnosis (L1a)": "pdfs/Lecture # 1a. T. Li, D.O. (PPT).pdf",
    "OMM: Diagnosis of the Pelvis (L1b)": "pdfs/Lecture # 1b. M. Terzella, D.O. (PPT).pdf",
    "Neuroembryology (L2)": "pdfs/Lecture # 2. K. Poole, Ph.D. (PPT)-1.pdf",
    "Neuroanatomy: Meninges & CSF (L3)": "pdfs/Lecture # 3. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "Blood Supply of the CNS (L4)": "pdfs/Lecture # 4. J. Xie, Ph.D. (PPT).pdf",
    "Clinical Apps of Neuroimaging (L5)": "pdfs/Lecture # 5. S. Zakhary, D.O. (PPT).pdf",
    "Spinal Cord Anatomy (L6)": "pdfs/Lecture # 6. J. Xie, Ph.D. (PPT).pdf",
    "Brain Stem I (L7)": "pdfs/Lecture # 7. I. Kurtzer, Ph.D. (PPT).pdf",
    "Brain Stem II (L8)": "pdfs/Lecture # 8. I. Kurtzer, Ph.D. (PPT).pdf",
    "Reticular Formation (L9)": "pdfs/Lecture # 9. J. Xie, Ph.D. (PPT)-1.pdf",
    "Autonomic Nervous System (L10)": "pdfs/Lecture # 10. V. Grubisic, M.D., Ph.D. (PPT)-1.pdf",
    "Hypothalamus (L11)": "pdfs/Lecture # 11. V. Grubisic, M.D., Ph.D. (PPT).pdf",
    "Thalamus Anatomy & Phys (L12)": "pdfs/Lecture # 12. J. Xie, Ph.D. (PPT).pdf",
    "Clinical Decision Making (L13)": "pdfs/Lecture # 13. R. Morgan, D.O. (PPT).pdf",
    "General Sensory System (L15)": "pdfs/Lecture # 15. J. Xie, Ph.D. (PPT)-1.pdf",
    "Visual System (L16)": "pdfs/Lecture # 16. G. Otazu, Ph.D. (PPT)-1.pdf",
    "Auditory System (L17)": "pdfs/Lecture # 17. G. Otazu, Ph.D. (PPT)-1.pdf",
    "Vestibular System (L18)": "pdfs/Lecture # 18. R. Ramos, Ph.D. (PPT)-1.pdf",
    "Pharm: Cholinomimetics (L19)": "pdfs/Lecture # 19. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Indirect Cholinomimetics (L20)": "pdfs/Lecture # 20. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Antimuscarinics (L21)": "pdfs/Lecture # 21. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Ganglionic/NM Blockers (L22)": "pdfs/Lecture # 22. L. Goldstein, Pharm.D. (PPT).pdf",
    "Path: Auditory/Vestibular (L23)": "pdfs/Lecture # 23. A. Reno, D.O. (PPT).pdf",
    "Neuro: Olfaction/Taste (L24)": "pdfs/Lecture # 24. G. Otazu, Ph.D. (PPT)-1.pdf",
    "Neuro: Limbic System (L25)": "pdfs/Lecture # 25. J. Xie, Ph.D. (PPT).pdf",
    "Clin: Neuro Exam I (L26)": "pdfs/Lecture # 26. R. Morgan, D.O. (PPT).pdf",
    "OMM: Lab 17 Prep (L27)": "pdfs/Lecture # 27. T. Li, D.O. (PPT).pdf",
    "Neuro: Neocortex (L28)": "pdfs/Lecture # 28. R. Ramos, Ph.D. (PPT).pdf",
    "Neuro: Neocortical Dev (L29)": "pdfs/Lecture # 29. R. Ramos, Ph.D. (PPT).pdf",
    "Neuro: Motor Systems I (L30)": "pdfs/Lecture # 30. I. Kurtzer, Ph.D. (PPT).pdf",
    "Neuro: Basal Ganglia (L31)": "pdfs/Lecture # 31. I. Kurtzer, Ph.D. (PPT).pdf",
    "Neuro: Cerebellum (L32)": "pdfs/Lecture # 32. I. Kurtzer, Ph.D. (PPT).pdf",
    "Pharm: Sympathomimetics I (L33)": "pdfs/Lecture # 33. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: Sympathomimetics II (L34)": "pdfs/Lecture # 34. L. Goldstein, Pharm.D. (PPT).pdf",
    "Neuro: Cranial Nerves I-VI (L35)": "pdfs/Lecture # 35. I. Kurtzer, Ph.D. (PPT).pdf",
    "Neuro: Cranial Nerves VII-XII (L36)": "pdfs/Lecture # 36. I. Kurtzer, Ph.D. (PPT).pdf",
    "DPR: Neuro Exam - Motor/Reflex (L37)": "pdfs/Lecture # 37. R. Morgan, D.O. (PPT).pdf",
    "OMM: Sacral Diagnosis (L38)": "pdfs/Lecture # 38a. M. Terzella, D.O. (PPT).pdf",
    "Pharm: Adrenergic Antagonists (L39)": "pdfs/Lecture # 39. L. Goldstein, Pharm.D. (PPT)-1.pdf",
    "Neuro: Spinal Cord Syndromes (L40)": "pdfs/Lecture # 40. A. Leder, D.O. (PPT)-1.pdf",
    "Neuro: Localization (L41)": "pdfs/Lecture # 41. A. Leder, D.O. (PPT)-1.pdf",
    "Path: Demyelinating Diseases (L42)": "pdfs/Lecture # 42. M. Plummer, M.D. (PPT)-1.pdf",
    "Pharm: Multiple Sclerosis (L43)": "pdfs/Lecture # 43. M. Pino, Ph.D. (PPT)-1.pdf",
    "Ophtho: Introduction (L44)": "pdfs/Lecture # 44. A. Nattis, D.O. (PPT).pdf",
    "Neuro: Structure-Function Integration (L45)": "pdfs/Lecture # 45. J. Xie, Ph.D. (PPT).pdf",
    "Neuro: Sensory Exam/Special Tests (L46)": "pdfs/Lecture # 46. R. Morgan, D.O. (PPT).pdf",
    "Pharm: Sedative Hypnotics (L48)": "pdfs/Lecture # 48. M. Pino, Ph.D. (PPT).pdf",
    "OMM: Sacral MET 2 (L60)": "pdfs/Lecture # 60. D. Whitson, D.O. (PPT).pdf",
    "Neurology: Gait & Movement (L61)": "pdfs/Lecture # 61. A. Leder, D.O. (PPT - updated 1.29.26).pdf",
    "Neurology: Brachial Plexus (L62)": "pdfs/Lecture # 62. M. Mihlbachler, Ph.D. (PPT).pdf",
    "Neurology: Headache (L63)": "pdfs/Lecture #63. A. Reno, DO, MPH (PPT).pdf",
    "Pharmacology: General Anesthetics 1 (L64)": "pdfs/Lecture #64. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "Pharmacology: Antiseizure Drugs, Part 2 (L65)": "pdfs/Lecture # 65. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "L65": "pdfs/Lecture # 65. L. Goldstein, Pharm.D. (PPT) 2.12.26.pdf",
    "Pharmacology: Local Anesthetics (L66)": "pdfs/Lecture # 66. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharmacology: Opioid Analgesics (L67)": "pdfs/Lecture # 67. M. Pino, Ph.D. (PPT).pdf",
    "Physiology: Drug Addiction (L68)": "pdfs/Lecture # 68. G. Otazu, Ph.D. (PPT).pdf",
    "8-Neurooncology: Gliomas & Ependymomas (L72)": "pdfs/Lecture # 72. M. Plummer, M.D..pdf",
    "8-Neuronal Tumors, Medulloblastoma & Meningioma (L73)": "pdfs/Lecture # 73. M. Plummer, M.D..pdf",
    "8-Neuro Birth Defects (L74)": "pdfs/Lecture # 74. W. Zaloga, D.O. (PPT).pdf",
    "8-Pediatric Neuro 1 (L75)": "pdfs/Lecture # 75. T. Chan, D.O. (PPT).pdf",
    "8-Pediatric Neuro II (L76)": "pdfs/Lecture # 76. T. Chan, D.O. (PPT)-1.pdf",
    "8-Neurodevelopment & Behav Problems (L77)": "pdfs/Lecture # 77. A. Hurst, M.D. (PPT).pdf",
    "8-ADHD & Adolescent Development (L78)": "pdfs/Lecture # 78. A. Hurst, M.D. (PPT)-1.pdf",
    "8-Pharmacologic Management of ADHD (L79)": "pdfs/Lecture # 79. D. Cummins, Pharm.D., BCPS (PPT).pdf",
    "8-Bipolar and Depressive Disorders (L80)": "pdfs/Lecture #80. C. Dyson, M.D. (PPT).pdf",
    "8-Anxiety Disorders (L81)": "pdfs/Lecture # 81. A. Raj, Psy.D. (PPT).pdf",
    "8-Schizophrenia and Psychotic Disorders (L82)": "pdfs/Lecture # 82. C. Dyson, M.D. (PPT).pdf",
    "8-Unusual Neurological Diseases (L83)": "pdfs/Lecture # 83. A. Leder, D.O. (PPT).pdf",
    "L82": "pdfs/Lecture # 82. C. Dyson, M.D. (PPT).pdf",
    "L83": "pdfs/Lecture # 83. A. Leder, D.O. (PPT).pdf",
    "L84": "pdfs/Lecture # 84. A. Patel, D.O. (PPT).pdf",
    "8-Pediatrics Part 2 (L84)": "pdfs/Lecture # 84. A. Patel, D.O. (PPT).pdf",
    "L86": "pdfs/Lecture # 86. M. Pino, Ph.D. (PPT).pdf",
    "L87": "pdfs/Lecture # 87. M. Pino, Ph.D. (PPT).pdf",
    "9-Pharmacology: Antipsychotics (L87)": "pdfs/Lecture # 87. M. Pino, Ph.D. (PPT).pdf",
    "L88": "pdfs/Lecture # 88. A. Raj, Psy.D. (PPT).pdf",
    "9-Psychotherapy: Basic Theoretical Principles (L88)": "pdfs/Lecture # 88. A. Raj, Psy.D. (PPT).pdf",
    "L89": "pdfs/Lecture # 89. L. Hoffman, Ph.D. (PPT).pdf",
    "9-Neuropsychological Testing (L89)": "pdfs/Lecture # 89. L. Hoffman, Ph.D. (PPT).pdf",
    "L90": "pdfs/Lecture # 90. L. Jarkon, D.O. (PPT).pdf",
    "9-Personality Disorders (L90)": "pdfs/Lecture # 90. L. Jarkon, D.O. (PPT).pdf",
    "L91": "pdfs/Lecture # 91. A. Coladner, D.O. (PPT).pdf",
    "9-Eating Disorders (L91)": "pdfs/Lecture # 91. A. Coladner, D.O. (PPT).pdf",
    "L92": "pdfs/Lecture # 92. A. Loftis, D.O. M.S. (PPT).pdf",
    "9-Sexual Disorders (L92)": "pdfs/Lecture # 92. A. Loftis, D.O. M.S. (PPT).pdf",
    "L93": "pdfs/Lecture #93. J. Goldberg (PPT).pdf",
    "L94": [
        "pdfs/Lecture #94 J. Goldberg (PPT #1).pdf",
        "pdfs/Lecture #94. J. Goldberg (PPT #2).pdf"
    ],
    "9-Disaster Psychiatry & PTSD (L94)": [
        "pdfs/Lecture #94 J. Goldberg (PPT #1).pdf",
        "pdfs/Lecture #94. J. Goldberg (PPT #2).pdf"
    ],
    "L95": "pdfs/Lecture #95. J. Goldberg (PPT).pdf",
    "9-Special Issues in Psychiatry (L95)": "pdfs/Lecture #95. J. Goldberg (PPT).pdf",
    "L96": "pdfs/Lecture # 96. T. Chan, D.O. (PPT).pdf",
    "9-Adolescent Wellness (L96)": "pdfs/Lecture # 96. T. Chan, D.O. (PPT).pdf",
    "L98": "pdfs/Lecture # 98. T. Slieman, Ph.D. (PPT).pdf",
    "L99": "pdfs/Lecture # 99. T. Slieman, Ph.D. (PPT).pdf",
    "L100": "pdfs/Lecture # 100. T. Slieman, Ph.D. (PPT)-1.pdf",
    "L101": "pdfs/Lecture # 101. L. Goldstein, Pharm.D. (PPT).pdf",
    "Pharm: CNS Infections (L102)": "pdfs/Lecture # 102. M. Pino, Ph.D. (PPT).pdf",
    "12-Path: Bone & Joints Pt 2 (L105)": "pdfs/Lecture #105. E. Petcu, M.D. (PPT).pdf",
    "12-Path: Pathology of Soft Tissue (L106)": "pdfs/Lecture # 106. W. Zaloga, D.O. (PPT).pdf",
    "L106": "pdfs/Lecture # 106. W. Zaloga, D.O. (PPT).pdf",
    "L108": "pdfs/Lecture # 108. A. Coladner, D.O. (PPT).pdf",
    "12-DPR: Shoulder & Elbow (L108)": "pdfs/Lecture # 108. A. Coladner, D.O. (PPT).pdf",
    "13-Orthopedics: Lower Extremity (L111)": "pdfs/Lecture # 111. M. Heller, D.O. (PPT).pdf",
    "13-Pediatric Orthopedics (L116)": "pdfs/Lecture # 116. M. Scotten, M.D. (PPT)-1.pdf",
    "13-Sports Medicine: Overuse Injuries (L115)": "pdfs/Lecture # 115. H. Zwibel, D.O. (PPT).pdf",
    "13-DPR: History and Physical Exam of the Spine (L121)": "pdfs/L121.pdf",
    "14-Rheumatology 3: Diseases Affecting Muscle (L129)": "pdfs/Lecture # 129. W. Palmer, M.D. (PPT).pdf",
    "14-Pediatric Rheumatology (L131)": "pdfs/Lecture # 131. A. Patel, D.O. (PPT).pdf",
    "14-DPR: Hip and Knee Exam (L134)": "pdfs/Lecture # 134. M. Heller, D.O. (PPT).pdf",
    "15-Allergens and Allergic Rhinitis (L139)": "pdfs/Lecture # 139. M. Pino, Ph.D. (PPT).pdf",
    "L140": "pdfs/Lecture # 140. J. Maccagnano, D.O. (PPT).pdf",
    "15-Anaphylaxis and Allergic Reactions (L140)": "pdfs/Lecture # 140. J. Maccagnano, D.O. (PPT).pdf",
    "15-Immunogenetics, Lymphocyte Activation, Immune Reg. and Tolerance 1 (L141)": "pdfs/Lecture # 141. B. Hickey, M.D. (PPT).pdf",
    "15-Immunogenetics, Lymphocyte Activation, Immune Reg. and Tolerance 2 (L142)": "pdfs/Lecture # 142. B. Hickey, M.D. (PPT).pdf",
    "L142": "pdfs/Lecture # 142. B. Hickey, M.D. (PPT).pdf",
    "L143": "pdfs/Lecture # 143. L. Goldstein, Pharm.D. (PPT).pdf",
    "L144": "pdfs/Lecture # 144. L. Goldstein, Pharm.D. (PPT).pdf",
    "L145": "pdfs/Lecture # 145. A. Hurst, M.D. (PPT).pdf",
    "L147": "pdfs/Lecture # 147. C. Abraham, M.D. (PPT).pdf",
    "15-Public & Global Health: Role of Immunizations (L147)": "pdfs/Lecture # 147. C. Abraham, M.D. (PPT).pdf",
    "17-Hematology: ABO Groups, Rh Disease (L149)": "pdfs/Lecture # 149. W. Zaloga, D.O. (PPT).pdf",
    "17-Hematology: Hematopoiesis (L150)": "pdfs/Lecture # 150. M. Plummer, M.D. (PPT).pdf",
    "17-Hematology: Laboratory Medicine and Anemias Part 1 (L151)": "pdfs/Lecture # 151. G. Saggio, D.O. (PPT).pdf",
    "17-Hematology: Laboratory Medicine and Anemias Part 1 - Vignettes Part 2 (L151)": "pdfs/Lecture # 151. G. Saggio, D.O. (PPT).pdf",
    "17-Hematology: Laboratory Medicine and Anemias Part 2 (L152)": "pdfs/Lecture # 152. G. Saggio, D.O. (PPT).pdf",
    "17-Hematology: Laboratory Medicine and Anemias Part 2 - Vignettes Part 2 (L152)": "pdfs/Lecture # 152. G. Saggio, D.O. (PPT).pdf",
    "17-Hematology: Pharmacology of Anemias (L153)": "pdfs/Lecture # 153. L. Goldstein, Pharm.D. (PPT).pdf",
    "17-Hematology: Leukemias, Lymphomas, and Plasma Cell Neoplasms (L154)": "pdfs/Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf",
    "17-Hematology: Leukemias - Vignettes Part 2 (L154)": "pdfs/Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf",
    "17-Hematology: Lymphomas (L155)": "pdfs/Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf",
    "17-Hematology: Lymphomas - Vignettes Part 2 (L155)": "pdfs/Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf",
    "17-Pharmacology: Antineoplastic Agents 1 (L156)": "pdfs/Lecture # 156. L. Goldstein, Pharm.D. (PPT).pdf",
    "17-Pharmacology: Antineoplastic Agents 2 (L157)": "pdfs/Lecture # 157. L. Goldstein, Pharm.D. (PPT).pdf",
    "17-Hematology: Pathology: Hemostasis (L158)": "pdfs/Lecture #158. E. Petcu (PPT).pdf",
    "17-Clinical Medicine: Introduction to the Gynecological and Obstetrical History (L159)": "pdfs/Lecture # 159. S. Lewis, M.D. (PPT).pdf",
    "18-Hematology: Pathology of Hemorrhage (L161)": "pdfs/Lecture # 161. M. Plummer, M.D. (PPT)-1.pdf",
    "18-Hematology: Pathology of Thrombosis (L162)": "pdfs/Lecture # 162. M. Plummer, M.D. (PPT).pdf",
    "18-Hematology: Pediatric Considerations in Hematology and Oncology (L163)": "pdfs/Lecture # 163. T. Chan, D.O. (PPT).pdf",
    "18-Pharmacology: Drugs Used in Coagulation Disorders, Part 1 (L164)": "pdfs/Lecture # 164. L. Goldstein, Pharm.D. (PPT).pdf",
    "18-Pharmacology: Drugs Used in Coagulation Disorders, Part 2 (L165)": "pdfs/Lecture # 165. L. Goldstein, Pharm.D. (PPT).pdf",
    "18-Microbiology: Emerging Blood Borne Infections (L166)": "pdfs/Lecture # 166. C. Abraham, M.D. (PPT).pdf",
    "18-Microbiology: Emerging Blood Borne Infections - Vignettes Part 2 (L166)": "pdfs/Lecture # 166. C. Abraham, M.D. (PPT).pdf",
    "18-Microbiology: HIV, AIDS and Human Retroviruses (L167)": "pdfs/Lecture # 167. C. Abraham, M.D. (PPT)-1.pdf",
    "18-Microbiology: Hemorrhagic Viral Infections (L168)": "pdfs/Lecture # 168. T. Slieman, Ph.D. (PPT).pdf",
    "18-Microbiology: Opportunistic Infections (L169)": "pdfs/Lecture # 169. C. Abraham, M.D. (PPT).pdf",
    "18-DPR: Introduction to Behavioral Medicine (L170)": "pdfs/Lecture # 170. L. Hoffman, Ph.D. (PPT).pdf",
    "L161": "pdfs/Lecture # 161. M. Plummer, M.D. (PPT)-1.pdf",
    "L162": "pdfs/Lecture # 162. M. Plummer, M.D. (PPT).pdf",
    "L163": "pdfs/Lecture # 163. T. Chan, D.O. (PPT).pdf",
    "L164": "pdfs/Lecture # 164. L. Goldstein, Pharm.D. (PPT).pdf",
    "L165": "pdfs/Lecture # 165. L. Goldstein, Pharm.D. (PPT).pdf",
    "L166": "pdfs/Lecture # 166. C. Abraham, M.D. (PPT).pdf",
    "L167": "pdfs/Lecture # 167. C. Abraham, M.D. (PPT)-1.pdf",
    "L168": "pdfs/Lecture # 168. T. Slieman, Ph.D. (PPT).pdf",
    "L169": "pdfs/Lecture # 169. C. Abraham, M.D. (PPT).pdf",
    "L170": "pdfs/Lecture # 170. L. Hoffman, Ph.D. (PPT).pdf",
    "L172": "pdfs/Lecture # 172. L. Goldstein, Pharm.D. (PPT).pdf",
    "19-Pharmacology: Chemotherapy of Malaria (L172)": "pdfs/Lecture # 172. L. Goldstein, Pharm.D. (PPT).pdf",
    "L173": "pdfs/Lecture # 173. L. Goldstein, Pharm.D. (PPT).pdf",
    "19-Pharmacology: Chemotherapy of Protozoal Infections (L173)": "pdfs/Lecture # 173. L. Goldstein, Pharm.D. (PPT).pdf",
    "L174": "pdfs/Lecture # 174. I. Kurtzer, Ph.D. (PPT).pdf",
    "19-Histology: Skin Part 1 - Epidermis, Dermis, Hypodermis (L174)": "pdfs/Lecture # 174. I. Kurtzer, Ph.D. (PPT).pdf",
    "L175": "pdfs/Lecture # 175. I. Kurtzer, Ph.D. (PPT)-1.pdf",
    "19-Histology: Skin Part 2 - Hair, Nails, Glands, Sensory Receptors (L175)": "pdfs/Lecture # 175. I. Kurtzer, Ph.D. (PPT)-1.pdf",
    "L176": "pdfs/Lecture # 176. C. Abraham, M.D. (PPT).pdf",
    "19-Microbiology: Skin and Mucous Membrane Infections (L176)": "pdfs/Lecture # 176. C. Abraham, M.D. (PPT).pdf",
    "L177": "pdfs/Lecture # 177. T. Slieman, Ph.D. (PPT).pdf",
    "19-Microbiology: Zoonotic Infections (L177)": "pdfs/Lecture # 177. T. Slieman, Ph.D. (PPT).pdf",
    "L178": "pdfs/Lecture # 178. L. Goldstein, Pharm.D. (PPT).pdf",
    "19-Pharmacology of Antifungal Agents (L178)": "pdfs/Lecture # 178. L. Goldstein, Pharm.D. (PPT).pdf",
    "L179": "pdfs/Lecture # 179. K. Cornick, D.O. (PPT).pdf",
    "19-DPR: History and Physical Exam of the Integumentary System (L179)": "pdfs/Lecture # 179. K. Cornick, D.O. (PPT).pdf",
    "L180": "pdfs/Lecture # 180. K. Cornick, D.O. (PPT).pdf",
    "19-Dermatology: Viral Exanthems (L180)": "pdfs/Lecture # 180. K. Cornick, D.O. (PPT).pdf",
    "L181": "pdfs/Lecture # 181. W. Zaloga, D.O. (PPT).pdf",
    "19-Non-Neoplastic Skin Pathology (L181)": "pdfs/Lecture # 181. W. Zaloga, D.O. (PPT).pdf",
    "L182": "pdfs/Lecture # 182. W. Zaloga, D.O. (PPT).pdf",
    "19-Pathology: Skin Tumors (L182)": "pdfs/Lecture # 182. W. Zaloga, D.O. (PPT).pdf",
    "L149": "pdfs/Lecture # 149. W. Zaloga, D.O. (PPT).pdf",
    "L150": "pdfs/Lecture # 150. M. Plummer, M.D. (PPT).pdf",
    "L151": "pdfs/Lecture # 151. G. Saggio, D.O. (PPT).pdf",
    "L152": "pdfs/Lecture # 152. G. Saggio, D.O. (PPT).pdf",
    "L153": "pdfs/Lecture # 153. L. Goldstein, Pharm.D. (PPT).pdf",
    "L154": "pdfs/Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf",
    "L155": "pdfs/Lecture #154. M. Plummer, M.D. (StudySheet) updated 4.23.26.pdf",
    "L156": "pdfs/Lecture # 156. L. Goldstein, Pharm.D. (PPT).pdf",
    "L157": "pdfs/Lecture # 157. L. Goldstein, Pharm.D. (PPT).pdf",
    "L158": "pdfs/Lecture #158. E. Petcu (PPT).pdf",
    "L159": "pdfs/Lecture # 159. S. Lewis, M.D. (PPT).pdf",

    // Pathoma Chapter 6 (White Blood Cell Disorders) - Section IV supplemental
    "Pathoma-Acute Leukemia (6.2)": "pdfs/6.2 acute leukemia.pdf",
    "Pathoma-Chronic Leukemia (6.3)": "pdfs/6.3 Chronic Leukemia.pdf",
    "Pathoma-Myeloproliferative Disorders (6.4)": "pdfs/6.4 Myeloproliferative Disorders.pdf",
    "Pathoma-LAD, Lymphoma, & Hodgkin Lymphoma (6.5-6.7)": "pdfs/6.5-6.7 LAD, Lymphoma, Hodgkin Lymphoma.pdf",

    "L184": "pdfs/Lecture # 184. L. Goldstein, Pharm.D. (PPT).pdf",
    "20-Pharmacology: Antiretroviral Drugs Part 1 (L184)": "pdfs/Lecture # 184. L. Goldstein, Pharm.D. (PPT).pdf",
    "L185": "pdfs/Lecture # 185. L. Goldstein, Pharm.D. (PPT).pdf",
    "20-Pharmacology: Antiretroviral Drugs Part 2 (L185)": "pdfs/Lecture # 185. L. Goldstein, Pharm.D. (PPT).pdf",
    "L186": "pdfs/Lecture # 186. C. Hoffman, D.O. (PPT)-2.pdf",
    "20-Dermatology: Stasis Dermatitis and Papulosquamous Eruptions (L186)": "pdfs/Lecture # 186. C. Hoffman, D.O. (PPT)-2.pdf",
    "L187": "pdfs/Lecture #187. C. Hoffman, D.O. (PPT).pdf",
    "20-Dermatology: Dermatologic Signs of Systemic Diseases (L187)": "pdfs/Lecture #187. C. Hoffman, D.O. (PPT).pdf",
    "L188": "pdfs/Lecture #188. C. Hoffman, D.O. (PPT)-1.pdf",
    "20-Dermatology: Evaluation of Pigmented Lesions (L188)": "pdfs/Lecture #188. C. Hoffman, D.O. (PPT)-1.pdf",
    "L189": "pdfs/Lecture # 189. J. Maccagnano, D.O. (PPT)-1.pdf",
    "20-Dermatology: Dermatologic Emergencies (L189)": "pdfs/Lecture # 189. J. Maccagnano, D.O. (PPT)-1.pdf",
    "L190": "pdfs/Lecture # 190. O. Savinova, Ph.D. (PPT)-1.pdf",
    "20-Physiology: Thermoregulation (L190)": "pdfs/Lecture # 190. O. Savinova, Ph.D. (PPT)-1.pdf",
    "L191": "pdfs/Lecture # 191. M. Gindi, M.D. (PPT).pdf",
    "20-Cold Related Injuries & Emergency Treatment of Hypothermia (L191)": "pdfs/Lecture # 191. M. Gindi, M.D. (PPT).pdf",
    "L192": "pdfs/Lecture # 192. M. Gindi, M.D. (PPT)-1.pdf",
    "20-Emergency Treatment of Hyperthermia (L192)": "pdfs/Lecture # 192. M. Gindi, M.D. (PPT)-1.pdf",
    "CV22": "pdfs/Lecture # 22. Y. Zhang, M.D., Ph.D. (PPT)-1.pdf",
    "CV1": "pdfs/Lecture # 1. H. Ettlinger S. Yao (PPT)-1.pdf",
    "CV2": "pdfs/Lecture # 2. T. Li D.O. (PPT)-1.pdf",
    "CV3": "pdfs/Lecture #3. N. Solounias, Ph.D. (PPT).pdf",
    "CV4": "pdfs/Lecture # 4. B.Askari Ph. D. (PPT).pdf",
    "CV6": "pdfs/Lecture # 6. B.Askari Ph. D. (PPT).pdf",
    "CV7": "pdfs/Lecture # 7. B.Askari Ph. D. Kyle Dixson; Medical Scholar (PPT)-1.pdf",
    "CV8": "pdfs/Lecture # 8. B.Askari Ph. D. Bryan Koflanovich; Medical Scholar (PPT).pdf",
    "CV9": "pdfs/Lecture # 9. B.Askari Ph. D. (PPT).pdf",
    "CV10": "pdfs/Lecture # 10. B.Askari Ph. D. (PPT).pdf",
    "CV11": "pdfs/Lecture #11. H. Ettlinger, D.O. (PPT).pdf",
    "CV12": "pdfs/Lecture # 12. S. Yao, D.O. (PPT).pdf",
    "CV13": "pdfs/Lecture # 13. M. Ventimiglia D.O. (PPT).pdf",
    "CV21": "pdfs/Lecture # 21. M. Terzella, D.O. (PPT)-1.pdf",
};


// Expose to global scope
window.PDF_MAPPING = PDF_MAPPING;
